mozilla/glean

Cargo.lock
glean-core/Cargo.toml
glean-core/ffi/Cargo.toml
glean-core/rlb/Cargo.toml

@mdboom I had to revert #1268, mozilla-central is still at the old version and we should probably soon-ish get in the RLB part, so we can start working with it.
By avoiding that upgrade we save us from one more thing to figure out right now.

Dependency update

---

glean-core/src/upload/mod.rs

Reduce Sentry noise for Fx-iOS by reducing the logging level of the recoverable network errors in the upload module.

Bug 1672984 - Recoverable network error is noisily logged at error level

---

docs/dev/core/internal/reserved-ping-names.md
glean-core/android/metrics.yaml
glean-core/metrics.yaml
glean-core/pings.yaml

This adds better internal documentation and references with respect to special ping names inside SDK-owned registry files.

Bug 1664501 - Add better docs for special pings [doc only]

---

CHANGELOG.md
gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy

This should address the intermittent build failures in android-components [described here](https://github.com/gradle/gradle/issues/7047#issuecomment-430139316).
We will need to make a Glean release and ship it to android-components to fix the build failures there.  I was unable to confirm the existing build failure in a-c, but I did confirm that this patch seems to do no harm there.
Cc @pocmo

Don't run Miniconda install in parallel

---

docs/user/metrics/boolean.md
glean-core/rlb/src/private/boolean.rs
glean-core/src/traits/boolean.rs
glean-core/src/traits/counter.rs
glean-core/src/traits/custom_distribution.rs
glean-core/src/traits/datetime.rs
glean-core/src/traits/event.rs
glean-core/src/traits/jwe.rs
glean-core/src/traits/memory_distribution.rs
glean-core/src/traits/quantity.rs
glean-core/src/traits/string.rs
glean-core/src/traits/string_list.rs
glean-core/src/traits/timespan.rs
glean-core/src/traits/timing_distribution.rs
glean-core/src/traits/uuid.rs

This also fixes the already existing `BooleanMetric` and updates the related docs.

Bug 1672990 - Make the ping name optional in the RLB testing APIs

---

glean-core/rlb/src/dispatcher/mod.rs

Just before the launch we send a shutdown command.
If processing is faster on the main thread it might still be able to
send the following command.
But it also might not.
In any case a task that is sent after a shutdown command should not be executed.
And that's what we test for.
Note: the *global* dispatcher API does not return a `Result`, so users
shouldn't even need to deal with this.

Bug 1672722 - Ignore return value of a launch that may fail or it might not.

---

.github/dependabot.yml

From the docs at https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates#versioning-strategy: 
Only create pull requests to update lockfiles updates. Ignore any new versions that would require package manifest changes.
---
Followup after #1295

Change to lockfile-only strategy for dependency updates

---

docs/user/adding-new-metrics.md
docs/user/metric-parameters.md

Bug 1673401 - Call out that `notification_emails` are used to send expiration alerts

---

CHANGELOG.md
Cargo.lock
glean-core/rlb/Cargo.toml
glean-core/rlb/examples/prototype.rs
glean-core/rlb/src/configuration.rs
glean-core/rlb/src/dispatcher/global.rs
glean-core/rlb/src/dispatcher/mod.rs
glean-core/rlb/src/lib.rs
glean-core/rlb/src/net/http_uploader.rs
glean-core/rlb/src/net/mod.rs
glean-core/rlb/src/private/ping.rs
glean-core/rlb/src/test.rs
glean-core/rlb/tests/schema.rs

This introduces the 'net' module for the RLB, fixes the ping submission functions and allows RLB consumers to
specify uploader implementations.
Thanks @badboy for the help on the flaky tests.

Bug 1672958 - Introduce the RLB `net` module

---

.circleci/config.yml

[skip ci]
I finished the release of 33.2.0 manually, then traced back my steps to reapply them to our config.
It's really just installing ssh and then skipping the double-rustup install.

Install ssh and don't try to install rustup again on pypi-linux-release

---

.circleci/config.yml
.dictionary
CHANGELOG.md
glean-core/src/database/mod.rs

This automatically migrates an existing LMDB database of Glean to a safe-mode database, if and only if the `rkv-safe-mode` feature is activated on the glean-core crate.
The plan will be to enable this in mozilla-central.
I already took this for a manual test using my local m-c checkout and migration succeeds as expected and keeps the `client_info.client_id`.

Bug 1676866 - Migrate to safe mode

---

CHANGELOG.md
bin/bootstrap.sh
glean-core/ios/Glean/Net/HttpPingUploader.swift
glean-core/python/glean/glean.py
glean-core/python/glean/net/ping_upload_worker.py

Bug 1676712 - Use the correct time unit for sleeps in Swift and Python 

---

glean-core/src/database/mod.rs

@badboy, I just fixed the issue. Thanks a lot for the guidance you provided on Bugzilla. Looking forward to some feedback.

Calculate the database size from all files in the directory

---

glean-core/ffi/src/byte_buffer.rs

The error is from [here](https://firefox-ci-tc.services.mozilla.com/tasks/LGW47wKWS0CgcRG2HMqSHQ/runs/0/logs/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FLGW47wKWS0CgcRG2HMqSHQ%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log#L1051-1057).

Fix clippy for Rust Beta 1.49.0

---

docs/user/metrics/quantity.md

This is causing rendering breakage on the page:

Add missing `div` for Java API in Quantity docs

---

CHANGELOG.md
docs/user/metrics/uuid.md
glean-core/ffi/glean.h
glean-core/ffi/src/uuid.rs
glean-core/ios/Glean/GleanFfi.h
glean-core/python/tests/metrics/test_uuid.py
glean-core/rlb/src/private/uuid.rs
glean-core/src/metrics/uuid.rs

Even though for statically typed languages it is impossible to set the UUID to something invalid, there is still a hole for dynamically-typed languages, since we pass it over FFI as a string.
This solution is a little "deeper" than we might otherwise like, but it is currently impossible to record errors through the FFI, and even the `glean-ffi` itself can't record errors (since the API for it is all private).  But I think it's not terrible (the `glean-core` API isn't the real public RLB API anyway, so adding a new method there for this use doesn't seem that bad...)

1678151: Record an error if UUID is invalid (affects only Python)

---

CHANGELOG.md
glean-core/rlb/src/lib.rs

This exclusively shuts down the dispatcher. Any additional complex behaviour should be discussed in bug 1647348 and probably addressed for all the platforms.

Bug 1679426 - Allow RLB consumers to shut down Glean.

---

CHANGELOG.md
glean-core/rlb/src/lib.rs
glean-core/rlb/src/test.rs

This makes sure RLB consumers can directly enable logging, set debug tags or source tags by calling Glean APIs in addition to setting environment variables (e.g. this is needed for FOG's `about:glean`)

Bug 1679428 - Provide Glean debugging APIs for RLB consumers

---

glean-core/rlb/src/lib.rs

The `ErrorType` is required for consumers to use the testing APIs to count the number of reported errors.

Expose the core's `ErrorType` in the RLB

---

docs/user/metrics/labeled_booleans.md
docs/user/metrics/labeled_counters.md
docs/user/metrics/labeled_strings.md

Bug 1677807 - Document that invalid labels result in recordings going to the `__other__` label

---

glean-core/ffi/glean.h
glean-core/ffi/src/byte_buffer.rs
glean-core/ffi/src/lib.rs
glean-core/ios/Glean/GleanFfi.h
glean-core/rlb/src/lib.rs
glean-core/src/lib.rs
glean-core/src/metrics/memory_distribution.rs
glean-core/src/metrics/timing_distribution.rs
glean-core/src/traits/memory_distribution.rs
glean-core/src/traits/timing_distribution.rs
glean-core/src/upload/mod.rs

This fixes a number of warnings emitted during the rustdoc build, and also turns those warnings into errors to prevent them from reappearing.  (There's also probably a lot that could be done to improve the intra-doc linking, but that's work for another PR...)

Get to zero rustdoc warnings

---

CHANGELOG.md
glean-core/python/glean/_process_dispatcher.py
glean-core/python/tests/test_network.py

We only want to run one ping uploading subprocess at a time -- for one, it might
delete ping files, and we can't have contention for that. This is currently
handled by waiting on an existing uploading subprocess before firing off a new
one. However, this can cause the main dispatcher thread to block, causing work
to go uncompleted and subsequent pings to go unsent, on shutdown of the main process.
Instead, this just does nothing if an uploading subprocess is already running,
since the existing uploader will also pick up any new pings added to the
outgoing directory and send them.

Bug 1679949: Don't block on running ping uploading process

---

CHANGELOG.md
glean-core/python/glean/net/ping_upload_worker.py

Partial revert of 2261845761251d91b6968f29846dc3aabbc0cc45
The default-increased sleep time causes issues for short-lived
applications, such as tests (burnham) or command-line tools (if they are
_really_ quick):
Glean initializes asynchronously, so by the time the first ping is
submitted it is not yet done with initialization and scanning the
pending pings directory and therefore asking the uploader to sleep for a
moment and return when the scan finished.
However right now it has no mechanism to communicate a short wait, so
consumers default to the throttle backoff time (which is 60s).
So if a fast client:
1. Calls `Glean.initialize`
2. Records some data and submits a ping
3. Stops
the uploader will start, get told to wait, sleep for 60s.
Meanwhile Glean-py's shutdown routine asks the …

Bug 1679949 - Hacky bug fix: Lower sleep time to one second

---

.circleci/config.yml
CHANGELOG.md

manylinux10 is based on CentOS 6, which as of 2020-12-02 09:00 is dead.
From http://mirror.centos.org/centos/6/readme:
> The whole CentOS 6 is *dead* and *shouldn't* be used anywhere at *all*
We rely on installing an SSH client (probably to checkout the repository),
so CentOS 6 is no good for us.
manylinux2014 is CentOS 7.8, which is also unmaintained, but at least
continues to work for now.
[doc only]

Upgrade to newer manylinux image

---

bin/prepare-release.sh

Avoid an early exit when there is _no_ `upstream` remote

---

glean-core/rlb/src/dispatcher/mod.rs
glean-core/rlb/src/lib.rs
glean-core/rlb/src/net/mod.rs

This exclusively changes the way we spawn threads: instead of using `thread::spawn` we use a `Builder`.
Unfortunately, `cargo fmt` re-indents most of the code so the changes look much bigger.

Bug 1680477 - Provide names for the thread spawned in rust

---

glean-core/rlb/src/dispatcher/global.rs
glean-core/rlb/src/dispatcher/mod.rs
glean-core/rlb/src/lib.rs

This makes sure tools (e.g. TSAN) properly account for the thread being shut down and do not flag this as a pending
thread error.

Bug 1680474- Join on the dispatcher thread after shutting it down

---

glean-core/python/glean/_ffi.py
glean-core/python/setup.py

This will fix not being able to pip install MozPhab on FreeBSD, etc.

Unbreak Python on non-Linux ELF platforms (*BSD, Solaris/illumos)

---

glean-core/rlb/src/private/uuid.rs

Rust UUID test APIs must correctly block on the dispatcher

---

CHANGELOG.md
glean-core/rlb/src/common_test.rs
glean-core/rlb/src/lib.rs

FOG tests sometimes don't do anything other than initializing Glean. In these cases, nothing blocks on the dispatcher and tests might end up triggering init twice, in parallel, locking files on the disk or corrupting local data. This, in turn, makes FOG tests flaky and even RLB tests occasionally fail.

Bug 1680789 - Properly shut down glean in tests (RLB)

---

.dictionary
CHANGELOG.md
glean-core/rlb/src/private/timespan.rs
glean-core/src/event_database/mod.rs

(Taking this for a try run in m-c to ensure it works before we land this)

Fix 2 lock-order-inversion bugs as found by TSan on m-c tests

---

docs/user/metrics/memory_distribution.md

I found this only because I was copy-pasta'ing it for the string list type... ;)

[doc only] Fix typo in memory distribution RLB doc example

---

glean-core/src/metrics/datetime.rs

This adds the missing parameter to the snapshot function,
it was missing due to a wrong rebase.

Fix broken tree

---

docs/user/metrics/timespan.md
glean-core/ffi/src/timespan.rs
glean-core/src/metrics/timespan.rs
glean-core/tests/timespan.rs

In [bug 1562859](https://bugzilla.mozilla.org/show_bug.cgi?id=1562859) we changed how this work: a timespan never overwrites a previous value, not even with `set_raw_nanos`.
We didn't document the error it records though.
We also didn't remove the unused parameter.
This tackles both.

Document that timespan doesn't overwrite and records `InvalidState`

---

glean-core/rlb/src/lib.rs
glean-core/rlb/src/private/boolean.rs
glean-core/rlb/src/private/counter.rs
glean-core/rlb/src/private/datetime.rs
glean-core/rlb/src/private/event.rs
glean-core/rlb/src/private/labeled.rs
glean-core/rlb/src/private/memory_distribution.rs
glean-core/rlb/src/private/quantity.rs
glean-core/rlb/src/private/string.rs
glean-core/rlb/src/private/string_list.rs
glean-core/rlb/src/private/timespan.rs
glean-core/rlb/src/private/uuid.rs
glean-core/rlb/src/test.rs

This ensures a test case like the following doesn't hang, but explodes:
1. create a metric
2. check what it contains
3. init glean

Bug 1677150: Panic before blocking

---

CHANGELOG.md
docs/user/pings/custom.md
glean-core/rlb/src/lib.rs
glean-core/rlb/src/test.rs

This is needed so that products using Glean (and tests) could register pings at an arbitrary time, even if the Glean init is deferred a bit.

Bug 1673850 - Allow ping registration before RLB init

---

glean-core/src/metrics/string.rs
glean-core/src/traits/string.rs

[doc only]
Randomly found this bug while reading through code.

Update identifier in string metric `set` docstring

---

Cargo.lock
glean-core/rlb/Cargo.toml

This is needed to coordinate with an update in the other parts of mozilla-central.

Update to crossbeam-channel 0.5

---

.circleci/config.yml
.dictionary
CHANGELOG.md
Makefile
docs/user/adding-glean-to-your-project.md
glean-core/python/setup.py

This adds the ability to install from a source Python package on musl-based platforms, such as Alpine Linux.  This still requires that a Rust compiler is installed (the usual `rustup` incantation should be sufficient).  This is a partial fix for #1410.
To test, in an Alpine Linux Docker image, such as `python:alpine-3.8`.  You can install the pip package from git from this branch:
```
apk add curl
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
export PATH=~/.cargo/bin:$PATH
apk add gcc musl-dev libffi-dev
pip install git+git://github.com/mdboom/glean.rs.git@3e4ff4d36f5aa2535965b51444d79aecc666a96e#egg=glean_sdk
```
Cc: @marco-c

Support installing Glean Python on musl-based platforms

---

glean-core/python/setup.py

This is just to satisfy this new warning from recent versions of setuptools:
.venv3.9/lib/python3.9/site-packages/setuptools/distutils_patch.py:25: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.

Python: import setuptools first

---

docs/glean.css
docs/tabs.js

Before, the tabs would all be the same height as the longest tab,
which would result in a lot of unnecessary white space at the bottom of
a tab, if a tab with very little content was sibling
to a tab with a lot of content.
See this problem, for example, by selecting the C# tab in this page: https://mozilla.github.io/glean/book/user/general-api.html
[UPDATE]
Found another bug on the tabs, where no tab would be selected in case the "Kotlin" (the default) tab was not present. I fixed it in 335e921. You can see this bug on the "Paralelism" section of the same link I posted above. If this behaviour was intentional, we can just delete that commit :)

Have each tab constrain its height based on its own content [doc only]

---

.circleci/config.yml
docs/dev/cut-a-new-release.md

Not yet ready -- I'm taking this for a test run with a sample crate.

Bug 1598291 - Publish the Rust crates from CI on every release

---

Cargo.lock
glean-core/Cargo.toml

Upgrade rkv to 0.17 to remove the dependency to failure in mozilla/rkv#210 as part of [effort](https://bugzilla.mozilla.org/show_bug.cgi?id=1681898) of removing dependencies to `failure` in m-c, as `failure` has been [officially deprecated](https://rustsec.org/advisories/RUSTSEC-2020-0036.html).

Upgrade rkv to 0.17

---

.circleci/config.yml
glean-core/rlb/src/dispatcher/mod.rs
glean-core/rlb/src/lib.rs

Actually what's to come is `preinit_tasks_overflow`, but these are necessary refactorings to make that possible to implement & test.

Refactoring as preparation for what's to come

---

.circleci/config.yml

The C# implementation is deprecated. We don't need to use up CI resources for it anymore.

Disable C# tests

---

CHANGELOG.md
glean-core/rlb/src/dispatcher/global.rs
glean-core/rlb/src/dispatcher/mod.rs
glean-core/rlb/src/glean_metrics.rs
glean-core/rlb/src/lib.rs
glean-core/rlb/src/private/counter.rs
glean-core/rlb/src/test.rs
glean-core/rlb/tests/overflowing_preinit.rs

Based on #1437.
The last 3 commits are the new implementation.
I went for an integration test to avoid having to deal with resetting the dispatcher and Glean.

Bug 1686736 - (RLB) Record the number of tasks queued in the pre-initialization buffer.

---

.cargo/config

Currently the project fails to compile on Big Sur.
I was able to fix it by explicitly setting the linkers in the cargo config

Explicitly set linker for Big Sur

---

glean-core/src/lib_unit_tests.rs

The test fails on Windows 10, possibly because it uses permissions. The offending line is `assert!(submitted.is_err());`. It indicates that Glean had no problem writing to disk.

Disable the `records_io_errors` test on Windows

---

CHANGELOG.md

---
iOS release in progress: https://github.com/mozilla/glean/releases/tag/v29.1.2

Backport changelog entry for 29.1.2

---

Cargo.lock

This reverts commit 2eae7c941c665a614abd2d10a9d38dc7468ead65.
---
No changelog, no git tag on the repo.
This definitely doesn't seem to be a patch release.
It's causing intermittents on CI, probably because it requires more memory during compilation/linking.
I should have been more careful in merging #1451

Revert "Bump criterion from 0.3.3 to 0.3.4"

---

CHANGELOG.md
docs/user/collected-metrics/metrics.md
docs/user/pings/baseline.md
docs/user/pings/events.md
docs/user/pings/index.md
glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt
glean-core/android/src/main/java/mozilla/telemetry/glean/rust/LibGleanFFI.kt
glean-core/android/src/main/java/mozilla/telemetry/glean/scheduler/GleanLifecycleObserver.kt
glean-core/android/src/test/java/mozilla/telemetry/glean/GleanFromJavaTest.java
glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt
glean-core/ffi/glean.h
glean-core/ffi/src/lib.rs
glean-core/ios/Glean/GleanFfi.h
glean-core/pings.yaml
glean-core/rlb/src/core_metrics.rs
glean-core/rlb/src/lib.rs
glean-core/rlb/src/test.rs
glean-core/src/internal_pings.rs
glean-core/src/lib.rs
glean-core/src/lib_unit_tests.rs

This PR does a bunch of things:
- it implements the client activity API in glean-core;
- it implements the startup `baseline` ping with reason `dirty_startup` for the RLB;
- it updates the other language bindings to use the clients activity API
TODO:

Bug 1685522 - Add the 'clients activity API' and implement the baseline ping for the RLB

---

.circleci/config.yml
samples/ios/app/bootstrap.sh

We need release mode to correctly ship bitcode for dependencies.
It fails without that, so there's no reason to keep the old way of doing it.

Always bootstrap the sample with release-mode dependencies

---

.circleci/config.yml

---
Now we release everything else with Python 3.8.
Is that gonna be a problem?

Use Python 3.9 on macOS on release

---

CHANGELOG.md
glean-core/ios/Glean/Glean.swift

This will avoid sending a dirty startup ping if the previous run of the application didn't
successfully and completely initialize Glean.
Unfortunately this is impossible to really test.
Because we currently consider initialization as a "foreground notification" (for the lack of other signals)
we immediately re-set the dirty flag to true.
So once the `initialization` completes we can't observe the previous
state anymore.
---
@mdboom because he did the original implementation.
@travis79 for the Swift review.
I'm going to post another PR for discussion around the notifications shortly. Not gonna land this before we discussed that one.

Bug 1647764 - Swift: Check and reset dirty flag on startup

---

CHANGELOG.md
glean-core/rlb/src/lib.rs
glean-core/rlb/src/test.rs

This makes sure no baseline ping with reason `dirty_startup` is generated when starting RLB consumers after a clean shutdown.

Bug 1690751 - Clear the dirty ping on shutdown in the RLB

---

build.gradle
glean-core/android/build.gradle
glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt
glean-core/android/src/test/java/mozilla/telemetry/glean/TestUtil.kt
glean-core/android/src/test/java/mozilla/telemetry/glean/debug/GleanDebugActivityTest.kt
glean-core/android/src/test/java/mozilla/telemetry/glean/pings/CustomPingTest.kt
glean-core/android/src/test/java/mozilla/telemetry/glean/pings/DeletionPingTest.kt
glean-core/android/src/test/java/mozilla/telemetry/glean/private/EventMetricTypeTest.kt
glean-core/android/src/test/java/mozilla/telemetry/glean/private/PingTypeTest.kt
glean-core/android/src/test/java/mozilla/telemetry/glean/scheduler/MetricsPingSchedulerTest.kt

My system Java recently upgraded to Java 11, breaking the Glean build.
CI is still on Java 8 so is not seeing these issues, but if we can find
a way to be compatible across these versions, I guess we should try.
One issue was just requiring a new jacoco config flag (which I admit I don't
really understand, but it works):
https://github.com/gradle/gradle/issues/5184#issuecomment-457865951
Behind that is the old version of okhttp3.mockwebserver is no longer compatible.
Upgrading that lead to some incompatible API changes, mostly that the API is now
much more shouty -- resulting in most of the changes here.
~It remains to be seen whether these fixes will work on CI with Java 8.~  They work!

Bug 1690887: Fix Android build for Java 11

---

docs/user/metrics/timespan.md

Used the sample and noticed that the linter complained about `milliseconds` not being right. :)

Docs: Fix timespan example

---

glean-core/ios/GleanTests/GleanTests.swift

We recently got a new `glean.validation.pings_submitted` labeled counter
that now shows up.
We need to take care of that in tests.

Bug 1691080 - Check for glean.validation keys as well

---

CHANGELOG.md
glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt
glean-core/android/src/main/java/mozilla/telemetry/glean/private/BooleanMetricType.kt
glean-core/android/src/main/java/mozilla/telemetry/glean/private/CounterMetricType.kt
glean-core/android/src/main/java/mozilla/telemetry/glean/private/CustomDistributionMetricType.kt
glean-core/android/src/main/java/mozilla/telemetry/glean/private/DatetimeMetricType.kt
glean-core/android/src/main/java/mozilla/telemetry/glean/private/EventMetricType.kt
glean-core/android/src/main/java/mozilla/telemetry/glean/private/JweMetricType.kt
glean-core/android/src/main/java/mozilla/telemetry/glean/private/MemoryDistributionMetricType.kt
glean-core/android/src/main/java/mozilla/telemetry/glean/private/QuantityMetricType.kt
glean-core/android/src/main/java/mozilla/telemetry/glean/private/StringListMetricType.kt
glean-core/android/src/main/java/mozilla/telemetry/glean/private/StringMetricType.kt
glean-core/android/src/main/java/mozilla/telemetry/glean/private/TimespanMetricType.kt
glean-core/android/src/main/java/mozilla/telemetry/glean/private/TimingDistributionMetricType.kt
glean-core/android/src/main/java/mozilla/telemetry/glean/private/UuidMetricType.kt

This just adds a better informational message when a `NullPointerException` is thrown from the Kotlin testing APIs.
As the bug contemplates, we could throw a different exception, but that's strictly speaking a breaking API change...  How much that matters in practice is perhaps up for debate, however.

Bug 1655112: Add messages to NullPointerExceptions in testing API

---

.cargo/config
.circleci/config.yml
.circleci/jazzy.yml
bin/bootstrap.sh
bin/build-swift-docs.sh
build-scripts/xc-universal-binary.sh
docs/dev/ios/setup-ios-build-environment.md
glean-core/ios/Glean.xcodeproj/project.pbxproj
samples/ios/app/bootstrap.sh
samples/ios/app/glean-sample-app.xcodeproj/project.pbxproj

This is my first try at building Glean iOS on a M1 (arm) machine.
It essentially requires us to use xcframeworks, because the Carthage workaround is not suitable on M1 machines (as we can't exclude the arm64 target, because that IS the host target).
I can build Glean iOS now on my M1.
I can't run the tests though, because [Rust doesn't know the difference between the host system and the simulator](https://github.com/rust-lang/rust/issues/81632).
It's also likely that our sample app won't work the same anymore, at least not if I also want to get that compilable and runnable on an M1. It will need to start using xcframeworks too.
Carthage currently cannot produce xcframework binary releases, so the sample will always need to compile Glean.
Consumers wouldn't be affected, as long as they …

Bug 1688178 - Big Sur/M1 updates: xcframeworks, using Xcode clang, lipo

---

glean-core/rlb/src/lib.rs
glean-core/rlb/src/private/boolean.rs
glean-core/rlb/src/private/counter.rs
glean-core/rlb/src/private/custom_distribution.rs
glean-core/rlb/src/private/datetime.rs
glean-core/rlb/src/private/event.rs
glean-core/rlb/src/private/memory_distribution.rs
glean-core/rlb/src/private/quantity.rs
glean-core/rlb/src/private/string.rs
glean-core/rlb/src/private/string_list.rs
glean-core/rlb/src/private/timespan.rs
glean-core/rlb/src/private/timing_distribution.rs
glean-core/rlb/src/private/uuid.rs

Two functions were added: `launch_with_glean` & `launch_with_glean_mut`; test cases passes.
When running `make clippy`, clippy says `extra` in the following snippet is a redundant clone:
```
pub fn set_experiment_active(
branch: String,
extra: Option<HashMap<String, String>>,
) {
dispatcher::launch_with_glean(move |glean| {
glean.set_experiment_active(experiment_id.to_owned(), branch.to_owned(), extra.to_owned)
})
}
```
while the original `set_experiment_active`, which doesn't causes the "redundant clone" error, looks like this:
```
pub fn set_experiment_active(
branch: String,
extra: Option<HashMap<String, String>>,
) {
dispatcher::launch(move || {
with_glean(|glean| {
glean.set_experiment_active(
experiment_id.to_owned(),
branch.to_owned(),
extra.to_owned(),
)
});
})
}
```
I am still …

Bug 1677441: Add launch_with_glean and launch_with_glean_mut for readibility

---

.circleci/config.yml

This brings Java 11.
We fixed support for that in commit 3ff81f0794696491cc6b094d74550fffe4e3211d

Bug 1659706 - CI: Use up-to-date CircleCI-provided Android image again

---

.circleci/config.yml

This was preventing the books from loading shared resources.

Persist shared folder to workplace after building docs [doc only]

---

README.md

Follow-up to https://github.com/mozilla/glean/pull/1502

Fix link to Glean logo

---

.circleci/config.yml
Cargo.lock
build-scripts/xc-universal-binary.sh
glean-core/ios/Glean.xcodeproj/project.pbxproj
glean-core/ios/base.xcconfig
samples/ios/app/glean-sample-app.xcodeproj/project.pbxproj

This currently requires a local build of rustc with https://github.com/rust-lang/rust/pull/81966 to enable the target (and also LLVM 12, LLVM 11 untested). Thus we can't really land that before that becomes stable.
I think it would also require direct consumers to switch over to xcframeworks.
It's untested in app-services, I guess it _could_ work for Intel builds there, but this would need to be tested.
No need for a formal review or test yet.

iOS: Don't exclude arm64 build for the simulator

---

CHANGELOG.md
Makefile
glean-core/python/setup.py

I think this fixes test failures such as this one: https://app.circleci.com/pipelines/github/mozilla/glean/7162/workflows/33e489f9-56fa-4f0b-b2fa-c4bf03b52604/jobs/124598 (see #1507).
I ran it locally and saw this:
```
Traceback (most recent call last):
File "/home/jer/src/mozilla/glean/glean-core/python/.venv3.8/lib64/python3.9/site-packages/glean_sdk-34.1.0-py3.9-linux-x86_64.egg/glean/_subprocess/_process_dispatcher_helper.py", line 36, in <module>
success = func(*args)
File "/home/jer/src/mozilla/glean/glean-core/python/.venv3.8/lib64/python3.9/site-packages/glean_sdk-34.1.0-py3.9-linux-x86_64.egg/glean/net/ping_upload_worker.py", line 152, in _process
time.sleep(incoming_task.wait / 1000)
OverflowError: timestamp too large to convert to C _PyTime_t
```
Adding some logging it shows …

Python: increase minimal supported cffi version

---

.circleci/config.yml

I already changed the GitHub configuration to make this a required task (and drop the 3.9 min test task)

Bug 1694950 - CI: Test minimum versions of Python packages on Python 3.9

---

docs/user/user/metrics/index.md

This was included in the docs, but not linked from the metrics index page.

[no bug] Add a link to labeled boolean docs from metrics index

---

.dictionary
docs/dev/README.md
docs/user/README.md

I tried to make the content on the front page of the user book a bit less SDK specific with the future addition of Glean.js documentation in mind.
I sent a third commit where I mention both Glean clients in the user book's front page. I made it into a separate commit on purpose, after I was done and read it, I wondered if we should hold off on mentioning it in the front page (since all the rest of the book is still heavily SDK specific).

Bug 1693489 -  Update Glean SDK development and Glean book front page content

---

.circleci/config.yml
.dictionary
CHANGELOG.md
docs/dev/code_coverage.md
docs/user/user/testing-metrics.md
glean-core/src/coverage.rs
glean-core/src/event_database/mod.rs
glean-core/src/lib.rs
glean-core/src/metrics/boolean.rs
glean-core/src/metrics/counter.rs
glean-core/src/metrics/custom_distribution.rs
glean-core/src/metrics/datetime.rs
glean-core/src/metrics/denominator.rs
glean-core/src/metrics/experiment.rs
glean-core/src/metrics/jwe.rs
glean-core/src/metrics/memory_distribution.rs
glean-core/src/metrics/quantity.rs
glean-core/src/metrics/rate.rs
glean-core/src/metrics/string.rs
glean-core/src/metrics/string_list.rs
glean-core/src/metrics/timespan.rs
glean-core/src/metrics/timing_distribution.rs
glean-core/src/storage/mod.rs

Just a playground to see if I can get the pieces working together.
Depends on https://github.com/mozilla/glean_parser/pull/272 for the glean_parser side of things.
Example coverage uploaded to codecov.io here: https://codecov.io/gh/mozilla/glean/src/ed8704ac50bcdfcb44ddd3a1fd6004d0eef57675/glean-core/metrics.yaml
Unfortunately, this requires forking the codecov.io uploader, since it explicitly filters out coverage reporting on `yaml` files.  (In fairness "coverage" on yaml files is unusual, but seems like it shouldn't be out-and-out disallowed).  Anyway, we might have to address that upstream in order for codecov.io to be a viable solution for our users of this feature.
Other than that, the implementation here turned out much simpler than in the proposal (reminder to go back and update …

Bug 1690780 - Coverage support

---

docs/user/README.md

Somehow we broke that link again, probably when we split the book or moved things around

Fix link to dev book

---

CHANGELOG.md
Cargo.lock
glean-core/rlb/Cargo.toml
glean-core/rlb/src/lib.rs
glean-core/rlb/src/system.rs

At the first glance, two existing crates could be used: `sys_info` and `os_info`.
`os_info` returns the distribution version instead of the kernel version for Linux systems, so we are only left with `sys_info`.
Following the [proposal](https://docs.google.com/document/d/1VD1z8njHu6A_vvojyIQhKcUmvhlQHVjVAlug2jitqbM/), `get_os_version()` is added to `glean_core::system.rs`, however I doubt this is the right place, since `internal_metrics::os_version` is initialized in `rlb`. 
Given the fact that we have to manipulate the `String` returned by `sys_info` in case of Linux, I failed to come up with a way to create something like `pub const OS_VERSION: String`.
Any suggestion is appreciated!

Bug 1679837: Set internal_metrics::os_version for specific os

---

.circleci/config.yml
Makefile
glean-core/python/setup.py

This also refactors wheels creation to allow cross-compilation in a smoother manner.

Add wheels for arm64 macos

---

taskcluster/docker/linux/Dockerfile
taskcluster/scripts/cross-compile-setup.sh
taskcluster/scripts/macos-cc-tools.manifest

We now use `clock_gettime_nsec_np`, which was only introduced in 10.12
(which was released in 2016).
This effectively drops support for 10.11 for Android builds.

[ci full] Bump macOS SDK to 10.12 (Sierra)

---

glean-core/src/common_metric_data.rs
glean-core/src/error_recording.rs
glean-core/src/metrics/labeled.rs
glean-core/src/metrics/mod.rs

Additionally this hides previously publicly exported functions.
Technically this would be a breaking change, but glean-core is not
considered a stable public API, so this can be handled as a patch change
only.

Bug 1697469 - Rename internal function to express what it does: validate a dynamic label

---

.dictionary
CHANGELOG.md
glean-core/android/src/main/java/mozilla/telemetry/glean/private/TimespanMetricType.kt
glean-core/android/src/main/java/mozilla/telemetry/glean/private/TimingDistributionMetricType.kt
glean-core/android/src/test/java/mozilla/telemetry/glean/private/TimespanMetricTypeTest.kt
glean-core/android/src/test/java/mozilla/telemetry/glean/private/TimingDistributionMetricTypeTest.kt

This can change control flow, as the code is essentially copied 1:1 in
place, which means `return` inside will be an early return before our
measure wrapper gets to stop the timer.
Thanks to @mcomella for the detailed explanation in the bug report.
See: https://blog.mindorks.com/understanding-inline-noinline-and-crossinline-in-kotlin

Bug 1699505 - Kotlin: Don't inline the closure when measuring

---

Cargo.lock
DEPENDENCIES.md
glean-core/android/dependency-licenses.xml
glean-core/ffi/Cargo.toml

This avoids some transitive dependencies on update that are missing
license files (crunchy).

Bug 1699522 - Bump oslog from 0.0.3 to 0.1.0

---

CHANGELOG.md
glean-core/rlb/src/private/timing_distribution.rs
glean-core/src/metrics/timing_distribution.rs
glean-core/tests/timing_distribution.rs

Unfortunately this needs a new API instead of the already existing `accumulate_samples_signed`.
We want the RLB consumer (in this case: FOG) to not care about the unit,
so we expect nanosecond samples.
Internally we then do the right thing.
And because this is pure Rust we can rely on `u64` and just never need
to filter out negative samples.

Bug 1695228 - RLB: API to pass in raw samples for timing distributions

---

docs/user/user/debugging/index.md
glean-core/ios/Glean/Glean.swift
glean-core/rlb/src/lib.rs
glean-core/src/debug.rs
glean-core/src/lib.rs

Docs were not clear about the fact that **all** source tags
are ignored if one or more of the tags in the list are invalid.
[doc only]

Bug 1697214 - Clarify source tags documentation about validation

---

glean-core/ffi/Cargo.toml
glean-core/rlb/Cargo.toml

Otherwise e.g. Rust users need to awkwardly also depend on `glean-core`
to set that feature (FOG does just that).
Plus now that we might switch Python we need it on glean-ffi too to
activate it in a wheel build.
---
Prerequisite for #1551

Expose rkv-safe-mode feature on the crates that are directly consumed

---

.dictionary
CHANGELOG.md
glean-core/python/glean/net/ping_upload_worker.py
glean-core/python/setup.py
glean-core/python/tests/test_dispatcher.py
glean-core/python/tests/test_network.py
glean-core/src/lib.rs

Posting this early to show the (straightforward) `setup.py` changes required to use SafeMode.
Unfortunately, safe mode isn't safe for multiple processes writing to the database at the same time.
In the general case, we can't guard against this short of some sort of lockfile (and all of the challenges that come with that). The use case of a command line tool that is run in parallel as part of a build is probably real enough that we should care someday, but is probably only a hazard waiting to be tripped on right now.
Beyond that, Glean require changes even for normal single-process usage, since the ping uploader runs in a separate process *and* sets network error metrics in the database.  This probably needs to be refactored so network error metrics are reported back to the main process …

Bug 1675580: Use rkv SafeMode in Python

---

glean-core/ffi/src/byte_buffer.rs
glean-core/src/database/mod.rs
taskcluster/ci/rust/kind.yml
taskcluster/scripts/rustup-setup.sh

This is valid code in release, so we can apply them now.

Fix clippy suggestions (in beta)

---

.dictionary
docs/user/user/metrics/event.md
docs/user/user/metrics/index.md
docs/user/user/metrics/memory_distribution.md

Relates to https://github.com/mozilla/glean_parser/pull/303

[doc only] Bug 1703280: Move metric parameter docs to the Glean Book

---

docs/user/user/metrics/event.md

Per discussion today in #glam, we should warn about using events in this document as well (as we do here: https://mozilla.github.io/glean/book/user/adding-new-metrics.html#do-you-need-to-know-the-order-of-events-relative-to-other-events).

Add a warning about using events

---

.circleci/config.yml

We still require to update carthage though, as only 0.37.0 brings
xcframework support.
Supported software: https://circle-macos-docs.s3.amazonaws.com/image-manifest/v4519/index.html
---
I saw that the iOS builds just broken on `main`. Not looking into this for now, but just upgrading Xcode and see if that works.

Update to Xcode 12.4

---

Makefile
docs/user/user/adding-new-metrics.md
docs/user/user/instrument-android-crashes-example.md
docs/user/user/pings/custom.md
docs/user/user/pings/testing-custom-pings.md
glean-core/Cargo.toml
glean-core/android/metrics.yaml
glean-core/csharp/Glean/GleanParser.cs
glean-core/ios/sdk_generator.sh
glean-core/metrics.yaml
glean-core/pings.yaml
glean-core/python/glean/__init__.py
glean-core/python/setup.py
gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy
samples/android/app/metrics.yaml
samples/android/app/pings.yaml
samples/csharp/metrics.yaml
samples/csharp/pings.yaml
samples/ios/app/metrics.yaml
samples/ios/app/pings.yaml

Update to 2.0.0 glean_parser schemas

---

docs/user/user/metrics/index.md
docs/user/user/metrics/labeled_booleans.md
docs/user/user/metrics/labeled_counters.md
docs/user/user/metrics/labeled_strings.md

The limit was raised in https://github.com/mozilla/glean_parser/pull/297
[doc only]
---
This should be landed when we update glean_parser to include that limit.

Bug 1702280 - Document the limit on number of statically-defined labels

---

glean-core/examples/sample.rs
glean-core/ffi/src/lib.rs
glean-core/rlb/src/lib.rs
glean-core/src/database/mod.rs
glean-core/src/event_database/mod.rs
glean-core/src/lib.rs
glean-core/tests/common/mod.rs

This might or might not avoid the crash in the linked bug.

Bug 1706411 - Use proper `Path`s throughout glean-core

---

CHANGELOG.md

The IO error fix was erroneously called out for the last release already.
[doc only]
---
We can land #1593 first, then I can rebase this and do a release.

Update changelog with changes since last release

---

docs/shared/tabs.js
docs/user/reference/metrics/boolean.md
docs/user/reference/metrics/counter.md

...And add Glean.js information to them.
[Rendered Boolean](https://innate-earth.surge.sh/reference/metrics/boolean.html)
[Rendered Counter](https://innate-earth.surge.sh/reference/metrics/counter.html)
Adding both metrics to the same PR, because they can then serve as a blueprint for all other metrics :)

Bug 1698800 - Conform boolean and counter metric pages to new structure

---

build.gradle
glean-core/android/src/test/java/mozilla/telemetry/glean/debug/GleanDebugActivityTest.kt

This requires disabling the GleanDebugActivity tests for now.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1698471 for more.
---
Tests in #1613 failed again, this should finally solve that

Kotlin: Upgrade to Robolectric 4.5.1 to gain Java 11 support

---

gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy

In Gradle 6.x `getBuildConfigPackageName` was reaplced by `namespace`.
We want to be forward compatible, so we check that first or fallback to the old method.
See changes here:
https://cs.android.com/android-studio/platform/tools/base/+/c20e34494964552a5ce2787bb4c05016ac022378:build-system/gradle-core/src/main/java/com/android/build/gradle/tasks/GenerateBuildConfig.kt;dlc=fa4d27e36ad755e7f270d342c8cb6e367ea05149

Bug 1700942 - Gradle plugin: Provide forward-compatibility with Gradle 6.8

---

glean-core/rlb/src/lib.rs
glean-core/rlb/src/test.rs

This avoids a race condition where there might not be a global Glean
yet.
But source tags are only needed for the ping assembly, and that's also
dispatched, so either happened before anyway or will happens afterwards.

Bug 1706729 - RLB: Dispatch setting the source tag.

---

docs/user/user/adding-glean-to-your-project.md

Missed one part where we still recommend generating markdown for Mozilla projects

---

CHANGELOG.md
glean-core/examples/sample.rs
glean-core/ffi/src/lib.rs
glean-core/rlb/examples/prototype.rs
glean-core/rlb/src/common_test.rs
glean-core/rlb/src/configuration.rs
glean-core/rlb/src/lib.rs
glean-core/rlb/src/test.rs
glean-core/rlb/tests/init_fails.rs
glean-core/rlb/tests/no_time_to_init.rs
glean-core/rlb/tests/overflowing_preinit.rs
glean-core/rlb/tests/schema.rs
glean-core/rlb/tests/simple.rs
glean-core/src/lib.rs
glean-core/src/metrics/string.rs
glean-core/src/scheduler.rs
glean-core/tests/common/mod.rs

The MPS has actually been written for a little while. I strove for as direct a translation of `MetricsPingScheduler.{kt|swift}` as was practicable (we can always refactor it later). The hard part has been tests. 
I've tried making this testable in a few ways. The first way you can see in the second commit and is straightforward, but it can't actually observe most of the behaviour we hope to test.
The second way apes the `Policy` approach of gecko JSMs. (I had some struggles with the borrow checker on this approach, so it's very possible this is more ornate than it needs to be) I think this `Policy` approach is the better one because it allows us to inspect and test every operation of the MPS which, as history has taught us, is absolutely crucial for peace of mind.
(( I also attempted to …

Bug 1672951 - Implement a Metrics Ping Scheduler in glean-core

---

.circleci/config.yml

CircleCI rolled out a quickfix that does the `brew update` now,
and will soon update their machine to already contain an updated
homebrew.
Details: https://discuss.circleci.com/t/macos-image-users-homebrew-brownout-2021-04-26/39872/2

CI: Don't force brew update

---

CHANGELOG.md
glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt

There's a chance that the app is killed at any point.
If that happens while setting core metrics, on next start a ping might
be sent, which is then missing data.
Some of this data is required; and if missing the pipeline rejects the
ping during validation. By moving these metrics first we increase the
chance for them to be set.
This is a very desperate attempt on mitigating missing data.
---
I've spent all day reading the code over and over again, starting Fenix, trying to capture any ping without the app_build data.
I've only found _one_ tiny (forced) edge case:
When adding a delay (30s) right before setting `app_build`, then killing Fenix when it's waiting there, then starting it again, will trigger a ping that's missing the app build as expected.
Now in production we of course don't …

Kotlin: Set required client_info fields first

---

docs/user/reference/metrics/counter.md
docs/user/reference/metrics/datetime.md

...and Add Glean.js information to datetime metric page.
I also found a bug in the Swift example and fixed it (thanks @travis79 !).
[Rendered](https://innate-earth.surge.sh/reference/metrics/datetime.html).
Somethings I noticed:
- Java and Kotlin don't have the `testGetValue` API documented, was that on purpose? [That API seems to exist](https://github.com/mozilla/glean/blob/main/glean-core/android/src/main/java/mozilla/telemetry/glean/private/DatetimeMetricType.kt#L185). I can just include the missing examples in this PR, but wanted to double check first.
- Firefox Desktop `testGetValue` actually works like the `testGetValueAsString`. Worth filing a bug or was this on purpose?

Bug 1698800 - Conform datetime metric reference page to new format

---

glean-core/src/scheduler.rs

The correct lock order is 1) Global Glean 2) MPS' condvar's cancelled lock.

bug 1710990 - Don't take the Global Glean's lock while holding MPS's condvar lock

---

docs/user/reference/metrics/string.md
docs/user/reference/metrics/uuid.md

...and add Glean.js and Rust information to string and UUID metric page.
- String page: I also updated the error type in the `testGetNumRecordedErrors` examples to `InvalidOverflow`.
- UUID page: I also added `testGetNumRecordedErrors` docs.
[Rendered String](https://innate-earth.surge.sh/reference/metrics/string.html).
[Rendered UUID](https://innate-earth.surge.sh/reference/metrics/uuid.html).

Bug 1698800 - Conform string and UUID metric reference page to new format

---

docs/shared/glean.css
docs/user/_includes/labels-parameter.md
docs/user/reference/metrics/labeled_booleans.md
docs/user/reference/metrics/labeled_counters.md
docs/user/reference/metrics/labeled_strings.md

[Rendered Labeled Boolean](https://innate-earth.surge.sh/reference/metrics/labeled_booleans.html)
[Rendered Labeled Counter](https://innate-earth.surge.sh/reference/metrics/labeled_counters.html)
[Rendered Labeled String](https://innate-earth.surge.sh/reference/metrics/labeled_strings.html)
I also found a few missing docs, here is a ~possibly non-comprehensive~ list:
- Added docs for the `labels` extra metric parameter;
- Added Java tabs to all pages;
- Added `testGetValue` docs to LabeledString.

Bug 1698800 - Update labeled metrics docs to new structure and add Glean.js docs

---

docs/user/reference/metrics/boolean.md
docs/user/reference/metrics/counter.md
docs/user/reference/metrics/datetime.md
docs/user/reference/metrics/event.md
docs/user/reference/metrics/quantity.md
docs/user/reference/metrics/timespan.md

With these done all Glean.js metrics reference is done. The metrics pages I haven't changed during this effort, were not changed because they were not implemented in Glean.js yet. I'll file bugs for each individual missing page.
[doc only]

Bug 1698800 - Finish including Glean.js docs to metrics reference pages

---

docs/user/reference/metrics/uuid.md

Generate only v4 UUIDs.
Accepts any UUID in the typical 8-4-4-4-12 format.
[doc only]

Bug 1710424 - Document more precisely how the UUID type behaves

---

Makefile

Turns out `lint` does stuff on top of ktlint and detekt.
It's run on CI, but wasn't included when running locally.

Kotlin: Actually run Kotlin's own linter as part of the make command

---

CHANGELOG.md
Makefile
docs/user/reference/metrics/custom_distribution.md
glean-core/Cargo.toml
glean-core/csharp/Glean/GleanParser.cs
glean-core/ios/sdk_generator.sh
glean-core/python/glean/__init__.py
glean-core/python/setup.py
gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy

Requires https://github.com/mozilla/glean_parser/pull/346 & a release.
The doc will be correct when said release lands in m-c and I can land the code there too.

Bug 1713398 - glean_parser update & desktop custom distribution API docs

---

docs/user/user/adding-glean-to-your-project/python.md

This is probably good advice in general, but is mainly in response to bug 1716305.

Bug 1716305: Add note about upgrading pip

---

glean-core/metrics.yaml

This definition is only useful for documentation purposes, because [we are not using it internally](https://searchfox.org/glean/rev/42e5778f4aaf240330eae1ce5bebfa35e19642a0/glean-core/src/ping/mod.rs#71). We are not even using a field with the same name :-) We're using `sequence` internally, instead of `seq`.

Use the correct type for the `seq` field

---

glean-core/metrics.yaml

This reflects what's [happening in the code](https://searchfox.org/glean/rev/42e5778f4aaf240330eae1ce5bebfa35e19642a0/glean-core/src/ping/mod.rs#97), so that it's visible in the Glean Dictionary.

Add the time unit to the start_time/end_time

---

glean-core/metrics.yaml

This is an internal metric and thus the code already uses a never-ending
metric. All prior versions will continue to collect this metric too,
even beyond the initial date.
This is therefore mostly a documentation update.
[doc only]

Bug 1717402 - Extend `invalid_timezone_offset` metric until the end of the year

---

.circleci/config.yml

See upstream report: https://gitlab.alpinelinux.org/alpine/aports/-/issues/12396
And docs: https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.14.0#faccessat2

Downgrade to known-working version of Python/Alpine image

---

docs/user/reference/metrics/counter.md
docs/user/reference/metrics/datetime.md
docs/user/reference/metrics/event.md
docs/user/reference/metrics/labeled_booleans.md
docs/user/reference/metrics/labeled_counters.md
docs/user/reference/metrics/labeled_strings.md
docs/user/reference/metrics/quantity.md
docs/user/reference/metrics/string.md
docs/user/reference/metrics/timespan.md
docs/user/reference/metrics/uuid.md

Bug 1714365 - Update JS docs for testGetNumRecordedErrors to use ErrorType enum

---

glean-core/metrics.yaml

[doc only]
Same change was necessary on Glean.js (https://github.com/mozilla/glean.js/pull/504).
I noticed this was missing because it is not listed on the Glean Dictionary. 
Note that `android_sdk_version` is also not there, but that is because the Android specific `metrics.yaml` file is not in `repositories.yaml` ([bug filed](https://bugzilla.mozilla.org/show_bug.cgi?id=1719310)).

No bug - Add missing telemetry_sdk_build metric to metrics.yaml

---

.circleci/config.yml

CircleCI upgraded their Docker in use.
See https://discuss.circleci.com/t/unable-to-use-make/40552/4

Bug 1719129 - Use latest Python+Alpine image again

---

docs/user/user/metrics/adding-new-metrics.md

Small note. Had to manually check this earlier today so I thought I'd just add it to the docs.

No bug - Add note on capitalization of event extras [doc only]

---

.dictionary
docs/dev/core/internal/payload.md
docs/user/SUMMARY.md
docs/user/reference/metrics/index.md
docs/user/reference/metrics/url.md

Blocked until a release of Glean.js comes out with https://github.com/mozilla/glean.js/pull/529.

Bug 1719315 - Add documentation about the URL metric type

---

docs/user/SUMMARY.md
docs/user/reference/general/shutdown.md

~Blocked until https://github.com/mozilla/glean.js/pull/542 makes it into a release.~ This feature was released in [v0.18.0](https://github.com/mozilla/glean.js/releases/tag/v0.18.0).
Filed a bug to also add docs about the RLB shutdown API: https://bugzilla.mozilla.org/show_bug.cgi?id=1721388

Bug 1707891 - Add shutdown API reference page [doc only]

---

.taskcluster.yml

I tried rebuilding the `build-docker-image-linux` task via `add-new-jobs`, but because we're missing the appropriate `.taskcluster.yml` sections, it ran `rust-beta-tests` instead =\
This should hopefully allow us to use actions, and rebuild the `build-docker-image-linux` task before I invalidate the old CoT key.

update .taskcluster.yml to allow for actions

---

docs/user/user/pings/custom.md

[doc only]
This documentation is related to the feature being implemented on https://github.com/mozilla/glean.js/pull/607
I'll take this out of draft mode once that is merged.
**Note**: I intentionally did not add this docs to the event metric reference page, because the error recorded is only ever recorded for the `glean.restarted` event and no other.

Bug 1720467 - Add docs on error recording if offset between restarts is decreasing

---

.circleci/config.yml
Makefile
build.gradle
docs/dev/api/index.md
docs/dev/docs.md
docs/user/reference/general/experiments-api.md
docs/user/reference/metrics/boolean.md
docs/user/reference/metrics/counter.md
docs/user/reference/metrics/custom_distribution.md
docs/user/reference/metrics/datetime.md
docs/user/reference/metrics/event.md
docs/user/reference/metrics/labeled_booleans.md
docs/user/reference/metrics/labeled_counters.md
docs/user/reference/metrics/labeled_strings.md
docs/user/reference/metrics/memory_distribution.md
docs/user/reference/metrics/quantity.md
docs/user/reference/metrics/string.md
docs/user/reference/metrics/string_list.md
docs/user/reference/metrics/timespan.md
docs/user/reference/metrics/timing_distribution.md
docs/user/reference/metrics/uuid.md
glean-core/android-native/build.gradle
glean-core/android/build.gradle
glean-core/android/src/test/java/mozilla/telemetry/glean/TestUtil.kt
glean-core/android/src/test/java/mozilla/telemetry/glean/scheduler/MetricsPingSchedulerTest.kt
gradle/wrapper/gradle-wrapper.properties
samples/android/app/build.gradle
samples/android/app/src/androidTest/java/org/mozilla/samples/gleancore/MainActivityTest.kt
samples/android/app/src/androidTest/java/org/mozilla/samples/gleancore/pings/SharedTestUtils.kt
taskcluster/docker/linux/Dockerfile

Also upgrading Gradle and some dependencies.
Draft as I also want to update some stuff on CI

Bug 1722271 - Update to Kotlin 1.5

---

.dictionary
docs/dev/core/internal/payload.md
docs/user/_includes/lifetimes-parameters.md
docs/user/user/pings/baseline.md
docs/user/user/pings/index.md

The main content change here is just the `X-Telemetry-Agent` header information. I also noticed the `Limitations` section was a bit too `glean-core` specific and did not make 100% sense for Glean.js, so I made it a bit more generic.
I took this oppotunity to edit the structure of the ping index page to comply to the docs structuring guidelines. The biggest change is [preferring headers over lists or tables](https://mozilla.github.io/glean/book/appendix/contribution-guidelines.html#prefer-using-headers-whenever-a-new-topic-is-introduced). I also added a table of contents because this is a long page. 
I suggest reviewing this PR commit by commit, in order to single out the actual content changes, because 7610132 is mostly structural.

Bug 1722455 - Update pings documentation with Glean.js information

---

CHANGELOG.md
glean-core/android-native/publish.gradle
glean-core/android/publish.gradle

Also includes a changelog entry for the kotlin upgrade.
---
full ci run on TaskCluster to ensure it works.

Android: Use correct release target when publishing  [ci full]

---

glean-core/android/build.gradle

Since 186fec7d85 the generated docs include an extra header to point to
the Glean.js docs.
Because of this the file generated by the gradle plugin will always
differ from what's in the repository.
As the easy way out we just skip generating this file from Kotlin now.
It can be manually created using `make metrics-docs`, which does the
right thing.
(Alternatively we could add an post-glean plugin hook to modify the
file, but ... nah.)
[doc only]

Do not generate markdown docs as part of Kotlin build

---

docs/user/reference/pings/index.md

~Draft until https://github.com/mozilla/glean_parser/pull/365 makes it into a release.~
Made it into [v3.8.0](https://github.com/mozilla/glean_parser/releases/tag/v3.8.0).

Bug 1719136 - Use enum for ping reason in JS ref [doc only]

---

CHANGELOG.md
gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy

Because of the native code shipped it's essential that all downstream
users rely on the same Glean version.
Gradle can be overeager in chosing a single version when multiple are in
the dependency tree, always picking the latest, even across potentially
breaking-change (that is: major) releases.
Gradle has a way to influence dependency resolution and can even
disallow differing versions using `failOnVersionConflict`.
But that applies to all dependencies and there's no native way to
enforce that for a single dependency.
So the recommended solution[1] is to "manually" check if a dependency was
resolved from multiple versions and raise an issue.
For the ease of consumption by users, such as Fenix, we can apply this
in the Gradle plugin, because that's guaranteed to execute as part of
the …

Bug 1726765 - Force a compile failure when multiple Glean versions are detected in the build

---

docs/user/reference/metrics/quantity.md

And nix the bit about clearing values. That's a lifetime thing, not a "counter vs quantity" thing.

Have quantity docs skip a non-counter example for counters [doc only]

---

CHANGELOG.md
Makefile
glean-core/Cargo.toml
glean-core/csharp/Glean/GleanParser.cs
glean-core/ios/sdk_generator.sh
glean-core/python/glean/__init__.py
glean-core/python/setup.py
gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy

Notable changes:
* Reserve the default ping name. It can't be used as a ping name, but it can be used in send_in_pings
* New lint: Check for redundant words in ping names
---
Nothing significant for Glean, but doing that update now to see if it all continues to work (especially with the new lints)

Upgrade to glean_parser v4.0.0

---

docs/user/user/debugging/ios.md

Fixes a typo in the iOS debugging docs changing `sendPings` to the proper `sendPing`

[doc only] Fix typo in iOS debug command docs

---

docs/user/reference/metrics/string_list.md

Since the metric `string_list` has now been [implemented in Glean.js](https://github.com/mozilla/glean.js/pull/614), I have updated the documentation.
Any advice is appreciated!

Update JS doc for string_list

---

glean-core/csharp/README.md

[doc only]
---
Noticed it's nowhere written that this lacks functionality and is deprecated. Shall we add this note?

Add note that C# is deprecated

---

docs/user/reference/pings/index.md

The previous example did not work, error:
```
TypeError [ERR_INVALID_ARG_TYPE]: The "fn" argument must be of type function. Received undefined
```

Fix testBeforeNextSubmit Javascript example in the book [doc only]

---

build.gradle
glean-core/android-native/build.gradle
glean-core/android/build.gradle

Revert of 3cfa1bc3178faeb4e831e455ad842a8c1e7bd64b with slight
adjustements: local tests will now only build the host target, because
that's all we need.

Android: Ensure native library is built & bundled [ci full]

---

docs/user/reference/pings/index.md

I also removed a redundant paragraph from the bottom of the "Submission API" section and moved the info box related to built-in pings to the top of the page.

Bug 1731963 - Document that it is unnecessary to check if Glean is enabled before submitting pings

---

glean-core/ffi/src/lib.rs

Previously we enabled debug logging for all Rust modules within the same build.
This causes far too many logs in geckoview builds.
This stops that and only enables Glean logging.

Bug 1733152 - Explicitly only allow glean logs on Android

---

CHANGELOG.md
glean-core/rlb/src/lib.rs
glean-core/rlb/tests/persist_ping_lifetime_nopanic.rs

By its nature, persist_ping_lifetime_data performs I/O.
To be consistent across our public API surface, we should dispatch the call.

bug 1732988 - Make glean::persist_ping_lifetime_data async

---

docs/user/user/debugging/javascript.md

Bug 1733488 - Change "Python" to "JavaScript" wording in JavaScript debugging doc

---

.circleci/config.yml
CHANGELOG.md
glean-core/python/setup.py

This also uses the "next gen" Python Docker images from CircleCI.
Also removes some `persist_to_workspace` that is no longer needed.

Support Python 3.10

---

docs/dev/contributing.md

These two parts of the bug have not been addressed:
- Only explains how to run the Kotlin and Switf tests
- Mentions a CODEOWNERS file which does not exist

[doc only] Add in labeling and doc only info

---

docs/user/appendix/glossary.md
docs/user/user/metrics/adding-new-metrics.md
docs/user/user/pings/custom.md
docs/user/user/pings/metrics.md

The glean_parser documentation just redirects back to this, so let's
save our users some trouble. We still link to the glean_parser
documentation for the actual schema definition.

Use in-tree references for the YAML format documentation

---

glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt
glean-core/ios/Glean/Glean.swift
glean-core/uniffi/src/glean.udl
glean-core/uniffi/src/lib.rs

`setUploadEnabled` is a bit more complex than just flipping the `uploadEnabled` bit.
Before disabling upload we want any upload operation to be stopped.
The Metrics ping scheduler need to be cancelled too.
If upload is not actually changed no further action is required.
If upload is changed from on to off we need to trigger the uploader
once more to upload a deletion request ping.
If upload is changed from off to on we need to set the core metrics
again, which includes data from the application.
All of that should run in the dispatcher for 2 reasons:
* Not blocking the application
* Running in the expected order with other Glean recording operations
To keep most of current logic we can use callbacks on each of these cases.
The alternative to this would be:
* Store the required data for …

Implement `setUploadEnabled` using a callback mechanism

---

glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt
glean-core/ios/Glean/Glean.swift
glean-core/uniffi/src/core/mod.rs
glean-core/uniffi/src/debug.rs
glean-core/uniffi/src/glean.udl
glean-core/uniffi/src/lib.rs

This is internal API, but called from the SDK wrappers, thus we need to
define it in the UDL, then expose it to users.
---
This includes 2 cleanup commits.
I have one more thing and then I can probably start working on making this all compile again properly.

Implement debug view/source tags & log pings API

---

docs/dev/ios/setup-ios-build-environment.md

The new aarch64 simulator target is stable now, no special instructions
required for M1 hardware anymore.
[doc only]

Update iOS build environment instructions

---

CHANGELOG.md
Makefile
glean-core/Cargo.toml
glean-core/csharp/Glean/GleanParser.cs
glean-core/ios/sdk_generator.sh
glean-core/python/glean/__init__.py
glean-core/python/setup.py
gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy
samples/android/app/metrics.yaml
samples/android/app/tags.yaml

Requires https://github.com/mozilla/glean_parser/pull/409 and a followup release.
We should probably document that.
cc @wlach

Bug 1738878 - Glean parser with tags

---

bin/build-carthage.sh
xcconfig/xcode-12-fix-carthage-lipo.xcconfig

We've since long supported properly building on M1 machines relying on
xcframeworks.
CI was also switched to Xcode 13 a while ago.

Remove Xcode 12 hack

---

glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt
glean-core/ios/Glean/Glean.swift
glean-core/uniffi/src/core/mod.rs
glean-core/uniffi/src/glean.udl
glean-core/uniffi/src/lib.rs

This now makes me believe I _should_ store a general callback to trigger the uploader, just to avoid passing a new callback all the time

Implement client activity API

---

docs/user/user/adding-glean-to-your-project/javascript.md

[doc only]
It seems this warning is more confusing than not. Everything above it already gives the necessary instructions. Also allowing CORS, it turns out, does not mean Host permissions are not necessary on web extensions, so the bug link was also confusing.

No bug - Remove confusing and redundant bullet point from JS docs

---

glean-core/ios/Glean/Metrics/EventMetric.swift

Label each field public on the RecordedEventData struct for EventMetric - otherwise internal by default.
Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1741229

Bug 1741229 - Public access for struct RecordedEventData fields

---

docs/user/user/metrics/adding-new-metrics.md

https://mozilla.github.io/glean/book/user/metrics/adding-new-metrics.html is supposed to show a link to metric-lifetime-timeline.svg, but it doesn't get the path quite correct - so it does show the alt-text ("Metric lifetime timeline") but no image.

Fix path to metric-lifetime-timeline.svg

---

docs/user/reference/metrics/event.md

This updates the limits described in the Glean docs around event extras, specifically the value limitation of "50" utf-8 bytes is actually "100" utf-8 bytes.

[doc only]Bug 1736674 - Update limitations of event extras in the docs

---

docs/user/user/adding-glean-to-your-project/index.md

This adds information about the need for libraries that integrate/add Glean to specify the applications that depend on them when filing the bug to get the library product added for ingestion.

[doc only] Bug 1739459 - Add documentation about specifying dependencies for libraries

---

glean-core/python/glean/_process_dispatcher.py
glean-core/python/tests/test_dispatcher.py

@cpeterso: Can you confirm this addresses your issue by copying `_process_dispatcher.py` on this branch to `/Users/chris/Code/mozilla/firefox/obj-x86_64-apple-darwin20.3.0-clang-mozbuild/_virtualenvs/init_py3/lib/python3.8/site-packages/glean/`?

Bug 1697100: Don't let environment affect subprocess module search path

---

glean-core/rlb/src/pings.rs

Fix for [issue 1884](https://github.com/mozilla/glean/issues/1884).

Fix to name given to the events ping when instantiated.

---

CHANGELOG.md
glean-core/rlb/src/glean_metrics.rs
glean-core/rlb/tests/overflowing_preinit.rs

Otherwise this records the metric into the wrong full identifier

BUGFIX: Swap category and name

---

glean-core/python/glean/_process_dispatcher.py

The previous fix set the `PYTHONPATH` for the subprocess.
That overwrites the complete environment, clearing out any other
variables.
That can cause problems when other parts rely on something, such as the
RNG in Python relying on `SYSTEMROOT`

Bug 1745908 - Python: Copy the environment when launching the upload process

---

Cargo.lock

When building the wheel on platforms that don't come with a pre-built
wheel, it may fail to build because of issues that were fixed in recent
versions of the cc crate.

Upgrade cc crate

---

CHANGELOG.md
glean-core/rlb/src/lib.rs

This is important, because most of `destroy_glean` assumes init has completed:
1) Dispatcher reset? Runs all its tasks. Including ones using `with_glean`
2) Global state reset? Assumes the global state was setup.
Despite being important, this is not something that I've found a way to test.
The join behaviour's well tested, but the thing I want to test --
"Calling destroy_glean between `initialize()` being called and `glean.init`
completing." -- isn't. Ah well.
Note that we store multiple JoinHandles. There's nothing stopping N threads
from all calling `initialize()` simultaneously, starting N glean.init threads.
We'd need to compare_and_swap on INITIALIZE_CALLED for that guarantee.
(Not sure why we don't).

bug 1750235 - Ensure init is complete before destroying Glean

---

.circleci/config.yml

mdbook-dtmo v0.10 updates the other mdbook-* dependencies, dropping some
annoying markdown roundtripping issues.

Update to mdbook-dtmo v0.10.0

---

CHANGELOG.md
glean-core/python/glean/metrics/datetime.py
glean-core/python/tests/metrics/test_datetime.py

Turns out `datetime.now` defaults to `tz=None` and thus DOES NOT record
the timezone offset.
We treat that as an offset of 0 seconds.
However Python _does_ know about local time, so turning the current
local time into UTC, then back to local time gets us a timezone, from
which we can extract the timezone offset.
---
I've checked mozregression, moz-phab, mach and burnham. None of them uses `datetime.set()` to force `now`.

Python: Record correct timezone offset in datetime metrics

---

CHANGELOG.md
Makefile
docs/user/language-bindings/android/android-build-configuration-options.md
glean-core/Cargo.toml
glean-core/ios/sdk_generator.sh
glean-core/python/glean/__init__.py
glean-core/python/setup.py
gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy
samples/android/app/build.gradle
samples/android/app/metrics.yaml

This bumps the version of glean_parser currently being used by Glean and enables Android products to use expiration by version. To make sure things actually work, we change the Android sample to use expiration by version instead of a weird date.

Bug 1753194 - Enable support for expiration by version on Android

---

docs/user/user/pings/sent-by-glean.md

The events pings is sent on startup and on the API call.
[doc only]
---
I think marking "not sent" explicitly with ❌ makes things more obvious.

Document that Python can send the baseline ping

---

.taskcluster.yml
taskcluster/ci/android-build/kind.yml
taskcluster/glean_taskgraph/transforms/module_build.py
taskcluster/scripts/cross-compile-setup.sh

The previous commit updated Taskgraph to the latest version, which
contained a backwards incompatible change (introduced last summer) that
renamed the default checkout path from 'src' -> 'vcs'. This is causing
the build to fail.
Since this backwards incompatible change was introduced, we've since
started releasing to Pypi with proper version numbers and are now
following SemVer. So hopefully cases like this won't happen again.
(Ironically preventing cases like this is what the PR was trying to
solve).

Rename 'src -> vcs' in hardcoded paths in CI tasks [ci full]

---

docs/user/reference/metrics/rate.md

```
0:03.96 /home/tom/Documents/moz/mozilla-unified-7/dom/xml/nsXMLContentSink.cpp:629:48: error: no member named 'add_to_numerator' in 'mozilla::glean::impl::NumeratorMetric'; did you mean 'AddToNumerator'?
```

Fix rate C++ example (#1985) [doc only]

---

docs/user/user/pings/index.md
glean-core/ios/Glean/Net/HttpPingUploader.swift
glean-core/ios/GleanTests/Net/HttpPingUploaderTests.swift
glean-core/src/upload/request.rs

- Removed references to X-Client-Type and X-Client-Version in tests & documentation
- Replaced test header X-Client-Type -> X-Test-Only
An open question I have is for the upload function in HttpPingUploader.swift are there other headers? If so, I can add a line to the documentation since there is not currently an explainer for the headers parameter. If not, can we remove it from the function? @badboy

 [bug 1742614] Remove legacy X-Client-Type and X-Client-Version from Glean Pings

---

CHANGELOG.md
docs/dev/contributing.md
glean-core/rlb/src/dispatcher/global.rs
glean-core/rlb/tests/overflowing_preinit.rs

FOG's on Desktop and is init whenever BrowserGlue gets around to it.
We have the memory to play with.
This is a temporary measure until we make this configurable or limitless.

bug 1764549 - Bump the RLB preinit queue from 10^2 to 10^3

---

CHANGELOG.md
docs/user/language-bindings/ios/ios-build-configuration-options.md
glean-core/ios/sdk_generator.sh

It's up to the embedding application to provide the correct version
number.

Bug 1753975 - Support expiration by major version on iOS

---

docs/user/reference/general/initializing.md
docs/user/reference/metrics/boolean.md
docs/user/reference/metrics/counter.md
docs/user/reference/metrics/datetime.md
docs/user/reference/metrics/event.md
docs/user/reference/metrics/labeled_booleans.md
docs/user/reference/metrics/labeled_counters.md
docs/user/reference/metrics/labeled_strings.md
docs/user/reference/metrics/memory_distribution.md
docs/user/reference/metrics/quantity.md
docs/user/reference/metrics/string.md
docs/user/reference/metrics/string_list.md
docs/user/reference/metrics/timespan.md
docs/user/reference/metrics/timing_distribution.md
docs/user/reference/metrics/url.md
docs/user/reference/metrics/uuid.md
docs/user/reference/pings/index.md

It's not needed:
Everything in Glean is reachable without `testable`.
All test methods are on objects created in the application's scope, no
need to call things coming from Glean directly.
[doc only]

Bug 1762855 - Remove testable import in Swift doc examples

---

CHANGELOG.md
docs/dev/SUMMARY.md
docs/dev/android/glean-parser-substitution.md
gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy

A user can set an override for the glean_parser to be installed in the
virtual environment.
ext.gleanParserOverride = "git+ssh://git@github.com/mozilla/glean_parser@main#glean-parser"
This allows to switch out the used glean_parser version for local
testing.
---
It's a bit of magic in the code, but I didn't want to learn more groovy to make it "nice"

Bug 1766988 - Gradle Plugin: Allow override of the glean_parser to be installed

---

.gitignore
build-scripts/publish_to_maven_local_if_modified.py
build-scripts/shared.py
build-scripts/substitute-local-glean.gradle
build.gradle
docs/dev/android/development-with-android-components.md
docs/dev/android/locally-published-components-in-fenix.md
glean-core/android-native/publish.gradle
glean-core/android/publish.gradle
gradle-plugin/build.gradle
settings.gradle

This is part of my effort to make local Glean testing across the Android apps easier again.
This will require some changes to A-C and Fenix as well, that I'm putting up next.
It's all based directly on what application-services is doing [here](https://github.com/mozilla/application-services/blob/main/build-scripts/substitute-local-appservices.gradle) and [here](https://github.com/mozilla/application-services/blob/main/automation/publish_to_maven_local_if_modified.py).
It's still not perfect, because Glean gets shipped through GeckoView and we also have the gradle plugin, which we can't just substitute in.
Putting this into draft as we will also need doc changes.
---
* [Android Components changes](https://github.com/badboy/android-components/commit/c376be4736a45f0e6ae2f99ec494a63da95b5c39) …

Bug 1765950 - Add a workflow & substitute script to build and autopublish Glean locally

---

gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy

Woops, `matches` matches the whole string always.

Gradle plugin: Correctly detect git URL for glean_parser

---

.circleci/config.yml

1.61.0, released yesterday (2022-05-19) seems to lead to memory
exhaustion on CircleCI.
Let's go back to 1.60 for now.

CI: Run Rust tests on 1.60.0

---

glean-core/python/glean/_ffi.py
glean-core/python/tests/test_subprocess.py
glean-core/src/lib.rs

for [bug 1770791](https://bugzilla.mozilla.org/show_bug.cgi?id=1770791)
On Windows, Creating `FdLogger` twice causes the subsequent `subprocess` operation somehow fail.
And apparently the duplicate initialization is completely unnecessary.
So, applied 2 fixes, both on Rust side and Python side.
Rust side's `glean_enable_logging_to_fd` uses `OnceCell` to prevent subsequent call overwriting the value,
but `fd_logger::FdLogger::new(fd)` is not guarded.
So, it should check `FD_LOGGER.get().is_some()` before `fd_logger::FdLogger::new(fd)`.
Python side calls `setup_logging` twice, first time from `_ffi.py` top-level, and second time from `glean.py` top-level.
Either of them should be removed, and I've removed the former one.
The attached testcase fails on windows, with `py.test -s …

Bug 1770791 - Remove duplicate initialization in python glean package

---

.github/CODEOWNERS
.github/auto_assign.yml

Making use of GitHub's ability to auto-assign people from a team in a
round-robin fashion: https://docs.github.com/en/organizations/organizing-members-into-teams/managing-code-review-settings-for-your-team#routing-algorithms

Replace auto-assign bot with CODEOWNERS and GitHub's auto-assignment

---

glean-core/python/tests/test_glean.py
glean-core/rlb/src/lib.rs
glean-core/src/lib.rs

This was used to unblock the Rust dispatcher from foreign language bindings.
Now that we have _only_ the Rust dispatcher it's of course the one
that's going to be unblocked by `initialize`.
The functionality to automatically call this from `glean-ffi` was
removed when `glean-ffi` itself was removed.
This is thus just a cleanup of already unused functionality.

Remove `rlb_flush_dispatcher` symbol

---

glean-core/rlb/src/private/mod.rs

This can then be used in generated code without the end user required to
depend on the (right) version of once_cell.
---
glean_parser update coming.

Re-export once_cell

---

CHANGELOG.md
glean-core/src/common_metric_data.rs

Needed for JOG (tested the change locally and it works with my JOG patches in m-c)

bug 1772156 - Derive (De)Serialize for CMD and Lifetime

---

Makefile
glean-core/src/dispatcher/mod.rs
glean-core/src/error_recording.rs
glean-core/src/histogram/exponential.rs
glean-core/src/histogram/linear.rs
glean-core/src/histogram/mod.rs
glean-core/src/lib.rs
glean-core/src/metrics/recorded_experiment.rs
glean-core/src/metrics/time_unit.rs
glean-core/src/upload/mod.rs
glean-core/src/upload/request.rs

This fixes some clippy warnings that have popped up with the latest rust-beta.
In the places where I moved a method call outside of a loop or match and replaced it with a variable holding the result, it was due to this lint: https://rust-lang.github.io/rust-clippy/master/index.html#significant_drop_in_scrutinee
In the places where I added the derive for `Eq`, it was to satisfy this lint: https://rust-lang.github.io/rust-clippy/master/index.html#derive_partial_eq_without_eq

Fixes clippy lints and warnings for Rust 1.63.0-beta.2

---

Cargo.lock
DEPENDENCIES.md
glean-core/Cargo.toml
tools/embedded-uniffi-bindgen/Cargo.toml

This update to UniFFI contains a fix for the Swift code generation, unbreaking the Glean iOS build.

Update to UniFFI v0.19.3

---

glean-core/python/requirements_dev.txt
glean-core/python/setup.py

UniFFI uses ctypes which comes with Python.
No need for anything else anymore.

Python: drop dependency on cffi

---

CHANGELOG.md
build.gradle
gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy
gradle/wrapper/gradle-wrapper.properties

This additionally bumps the Gradle version and fixes the breakage due to querying the `namespace` property at configuration time. We instead query it at evaluation time now.
This unblocks mozilla-mobile/android-components#12386
**Note**: I'm making this a draft until I test it in A-C.

Bug 1776445 - Bump the Android Gradle Plugin to v7.2.1

---

.circleci/config.yml
.gitignore
Cargo.lock
Cargo.toml
bin/update-glean-parser-version.sh
docs/user/SUMMARY.md
docs/user/user/adding-glean-to-your-project/index.md
docs/user/user/adding-glean-to-your-project/rust.md
glean-core/build/Cargo.toml
glean-core/build/LICENSE
glean-core/build/README.md
glean-core/build/src/lib.rs
samples/rust/Cargo.toml
samples/rust/build.rs
samples/rust/metrics.yaml
samples/rust/pings.yaml
samples/rust/src/main.rs
taskcluster/docker/linux/Dockerfile

This crate should be used as a build dependency in Rust consumers.
In their `build.rs` they can call the builder to auto-generate code from
`metrics.yaml` and `pings.yaml` definitions:
glean_build::Builder::default()
.metrics("metrics.yaml")
.pings("pings.yaml")
.generate()
.expect("Error generating Glean Rust bindings");
This requires a working Python3 & pip installation.
Windows untested.
Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1713573 and https://bugzilla.mozilla.org/show_bug.cgi?id=1772566
---
This is my first stab at bug 1772566. It seems to work.
Todo:

Bug 1772566 - Implement a glean-build crate for use in Rust consumers

---

glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt

We saw some intermittents on Android Components failing in the `assert(isInitialized())` line.
This leads me to believe that it runs before Glean.initialize is
finished off-thread.
To fix this we introduce a new task queue: run things right after
Glean.initialize calls back into the wrapper.
We need to be careful though: This is triggered from the Rust side so we
can't call back and forth between Kotlin and Rust inside that task or we
risk deadlocks.
But in this instance we're safe:
1. We only allow tasks in test mode
2. We only call it in a single place
In theory there's a race condition still there, because we use
unsynchronized access to the `afterInitQueue`, but really ... it's test
mode and might just be fine enough for all we care? Let's hope so.
I am not able to reproduce the same …

Bug 1779638 - Kotlin: Add a hook to run tasks after init

---

CHANGELOG.md
docs/dev/contributing.md
glean-core/rlb/src/private/event.rs

This enables runtime-defined extra keys for runtime-defined event metrics.
Alternatively to this we could give RLB a RuntimeExtraKeys like NoExtraKeys and
specialize the impl of EventMetric to not use ALLOWED_EXTRA or into_ffi_extra,
but given that runtime-defined metrics are a dev-only feature (at present)
maybe this is enough?

bug 1767037 - RLB: Add a new ctor to Event that takes a list of allowed event extra keys.

---

.circleci/config.yml
CHANGELOG.md
glean-core/Cargo.toml
glean-core/bundle-android/Cargo.toml
glean-core/bundle/Cargo.toml
glean-core/python/setup.py
glean-core/rlb/Cargo.toml
glean-core/src/database/mod.rs
samples/rust/Cargo.toml

This effectively enables safe-mode everywhere, forcing migration from
LDMB to safe-mode in clients.
Note:
The iOS build was one of the last ones that really used LMDB mode.
Standalone Android builds also uses LMDB mode.
Other Android builds are shipped through GeckoView, where safe-mode was already
enabled.

Bug 1772148 - Remove rkv safe-mode toggle. It's default enabled now.

---

docs/dev/cut-a-new-release.md

Bug 1779411 - Document that release CI tasks can be rerun

---

glean-core/android/src/main/java/mozilla/telemetry/glean/Dispatchers.kt
glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt

This should delay loading the bundled library, which can be quite time
consuming itself.
---
This restores the minimal functionality from our previous Dispatcher.
I opted for that way because we know it works.
I have _not_ tested this in an app yet. In our tests we rely on test mode -> synchronous, so we're not exercising that code path. The sample app though should use that code path. We don't run sample app tests in CI though.

Bug 1756153 - Put Glean initialization on a async Kotlin task

---

CHANGELOG.md
glean-core/android/src/test/java/mozilla/telemetry/glean/private/PingTypeTest.kt
glean-core/ios/GleanTests/Metrics/PingTests.swift
glean-core/src/core_metrics.rs
glean-core/src/lib.rs

[backport from 465c09ce47e2e6c9f3abbd831ec964e9c45ede6b]
Also adding simple tests to check those are passed through the
Kotlin/Swift SDK.
---
Backports a single fix on top of the 50.1.2 release. Putting it up now, but we have not made the decision to cut this release yet.

Add back missing client_info metrics

---

glean-core/src/core/mod.rs
glean-core/src/lib.rs
glean-core/src/upload/mod.rs

If Glean is uninitalized a `Done` task is returned, instructing the
uploader to not request further upload tasks and finish.
Uploads might now be delayed until the next ping is submitted (or the app restarted),
but that was kinda already the case if this crashed anyway.
---
While I still don't know the actualy root cause of the crashes we've been seeing, this should mitigate it.

Bug 1781823 - Handle that Glean might be uninitalized when an upload task is requested

---

.buildconfig.yml
CHANGELOG.md
Cargo.lock
DEPENDENCIES.md
glean-core/Cargo.toml
glean-core/python/setup.py
glean-core/rlb/Cargo.toml
glean-core/src/core/mod.rs
glean-core/src/lib.rs
glean-core/src/upload/mod.rs
gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy

If Glean is uninitalized a `Done` task is returned, instructing the
uploader to not request further upload tasks and finish.
Uploads might now be delayed until the next ping is submitted (or the app restarted),
but that was kinda already the case if this crashed anyway.
---
Cherry-picked on top of v50.1.3
Original: https://github.com/mozilla/glean/pull/2131

Handle that Glean might be uninitalized when an upload task is requested [backport]

---

CHANGELOG.md
gradle-plugin/bin/main/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy

This check didn't work out as expected,
and caused more problems for us when updating Glean than it caught issues.
Now the consuming module need to ensure it uses a single version across all dependencies.

Bug 1782194 - Gradle plugin: Remove the version conflict check

---

glean-core/python/tests/metrics/test_timing_distribution.py

Hmm, not sure about the readme. Will fix tomorrow.
Anyway, here is the strategy I've cooked up (thanks stackoverflow!). It uses a guarded while loop (so, max number of iterations)
Here are the test results I did up quickly. Average over 100 loops for how much deviation there is from the desired time. While this doesn't perfectly mirror the test env or guarantee the problem is fixed, it should make that error far less likely.
I also tried using a small value for sleep and looping and checking but this was... not good lol
```
(base) pmcmanis@MacBook-Pro scratch % python time_loop_tests.py
sleep test average deviation 3.47556ms
sleep loop test average deviation 28.14823ms
perf counter test average deviation 0.0032599999999979447ms
guarded perf counter test average deviation …
```

1783739 sleep causing intermittent

---

CHANGELOG.md
Makefile
bin/update-glean-parser-version.sh
glean-core/ios/sdk_generator.sh
glean-core/python/glean/__init__.py
glean-core/python/requirements_dev.txt
glean-core/python/setup.py
gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy

In pip `~=V.N` is equivalent to `>= V.N, == V.*`
So we essentially allow everything from the specified minor version
upwards until the next major version (excluded).
As long as glean_parser is careful to not introduce breaking changes
before that this will simplify work a lot by allowing small bug fixes
without requiring subsequent Glean releases to bump versions all the
time.

Bug 1773262 - Relax glean_parser version requirement to "all compatible releases"

---

CHANGELOG.md
gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy

This was broken in the last release.
ec61a9ddf662cf2c574e9d195d861729a7bf2bff modified the wrong file.

Correctly remove the version conflict check.

---

taskcluster/ci/rust/kind.yml

Let's see if that fixes the issues we have.

TC: Limit to 6 test jobs on the Rust Beta tests

---

taskcluster/scripts/rustup-setup.sh

We set `set -x` early on, thus seeing all commands from rustup-setup.sh,
but then disable that afterwards.
The log then only shows the output, making it harder to understand what
output is from what command.
Now we just leave the `set -x` and it will apply to all the following
commands.

TC: Don't hide which tasks are executed anymore.

---

docs/dev/contributing.md

The [previous link was archived on MDN](https://github.com/mdn/content/pull/4599), so for now we will use this link until this section is rewritten.

Bug 1786279 - fix broken "engineering practices & quality standards" link

---

.circleci/config.yml
glean-core/rlb/src/test.rs

These tests cause test timeouts on TaskCluster with Rust Beta.
We don't know yet why, they run fine on CircleCI/Rust Stable.
We ignore them for the time being, but explicitly run them on CI.

Bug 1780410 - RLB: Ignore two tests by default, run them on CI.

---

.circleci/config.yml
glean-core/rlb/src/test.rs
taskcluster/ci/rust/kind.yml

This reverts commit 01b1770
We still haven't figured out why some tests keep stalling.
This only happens on the TaskCluster instances and is so far not
reproducible in any other environment, including a local Docker run.
I'm out of options here.
---
I've now run the tests hundred of times in my local Docker on a Linux machine, limiting it to 2 vCPUs and 4 G of RAM, same as the taskcluster instance has, with no success to make them fail in the same way.

Bug 1780410 - TC: Don't run Rust tests

---

.detekt.yml
CHANGELOG.md
glean-core/android/src/main/java/mozilla/telemetry/glean/scheduler/PingUploadWorker.kt
glean-core/ios/Glean/Net/HttpPingUploader.swift
glean-core/python/glean/net/ping_upload_worker.py
glean-core/rlb/src/net/mod.rs
glean-core/rlb/src/test.rs
glean-core/src/core/mod.rs
glean-core/src/glean.udl
glean-core/src/lib.rs
glean-core/src/upload/mod.rs
glean-core/src/upload/result.rs

Putting this up so it's up.
I want to discuss this with chutten when he's back.
I'm not super happy with it because the `UploadResult::Done` needs to be handled on a different layer than all the other `UploadResult` variants.
(It's also only implemented for the RLB right now)

Bug 1780806 - Allow the uploader to signal it is done handling uploads.

---

docs/user/user/pings/custom.md

Updating docs as a part of https://github.com/mozilla/glean.js/pull/1452

Bug 1723090 - Add note to `glean.restarted` docs about leading/trailing event omission

---

CHANGELOG.md
glean-core/python/tests/metrics/test_uuid.py
glean-core/src/metrics/uuid.rs

This fixes a regression in the Glean Python SDK.
We used to do this, but failed to correctly encode UUIDs since v50.
The Glean ping schema expects UUIDs in a hyphenated form a la `060f830d-3bcc-4a6a-b4b1-7336271a2b34`. However we passed the user data through without re-encoding, thus leading to non-hyphenated strings landing in the JSON payload of a ping and then getting rejected by the pipeline.
This is only an issue for Python, because for Kotlin and Swift we don't accept plain strings, but only `UUID` types, which serialize to hyphenated strings.

Bug 1789615 - Always store a UUID hyphenated

---

CHANGELOG.md
gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy

Should fix https://github.com/mozilla-mobile/fenix/issues/27053
Fixes #2192

Use single-quote to ensure code is valid when executed on Windows

---

Cargo.lock
glean-core/Cargo.toml
tools/embedded-uniffi-bindgen/Cargo.toml

I need to update Glean's UniFFI dependency to match what is used in Application-Services

Update UniFFI to v0.20.0 to match Application Services

---

CHANGELOG.md
docs/user/reference/metrics/url.md
glean-core/android/src/test/java/mozilla/telemetry/glean/private/UrlMetricTypeTest.kt
glean-core/ios/GleanTests/Metrics/UrlMetricTests.swift
glean-core/python/tests/metrics/test_url.py
glean-core/src/metrics/url.rs

Update the URL metric to have an 8k limit. Also updated the docs to reflect the new URL length.
Glean.js PR - https://github.com/mozilla/glean.js/pull/1513

Bug 1790949 - Bump URL metric limit to 8k

---

.buildconfig.yml
CHANGELOG.md
Cargo.lock
DEPENDENCIES.md
glean-core/Cargo.toml
glean-core/python/setup.py
glean-core/rlb/Cargo.toml
gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy

New release branch PR
[Full changelog](https://github.com/mozilla/glean/compare/v51.3.0...v51.4.0)
* Kotlin
* Update Kotlin and Android Gradle Plugin to the latest releases ([#2211](https://github.com/mozilla/glean/pull/2211))
* Swift
* Fix for iOS startup crash caused by Glean ([#2206](https://github.com/mozilla/glean/pull/2206))

Release v51.4.0

---

docs/user/reference/metrics/timing_distribution.md

Now that timing_distribution is being implemented in Glean.js, we no longer need to say that the API is not available.
Glean.js PR - https://github.com/mozilla/glean.js/pull/1475

Bug 1716954 - Update timing_distribution metric docs

---

docs/user/reference/metrics/memory_distribution.md

Added JS examples in the Glean Book now that we support `memory_distribution`s in Glean.js https://github.com/mozilla/glean.js/pull/1514. These examples mimic the rest of the `memory_distribution` examples.

Bug 1716952 - Add JS examples to memory_distribution metric docs

---

docs/dev/cut-a-new-release.md

The "spelling error" is `CircleCI`, which is used a few lines prior

[doc only] Updates instructions to be more clear around release steps

---

docs/user/reference/metrics/custom_distribution.md

Added JS examples in the Glean Book now that we support custom_distributions in Glean.js https://github.com/mozilla/glean.js/pull/1516. These examples mimic the rest of the custom_distribution examples.

Bug 1716951 - Add JS examples to custom_distribution metric docs

---

build.gradle

This was done in AC a long time ago. I don't think we need to do anything more other than changing the name given the limited usage in this case, but some local testing would be appreciated by someone with a working environment.

Switch from deprecated digital.wup.android-maven-publish to maven-publish plugin

---

.dictionary
CHANGELOG.md
Cargo.lock
glean-core/Cargo.toml
tools/embedded-uniffi-bindgen/Cargo.toml

Also updated the changelog while I was at it.

Upgrade to UniFFI 0.21.0

---

.circleci/config.yml

I manually applied these steps for the 51.5.0 release just now.

Use Python 3.10 on macOS release builds

---

CHANGELOG.md
glean-core/Cargo.toml
glean-core/rlb/Cargo.toml
glean-core/src/dispatcher/global.rs

Firefox Desktop appears confident in its ability to always init Glean _eventually_, and is willing to bet a few MB to that end.

bug 1796258 - Introduce cargo feature `preinit_million_queue`

---

docs/user/_includes/label-errors.md
docs/user/_includes/label-limits.md
docs/user/_includes/labels-parameter.md
docs/user/reference/metrics/labeled_booleans.md
docs/user/reference/metrics/labeled_counters.md
docs/user/reference/metrics/labeled_strings.md
glean-core/src/metrics/ping.rs
glean-core/src/upload/mod.rs
glean-core/tests/labeled.rs

These docs are relevant for the set/add methods, so better to call them out there and then.
To reduce copy-pasta I pulled that info out into includes.
[doc only]

Bug 1797934 - Pull up label limits to the recording API docs

---

glean-core/build/src/lib.rs

glean-build: Pull out `default` method as trait impl

---

CHANGELOG.md
glean-core/ios/Glean/Net/HttpPingUploader.swift

If I understood the documentation right the worst that should happen here is that we leak memory until the application quits. Now if our assumption is right and the crashes happen when the app gets backgrounded it eventually quits anyway and we should be fine.

Try to avoid a crash by not invalidating upload sessions

---

glean-core/src/internal_pings.rs

This is already defined in the `metrics.yaml`, but was not adjusted in the code.
Luckily right now there's always a metric in there (`first_run_hour`), so it was never empty to begin with.

Ensure the baseline ping is sent when empty

---

docs/user/reference/metrics/datetime.md
docs/user/reference/metrics/memory_distribution.md
docs/user/reference/metrics/timespan.md
docs/user/reference/metrics/timing_distribution.md

Bug 1799852 - Document `time_unit` and `memory_unit` as optional parameters

---

CHANGELOG.md
build-scripts/xc-universal-binary.sh
glean-core/bundle-android/Cargo.toml
samples/ios/app/glean-sample-app.xcodeproj/project.pbxproj

`--crate-type` was stabilized in cargo 1.64.0 (cargo#10838)

iOS: Build _only_ a staticlib.

---

glean-core/src/error_recording.rs

No bug. See discussion: https://github.com/mozilla-mobile/mozilla-vpn-client/pull/4919#discussion_r1021961072

Allow ErrorType to be passed thorugh an FFI boundary

---

CHANGELOG.md
Cargo.lock
glean-core/Cargo.toml

This contains an important bug fix: Data is now written to a temporary file before being moved to the final database file location. This avoids truncated database files in case the write gets interrupted.

Update to rkv 0.18.3

---

glean-core/Cargo.toml

glean-core shouldn't be making this decision for its users.

Disable env_logger features in glean-core

---

build.gradle
glean-core/Cargo.toml
glean-core/bundle-android/Cargo.toml
glean-core/src/lib.rs

This has no immediate effect on any other usage.
It's still in use as a dev-dependency in Rust (and thus can be enabled for tests).
It also is active for local builds of Glean for Android for testing.

Bug 1804632 - Include `env_logger` only in debug builds

---

CHANGELOG.md
glean-core/android/src/main/java/mozilla/telemetry/glean/debug/GleanDebugActivity.kt
glean-core/android/src/main/java/mozilla/telemetry/glean/scheduler/MetricsPingScheduler.kt
glean-core/android/src/test/java/mozilla/telemetry/glean/debug/GleanDebugActivityTest.kt

I tried testing this with the instructions from https://bugzilla.mozilla.org/show_bug.cgi?id=1808231#c29
but wasn't able to reproduce the issue to begin with.
However I was able to trigger the behavior by just running the debug activity myself a couple of times with Fenix closed before:
```
adb shell am start -n org.mozilla.fenix/mozilla.telemetry.glean.debug.GleanDebugActivity --ez logPings true --es debugViewTag jer-fenix --es sendPing metrics
```
That eventually gave me the log message.
With this PR applied everything still seems to work and it sends pings as expected once Glean is initialized.

Bug 1808586 - Kotlin: GleanDebugActivity can run without Glean being initialized 

---

docs/user/user/metrics/validation-checklist.md

Update to the book to indicate that distributions take a few days to settle. I also made a change to temper language in one spot that I noticed right afterwards.

Documentation update to indicate time for distribution 

---

.buildconfig.yml
.dictionary
CHANGELOG.md
Cargo.lock
DEPENDENCIES.md
glean-core/Cargo.toml
glean-core/android-native/dependency-licenses.xml
glean-core/android/dependency-licenses.xml
glean-core/python/setup.py
glean-core/rlb/Cargo.toml
glean-core/rlb/src/system.rs
gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy

Bugfix for broken windows build due to whatsys changes
```markdown
* General
* BUGFIX: Properly invoke the windows buildid function from whatsys ([bug 1812672](https://bugzilla.mozilla.org/show_bug.cgi?id=1812672))
```

Release v52.1.1

---

.circleci/config.yml
Cargo.lock
README.md
glean-core/Cargo.toml
glean-core/build.rs
glean-core/build/Cargo.toml
glean-core/rlb/Cargo.toml
glean-core/src/lib.rs
tools/embedded-uniffi-bindgen/Cargo.toml

This adopts the new crate layout and only directly depends on the `uniffi` crate.
Everything else is a transitive dependency. This hopefully reduces the amount of churn and coordination needed when uniffi_* crates are updated.
---
~~v0.23 is not yet released. This currently uses it from the git repository.~~

Update to UniFFI 0.23

---

glean-core/ios/GleanTests/Metrics/LabeledMetricTests.swift
glean-core/ios/GleanTests/Metrics/PingTests.swift
glean-core/ios/GleanTests/Scheduler/MetricsPingSchedulerTests.swift

This test takes up to 40s on a dev machine and closer to 70s on CI.
The underlying implementation has changed since the regression.
We also still have tests for this in Kotlin and Python (Python takes ~7s),
so we can keep those only.
Second commit reduces timeouts just a tiny bit.
Both commits can be reviewed on each own and also separate landed.

Swift: Remove super long-running test

---

.circleci/config.yml
CHANGELOG.md
glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt
glean-core/ios/Glean/Glean.swift
glean-core/python/glean/glean.py
glean-core/rlb/examples/long-running.rs
glean-core/rlb/src/lib.rs
glean-core/rlb/src/net/mod.rs
glean-core/rlb/tests/test-shutdown-blocking.sh
glean-core/src/dispatcher/global.rs
glean-core/src/glean.udl
glean-core/src/lib.rs

RLB: Wait for uploader on shutdown using new `shutdown` mechanism
On shutdown we now wait up to 30s for the upload thread to finish.
This gets done just after we drain and shut down the dispatcher,
but before Glean is considered fully shutdown.
The callback MUST NOT put any new tasks on the dispatcher.
The callback SHOULD NOT block arbitrarily long.
The RLB implementation of that callback instructs a potential uploader
thread to end operation after it finished one upload.
It also blocks any new upload thread from getting started.
This means an in-flight upload can finish as usual, but no new one
is launched.
If the upload thread is currently sleeping, it gets one more upload.
This also adds a new test.
The only way to reliably test this is from the outside,
so the test invokes an example …

Bug 1749510 - RLB: Wait for uploader on shutdown using new shutdown mechanism

---

glean-core/rlb/tests/schema.rs
glean-core/src/lib_unit_tests.rs
glean-core/src/metrics/string.rs
glean-core/src/metrics/text.rs
glean-core/src/metrics/url.rs
glean-core/src/ping/mod.rs
glean-core/src/upload/mod.rs
glean-core/tests/custom_distribution.rs
glean-core/tests/datetime.rs
glean-core/tests/labeled.rs
glean-core/tests/memory_distribution.rs
glean-core/tests/ping.rs
glean-core/tests/ping_maker.rs
glean-core/tests/quantity.rs
glean-core/tests/string.rs
glean-core/tests/string_list.rs
glean-core/tests/text.rs
glean-core/tests/timespan.rs
glean-core/tests/timing_distribution.rs
glean-core/tests/uuid.rs

Binding to `_` _immediately_ drops the value.
This causes the temp directory to be removed, which in turn causes errors when writing into the database.
Surprisingly enough things keep working for tests to still work*!
* Because we have all data in-memory anyway.

Rust testing: Always keep a handle to the temporary directory

---

glean-core/ios/Glean/Glean.swift
glean-core/ios/GleanTests/Net/BaselinePingTests.swift

This puts an interlock on calling `glean_handle_active` to ensure it is only called once until `glean_handle_inactive` is called.

Bug 1716847 - Fix for Glean internal metric `baseline.duration` InvalidState errors

---

Cargo.lock
glean-core/Cargo.toml

This avoids some dep updates that clash when getting pulled into m-c.

Rust: Downgrade oslog dependency to avoid cascading dep updates

---

samples/android/app/README.md

The "Setup the Android Build Environment" link in the android sample project was broken.

Fix android setup link in sample project readme

---

CHANGELOG.md
glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt
glean-core/ios/Glean/Glean.swift
glean-core/ios/Glean/Net/HttpPingUploader.swift
glean-core/metrics.yaml
glean-core/rlb/src/lib.rs
glean-core/rlb/tests/upload_timing.rs
glean-core/src/glean.udl
glean-core/src/internal_metrics.rs
glean-core/src/lib.rs
glean-core/src/metrics/timing_distribution.rs
glean-core/src/upload/mod.rs

This PR does multiple things:
* Bring back #2365 -- that's the first 3 commits, cherry-picked unchanged (#2374 reverted them)
* Refactors the uploader shutdown to be used in test reset 
* Implement uploader shutdown in Swift
* This is only used in test mode, because `glean::shutdown` is not called by the iOS bindings
* Tries to be a bit more defensive for the newly introduced timing distributions done in the uploader.
Out of 20+ runs locally I had only 3 test failures ("No database found"). I don't fully understand why that still happens.
But hey, with only #2365 we had 7 tests fail basically every time. Improvement!
Especially the last part though bugs me. The iOS uploader still has some runs where it does some work after we told it to shut ~~up~~ down. And yet it happens in some tests. …

Bug 1814592 - Instrument the time needed for a successful/failure upload of a ping & upload shutdown in testing

---

taskcluster/ci/beetmover/kind.yml
taskcluster/ci/signing/kind.yml
taskcluster/glean_taskgraph/loader/build_config.py
taskcluster/glean_taskgraph/loader/multi_dep.py

This fixes a couple places I neglected to convert when upgrading Taskgraph.
Issue: #2388

Rename 'job' -> 'task' in Taskgraph's multi_dep loader

---

glean-core/src/database/mod.rs

As discussed, this change only covers having this log in case of a DatabaseError.
I could find no tests around InvalidFile so I have not included any new ones.
This change is small enough that I wasn't sure a changelog entry was justified, especially given this isn't a change external folks should ever notice.

Bug 1820792 - handle rkv DatabaseCorrupted error by creating a new rkv

---

Cargo.lock

This should remove the last dependency on the potential vuln `remove_dir_all@0.5.3`

Bug 1820927 - Update tempfile crate

---

.circleci/config.yml
taskcluster/scripts/rustup-setup.sh

It became available in Rust 1.68.0
Additionally lets avoid incremental builds on CI.
That's just extra work which we don't need there.

Use the sparse protocol everywhere

---

Cargo.lock
glean-core/Cargo.toml
glean-core/src/event_database/mod.rs
glean-core/src/lib.rs
glean-core/src/ping/mod.rs

This avoids the Windows dependencies.
The bug that caused us to switch to the crate in the first place was addressed in Rust 1.66+ (https://github.com/rust-lang/rust/pull/104558)

Revert to libstd's remove_dir_all instead of external crate.

---

glean-core/python/glean/glean.py

This avoids an error message being logged because the function couldn't be called.
This also removes some debug logging.

Bug 1821254 - Python: Implement an empty shutdown function

---

.github/workflows/cargo-vet.yml
supply-chain/audits.toml
supply-chain/config.toml
supply-chain/imports.lock

I had a call with @perrymcmanis144 to discuss how we could make cargo-vet work more smoothly for glean. One issue we identified is that all of the auditing currently falls to the person vendoring glean into m-c, which is intended to be a more mechanical task. Ideally auditing would happen when the dependencies are added upstream, since that person has more context (and is also better able to weigh the trade-offs of auditing a big dependency versus finding a way to avoid it).
We can then pull the audits from glean into our [aggregated set](https://github.com/mozilla/supply-chain), which will make them automatically available to Firefox.

Set up cargo-vet instance

---

docs/dev/core/internal/payload.md
docs/user/reference/metrics/string.md
docs/user/reference/metrics/string_list.md
glean-core/rlb/tests/schema.rs

Bug 1820611 - Document string list behavior with empty lists

---

glean-core/src/core/mod.rs
glean-core/src/metrics/memory_distribution.rs

The "No database found" message is unique, so we _always_ know that it
happens in exactly that line.
That's not helpful during debugging though. We want to know which part
requested storage.
`track_caller` does that.
See https://doc.rust-lang.org/reference/attributes/codegen.html#the-track_caller-attribute
---
This is more of a workaround than a fix and we should eventually follow this up with properly addressing this in a more holistic way

Bug 1818361 -  Prevent another test-only issue: The storage going away when the uploader reports back its status

---

CHANGELOG.md
glean-core/src/database/mod.rs

Putting this up so we can discuss/not forget about it

Bug 1820792 - Create new RKV on DatabaseCorrupted Error and log error

---

CHANGELOG.md
glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt
glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt
glean-core/ios/Glean/Glean.swift
glean-core/ios/GleanTests/GleanTests.swift
glean-core/rlb/src/lib.rs
glean-core/src/core/mod.rs
glean-core/src/glean.udl
glean-core/src/lib.rs
glean-core/src/lib_unit_tests.rs
glean-core/src/metrics/metrics_enabled_config.rs
glean-core/src/metrics/mod.rs

This is in order to simplify the understanding of how the API works to a more natural form.

Bug 1811253 - Invert remote metric config logic

---

.circleci/config.yml

The default, `medium`, is gen1 and will be deprecated completely in October.
---
Let's try this out and see how much faster it is.

Bug 1826132 - CI: Switch to gen2 macos builders

---

glean-core/rlb/src/private/mod.rs
glean-core/rlb/src/test.rs

I added a test just to make sure the private version of TextMetric was being used. 
Do we have a canonical string for long entries? I'm not sure movie quotes are appropriate here

Bug 1828528 - add TextMetric entry to private mod.rs

---

glean-core/src/event_database/mod.rs

Detailed explanation in https://rust-lang.github.io/rust-clippy/master/index.html#lines_filter_map_ok We're unlikely to hit this, because `entry` is a file and thus continued read errors are unlikely.
But better be safe than sorry.

Apply clippy lint: Avoid potential infinite loop

---

CHANGELOG.md
glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt

This changes `setLogPings` and `setDebugViewTag` from internal to public access. This _doesn't_ make `sendPingsByName` public as that API is a bit trickier to use directly.

Bug 1830937 - Make `setLogPings` and `setDebugViewTag` public for Android

---

glean-core/ios/Glean/Utils/Logger.swift

Ok so, when I try to see Glean logs from an iOS device using `log` I just get `<private>` for all Glean messages. According to [this Stack Overflow](https://stackoverflow.com/questions/45908875/apple-iphone-debugging-with-console-private) that is because all dynamic strings are by default private. I made this change locally and I can now see the messages, would it be possible to get this merged? Thanks!

Proposal: Make Glean Swift logs public by default

---

.circleci/config.yml
taskcluster/ci/android-build/kind.yml
taskcluster/ci/module-build/kind.yml
taskcluster/ci/rust/kind.yml

Since we already run CI when merging this branch back to main, we can skip running it on the release branch

Bug 1827452 - Skip running CI on the release branch

---

CHANGELOG.md
glean-core/src/traits/timing_distribution.rs

This exposes `accumulate_samples` and `accumulate_raw_samples_nanos` in the TimingDistribution traits

Bug 1829745 - Expose accumulate samples APIs for TimingDistribution

---

CHANGELOG.md
glean-core/ios/Glean/Glean.swift

I forgot to ask for Swift changes on https://bugzilla.mozilla.org/show_bug.cgi?id=1830937. Can we get this change as well? 🥺

Proposal: Make Swift debug APIs public as well

---

docs/user/reference/general/initializing.md

Add a step to the docs to call `setDefaultMainProcess` to ensure pings are sent.

Bug 1831181 - android multi-process doc updates

---

.dictionary
docs/user/user/metrics/data-control-plane/advanced-topics.md
docs/user/user/metrics/data-control-plane/example-scenarios.md
docs/user/user/metrics/data-control-plane/experimenter-configuration.md
docs/user/user/metrics/data-control-plane/faq.md
docs/user/user/metrics/data-control-plane/index.md
docs/user/user/metrics/data-control-plane/product-integration.md

This adds documentation about the Glean Data Control Plane functionality (a.k.a. Server Knobs).

Bug 1826973 - Add Data Control Plane user documentation

---

.dictionary
CHANGELOG.md
glean-core/ios/Glean/Glean.swift
glean-core/ios/GleanTests/GleanTests.swift
glean-core/src/glean.udl
glean-core/src/lib.rs

This simply awaits the internal dispatcher which is where the pings are submitted from.

Bug 1832324 - Add a way to await ping submission in iOS 

---

CHANGELOG.md
docs/user/user/metrics/data-control-plane/advanced-topics.md
docs/user/user/metrics/data-control-plane/faq.md
docs/user/user/metrics/data-control-plane/product-integration.md
glean-core/src/core/mod.rs
glean-core/src/lib_unit_tests.rs

This merges configurations regardless of feature ID. A much simpler approach that basically offers the same protections as adding the additional feature-id stuff on top.

Bug 1833381 - Add capability to merge remote metric configs

---

.dictionary
CHANGELOG.md
docs/user/reference/metrics/string_list.md
glean-core/android/src/test/java/mozilla/telemetry/glean/private/StringListMetricTypeTest.kt
glean-core/ios/GleanTests/Metrics/StringListMetricTests.swift
glean-core/python/tests/metrics/test_string_list.py
glean-core/src/metrics/string_list.rs
glean-core/tests/string_list.rs

This increases the length of strings allowed in the list from 50 to 100 utf8 bytes to match the `StringMetric` type, as well as increasing the total number of strings allowed in the list from 20 to 100.

Bug 1833870 - Increase StringList metric type limits

---

taskcluster/docker/linux/Dockerfile

The main motivation to do this is to point to the now-canonical repo for tooltool.py. As an added bonus, it now has proper python3 support, so we can remove python2 from the Docker image we're using. That would in turn have ended up blocking our ability to update to a newer Ubuntu base as it's no longer distributed with 22.04.

Update tooltool.py to the latest upstream version

---

.circleci/config.yml
.circleci/jazzy.yml
CHANGELOG.md
bin/run-ios-build.sh
bin/run-ios-sample-app-build.sh
bin/run-ios-sample-app-test.sh
bin/run-ios-tests.sh
glean-core/ios/Glean.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
samples/ios/app/glean-sample-app.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

This is essentially a revert of the revert-commit f941d76 again.
---
We can hold off until our consumers are good to go with this.

Bug 1821437 - Upgrade to Xcode 14.0

---

glean-core/python/glean/metrics/datetime.py

mypy found this for me.
```
glean-core/python/glean/metrics/datetime.py:107: error: Incompatible types in assignment (expression has type "datetime", variable has type "Optional[Datetime]")  [assignment]
glean-core/python/glean/metrics/datetime.py:117: error: Incompatible return value type (got "Datetime", expected "Optional[datetime]")  [return-value]
```

Python: Avoid variable shadowing to avoid type confusion

---

glean-core/ios/GleanTests/GleanTests.swift
glean-core/ios/GleanTests/TestUtils.swift

This ensures it's a known type and avoids the warning
"empty collection literal requires an explicit type"

Swift (testing): Use a string as the json object

---

glean-core/src/lib.rs

Tested manually by running exceedingly short ( under 1s ) sessions on a self-built Firefox. A broad-spectrum tryrun is underway to ensure we haven't regressed anything we specifically care about: https://treeherder.mozilla.org/jobs?repo=try&revision=1f4ee9d8392cc0db1000c59b1c38eb573cfb2c6e

bug 1839433 - Try blocking shutdown 10s for init to complete

---

build.gradle
glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt

Changelog: https://github.com/pinterest/ktlint/releases/tag/0.50.0
Nothing super interesting in this update other than getting more strict about how suppressions are declared.

Update ktlint to version 0.50.0 and fix new warnings

---

build.gradle
glean-core/android/src/main/java/mozilla/telemetry/glean/Dispatchers.kt
gradle/wrapper/gradle-wrapper.properties

Doing this as a roll-up since it's just a handful of minor bugfix updates.

Update some Gradle dependencies

---

glean-core/ios/Glean/Glean.swift
glean-core/ios/Glean/Metrics/UuidMetric.swift

Frequently, we don't want to use the return of a UUID metric's `generateAndSet` function, or the result from `setDebugViewTag`.
However, this leaves warnings in Xcode and at build time:
[Swift has](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/attributes/#discardableResult) the `discardableResult` attribute to suppress these warnings, commonly used for functions whose return will often be unused - like these two.

Suppress Swift warnings

---

CHANGELOG.md
glean-core/python/glean/glean.py
glean-core/python/tests/test_glean.py

I manually tested it, using a sample app (maybe I should commit the sample app...)

Bug 1842821 - Python: Export the `shutdown` API

---

.dictionary
CHANGELOG.md
glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt
glean-core/android/src/main/java/mozilla/telemetry/glean/scheduler/PingUploadWorker.kt
samples/android/app/build.gradle
samples/android/app/metrics.yaml
samples/android/app/pings.yaml
samples/android/app/src/androidTest/java/org/mozilla/samples/gleancore/pings/BackgroundPingTest.kt
samples/android/app/src/main/AndroidManifest.xml
samples/android/app/src/main/java/org/mozilla/samples/gleancore/GleanApplication.kt
samples/android/app/src/main/java/org/mozilla/samples/gleancore/MainActivity.kt
samples/android/app/src/main/java/org/mozilla/samples/gleancore/SampleBackgroundProcess.kt

When Glean attempted to schedule an upload task on the WorkManager from a background process
it would get the main-process Glean when the task was executed. Since the main-process Glean
didn't have the data directory from the background process, it would not find the ping to be
able to upload it. This changes the uploader to run on the internal Glean Dispatcher when it
is being run from a background service or process and continues to rely on WorkManager for
the main process execution.

Bug 1844533 - Fixes Glean ping uploading from background services in Kotlin

---

.github/dependabot.yml

This will reduce individual PRs in favor of a single PR updating multiple dependencies.
See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
[doc only]

Dependabot: Group all Python package updates

---

.dictionary
docs/user/user/metrics/data-control-plane/example-scenarios.md
docs/user/user/metrics/data-control-plane/product-integration.md

This updates the current Server Knobs documentation to reflect recent Nimbus updates which add support for multiple features in a single rollout or experiment.

Bug 1848616 - Update the Server Knobs documentation

---

CHANGELOG.md
build.gradle

Not changing the target SDK yet as 33 is still the target for AC, but we need to use SDK34 for compatibility with some newer dependencies.

Switch to Android SDK 34

---

docs/user/reference/metrics/event.md

Docs only
This issue was reported by agibson when using the newest version (v2.0.2) of Glean.js.

Bug 1854678 - maxEvents=1 docs clarifying comments

---

docs/dev/book.toml
docs/user/book.toml

This should enable a button to edit the current page via github, as documented [in the mdbook docs](https://rust-lang.github.io/mdBook/format/configuration/renderers.html)

Enable edit this page on our documentation

---

docs/user/reference/metrics/event.md

This removes the scary box around "not use events", since this is confusing for non-native applications developers.
This further clarifies a question about "when are events sent" which keeps coming up.

Clarify events usage and immediacy

---

.github/dependabot.yml

This reverts commit cbe5ef9be06359a7b218c008834c3bae145b88c9
---
The bundling didn't play out as I hoped it would.
The PR titles are now less descriptive ("Bump the python-packages group in /glean-core/python with 1 update") and still mostly contain only a single dependency update.
Feels like reverting this thus is better.

Revert "Dependabot: Group all Python package updates"

---

.circleci/config.yml
.github/workflows/cargo-vet.yml
Cargo.lock
README.md
deny.toml
glean-core/Cargo.toml
glean-core/build/Cargo.toml
glean-core/rlb/Cargo.toml
samples/rust/Cargo.toml
supply-chain/audits.toml
supply-chain/config.toml
supply-chain/imports.lock

Update dependencies to bring in line with mozilla-central

---

supply-chain/audits.toml
supply-chain/imports.lock

I publish this crate, so a wildcard is more appropriate than a trusted marker.
[doc only]

Add a wildcard audit for jsonschema-valido

---

Cargo.lock
glean-core/build/Cargo.toml
glean-core/build/src/lib.rs

This is needed for Python 3.12 (https://github.com/python/cpython/issues/95299)
(I hit this after upgrading to Fedora 39 and trying to build app-services)

Install setuptools in Builder

---

glean-core/src/ping/mod.rs

While technically part of the API since forever, it was never part of the supported public API and not used within the SDK either.

Bug 1809317 - Rust: Remove `collect_string` method

---

taskcluster/requirements.in
taskcluster/requirements.txt

This fixes a regression from 7.0.0 that was causing actions to fail.

CI: Upgrade Taskgraph to 7.0.2

---

gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy

Tested locally and this seems to be enough for moving forward with https://bugzilla.mozilla.org/show_bug.cgi?id=1870050.
Also, before going even further https://github.com/mozilla/glean/pull/2680 IMO this would be a good test to see if moving to Task Configuration Avoidance would be smooth.

Bug 1870048 - Replace whenTaskAdded with configureEach to avoid unnecesary configuration.

---

Cargo.lock
glean-core/Cargo.toml
supply-chain/audits.toml

I see a couple of failures locally on Windows:
* database::test::safe_mode::migration_doesnt_overwrite
* database::test::safe_mode::migration_ignores_empty_database
But these two fail even without the update, so 🤷

Bug 1873911 - Update rkv to 0.19.0

---

.circleci/config.yml

There's no `latest` tag.
For publishing we're good with a up-to-date Rust.
We have a separate task for testing our own MSRV (and have Cargo.lock committed for reproducible builds).
[docs only]
(not really docs, but doesn't change any CI related things other than release)

CI: Pick the current Rust for the publish task

---

CHANGELOG.md
build.gradle

Just seeing how CI likes this right now. Need to coordinate merging with the Android team as getting Fenix bumped to API34 is high-priority.

Set the target Android SDK to version 34

---

CHANGELOG.md
glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt

Fixes an incorrect method name that slipped through review.

Fix incorrect method name in Kotlin

---

CHANGELOG.md
docs/user/SUMMARY.md
docs/user/reference/general/glean-event-listener.md
docs/user/reference/general/index.md
glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt
glean-core/android/src/test/java/mozilla/telemetry/glean/private/EventMetricTypeTest.kt
glean-core/android/src/test/java/mozilla/telemetry/glean/utils/DateUtilsTest.kt
glean-core/ios/Glean/Glean.swift
glean-core/ios/GleanTests/GleanTests.swift
glean-core/ios/GleanTests/Metrics/EventMetricTests.swift
glean-core/src/glean.udl
glean-core/src/lib.rs
glean-core/src/metrics/event.rs

This adds a method for a consuming application to register an event listener to receive notifications when events are recorded.

Prototyping a Glean Event Listener

---

glean-core/src/lib.rs

Now that Mutex, Vec and String have const `new` methods, we don't need the OnceCell anymore and can just use the statics directly.
This should still be safe:
* Everything still behind a Mutex, and thus thread-safe
* We previously didn't reset those values, and we still don't other than setting the Mutex-locked wrapped value
---
This is the followup I promised in #2719 comments

Rust: Remove `OnceCell`s around Mutexes

---

Cargo.lock
glean-core/rlb/Cargo.toml

These are unused or only used in tests.
---
`cargo clippy -- -D unused_crate_dependencies` uncovered these.

Remove some direct dependencies from RLB

---

docs/user/reference/metrics/object.md

This breaks page layout a bit at the moment.
[doc only]

Docs: Remove unneeded warning header

---

.circleci/config.yml
deny.toml

Updates for:
* ghr
* cargo-deny
* mdbook-dtmo
---
Just noticed some warnings/failures after installing `cargo-deny` locally

Update some CI tools

---

gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy

The super-old version of Miniconda we were using included only Python 3.7 Python 3.7 is EoL and glean_parser dropped support for it.
---
Tested on my macbook and on my Linux machine.

Bug 1775420 - Glean Gradle plugin: Upgrade to Miniconda 24.3.0 (and Python 3.11)

---

.cargo/config.toml
.circleci/config.yml
Cargo.lock
Cargo.toml
Makefile
bin/uniffi-bindgen
glean-core/bundle/Cargo.toml
glean-core/ios/Glean.xcodeproj/project.pbxproj
glean-core/rlb/tests/test-shutdown-blocking.sh
glean-core/rlb/tests/test-thread-crashing.sh
pyproject.toml
tools/embedded-uniffi-bindgen/Cargo.toml
tools/embedded-uniffi-bindgen/src/lib.rs

Turns out we currently cannot actualy install glean-sdk from just the source distribution (sdist).
This PR should tackle that.
The following now works:
```
$ make build-python-sdist
$ cd samples/python
$ python3 -m venv venv
$ venv/bin/python3 -m pip install setuptools  # only needed for Python 3.12 I guess -- we should fix that
$ venv/bin/python3 -m pip install ../../target/wheels/glean_sdk-*.tar.gz
```
I plan on filing a bug with `maturin` so they can fix up (or remove) `default-members` when they rewrite the `Cargo.toml`.
I think it should be fine for us for now to not have it be a `default-member`: `make build-rust` invokes `cargo build --all` anyway

Bug 1891744 - Python: make installing from sdist possible

---

CHANGELOG.md
glean-core/rlb/tests/timing_distribution_single_sample.rs
glean-core/src/metrics/timing_distribution.rs
glean-core/src/traits/timing_distribution.rs

Unfortunately I can't find timing_distribution tests that have a dispatcher, so I can't test this new API. Luckily, aside from a Duration -> u128 -> u64 conversion chain, all the logic is in accumulate_raw_samples_nanos_sync which is covered.

bug 1892097 - New TimingDistribution API for a single duration.

---

docs/user/reference/general/glean-event-listener.md

Fix "examples" missing header include

Fix docs:  glean-event-listener.md

---

gradle/libs.versions.toml

Version 0.9.4 has the fix for mozilla/rust-android-gradle#145. My NDK lives in a "non-standard" location (I'm using the one that `./mach bootstrap` installs), and 0.9.3 doesn't extract the version from it correctly.
We bumped App Services to 0.9.4 in mozilla/application-services#6210; I bumped Glean locally while working on https://phabricator.services.mozilla.com/D206066, and thought I'd send y'all the patch 😊 Thanks!

Bump `rust-android-gradle` to 0.9.4.

---

.circleci/config.yml

These are twice as costly per usage minute.
macos.x86.medium.gen2 will be gone in June 2024.
Maybe the raw performance makes up for the increase in costs.

Bug 1893207 - CI: Switch to M1 medium workers

---

glean-core/src/event_database/mod.rs
glean-core/src/histogram/exponential.rs
glean-core/src/histogram/linear.rs
glean-core/tests/counter.rs
glean-core/tests/timing_distribution.rs

We use this lock to synchronize the file access outside of it.
Thus we always need an exclusive lock, which is why we always used a `write` lock.
But if that's all we need a `Mutex` is really just good enough.
And newer Clippy was complaining about that

event database: Use a Mutex instead of a RwLock

---

glean-core/python/glean/__init__.py
samples/python/requirements.txt

importlib.metadata is available since Python 3.8, the minimum Python we support.

Bug 1894635 - Python: Use importlib.metadata instead of deprecated pkg_resources

---

.circleci/config.yml
tools/docker-winbuild/Dockerfile
tools/docker-winbuild/README.md
tools/docker-winbuild/build.sh
tools/docker-winbuild/init.sh
tools/patches/bcryptprimitives.rs

This brings along a minimal shim for bcryptprimitives.dll. It's really minimal and _only_ necessary for the Wine build.
How I got there? Well, I found https://github.com/rust-lang/rust/commit/07633821ed63360d4d7464998c29f4f588930a03
I'm not even sure if we need the `ProcessPrng` implementation, but I'm not here to find out.
What didn't work? Setting `WINEPATH` to the directory. It still won't find the library. Preloading it once though fixes it all.
It now seems to work in CI again.
And it does work in a Docker container as well.
The reason it worked on my machine: On Fedora wine brings along the bcryptprimitives.dll

CI: Build a bcryptprimitives shim for loading it in Python

---

glean-core/android/src/main/java/mozilla/telemetry/glean/testing/GleanTestRule.kt
glean-core/android/src/test/java/mozilla/telemetry/glean/GleanFromJavaTest.java
glean-core/android/src/test/java/mozilla/telemetry/glean/TestUtil.kt
glean-core/android/src/test/java/mozilla/telemetry/glean/private/AccumulationsBeforeGleanInitTest.kt
glean-core/android/src/test/java/mozilla/telemetry/glean/scheduler/MetricsPingSchedulerTest.kt
glean-core/android/src/test/java/mozilla/telemetry/glean/scheduler/PingUploadWorkerTest.kt

This fixes the leaked sqlite database errors found when using the GleanTestRule and also when running Glean android tests. Thanks to :jonalmeida for pointing us to the fix.

Bug 1719905 - Fixes leaked sqlite database in Android GleanTestRule

---

docs/user/SUMMARY.md

GitHub doesn't normalize a double-slash, and thus the link doesn't work correctly.
[doc only]

Remove double-slash in doc link

---

CHANGELOG.md
glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt
glean-core/ios/Glean/Glean.swift
glean-core/python/glean/glean.py
glean-core/python/glean/net/ping_upload_worker.py
glean-core/rlb/src/configuration.rs
glean-core/rlb/src/lib.rs
glean-core/rlb/src/test.rs
glean-core/src/core/mod.rs
glean-core/src/glean.udl
glean-core/src/lib.rs
glean-core/src/lib_unit_tests.rs
glean-core/src/metrics/ping.rs
glean-core/tests/common/mod.rs
glean-core/tests/event.rs
glean-core/tests/ping_maker.rs

This now adds a configuration option to pass a map along that would otherwise be set on the individual ping instances.
It thus works for the builtin pings.
The ping-specific list still works and is preferred, only if empty we go for the top-level map.
Aside:
Note that this is _technically_ a breaking change because the whole configuration is public and we cannot provide default values in Rust (we should really fix that as a breaking-change-thing).
If we go this route I'd still vote for handling this as a feature change only (and we'll mark the non-builder Rust API as "private", so changing it isn't a breaking change anymore). This saves us from the hefty coordination with a-s.
Consumers are fine either way, because we can handle the defaults in the bindings and for RLB we're the only ones …

Bug 1897219 - Add a global map of ping->[ride-along-pings] so we can correctly call it

---

CHANGELOG.md
glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt
glean-core/android/src/main/java/mozilla/telemetry/glean/config/Configuration.kt
glean-core/android/src/test/java/mozilla/telemetry/glean/scheduler/MetricsPingSchedulerTest.kt
glean-core/rlb/src/lib.rs
glean-core/src/database/mod.rs
glean-core/src/glean.udl
glean-core/src/lib.rs
samples/android/app/src/main/java/org/mozilla/samples/gleancore/GleanApplication.kt

For some documentation (also in the commit message):
Persist ping-lifetime data after 1000 writes
We now automatically flush data to disk after 1000 writes into the
in-memory ping-lifetime map.
If `delay_ping_lifetime_io` is set to true, the data is now flushed to
disk in these cases:
* When `persist_ping_lifetime_data` is called by the application.
* At shutdown (that calls `persist_ping_lifetime_data`) automatically.
* Every 1000 writes
* Calling `persist_ping_lifetime_data` resets the counter!
The downside with `delay_ping_lifetime_io` is the increased risk of
small windows of data loss:
Data is only persisted so often, so if the process crashes or is killed
in between the data is not persisted to disk and we will never know about.
We do our best to still persist frequently (after …

Kotlin: Allow configuring delayPingLifetimeIo in Kotlin

---

docs/user/reference/general/initializing.md
docs/user/reference/general/shutdown.md
docs/user/reference/general/toggling-upload-status.md
docs/user/reference/metrics/boolean.md
docs/user/reference/metrics/counter.md
docs/user/reference/metrics/datetime.md
docs/user/reference/metrics/event.md
docs/user/reference/metrics/labeled_booleans.md
docs/user/reference/metrics/labeled_counters.md
docs/user/reference/metrics/labeled_strings.md
docs/user/reference/metrics/quantity.md
docs/user/reference/metrics/string.md
docs/user/reference/metrics/timespan.md
docs/user/reference/metrics/url.md
docs/user/reference/metrics/uuid.md

This PR
- Updates existing links to point to new gleanjs doc links that still exist
- Removes links to Javascript API docs that no longer exist.
In the future if we determine we need the JSDoc/API docs again we can find a new way to deploy them on a sub-route of the new docs

Bug 1857411 - point to new links

---

.dictionary
docs/user/language-bindings/android/android-build-configuration-options.md
docs/user/language-bindings/android/android-offline-builds.md
gradle-plugin/README.md
gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy

mozilla-central uses a vendored copy of glean_parser except for the Android parts which currently download their own copy at build time through the Gradle plugin.
This provides a way to re-use an existing Python virtualenv, in the case of mozilla-central managed by mach, instead of setting up a bespoke one.
This has been tested locally and in [this Try run](https://treeherder.mozilla.org/jobs?repo=try&revision=fd0a81c9c14b1d9bad8e3656a4f564c3fcecdb08) where we can see that [the gradle-dependencies task](https://firefox-ci-tc.services.mozilla.com/tasks/cNe0bMCLSDi_bYCr3FNw7g) (using `gradle --online`) doesn't use Miniconda anymore and [the Android Searchfox task](https://firefox-ci-tc.services.mozilla.com/tasks/R6Rn09OBQ9-sqUblJdu_yA) (using `gradle --offline`) succeeds without supplying …

Bug 1906365 - Gradle plugin: support using an external venv.

---

CHANGELOG.md
glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt
glean-core/android/src/main/java/mozilla/telemetry/glean/private/HistogramBase.kt

In order to remove `service-glean` we need to first add an alias to accommodate glean_parser. We also need to make a few functions public so that they can be accessed by consumers.

Bug 1887023 - Prepare to remove `service-glean`

---

CHANGELOG.md
glean-core/android/src/test/java/mozilla/telemetry/glean/scheduler/MetricsPingSchedulerTest.kt
glean-core/metrics.yaml
glean-core/rlb/tests/test-thread-crashing.sh
glean-core/src/database/mod.rs
glean-core/src/internal_metrics.rs
glean-core/src/ping/mod.rs
glean-core/src/scheduler.rs
glean-core/tests/ping.rs

Due to this being deep within the database we need to do things slightly differently.
We will measure the time ourselves and keep the samples. When we later assemble a ping we record those samples into the databse (incidentally triggering _another_ write for now). Then it just goes the usual way.
Maybe this should be optimized:
* Only collect the samples when actually assembling the `metrics` ping
* Don't put those values into the database, just add them to the generated data right away.

Bug 1896193 - Collect samples of Rkv commit timing

---

samples/android/app/metrics.yaml
samples/android/app/src/main/java/org/mozilla/samples/gleancore/MainActivity.kt
samples/ios/app/glean-sample-app/ViewController.swift
samples/ios/app/metrics.yaml

This was broken in an older glean_parser.
---
~~glean_parser changes pending before this can land.~~

New object metric in samples to ensure we generate valid code

---

glean-core/ios/Glean/Metrics/ObjectMetric.swift
glean-core/ios/GleanTests/TestUtils.swift

This is otherwise a `non_optional_string_data_conversion` swiftlint warning (in swiftlint 0.55.1 at least, we might be using a different swiftlint in CI right now).

Swift: Use String(decoding:as:) to directly decode the UTF8 bytes

---

CHANGELOG.md
docs/user/reference/general/initializing.md
glean-core/Cargo.toml
glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt
glean-core/rlb/Cargo.toml
glean-core/rlb/tests/overflowing_preinit.rs
glean-core/src/dispatcher/global.rs

This also removes the associated Rust feature: `preinit_million_queue`. This feature was previously used to conditionally compile with the 1 million task queue size only when building for gecko.

Bug 1909246 - Set the default pre-init task queue size to 1 million tasks

---

CHANGELOG.md
glean-core/android/src/main/java/mozilla/telemetry/glean/testing/GleanTestLocalServer.kt

This adds an override for the `TestWatcher` `finished` method that ensures that the underlying `WorkManager` executor is properly terminated, and then closes the `WorkManager` database.

Bug 1787234 - Fix `GleanTestLocalServer` test rule leaking between tests

---

.circleci/config.yml
Makefile

Hopefully this fixes an issue with a transitive dependency of link-checker when run on Node 17 While at it we also  drop an ancient version of Node used for docs deploy.

Bug 1913578 - CI: Update node in use

---

glean-core/src/metrics/custom_distribution.rs

Presumably copy pasted from:
https://github.com/mozilla/glean/blob/c7118eea672938e215ebe38801d275047014f0fc/glean-core/src/metrics/memory_distribution.rs#L26-L28

docs(metrics): remove wrong copy paste doc comment

---

Cargo.lock
glean-core/Cargo.toml
glean-core/build/Cargo.toml
glean-core/build/src/lib.rs
glean-core/python/glean/__init__.py
samples/rust/metrics.yaml

glean_parser generated the wrong code for this, so this acts as a regression test.
requires https://github.com/mozilla/glean_parser/pull/750

Bug 1915744 - Rust sample: Add an event metric without extra keys

---

glean-core/src/error_recording.rs
glean-core/src/lib.rs
glean-core/src/metrics/remote_settings_config.rs

These now get caught in Rust beta.
[doc only]

Doc formatting: Address overly long paragraphs

---

CHANGELOG.md
glean-core/android/src/main/java/mozilla/telemetry/glean/Dispatchers.kt
glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt
glean-core/android/src/main/java/mozilla/telemetry/glean/scheduler/MetricsPingScheduler.kt

Changing the MPS `java.util.Timer` to use daemon-threads instead of the default user-threads because user-threads can potentially prevent the application from terminating properly since the OS requires all user-threads to be joined before the app can terminate. Daemon-threads are terminated by the OS once all user-threads have completed and are not awaited before the application can terminate.

Bug 1910449 - Use daemon-threads with the MPS timer instead of the default user-threads

---

.dictionary
docs/user/SUMMARY.md
docs/user/user/howto/real-time-events/real-time-events.md
docs/user/user/pings/events.md

This adds some more specific documentation about Glean's ability to submit events in "real-time" (sending, not analyzing) by way of using the maximum events per ping parameter to cause Glean to send an events ping for every event recorded.
This will be augmented later once I've gotten a chance to run some experiments and measure the impacts with real data.

Bug 1918144 - Document submitting Glean events in "real-time"

---

CHANGELOG.md
glean-core/rlb/tests/custom_distribution_buffered.rs
glean-core/rlb/tests/memory_distribution_buffered.rs
glean-core/rlb/tests/timing_distribution_buffered.rs
glean-core/src/histogram/exponential.rs
glean-core/src/histogram/functional.rs
glean-core/src/histogram/linear.rs
glean-core/src/histogram/mod.rs
glean-core/src/lib.rs
glean-core/src/metrics/custom_distribution.rs
glean-core/src/metrics/memory_distribution.rs
glean-core/src/metrics/mod.rs
glean-core/src/metrics/timing_distribution.rs
samples/rust/metrics.yaml
samples/rust/src/main.rs

This is the implementation for what's being designed in bug-1915388

Bug 1916673 - Buffered API for memory/timing distributions

---

build-scripts/xc-universal-binary.sh
glean-core/ios/Glean/Metrics/ObjectMetric.swift
glean-core/ios/GleanTests/TestUtils.swift

This will actually likely currently fail on CI, because the `swiftlint` we use there is older?
I have swiftlint 0.57 locally.
We might wanna update that check to Xcode 16 soon.

Small fixes to the iOS build

---

glean-core/ios/Glean.xcodeproj/project.pbxproj

On-disk file organization doesn't matter for Xcode whatsoever. Turns out that BaselinePingTest was dropped into the wrong folder in Xcode over 2 years ago. Now moved into the same folder in the Xcode project as it is on disk.

iOS: Move BaselinePingTests logically into the right folder

---

CHANGELOG.md
glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt
glean-core/android/src/main/java/mozilla/telemetry/glean/config/Configuration.kt
glean-core/android/src/test/java/mozilla/telemetry/glean/pings/RidealongPingTest.kt
glean-core/ios/Glean.xcodeproj/project.pbxproj
glean-core/ios/Glean/Config/Configuration.swift
glean-core/ios/Glean/Glean.swift
glean-core/ios/GleanTests/RidealongPingTests.swift
glean-core/ios/GleanTests/TestUtils.swift

We will most likely need this for the new ping on those platforms.

Pass through ping schedule for Swift and Kotlin

---

docs/user/_includes/labels-parameter.md

This limit was raised to 4096 back in 2022 already (bug 1772163)
[doc only]

Docs: Give correct number of allowed static lables

---

CHANGELOG.md
glean-core/src/histogram/functional.rs
glean-core/src/metrics/memory_distribution.rs
glean-core/src/metrics/timing_distribution.rs
glean-core/tests/labeled.rs
glean-core/tests/memory_distribution.rs
glean-core/tests/timing_distribution.rs

**BREAKING CHANGE**:
This changes the ping payload for memory/timing distributions.
---
I _think_ this is all it would require on the client-side to do.

Bug 1898336 - (Memory|Timing) Distribution: snapshot only contains non-zero buckets now

---

Makefile
glean-core/rlb/tests/test-delayed-ping-data.sh

just two little cleanups I did while working on other things

make task & better test error message

---

docs/user/user/howto/investigating-data-issues/investigating-data-issues.md

Bug 1928068 - doc: Add `ping_info.reason` for investigating data issues

---

docs/shared/glean.css

This makes it look nice for the dark themes too
[doc only]
---
Currently for the Ayu theme:
New for the Ayu theme:
Navy:
And Coal:

Bug 1929905 - docs: Use theme's variables to define tab colors

---

glean-core/build/src/lib.rs

This makes it easier to test locally with the Rust sample application and a local glean_parser.
I'll skip docs for now, we don't have any under https://mozilla.github.io/glean/book/language-bindings/index.html right now for Rust.

glean-build: Allow overwrite of Python venv using `GLEAN_PYTHON_VENV_DIR`

---

glean-core/src/metrics/timespan.rs
glean-core/tests/timespan.rs
glean-core/tests/timing_distribution.rs

This is a pre-requisite to allow the coming per-ping toggle:
At the `start` time we don't know _which_ pings to record for.
It's fine to do this because:
* Timespans, if at all, usually collect a span over a single action, with no chance of a upload toggle happening in between
* There's very few timespans in use right now
* It's often the wrong metric type anyway, and timing distributions should be used
* Timing Distributions already allow this

Allow timespans to track across upload toggles

---

glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt
glean-core/python/tests/data/core.yaml
glean-core/rlb/src/private/event.rs
glean-core/rlb/src/private/object.rs
glean-core/rlb/src/test.rs
glean-core/rlb/tests/custom_distribution_buffered.rs
glean-core/rlb/tests/memory_distribution_buffered.rs
glean-core/rlb/tests/timing_distribution_buffered.rs
glean-core/rlb/tests/timing_distribution_single_sample.rs
glean-core/src/event_database/mod.rs
glean-core/src/ping/mod.rs
glean-core/tests/event.rs
glean-core/tests/rate.rs
glean-core/tests/storage.rs
glean-core/tests/string_list.rs
glean-core/tests/timespan.rs
glean-core/tests/uuid.rs

This is in preparation of the further changes coming to how we handle pings.

Use the same test ping names consistently throughout all tests

---

glean-core/python/glean/_builtins.py
glean-core/python/requirements_dev.txt
pyproject.toml

as per the migration guide in https://importlib-resources.readthedocs.io/en/latest/migration.html#pkg-resources-resource-filename

Python: Replace deprecated pkg_resources usage with importlib_resources

---

gradle/libs.versions.toml

Release notes:
* https://github.com/detekt/detekt/releases/tag/v1.23.7
* https://github.com/mockito/mockito/releases (note, due to an error in their CI pipeline, the 5.15.x releases haven't ever been officially published to Maven)
* https://github.com/robolectric/robolectric/releases/tag/robolectric-4.14

Update various Android test dependencies

---

gradle/libs.versions.toml

Changelogs:
* https://developer.android.com/jetpack/androidx/releases/annotation#1.9.1
* https://developer.android.com/jetpack/androidx/releases/appcompat#1.7.0
* https://developer.android.com/jetpack/androidx/releases/lifecycle#2.8.7
* https://developer.android.com/jetpack/androidx/releases/work#2.9.1 (Note: 2.10.0 requires compileSDK 35)

Update various AndroidX Gradle dependencies

---

glean-core/python/requirements_dev.txt

Since switching to maturin in 959e3b44bcb3c41a4ac4f283fdf902bed4a80fdb the auditwheel package is not used anymore (maturin contains a reimplementation of its functionality that's enabled by default)

Python: Remove auditwheel

---

glean-core/src/lib_unit_tests.rs

Fixing clippy lint: Use parenthesizing to avoid operator precedence confusiong

---

CHANGELOG.md
glean-core/metrics.yaml
glean-core/src/metrics/ping.rs
glean-core/tests/ping.rs

This implements solution (2) from https://bugzilla.mozilla.org/show_bug.cgi?id=1932320#c1, as that is easy to implement

Bug 1932320 - Don't record `pings_submitted` for custom pings

---

Cargo.lock
Cargo.toml
supply-chain/audits.toml
supply-chain/config.toml
supply-chain/imports.lock

This might unbreak builds on Rust 1.84.0
Which is a bit weird, but ... eh.

Update flate2 and dependencies

---

glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt

Extending 9d3a300c44 to also apply to the experiment API as that's (obviously) called by Nimbus early as well.
---
I should take this for a proper test drive again before releasing.

Bug 1892234 - Kotlin: Dispatch experiment API on the task queue

---

.circleci/config.yml
.config/nextest.toml

nextest is a [next-generation test runner for Rust projects.](https://nexte.st/).
This isn't to say we _should_ do it.
But it was worth a look.
It's marginally faster (though our rust tests run in ~6s once built).
nextest does have junit output, which CircleCI has integration for, see the Tests tab on https://app.circleci.com/pipelines/github/mozilla/glean/12980/workflows/14ac220e-7661-411e-a7bc-76f44421ffa7/jobs/251666/tests
When all passes it's not interesting. But when a test fails you get it separated out nicely.
And because every test runs in a separate process these additional tests failing because the global lock is poisoned might go away too.
The change here _does_ rely on two external binaries (nextest and the circleci-junit-fix), so that's a bit of a risk (as always) (but I do …

CI: Use nextest to run tests

---

taskcluster/glean_taskgraph/transforms/signing.py

This needs to wait for https://github.com/mozilla-releng/scriptworker-scripts/pull/1123 to be deployed before it can be merged.

bug 1942364: switch to autograph gcp production for signing

---

glean-core/rlb/src/lib.rs
glean-core/rlb/src/private/event.rs
glean-core/rlb/src/private/object.rs
glean-core/rlb/tests/metric_metadata.rs
glean-core/src/metrics/mod.rs

We'd like to be able to access the name and label of a dynamic metric in FOG. To do this, glean-core's RLB needs to expose some way for us to actually access the underlying metadata. This PR adds a trait that does precisely this, and exports it through the RLB so that downstream consumers can access it.

Bug 1934880 - Provide a public interface so that consumers of glean's RLB can access metric identifiers

---

glean-core/android/src/main/java/mozilla/telemetry/glean/debug/GleanDebugActivity.kt

After doing a little research on this, I have a couple of things that should help
- Eliminates StrictMode violations (by ensuring immutable extras).
- Ensures safe intent launching (by verifying activity exports).

Bug 1946133 - GleanDebugActivity fixes for StrictMode violation in Fenix

---

CHANGELOG.md
gradle/libs.versions.toml

Most importantly, this bumps JNA to version 5.17.0 which includes Android 16KB page size support. Note that AppServices will require the same JNA bump when Glean is next updated there.

Various Gradle dependency updates

---

CHANGELOG.md
glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt
glean-core/android/src/main/java/mozilla/telemetry/glean/private/PingType.kt

This also ensures we run through the Kotlin task queue _before_ intializing Glean to keep the order correct.
This should mitigate yet another early libxul loading in Fenix due to Nimbus sending an early ping.
---
I tested this locally in a Fenix build, profiling startup using [simpleperf and samply](https://firefox-source-docs.mozilla.org/performance/profiling_with_simpleperf.html).
The profile doesn't show any `com.sun.jna.Native.load` or glean-core call on the `NimbusDbScope-t` stack.

Bug 1892234 - Kotlin: Dispatch ping instantiation and submit on the task queue

---

.circleci/config.yml

It was sort of a good idea, but it will fail on breaking changes, e.g. `glean-core` adding a new function that's called from the RLB, as `cargo package` builds the package against `crates.io` versions, and that updated `glean-core` won't be available
[doc only]

Remove package-dry run task

---

CHANGELOG.md
glean-core/src/lib.rs

They'll still crash before init, as advertised.

bug 1959515 - Let test_get_{attribution|distribution} wait on init if in progress

---

CHANGELOG.md
glean-core/src/lib.rs

I _would_ prefer to merely check the global_glean, but in tests we reset INITIALIZE_CALLED but we don't reset core::GLEAN, so here we are.

bug 1959771 - Ensure there's a global Glean before using it

---

.circleci/config.yml

The old get-pip URL is now Python 3.9+ only.
For the time being however we keep working on Python 3.8

CI: Fix Python 3.8 builds on Windows (Wine)

---

.circleci/config.yml

Avoids warnings like:
```
`/Users/distiller/.cargo/config` is deprecated in favor of `config.toml`
```

CI: Use non-deprecated file for cargo config

---

.circleci/config.yml
bin/build-win.sh
docs/dev/python/setting-up-python-build-environment.md
tools/docker-winbuild/Dockerfile
tools/docker-winbuild/build.sh
tools/docker-winbuild/init.sh

Python 3.8 is technically EoL.
However we continue to support Python 3.8.
But we don't test on that minimal version anymore on Windows.
---
We might decide to do this for the next release. For now #3115 fixes CI.

CI: Test Windows builds on Python 3.9

---

glean-core/src/core/mod.rs

This could've been helpful when debugging some test failures recently.

Log when metrics attempt to record against unknown pings

---

glean-core/src/metrics/datetime.rs
glean-core/tests/collection_enabled.rs
glean-core/tests/event.rs
glean-core/tests/ping_maker.rs

The `datetime.rs` was an unconditional error print, no one noticed for 4 years!
The second one is just in a test, swallowed by the test system all the time.
The third one now makes the beta clippy test fail. It's also in a test so no one would see it anyway.

Remove debug printing in some tests

---

CHANGELOG.md
glean-core/android/src/main/java/mozilla/telemetry/glean/private/PingType.kt

`this.innerPing` is lazy-initialized. It might not be set by the time `setEnabled` is called. By putting it on the dispatcher it is guaranteed to exist, because initialization is dispatched from `init` and that _always_ runs first.

Bug 1966698 - Kotlin: Dispatch setEnabled on thje Kotlin dispatcher

---

CHANGELOG.md
docs/user/reference/metrics/rate.md
docs/user/reference/metrics/text.md
glean-core/python/glean/metrics/__init__.py
glean-core/python/tests/metrics/test_rate.py
glean-core/python/tests/metrics/test_text.py
glean-core/tests/rate.rs
glean-core/tests/text.rs

Trying this again.
Turns out we never actually exposed them and thus they were unusable, even though we claimed it exists!
(currently based against https://github.com/mozilla/glean/pull/3129, will merge cleanly into main after it)

Python: Properly export rate/text metric

---

CHANGELOG.md
gradle/libs.versions.toml

We're seeing new Android 5/6 startup crashes in Focus 139 now that early RC rollout has begun. @bendk found an [upstream bug report](https://github.com/java-native-access/jna/issues/1662) that suggests that our only real course of action is going to be reverting the update until we're able to drop support for Android <7 (currently in the decision brief stage).
For 139, I'm not sure if we're going to need to spin a 64.1.2 release specifically or if we can go all the way to 64.3.1. Thoughts on that, @travis79 and @badboy?

Bug 1968018 - Revert JNA 5.17.0 update

---

glean-core/python/tests/metrics/test_event.py
glean-core/python/tests/metrics/test_timing_distribution.py
glean-core/python/tests/test_glean.py

These tests are either empty, not testing anything or broken. They haven't been touched in 2+ years. They won't be touched. Let's get rid of them.

Python: Remove already-skipped tests

---

CHANGELOG.md
taskcluster/scripts/rustup-setup.sh

This reverts commit 8c594d6ad93850108e526b191dcb84648bcc012d.

Bug 1968902 - Android: Use Rust 1.86.0 for builds [ci full]

---

glean-core/android/build.gradle
samples/android/app/build.gradle

When I follow the build docs and set `ndk.dir` to point to the r28b NDK, I get warnings (non-fatal errors?) when the glean samples build.
```
> Task :glean-sample-app:stripDebugDebugSymbols
[CXX1104] NDK from ndk.dir at /home/tcampbell/.mozbuild/android-ndk-r28b had version [28.1.13356709] which disagrees with android.ndkVersion [27.0.12077973]
[CXX1104] NDK from ndk.dir at /home/tcampbell/.mozbuild/android-ndk-r28b had version [28.1.13356709] which disagrees with android.ndkVersion [27.0.12077973]
[CXX1104] NDK from ndk.dir at /home/tcampbell/.mozbuild/android-ndk-r28b had version [28.1.13356709] which disagrees with android.ndkVersion [27.0.12077973]
[CXX1104] NDK from ndk.dir at /home/tcampbell/.mozbuild/android-ndk-r28b had version [28.1.13356709] which disagrees with …
```

Always set android.ndkVersion values

---

.circleci/config.yml
CHANGELOG.md

The Rust target is now only tier 2.
Firefox does not support x86 Windows as a build host.
We thus have no consumers of the Python build for it. We can drop it
---
See also: https://blog.rust-lang.org/2025/05/26/demoting-i686-pc-windows-gnu/
Just putting it out there. There's no immediate need to do this. It continues to work just fine and the effort it takes to maintain our CI for it is negligible.

Python: Remove windows i686 support

---

Makefile

This falls back to regular ol' `cargo test` if that command is not available. Should make local testing more convenient.
On CI we still invoke `cargo nextest` explicitly.

Run `cargo nextest` when available

---

Cargo.lock
Makefile
tools/embedded-uniffi-bindgen/Cargo.toml
tools/embedded-uniffi-bindgen/src/main.rs

We will be using macros soon, and that's when we need the library file to parse out additional types.
Unfortunately currently maturin in particular determines library mode based on whether there's _any_ UDL file in tree, which no way to overwrite this (https://github.com/PyO3/maturin/issues/2617). So we simply go look for the library and always pass it along. We do that for every one of our targets, then we won't even need to pass a new flag to uniffi-bindgen in the calling scripts.
---
This should fix the compile issues of #3135

UniFFI: Pass library path when generating foreign-language bindings

---

CHANGELOG.md
glean-core/src/metrics/labeled.rs
glean-core/tests/labeled.rs

If a labeled metrics records in MULTIPLE pings every ping counts as a use of a label.
That means a single labeled metric recorded into 16+ pings can only ever use a single label, before new labels being changed to `__other__`.
We don't have any metric that goes into 16 pings.
But we probably have some that go into 2 pings.
That means this metric can only use 8 labels maximum.
That's bad.

Bug 1970856 - Count distinct labels before spilling into __other__ bucket

---

CHANGELOG.md
glean-core/src/metrics/dual_labeled_counter.rs

This adds the missing `MetricType` impl for `DualLabeledCounter` metrics

Bug 1973287 - Add `MetricType` implementation for `DualLabeledCounter`

---

.circleci/config.yml
Makefile

This uses `zig` under the hood for easy cross-compiling. maturin ensures
to pick the right minimal glibc to support.

Bug 1924793 - CI: Build a Python wheel for aarch64-linux

---

Cargo.lock
glean-core/Cargo.toml
glean-core/src/event_database/mod.rs
glean-core/src/lib.rs
glean-core/src/lib_unit_tests.rs
glean-core/src/metrics/datetime.rs
glean-core/src/metrics/timespan.rs
glean-core/src/metrics/timing_distribution.rs
glean-core/src/scheduler.rs
glean-core/src/upload/mod.rs
glean-core/src/upload/request.rs
glean-core/src/util.rs
glean-core/tests/common/mod.rs
glean-core/tests/datetime.rs
supply-chain/audits.toml
supply-chain/config.toml
supply-chain/imports.lock

And deal with the fallout. The code now calls some deprecated-but-still-supported functions; I made no effort to switch to the recommended replacements.
With this, we can get Gecko off `time@0.1`.

chore: Update `time` to 0.3.41

---

docs/user/reference/metrics/dual_labeled_counters.md

[doc only]
Just noticed that these were missing. We usually add them as empty sections.

docs: Add (empty) API sections for dual labeled counters

---

CHANGELOG.md
glean-core/android/src/main/java/mozilla/telemetry/glean/private/BooleanMetricType.kt
glean-core/android/src/main/java/mozilla/telemetry/glean/private/CounterMetricType.kt
glean-core/android/src/main/java/mozilla/telemetry/glean/private/CustomDistributionMetricType.kt
glean-core/android/src/main/java/mozilla/telemetry/glean/private/DenominatorMetricType.kt
glean-core/android/src/main/java/mozilla/telemetry/glean/private/EventMetricType.kt
glean-core/android/src/main/java/mozilla/telemetry/glean/private/LabeledMetricType.kt
glean-core/android/src/main/java/mozilla/telemetry/glean/private/MemoryDistributionMetricType.kt
glean-core/android/src/main/java/mozilla/telemetry/glean/private/NumeratorMetricType.kt
glean-core/android/src/main/java/mozilla/telemetry/glean/private/ObjectMetricType.kt
glean-core/android/src/main/java/mozilla/telemetry/glean/private/QuantityMetricType.kt
glean-core/android/src/main/java/mozilla/telemetry/glean/private/RateMetricType.kt
glean-core/android/src/main/java/mozilla/telemetry/glean/private/StringListMetricType.kt
glean-core/android/src/main/java/mozilla/telemetry/glean/private/StringMetricType.kt
glean-core/android/src/main/java/mozilla/telemetry/glean/private/TextMetricType.kt
glean-core/android/src/main/java/mozilla/telemetry/glean/private/TimespanMetricType.kt
glean-core/android/src/main/java/mozilla/telemetry/glean/private/TimingDistributionMetricType.kt
glean-core/android/src/main/java/mozilla/telemetry/glean/private/UrlMetricType.kt
glean-core/android/src/main/java/mozilla/telemetry/glean/private/UuidMetricType.kt
glean-core/src/metrics/uuid.rs

This should mitigate yet another early libxul loading in Fenix.
---
This implements the list put together in https://docs.google.com/document/d/1vFgZp9K7pSc7kC_uB1T6JRCFRatr-6t4FcwFJL-ka7k/edit?tab=t.0#heading=h.a22b38t3zasz

Bug 1892234 - Kotlin: Dispatch several more metric type recordings

---

glean-core/python/tests/conftest.py

A cleanup.
These have not been used in a long long time.

Python: Remove unused test fixtures

---

taskcluster/scripts/cross-compile-setup.sh
taskcluster/scripts/macos.manifest

Currently failing: https://firefox-ci-tc.services.mozilla.com/tasks/GlOeui8_RZuohXu9XfipBw/runs/0/logs/public/logs/live.log
```
[task 2025-07-25T08:43:23.604Z] error: linking with `/builds/worker/clang/bin/clang` failed: exit status: 1
[task 2025-07-25T08:43:23.604Z]   |
[task 2025-07-25T08:43:23.604Z]   = note:  "/builds/worker/clang/bin/clang" "-Wl,-exported_symbols_list" "-Wl,/tmp/rustcQ8uBYG/list" "/tmp/rustcQ8uBYG/symbols.o" "<1 object files omitted>" "<sysroot>/lib/rustlib/aarch64-apple-darwin/lib/{libcompiler_builtins-*}.rlib" "-framework" "CoreFoundation" "-liconv" "-lSystem" "-lc" "-lm" "-arch" "arm64" "-mmacosx-version-min=11.0.0" "-o" "/builds/worker/checkouts/vcs/target/aarch64-apple-darwin/release/deps/libxul.dylib" "-Wl,-dead_strip" "-dynamiclib" "-nodefaultlibs" …
```

[ci full] Fix module-build-glean-native on TC

---

CHANGELOG.md
glean-core/metrics.yaml
glean-core/python/glean/testing/__init__.py
glean-core/python/tests/test_glean.py
glean-core/src/ping/mod.rs

Because I already prototyped that here's it as a PR.
Would benefit from more extensive tests.
And also checking that my logic is right to attach it only when there's already other data. 
And making sure it doesn't overwrite existing `string_list` metrics.
And also it hard-codes the `"string_list"` string in the code, which I don't like.
All in all I'd appreciate if someone takes this over and finishes it.

Bug 1976479 - Report a glean.ping.uploader_capabilities list in pings

---

.circleci/config.yml
CHANGELOG.md
glean-core/rlb/examples/mps-delay.rs
glean-core/rlb/tests/test-mps-delay.sh
glean-core/src/scheduler.rs

This code changed with the recent chrono update and can cause rapid rescheduling of metric pings due to wrong date and time math, that mixes local, naive and UTC times.
We now do the time math _always_ in the local timezone, ensuring to aim for a 4am submission of the metrics ping (in case it gets rescheduled). We also avoid any 0-duration reschedule (immediate). If somehow our math doesn't work out we schedule the metrics ping 24 hours into the future.
I used the following code to dig into what's happening:
```rust
#![allow(dead_code)]
use chrono::{DateTime, Days, Duration, FixedOffset, Local, NaiveDate, TimeZone, Utc};
fn local_now_with_offset() -> DateTime<FixedOffset> {
// See https://bugzilla.mozilla.org/show_bug.cgi?id=1611770.
//
// It's not clear if this bug on Windows still exist …
```

Bug 1979598 - MPS: Properly calculate rescheduled duration using local time and avoid re-scheduling anything immediately

---

Cargo.lock
glean-core/Cargo.toml

We upgraded it recently, but actually we dropped all direct usage

Remove unused `time` dependency

---

.dictionary
CHANGELOG.md
glean-core/Cargo.toml
glean-core/rlb/Cargo.toml
glean-core/rlb/src/net/mod.rs
glean-core/src/dispatcher/mod.rs
glean-core/src/lib.rs
glean-core/src/scheduler.rs
glean-core/src/thread.rs
glean-core/src/upload/mod.rs

As I was working on some profiling today I was getting annoyed by not seeing those threads.
So I'm bringing this back now.
As noted last time in the bug doing that on Android is not possible because of ... things (which we hopefully gonna fix at some point), but for Desktop we can register just fine.
I split it up into 2 commits:
1. Refactoring things so we spawn using a single function
2. Adding the Gecko thread registration in that one unique place
The diff looks bigger than it is due to the change in indentation, but `?w=1` in the URL should make that less noisy.

Bug 1899618 - Register Glean threads with the Gecko profiler (feature-gated)

---

publish.gradle

Gradle 9 updates the Groovy runtime to version 4, which requires an explicit import for this now.

Add an explicit import for XmlSlurper

---

CHANGELOG.md
glean-core/rlb/src/test.rs
glean-core/src/metrics/ping.rs

That is: if pings adhere to the baseline schedule but upload is disabled, any pings with `ping_schedule: [baseline]` still need to be checked and submitted if enabled.
Same as #3226

v64 backport: Handle ping schedules even for otherwise disabled pings

---

CHANGELOG.md
glean-core/ios/Glean.xcodeproj/project.pbxproj
glean-core/ios/Glean/Net/PingUploader.swift
glean-core/ios/GleanTests/PingUploaderTests.swift
glean-core/ios/GleanTests/makeCapablePingUploadRequestForTests.swift

Follow up on https://github.com/mozilla/glean/pull/3235
The headers are now public under the `PingUploadRequest`, but the typealias should be public too
```
public let headers: HeadersList
```

Refactor FXIOS-13276 - Missing public typealias

---

.circleci/config.yml
CHANGELOG.md

Same as the aarch64-linux build we're using zig to build for Windows here, that way we won't need additional tools.
A test build was done here: https://app.circleci.com/pipelines/github/mozilla/glean/13733/workflows/b550b662-b80b-4495-9033-a7a0f60113a2/jobs/268565/artifacts
and kagami tested that wheel and it seems to work.

Bug 1986149 - CI: Build a wheel for aarch64-windows

---

glean-core/ios/Glean/Net/HttpPingUploader.swift

- Noted [in this PR](https://github.com/mozilla-mobile/firefox-ios/pull/29054#discussion_r2310663289) we should be adjusting the `connectionTimeout` constant to 10 seconds, since `TimeInterval` is in fact in seconds and I think this was the original intent. 
- I am taking also the opportunity to also change an `if let` to a `guard`, just a matter of preference I just think the code reads better that way since there's less indentation.

HttpPingUploader minor improvements
