mozilla/glean

glean-core/src/common_metric_data.rs, glean-core/src/lib.rs, glean-core/src/metrics/counter.rs, glean-core/src/metrics/string.rs, glean-core/tests/simple.rs
=> Implement API to get the value back from a metric

glean-core/src/database/mod.rs, glean-core/src/storage/mod.rs
This additionally moves some Database specific
detail (i.e. storage names formatted as "{}#")
back to the Database.
=> Add test coverage for Database record

.circleci/config.yml, Makefile, glean-core/android/build.gradle, glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt
=> Add simple Kotlin test

glean-core/android/src/main/java/mozilla/telemetry/glean/rust/LibGleanFFI.kt, glean-core/ffi/examples/glean.h, glean-core/ffi/src/lib.rs, glean-core/src/common_metric_data.rs
=> Pass meta data

glean-core/ffi/src/lib.rs
=> Don't handle the array when getting a null pointer

glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/rust/LibGleanFFI.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt, glean-core/ffi/examples/glean.h, glean-core/ffi/src/lib.rs, glean-core/src/lib.rs
=> Add handleBackgroundEvent

glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/utils/LocaleUtils.kt
=> Add a few core metrics

samples/android/app/build.gradle, samples/android/app/metrics.yaml, samples/android/app/src/main/java/org/mozilla/samples/glean/MainActivity.kt
=> Sample generate

glean-core/tests/metrics.rs
=> Make use of test API

glean-core/android/src/main/java/mozilla/telemetry/glean/private/CounterMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/rust/LibGleanFFI.kt, glean-core/ffi/examples/glean.h, glean-core/ffi/src/lib.rs
=> Expose test api

samples/android/app/src/main/java/org/mozilla/samples/glean/MainActivity.kt
=> Send a ping from the button

glean-core/src/internal_metrics.rs, glean-core/src/lib.rs, glean-core/src/ping/mod.rs
=> Add smoke values for common fields to make valid pings

glean-core/android/build.gradle
This ... seems to fix the build issues.
Fixes #39
=> Include android resources when running tests

.circleci/config.yml
=> Enable gradle tests on CI 

.circleci/config.yml
This should speed up documentation generation by a bit.
=> Install mdbook from released binary

glean-core/android/build.gradle, glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/CounterMetricType.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/TestUtil.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/private/CounterMetricTypeTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/private/StringMetricTypeTest.kt, glean-core/ffi/src/lib.rs
=> Import test coverage from Glean-legacy for Counters and Strings

glean-core/android/src/main/java/mozilla/telemetry/glean/private/BooleanMetricType.kt, glean-core/src/common_metric_data.rs, glean-core/src/error_recording.rs, glean-core/src/first_run.rs, glean-core/src/internal_metrics.rs, glean-core/src/lib.rs, glean-core/src/metrics/boolean.rs, glean-core/src/metrics/counter.rs, glean-core/src/metrics/mod.rs, glean-core/src/metrics/string.rs, glean-core/src/metrics/string_list.rs, glean-core/src/metrics/uuid.rs, glean-core/src/ping/mod.rs, glean-core/src/storage/mod.rs, glean-core/src/util.rs, glean-core/tests/metrics.rs, glean-core/tests/simple.rs
=> Add the MPL 2.0 license header to all the source code files

docs/dev/android/setup-android-build-environment.md
=> Update the developer setup notes

glean-core/examples/sample.rs, glean-core/ffi/src/lib.rs, glean-core/src/database/mod.rs, glean-core/src/first_run.rs, glean-core/src/lib.rs, glean-core/tests/metrics.rs, glean-core/tests/simple.rs
Fixes #29
This is in preparation of the [error handling](https://bugzilla.mozilla.org/show_bug.cgi?id=1551141) so that I don't have to touch these parts again.
=> Initialize objects on creation

.circleci/config.yml
Now that we've removed the singletons, this works
Fixes #33
=> Enable parallel testing on CI

.circleci/config.yml, .detekt.yml, Makefile, build.gradle, glean-core/android/src/main/AndroidManifest.xml, glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/BooleanMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/CounterMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/StringMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/TimespanMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/rust/LibGleanFFI.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/rust/RustError.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/TestUtil.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/private/CounterMetricTypeTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/private/EventMetricTypeTest.kt, samples/android/app/build.gradle, samples/android/app/src/main/AndroidManifest.xml, samples/android/app/src/main/java/org/mozilla/samples/glean/GleanApplication.kt, samples/android/app/src/main/java/org/mozilla/samples/glean/MainActivity.kt
=> 1551258: Fix Kotlin linting and enable on CI

build.gradle, glean-core/android/build.gradle, glean-core/android/src/main/java/mozilla/telemetry/glean/Dispatchers.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/CounterMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/StringMetricType.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/DispatchersTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/TestUtil.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/private/CounterMetricTypeTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/private/StringMetricTypeTest.kt
=> Expose an internal sync API and make the public API async

glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt, glean-core/examples/sample.rs, glean-core/ffi/src/lib.rs, glean-core/src/lib.rs, glean-core/src/metrics/counter.rs, glean-core/src/metrics/string.rs, glean-core/src/ping/mod.rs, glean-core/src/storage/mod.rs, glean-core/tests/simple.rs
=> Dont send pings if empty

README.md
This also updates the bugzilla new bug template to add the expected priority and whiteboard tag so that bugs show up on bugzhub.
=> Add a Contact section to the readme file

Makefile
=> Small edits on makefile

glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/CounterMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/StringMetricType.kt
=> Enable checking for Dispatcher's test mode in the test API

glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/rust/LibGleanFFI.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt, glean-core/ffi/examples/glean.h, glean-core/ffi/src/lib.rs, glean-core/src/lib.rs, glean-core/tests/simple.rs
=> 1551692: Don't schedule the uploading worker if no ping queued

glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/CounterMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/StringMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/rust/LibGleanFFI.kt
=> 1552474: Add a Byte.toBoolean convenience function

glean-core/ffi/src/lib.rs, glean-core/src/common_metric_data.rs, glean-core/src/error.rs
=> Default to a ping lifetime during conversion

docs/SUMMARY.md, docs/dev/core/new-metric-type.md
=> Document how to add a new metric type in the code

glean-core/android/src/main/java/mozilla/telemetry/glean/private/BooleanMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/CounterMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/StringMetricType.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1552511
=> Bug 1552511 - Use finalizers to destruct metrics

glean-core/android/src/main/java/mozilla/telemetry/glean/private/BooleanMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/rust/LibGleanFFI.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/private/BooleanMetricTypeTest.kt, glean-core/ffi/examples/glean.h, glean-core/ffi/src/lib.rs, glean-core/src/metrics/boolean.rs
=> Bug 1552820 - Expose boolean test API and re-enable metric tests

Makefile, glean-core/tests/common/mod.rs, glean-core/tests/counter.rs, glean-core/tests/metrics.rs, glean-core/tests/simple.rs
=> 1552136: Convert CounterStorageEngineTests.kt to Rust

glean-core/tests/counter.rs, glean-core/tests/storage.rs, glean-core/tests/string.rs
=> Bug 1552857 - Convert StringsStorageEngineTests.kt to Rust

glean-core/tests/boolean.rs
=> Bug 1552860 - Convert BooleansStorageEngineTests.kt to Rust

glean-core/ffi/examples/glean_app.c
We never return an error and we certainly don't expect too many.
Yet we should log them _when we_ encounter them.
In debug mode we crash, in release we don't (that's what `debug_assert` is).
Now for the handle thing, do we want to avoid crashing even in debug mode when we get an invalid one? 
It certainly points to an error which we might want to see in debug (and the thing that made us aware, calling `set_upload_enabled` before init will get fixed in another way anyway).
Plus, so far we initialize logging during init, saving us a check at other points, but this means our `invalid handle used` log might actually get lost when it happens before the init.
wdyt?
- Any breaking changes to language …
=> Bug 1553424 - Fix C example (was: log on invalid handles, but don't crash)

glean-core/android/src/main/java/mozilla/telemetry/glean/rust/LibGleanFFI.kt, glean-core/ffi/examples/glean.h, glean-core/ffi/examples/glean_app.c, glean-core/ffi/src/lib.rs
Based on #90, will rebase when that is merged.
=> Enable logging at load time

glean-core/src/metrics/mod.rs, glean-core/src/metrics/string_list.rs, glean-core/src/metrics/uuid.rs
=> `should_record` fixup

docs/dev/core/new-metric-type.md
Add the missing steps for properly exposing a new metric type. Without these steps, build will fail.
=> Add how to publish new metric types in the module

glean-core/src/metrics/boolean.rs, glean-core/src/metrics/counter.rs, glean-core/src/metrics/string.rs, glean-core/src/storage/mod.rs
This avoids going awkwardly through a JSON-serialized storage and trying to find the right place.
Extracted from #95 
=> Snapshot a single metric

.circleci/config.yml
=> Revert "Fix Kotlin doc deployment"

.circleci/config.yml
=> Fix Kotlin doc deploy

glean-core/android/build.gradle
=> Hardcode project name in Kotlin doc generation

Cargo.lock, glean-core/Cargo.toml, glean-core/tests/common/mod.rs, glean-core/tests/ping_maker.rs
=> 1554275: Port PingMakerTests.kt to the rust side

docs/contributing.md
=> Small copypasta fix to contribution docs.

docs/SUMMARY.md, docs/dev/testing.md
=> 1552842: Document how to run tests

glean-core/examples/sample.rs
The limit was recently increased. In order to record something into the
metrics ping, we now need to add more.
=> Sample should be limited

docs/dev/core/new-metric-type.md
@badboy, @Dexterp37 : Did you have something more complex in mind for this bug?  Most of the documentation for this is already there, I just added a concrete example (now that we have one).
=> 1552774: Document more complex serialization

glean-core/android/sdk_generator.gradle, glean-core/src/metrics/labeled.rs
This is the glean-core version of https://github.com/mozilla-mobile/android-components/pull/3268
=> 1556684: Update the label length

glean-core/src/metrics/boolean.rs, glean-core/src/metrics/counter.rs, glean-core/src/metrics/datetime.rs, glean-core/src/metrics/labeled.rs, glean-core/src/metrics/mod.rs, glean-core/src/metrics/ping.rs, glean-core/src/metrics/string.rs, glean-core/src/metrics/string_list.rs, glean-core/src/metrics/uuid.rs
This is nowhere near complete, but it gets us started.
=> Start documenting public parts of all code

glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/rust/LibGleanFFI.kt, glean-core/examples/sample.rs, glean-core/ffi/examples/glean.h, glean-core/ffi/src/lib.rs, glean-core/src/lib.rs
=> 1557339: Simplify Glean.isInitialized

docs/user/metrics/string_list.md, glean-core/android/src/main/java/mozilla/telemetry/glean/private/StringListMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/rust/LibGleanFFI.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/private/StringListMetricTypeTest.kt, glean-core/ffi/src/lib.rs, glean-core/src/error_recording.rs, glean-core/src/metrics/string_list.rs, glean-core/tests/counter.rs, glean-core/tests/string.rs, glean-core/tests/string_list.rs
=> Bug 1552862 - Implement StringList metric type in glean-core

README.md
[Rendered](https://github.com/mozilla/glean/blob/improved-readme/README.md)
=> Link to documentation more prominently

glean-core/src/database/mod.rs, glean-core/src/metrics/string_list.rs, glean-core/tests/string_list.rs
Followup for #129.
Also see commit messages for details.
=> Bug 1557828 - Record error on too many list items

glean-core/src/common_metric_data.rs, glean-core/src/lib.rs, glean-core/src/metrics/ping.rs, glean-core/src/metrics/time_unit.rs, glean-core/src/ping/mod.rs, glean-core/src/storage/mod.rs
=> Bug 1554973 - Document all public items

docs/dev/core/new-metric-type.md
=> Mention new module structure for ffi component in the docs

glean-core/tests/string_list.rs
=> Refactor StringList rust tests to use new testing function.

.circleci/config.yml
=> 1557728: Store Android test artifacts

docs/dev/android/setup-android-build-environment.md, docs/dev/ffi/when-to-use-what-in-the-ffi.md
Some small clarifications I noticed while getting started.
=> Getting started docs

.buildconfig.yml, README.md, docs/user/error-reporting.md, docs/user/pings/index.md, glean-core/android/pings.yaml, glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/ffi/src/lib.rs, glean-core/src/lib.rs, glean-core/tests/boolean.rs, glean-core/tests/counter.rs, glean-core/tests/datetime.rs, glean-core/tests/string.rs, samples/android/app/metrics.yaml, samples/android/app/src/main/java/org/mozilla/samples/glean/GleanApplication.kt
I think that's all of them. It's unclear if I can change the project name in `gradle.properties` without causing much mischief (couldn't find definitive docs on that property), so I left it lowercase for now.
=> [branding] Capitalize Glean where appropriate

README.md
I discussed this with @georgf and looks like this could be a good way to credit. I'm not sure if the location within the README file is good enough. @badboy , thoughts?
=> Add Glean logo credits

glean-core/android/src/main/AndroidManifest.xml, glean-core/android/src/main/java/mozilla/telemetry/glean/debug/GleanDebugActivity.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/debug/GleanDebugActivityTest.kt
The first commit only copies the files over and adds the activity to the manifest. The other commits fixup the tests to work in this repo.
=> Import the GleanDebugActivity from glean-ac

docs/user/adding-glean-to-your-project.md, docs/user/adding-new-metrics.md
This also refactors the existing documentation -- since Glean can be used by
an application or a library, this hopefully makes it clear that most of this
applies to either, but there are some additional application-specific steps.
=> 1555976: Link to probe_scraper docs

README.md, docs/README.md, docs/contributing.md, docs/dev/core/index.md, docs/dev/core/internal.md, docs/dev/core/new-metric-type.md, docs/user/adding-glean-to-your-project.md, docs/user/adding-new-metrics.md, docs/user/debugging.md, docs/user/error-reporting.md, docs/user/metrics/event.md, docs/user/metrics/index.md, docs/user/metrics/labeled_timespans.md, docs/user/metrics/string.md, docs/user/metrics/string_list.md, docs/user/pings/custom.md, docs/user/pings/index.md, docs/user/testing-metrics.md, glean-core/android/metrics.yaml, glean-core/android/pings.yaml, glean-core/android/src/main/java/mozilla/telemetry/glean/Dispatchers.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/ffi/src/lib.rs, glean-core/src/lib.rs, samples/android/app/README.md, samples/android/app/metrics.yaml
Part of my "improve all the docs" sprint.
=> 1560030: Be clear about Glean SDK vs. other parts of Glean

.detekt.yml, glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/net/HttpPingUploader.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/net/PingUploader.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/DatetimeMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/LabeledMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/StringListMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/TimespanMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/rust/LibGleanFFI.kt
ktlint was accumulating some non-allowed stuff which we can easily get rid off.
(we allow up to 10 lint failures apparently)
=> Make the linter happy

glean-core/ffi/src/timespan.rs, glean-core/src/metrics/timespan.rs, glean-core/tests/timespan.rs
=> Extended timespan

docs/user/pings/baseline.md, docs/user/pings/events.md, docs/user/pings/metrics.md
=> Document the behavior of Glean pings on crash

glean-core/android/sdk_generator.gradle
This pulls in https://github.com/mozilla/glean_parser/pull/72 to avoid having duplicate entries in send_in_pings.
=> 1563879: Avoid duplicate entries in send_in_ping

glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/debug/GleanDebugActivityTest.kt
=> Remove duplicate WorkManager init in tests

glean-core/android/build.gradle
=> Try tests with less ram

docs/SUMMARY.md, docs/dev/android/index.md, docs/dev/android/setup-android-build-environment.md, docs/dev/core/index.md, docs/dev/ffi/index.md, docs/dev/index.md, docs/dev/testing.md, docs/user/index.md
=> Fill all sections with at least some basic content

glean-core/src/metrics/counter.rs, glean-core/tests/counter.rs
=> Saturate a counter at the i32 boundary

glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt, glean-core/src/lib.rs
This can happen when there are problems creating the data directory.
=> Don't crash and don't initialize further when database can't be initialized.

docs/user/metrics/timespan.md
This also includes documenting the raw API
=> Bug 1566382 - List error recording values for timespan

bin/build-rust-docs.bat, docs/SUMMARY.md, docs/dev/android/setup-android-build-environment.md, docs/user/pings/testing-custom-pings.md
This additionally adds a batch file to build docs on Windows and an explicit mention to the mdbook requirement.
=> Add documentation for custom ping testing

docs/user/metrics/labeled_counters.md, docs/user/metrics/labeled_strings.md, docs/user/metrics/labeled_timespans.md, glean-core/android/sdk_generator.gradle, glean-core/src/metrics/labeled.rs, glean-core/tests/labeled.rs
This adds a test for all the known valid label formats we should accept and additionally updates the docs.
=> Change labels to allow for '-' (hyphens)

glean-core/ffi/src/event.rs, glean-core/ffi/src/labeled.rs, glean-core/ffi/src/lib.rs, glean-core/ffi/src/macros.rs, glean-core/ffi/src/string_list.rs, glean-core/src/error.rs
=> Safer string array

docs/dev/core/internal/payload.md
Oh, and also the other bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1566854
=> Bug 1564820 - Document payload format for all metric types

glean-core/src/event_database/mod.rs
=> Don't log error message if file removal fails because file didn't exist

.gitignore, Makefile, glean-core/ffi/cbindgen.toml, glean-core/ffi/examples/Makefile, glean-core/ffi/examples/glean.h, glean-core/ffi/examples/glean_app.c
=> Regenerate header with updated and expanded config

Cargo.lock, glean-core/Cargo.toml, glean-core/ffi/Cargo.toml, glean-core/ffi/src/datetime.rs, glean-core/ffi/src/event.rs, glean-core/ffi/src/lib.rs, glean-core/ffi/src/string.rs, glean-core/ffi/src/string_list.rs, glean-core/ffi/src/timing_distribution.rs, glean-core/ffi/src/uuid.rs
=> Upgrade ffi-support to get pointer support

docs/user/adding-new-metrics.md, docs/user/metric-parameters.md, docs/user/metrics/boolean.md, docs/user/metrics/datetime.md, docs/user/metrics/string.md, docs/user/metrics/string_list.md, docs/user/metrics/uuid.md
=> [doc only] 1557700: Document some best practices for metrics

docs/dev/core/internal/payload.md
This just reformats the description of an event payload from an unordered list to a table, to be consistent with the rest of this page.
=> [doc only] Reformat the event payload description

docs/dev/core/new-metric-type.md, glean-core/src/metrics/mod.rs, glean-core/src/storage/mod.rs
=> 1566047: Rename category -> ping_section

docs/dev/android/setup-android-build-environment.md
=> Use correct name for environment variable

docs/dev/core/new-metric-type.md
=> Describe how to add a new metric type using the macro

glean-core/src/event_database/mod.rs
I keep learning as I read more Rust...
=> Remove unneeded closure

bin/build-rust-docs.bat, docs/SUMMARY.md, docs/user/experiments-api.md
=> Add documentation for the experiments API [doc only]

docs/user/debugging.md
Can anyone with a working Android Studio installation (cc @mdboom, @Dexterp37) verify the steps for Android Studio work (and do they work for any app or only for apps that are currently open as a project in Android Studio?)?
=> Document how to view application-specific logs throug Android Studio/adb

glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/scheduler/MetricsPingScheduler.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/scheduler/MetricsPingSchedulerTest.kt
=> Re-add missing metrics ping scheduler

docs/user/testing-metrics.md
=> Add a missing @Test tag to the docs [doc only]

docs/user/pings/testing-custom-pings.md, docs/user/testing-metrics.md
=> Improve the GleanTestRule docs [doc only]

.circleci/config.yml, README.md, glean-core/ffi/src/ping_type.rs
=> Minimum rust

.detekt.yml
Ports https://github.com/mozilla-mobile/android-components/pull/4006
=> Increase LongMethod lint threshold

glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/private/LabeledMetricTypeTest.kt
=> Remove some commented-out code in tests that's definitely not coming back

docs/dev/core/internal/reserved-ping-names.md, docs/user/metric-parameters.md, docs/user/pings/custom.md, glean-core/android/metrics.yaml
=> 1569765: Add "all_pings" to handle metrics that are sent on all pings

docs/dev/core/new-metric-type.md
=> Update docs to current way of providing implementation of a metric type

glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/scheduler/PingUploadWorker.kt
=> Bug 1568557 - Add missing test-only annotations

glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/scheduler/MetricsPingScheduler.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/scheduler/MetricsPingSchedulerTest.kt
=> 1570647 - Do not send 'metrics' ping if the app was not used

.circleci/config.yml, glean-core/android/src/main/java/mozilla/telemetry/glean/testing/GleanTestRule.kt
=> Hide it all

build.gradle, glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/rust/LibGleanFFI.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/private/DatetimeMetricTypeTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/private/LabeledMetricTypeTest.kt
This is mostly [the AC patch](https://github.com/mozilla-mobile/android-components/pull/3670) applied here.
As a side-effect it also [addresses most warnings](https://bugzilla.mozilla.org/show_bug.cgi?id=1564931) (one left, but that's most likely tackled when we re-enable some commented out code).
=> Support compling to Q in Glean

glean-core/android/src/main/java/mozilla/telemetry/glean/private/TimingDistributionMetricType.kt, glean-core/ffi/cbindgen.toml, glean-core/ffi/examples/glean.h, glean-core/ffi/src/lib.rs, glean-core/src/histogram.rs, glean-core/src/metrics/timing_distribution.rs, glean-core/tests/timing_distribution.rs
=> Bug 1568526 -  Review integer type usage

glean-core/android/src/main/java/mozilla/telemetry/glean/private/EventMetricType.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/private/BooleanMetricTypeTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/private/CounterMetricTypeTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/private/DatetimeMetricTypeTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/private/EventMetricTypeTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/private/StringListMetricTypeTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/private/StringMetricTypeTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/private/TimingDistributionMetricTypeTest.kt
Most commented code was already dropped earlier. This is now taking care of only some unused stuff.
=> Remove unneeded or commented imports

glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt
=> Use the same lifecycle event as the observer registered

build.gradle, glean-core/android/src/main/java/mozilla/telemetry/glean/config/Configuration.kt
=> Turn on all warnings as errors to fail builds early

docs/user/experiments-api.md
=> Mention that Glean SDK does not persist experiment data

.circleci/config.yml, docs/SUMMARY.md, docs/code_coverage.md, docs/contributing.md, glean-core/android/build.gradle
Code coverage ends up here: https://codecov.io/gh/mozilla/glean/
Badge for this branch: ![codecov badge: 62%](https://codecov.io/gh/mozilla/glean/branch/are-we-covered-yet/graph/badge.svg)
(We might want to exclude glean-core/ffi? But I would defer that to a follow-up)
=> Upload code coverage

.circleci/config.yml, Makefile
It's tested by usage through the Kotlin wrapper, not by itself.
=> Ignore FFI in coverage

docs/README.md, docs/contributing.md, docs/dev/core/internal/payload.md, docs/user/metrics/event.md, docs/user/metrics/index.md, docs/user/metrics/string.md, docs/user/pings/baseline.md, docs/user/pings/custom.md, docs/user/pings/index.md, docs/user/testing-metrics.md
=> Update all the small things in the book

docs/user/metrics/event.md
Found after merge by @mdboom. Sorry about merging before your review. :D
=> Fix small typo.

docs/SUMMARY.md, docs/dev/core/internal/payload.md, docs/user/metrics/custom_distribution.md, docs/user/metrics/index.md
=> [doc only] 1571744: Document the custom distribution type

docs/user/metrics/custom_distribution.md
This just fixes an edit that I only applied half way based on some PR feedback.
Thanks @dbaron for reporting.
=> [doc only] Make the custom distribution example self-consistent

docs/SUMMARY.md, docs/dev/core/internal/payload.md, docs/user/metrics/index.md, docs/user/metrics/memory_distribution.md
=> [doc only] Document memory distribution metric type

docs/SUMMARY.md, docs/user/adding-glean-to-your-project.md, docs/user/android-build-configuration-options.md
=> [doc only] 1568767: Document `sdk_generator.gradle` options

glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, samples/android/app/src/main/java/org/mozilla/samples/glean/MainActivity.kt, samples/android/app/src/main/res/layout/activity_main.xml, samples/android/app/src/main/res/values/strings.xml
=> 1574470: Make handleBackgroundEvent internal

.circleci/config.yml, .github/CODEOWNERS
=> Use a container with more memory available on CI

glean-core/android/src/main/java/mozilla/telemetry/glean/Dispatchers.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/DispatchersTest.kt
This reinstates the test and corrects the intermittent failure.
=> Bug 1576741 - Fix intermittent Dispatcher test failure

docs/user/android-build-configuration-options.md, glean-core/android/sdk_generator.gradle
This additionally adds documentation.
=> Backport the autodoc features from glean-ac

docs/user/debugging.md
Surprisingly, we were not mentioning nor linking to the debug view docs :)
=> Mention the Glean Debug View in the GleanDebugActivity docs [doc only]

glean-core/tests/memory_distribution.rs
=> Remove stray debug printing from test

glean-core/ios/Glean.xcodeproj/project.pbxproj, glean-core/ios/Glean.xcodeproj/xcshareddata/xcschemes/Glean.xcscheme, glean-core/ios/Glean/Glean.h, glean-core/ios/Glean/Glean.swift, samples/ios/app/glean-sample-app/ViewController.swift
=> Upgrade to Swift 5 and other upgrades

glean-core/ios/Glean.xcodeproj/project.pbxproj, glean-core/ios/Glean/Glean.swift, glean-core/ios/Glean/Scheduler/GleanLifecycleObserver.swift
=> 1579886 - Add iOS lifecycle observer

glean-core/ios/Glean.xcodeproj/project.pbxproj, glean-core/ios/Glean/Config/Configuration.swift, glean-core/ios/GleanTests/Config/ConfigurationTests.swift
=> 1579887 - Add Configuration struct

.circleci/config.yml, glean-core/ios/.swiftformat, glean-core/ios/Cartfile, glean-core/ios/Glean.xcodeproj/project.pbxproj, glean-core/ios/Glean.xcodeproj/xcshareddata/xcschemes/Glean.xcscheme, glean-core/ios/Glean/Config/Configuration.swift, glean-core/ios/Glean/Net/HttpPingUploader.swift, glean-core/ios/GleanTests/Config/ConfigurationTests.swift, glean-core/ios/GleanTests/HttpPingUploaderTests.swift
**ATTENTION** Requires landing #272 first and rebasing this PR on master after it lands.
=> 1579888 - Add HttpPingUploader

glean-core/ios/.swiftlint.yml, glean-core/ios/Glean.xcodeproj/project.pbxproj, glean-core/ios/Glean/Dispatchers.swift, glean-core/ios/Glean/Utils.swift, glean-core/ios/GleanTests/DispatchersTest.swift
=> 1580609 - Add iOS Dispatchers

.github/pull_request_template.md
We ignored it for most parts anyway, we don't have a changelog and
testing is done by CI and stuff only lands when green anyway.
=> Remove pull request check list

glean-core/ios/Glean/Config/Configuration.swift, glean-core/ios/Glean/Glean.swift, glean-core/ios/Glean/Net/HttpPingUploader.swift, glean-core/ios/Glean/Utils.swift, glean-core/ios/GleanTests/Config/ConfigurationTests.swift, glean-core/ios/GleanTests/HttpPingUploaderTests.swift
Requires #278 to land first and rebase on master after that.
=> 1579889 - Add ping upload scheduling for `baseline` and `events` pings

glean-core/ios/Glean.xcodeproj/project.pbxproj, glean-core/ios/Glean/Dispatchers.swift, glean-core/ios/Glean/Glean.swift, glean-core/ios/Glean/Metrics/CounterMetric.swift, glean-core/ios/Glean/Metrics/StringMetric.swift, glean-core/ios/Glean/Metrics/TimespanMetric.swift, glean-core/ios/Glean/Net/HttpPingUploader.swift, glean-core/ios/Glean/Scheduler/GleanOperation.swift, glean-core/ios/Glean/Scheduler/PingUploadOperation.swift, glean-core/ios/GleanTests/DispatchersTest.swift
I tried to break this down into logical commits for easier review.  I would recommend reviewing commit by commit, if possible.
=> Add concurrent operation for uploading and cancellation of background tasks

samples/ios/app/glean-sample-app.xcodeproj/project.pbxproj, samples/ios/app/glean-sample-app/AppDelegate.swift, samples/ios/app/glean-sample-app/ViewController.swift, samples/ios/app/glean-sample-appTests/glean_sample_appTests.swift, samples/ios/app/glean-sample-appUITests/glean_sample_appUITests.swift
Also adds MPL notice to the top of the codefiles
=> 1582807 - Update sample app to Swift 5

glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/acmigration/GleanACDataMigrator.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/scheduler/MetricsPingScheduler.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/acmigration/GleanACDataMigratorTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/scheduler/MetricsPingSchedulerTest.kt
See the description in the individual commits.
=> Migrate metrics ping scheduler

docs/user/adding-new-metrics.md
The implementation of this is in https://github.com/mozilla/probe-scraper/pull/116
=> 1523977: Document the issues with duplicate metric names

.circleci/config.yml, bin/build-swift-docs.sh, bin/run-ios-build.sh
=> Fix the docs by building the project first

docs/user/metrics/datetime.md
=> Update the comment in the swift datetime example

glean-core/android/src/main/java/mozilla/telemetry/glean/private/BooleanMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/CounterMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/CustomDistributionMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/DatetimeMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/EventMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/MemoryDistributionMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/QuantityMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/StringListMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/StringMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/TimespanMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/TimingDistributionMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/UuidMetricType.kt
This is for feature parity with mozilla-mobile/android-components#4617
=> Support calling the Specific Metrics API from Java

glean-core/ios/Glean/Glean.swift, glean-core/ios/GleanTests/Metrics/EventMetricTests.swift
This is a port of #338 to iOS.
=> 1585665: Port 1585021 to iOS: Make sure startup events are in order

glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt
In test mode we still need to keep track of pings, so they get re-registered after a reset.
We also only need to have them in that list once.
A list where everything is tracked once is a set. So we use that.
=> Keep track of all registered pings in test mode

.buildconfig.yml, CHANGELOG.md
Waiting for #363 first, then merging this, tagging and release!
=> Release new version 0.0.1-TESTING4

glean-core/android/build.gradle, glean-core/android/proguard-rules-consumer-jna.pro
See https://github.com/java-native-access/jna/blob/master/www/FrequentlyAskedQuestions.md#jna-on-android
=> Add JNA specific rules

.buildconfig.yml
This includes the JNA proguard changes.
=> Release 0.0.1-TESTING5

docs/user/adding-glean-to-your-project.md, docs/user/adding-new-metrics.md
This tackles 2 bugs in just one PR!
=> Small doc fixes

.buildconfig.yml, CHANGELOG.md, Cargo.lock, glean-core/Cargo.toml, glean-core/ffi/Cargo.toml
In preparation of a final release this week.
=> Release version 19.0.0

.circleci/config.yml
Here's a failed run to show how it looks: https://circleci.com/gh/mozilla/glean/18268
=> Run swiftformat and show potential diff

README.md, docs/README.md, docs/contributing.md, docs/dev/android/setup-android-build-environment.md, docs/dev/ffi/index.md, docs/dev/index.md, docs/dev/testing.md, glean-core/android/sdk_generator.gradle
Also adds our newest team member, brizental.
=> Remove unnecessary mentions of "legacy" glean-ac.

docs/user/metrics/custom_distribution.md
(and fix stray closing-parenthesis)
=> Link to both standard distribution metric types

docs/user/metrics/labeled_counters.md, docs/user/metrics/labeled_strings.md, glean-core/android/src/main/java/mozilla/telemetry/glean/private/LabeledMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/rust/LibGleanFFI.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/private/LabeledMetricTypeTest.kt, glean-core/ffi/glean.h, glean-core/ffi/src/labeled.rs, glean-core/ios/Glean/GleanFfi.h, glean-core/src/metrics/labeled.rs
#401 didn't include labeled metrics (in an attempt to not make that PR any bigger than it already was).
=> 1593055: Add testGetNumRecordedErrors to labeled metrics

.circleci/config.yml
I was getting too annoyed by the constant codecov upload problems.
We don't pay _that_ much attention on it anyway, let's just ignore if it fails.
=> Codecov fixes

.circleci/config.yml, Makefile, README.md, docs/SUMMARY.md, docs/api/index.md, docs/dev/python/index.md, docs/dev/python/setting-up-python-build-environment.md, docs/tab_header.md, docs/tabs.js, docs/user/adding-glean-to-your-project.md, glean-core/ffi/glean.h, glean-core/python/.gitignore, glean-core/python/glean/__init__.py, glean-core/python/glean/_ffi.py, glean-core/python/glean/config.py, glean-core/python/glean/glean.py, glean-core/python/requirements_dev.txt, glean-core/python/setup.py, glean-core/python/tests/test_glean.py
This is ready for review.
Basic features are:
- Automatic builds (including updating due to Rust changes)
- Unit testing
- API docs
- Loading the Rust library through FFI
Releases will have to be done eventually, but I'm considering that a follow-on bug.
@badboy or @travis79: Would you be willing to test drive the instructions on :apple:?
@dexter: Windows?
=> WIP: 1591185: Set up basic Python project structure

samples/android/app/pings.yaml, samples/ios/app/glean-sample-app.xcodeproj/project.pbxproj, samples/ios/app/glean-sample-app/AppDelegate.swift, samples/ios/app/glean-sample-app/Base.lproj/Main.storyboard, samples/ios/app/glean-sample-app/ViewController.swift, samples/ios/app/glean-sample-appUITests/BaselinePingTest.swift, samples/ios/app/glean-sample-appUITests/MockServer.swift, samples/ios/app/glean-sample-appUITests/ViewControllerTest.swift, samples/ios/app/metrics.yaml, samples/ios/app/pings.yaml
=> iOS ViewController test

CHANGELOG.md, glean-core/ios/sdk_generator.sh, glean-core/python/setup.py, gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy
This will need to wait for mozilla/glean_parser#137 and a new release to be cut.
=> Bump the glean_parsers to version 1.11.0

.buildconfig.yml, CHANGELOG.md, Cargo.lock, glean-core/Cargo.toml, glean-core/ffi/Cargo.toml, gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy
Let's get these two important bugfixes out...
@badboy: Used your new script.  Life changing.
=> Release version 21.2.0

.buildconfig.yml, docs/SUMMARY.md, docs/code_coverage.md, docs/dev/howtos/development-with-android-components.md, docs/dev/howtos/locally-published-components-in-fenix.md, docs/dev/testing.md, samples/android/app/build.gradle, settings.gradle
PR over at android-components: https://github.com/mozilla-mobile/android-components/pull/5129
=> Local glean dev

.circleci/config.yml
Let's see how that goes.
I will rekick the integration test a couple of times if it succeeds.
=> Use up2date emulator

Makefile
In the old config, it missed setup.py
=> MAINT: Run black on all the files

.circleci/config.yml, DEPENDENCIES.md, about.toml, bin/about.md.hbs, bin/about.xml.hbs, bin/build-carthage.sh, bin/dependency-summary.sh, deny.toml, glean-core/android/dependency-licenses.xml, publish.gradle
I will document the exact process in a followup
=> Add a summary of our third-party dependencies

glean-core/ios/Glean.xcodeproj/project.pbxproj, glean-core/ios/sdk_generator.sh
https://bugzilla.mozilla.org/show_bug.cgi?id=1585298
=> Extend the sdk_generator.sh script to support more features

samples/android/app/metrics.yaml, samples/android/app/pings.yaml, samples/ios/app/metrics.yaml, samples/ios/app/pings.yaml
Bringing those back on behalf of @mdboom
=> Fix yamllint

docs/user/adding-glean-to-your-project.md
=> Indicate that registering a new product requires a bug filed

.circleci/config.yml
=> Skip the iOS integration tests when push is marked as doc-only

.gitignore, bin/build-rust-docs.bat, bin/build-rust-docs.sh, docs/SUMMARY.md
=> Render the Glean changelog in the book

docs/user/general-api.md
https://bugzilla.mozilla.org/show_bug.cgi?id=1600880
=> Document queueing before Glean is initialized

docs/user/general-api.md
=> Clarify behavior for custom and built-in pings

docs/user/adding-glean-to-your-project.md, docs/user/pings/custom.md
=> Fix module name in Python documentation

docs/user/pings/testing-custom-pings.md
The bug mentions Swift as well, but I'm leaving that for a follow-on (don't have access to a Mac atm...)
=> 1605055: Document testing a custom ping from Python

tools/analysis/ping-patterns/README.md, tools/analysis/ping-patterns/config.py, tools/analysis/ping-patterns/ping-patterns.py
I don't know if this belongs here, but I'm not sure where else it belongs.  Thoughts?
=> 1601262: Ping pattern analysis tool

CHANGELOG.md, glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/scheduler/MetricsPingScheduler.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/scheduler/MetricsPingSchedulerTest.kt
=> Revert "1602024: Improve the metrics ping scheduler"

.circleci/config.yml
This should have zero effect on what this does -- it's just a duplication-removal effort.
=> Use anchors/tags to reduce duplication

.dictionary, CHANGELOG.md, docs/SUMMARY.md, docs/appendix/glossary.md
=> Start the glossary

CHANGELOG.md
=> Add off the main thread preinit dispatching to changelog [docs only]

glean-core/preview/src/lib.rs
This avoids the duplication of state.
We still need to keep some state: the channel and other client info
metrics, only set once at initialization, but reused across upload
toggles.
=> Use global object from glean-core in preview crate

docs/user/metrics/labeled_counters.md
This unfortunately requires a GeckoView note :(
=> Document changing labels [docs only]

docs/appendix/twig.md
=> Link new TWiG

docs/user/pings/metrics.md
=> 1591356 - Use consistent 24h clock in documentation

docs/user/metrics/boolean.md, docs/user/metrics/counter.md, docs/user/metrics/datetime.md, docs/user/metrics/string.md, docs/user/metrics/timespan.md, docs/user/metrics/timing_distribution.md, docs/user/metrics/uuid.md
=> Update Java documentation to use new API

docs/user/general-api.md
...where we talk about overflowing the task queue
=> [doc only] Mention the preinit_tasks_overflow metric

.buildconfig.yml, CHANGELOG.md, Cargo.lock, glean-core/Cargo.toml, glean-core/ffi/Cargo.toml, glean-core/preview/Cargo.toml, gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy
Release is in progress, it's up here already: https://github.com/mozilla/glean/releases/tag/v25.1.0
This merges back the changes into master.
=> Release v25.1.0

Cargo.lock, glean-core/ffi/Cargo.toml, glean-core/ffi/examples/glean_app.c, glean-core/ffi/glean.h, glean-core/ffi/src/lib.rs, glean-core/ffi/src/upload.rs, glean-core/ios/Glean/GleanFfi.h, glean-core/src/lib.rs, glean-core/src/upload/request.rs
Resolves [Bug 1614286](https://bugzilla.mozilla.org/show_bug.cgi?id=1614286)
=> Expose upload module functionality through the FFI

docs/user/metric-parameters.md
This might help with future cases similar to the one for the GFX metrics.
=> Clarify the usage of 'lifetime: application' [doc only]

.dictionary
=> Add missed word

docs/user/metrics/timing_distribution.md
[doc only]
Fixes [Bug 1619274](https://bugzilla.mozilla.org/show_bug.cgi?id=1619274)
=> Fix timing function name in timing distribution doc

.dictionary, docs/user/adding-new-metrics.md, docs/user/metric-lifetime-timeline.svg, docs/user/metrics/index.md, docs/user/metrics/timespan.md, docs/user/metrics/timing_distribution.md
The bones of this are done, but there are parts that I might need some help explaining.  Comments below.
=> Documentation about choosing metric types

docs/appendix/twig.md
[doc only]
Submitting on behalf of @mdboom
=> Add newest TWiG

CHANGELOG.md, docs/user/collected-metrics/metrics.md, glean-core/ios/sdk_generator.sh, glean-core/python/setup.py, glean-core/python/tests/data/core.yaml, gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy
**NOTE:** This one should have the iOS tests run before merging.
=> Upgrade glean_parser to 1.19.0

glean-core/src/metrics/ping.rs
=> Add missing documentation for parameters

.circleci/config.yml, glean-core/src/util.rs
1623307: Add Windows testing to CI
1624677: Make floating point calculations match on x86_64 Windows within Python
=> Python Windows testing

docs/user/adding-new-metrics.md, docs/user/metrics/counter.md
A lot of the issues mentioned in the bug were addressed by previous
documentation work, but this addresses all of the remaining things there.
=> bug 1615675: Document known telemetry antipatterns

CHANGELOG.md, glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/private/EventMetricTypeTest.kt, glean-core/ios/Glean/Glean.swift, glean-core/pings.yaml, glean-core/src/event_database/mod.rs, glean-core/tests/event.rs
=> bug 1604177: Add reason code to the events ping

glean-core/ios/Glean/Glean.swift, glean-core/ios/Glean/Metrics/DistributionData.swift, glean-core/ios/Glean/Metrics/Ping.swift, glean-core/ios/Glean/Net/HttpPingUploader.swift, glean-core/ios/Glean/Testing/ErrorType.swift, glean-core/ios/Glean/Utils/Utils.swift
```
100% documentation coverage with 0 undocumented symbols
```
=> Bug 1627312 - Fix undocumented pieces in Swift

glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/scheduler/PingUploadWorker.kt
[doc only]
Forgot to add them back to the just-merged PR, so here they come now. No need to run tests.
=> Fix indentation

docs/user/pings/index.md, glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt, glean-core/pings.yaml
=> [doc only] Comment / doc improvements for foreground baseline pings

docs/appendix/twig.md
=> Adding latest TWiG

Cargo.lock, DEPENDENCIES.md, glean-core/Cargo.toml, glean-core/android/dependency-licenses.xml, glean-core/ffi/Cargo.toml, glean-core/ffi/src/labeled.rs, glean-core/ffi/src/macros.rs, glean-core/ffi/src/ping_type.rs, glean-core/preview/Cargo.toml, glean-core/src/lib.rs, glean-core/src/metrics/labeled.rs
This seemed like pretty low hanging fruit for a Rust noob like me.  I expect that there will be things to change to make this correct but I am using it to learn more Rust so bring it on!
=> Bug 1626558 - Replace use of lazy_static with once_cell

docs/user/collected-metrics/metrics.md
=> Regenerate docs [doc only]

docs/dev/core/internal/implementations.md
[doc only]
Do as we say, not as we do : )
=> Warn prospective Rust consumers

.dictionary, docs/user/adding-glean-to-your-project.md
This should have been updated in #819
=> [doc only] Remove mention of multiprocessing

.circleci/config.yml
Just a test to see if the hack is still necessary.
=> Remove mingw hack

docs/user/metrics/counter.md
=> [doc only] Bug 1632072: Rephrase note on counter metrics

glean-core/android/src/main/java/mozilla/telemetry/glean/net/Upload.kt, glean-core/ffi/glean.h, glean-core/ios/Glean/GleanFfi.h, glean-core/src/event_database/mod.rs, glean-core/src/upload/directory.rs, glean-core/src/upload/mod.rs, glean-core/tests/common/mod.rs, glean-core/tests/ping_maker.rs
Also includes minor other fixes.
=> Bug 1634745 - Export ping request for use by Rust consumers

docs/appendix/twig.md
=> Add wlach's most recent TWiG

glean-core/python/glean/_loader.py, glean-core/python/glean/_process_dispatcher.py, glean-core/python/glean/config.py, glean-core/python/glean/glean.py, glean-core/python/glean/metrics/boolean.py, glean-core/python/glean/metrics/counter.py, glean-core/python/glean/metrics/datetime.py, glean-core/python/glean/metrics/event.py, glean-core/python/glean/metrics/experiment.py, glean-core/python/glean/metrics/labeled.py, glean-core/python/glean/metrics/ping.py, glean-core/python/glean/metrics/string.py, glean-core/python/glean/metrics/timespan.py, glean-core/python/glean/metrics/uuid.py, glean-core/python/glean/net/base_uploader.py, glean-core/python/glean/net/ping_uploader.py, glean-core/python/glean/testing/__init__.py
This should have zero impact on functionality -- it just improves the coverage of optional type annotations.
=> MAINT: Improve Python type annotation coverage

build.gradle, gradle/wrapper/gradle-wrapper.properties
These were blocked for local composite builds.
=> Upgrade Gradle & Android Gradle plugin

bin/prepare-release.sh
=> Regenerate dependency summary before a release

.circleci/config.yml
This fixes some rendering issues.
[doc only]
=> Upgrade mdbook in use

docs/user/general-api.md
=> Bug 1636951 - Document the requirement to configure an HTTP client

.dictionary, CHANGELOG.md, glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt
=> Bug 1635865: Fix ConcurrentModificationException

CHANGELOG.md, glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt
* Bug 1635865: Fix ConcurrentModificationException
* Add CHANGELOG
* Call registerPingType instead of calling FFI directly
* LINT
=> HOTFIX: Bug 1635865: Fix ConcurrentModificationException (#900)

.circleci/config.yml
Details here: https://circle-macos-docs.s3.amazonaws.com/image-manifest/v2960/index.html
=> Bug 1639859 - Upgrade to Xcode 11.5.0

glean-core/ffi/src/handlemap_ext.rs
Fixes [Bug 1640196](https://bugzilla.mozilla.org/show_bug.cgi?id=1640196)
=>  Change logging level of errors on the FFI 

glean-core/android/src/main/java/mozilla/telemetry/glean/scheduler/PingUploadWorker.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt
Fixes [Bug 1620672](https://bugzilla.mozilla.org/show_bug.cgi?id=1620672)
=>  Remove PINGS_DIR const from kotlin code

taskcluster/ci/android-build/kind.yml, taskcluster/ci/rust/kind.yml
=> TC: Store the test report as an artifact for later analysis 

docs/user/metrics/timing_distribution.md
=> Use correctly named method in docs

glean-core/csharp/Glean/LibGleanFFI.cs, glean-core/csharp/Glean/Metrics/UuidMetricType.cs, glean-core/csharp/GleanTests/Metrics/StringMetricTypeTest.cs, glean-core/csharp/GleanTests/Metrics/UuidMetricTypeTest.cs
=> Adding Uuid metric type for C# binding.

glean-core/python/glean/_dispatcher.py, glean-core/python/tests/test_dispatcher.py
=> Bug 1646173: Python: Fix database not found on app shutdown

glean-core/csharp/Glean/Dispatchers.cs, glean-core/csharp/Glean/Glean.cs, glean-core/csharp/Glean/LimitedConcurrencyLevelTaskScheduler.cs, glean-core/csharp/GleanTests/DispatchersTests.cs
This uses a custom TaskScheduler + Factory from Microsoft example: https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskscheduler?view=netcore-3.1
=> Fix a race condition in C# Dispatchers

docs/user/metrics/datetime.md
Reference Timespan instead of itself.
=> Fix the 'Datetime' docs [doc only]

.taskcluster.yml, taskcluster/ci/config.yml, taskcluster/ci/module-build/kind.yml, taskcluster/ci/signing/kind.yml, taskcluster/glean_taskgraph/__init__.py, taskcluster/glean_taskgraph/build_config.py, taskcluster/glean_taskgraph/loader/multi_dep.py, taskcluster/glean_taskgraph/transforms/__init__.py, taskcluster/glean_taskgraph/transforms/multi_dep.py, taskcluster/glean_taskgraph/transforms/signing.py, taskcluster/glean_taskgraph/worker_types.py
This is pulling in changes from https://github.com/mozilla/application-services/pull/3168
It again skips CircleCI tasks to reduce load there.
No Glean peer review needed yet.
cc @MihaiTabara
=> Bug 1644994 - TaskCluster: Enable signing tasks on release

taskcluster/ci/beetmover/kind.yml, taskcluster/ci/config.yml, taskcluster/glean_taskgraph/transforms/beetmover.py
=> Bug 1582644 - Add beetmover configuration and enable on releases

taskcluster/ci/beetmover/kind.yml, taskcluster/ci/signing/kind.yml
=> TC: Add mail notificiation on failures

glean-core/csharp/Glean/Dispatchers.cs, glean-core/csharp/Glean/Glean.cs, glean-core/csharp/Glean/Glean.csproj, glean-core/csharp/Glean/LibGleanFFI.cs, glean-core/csharp/Glean/Net/BaseUploader.cs, glean-core/csharp/Glean/Utils/GleanLogger.cs
- Adds a GleanLogger wrapper around the Serilog Logger to make configuration simple.
- Update any commented out logging or Console.WriteLine to use the GleanLogger
=> Bug 1643571 - Add C# Logger

.taskcluster.yml
=> TC: Limit CI runs to default branch only 

glean-core/ffi/src/lib.rs, glean-core/python/tests/test_glean.py, glean-core/python/tests/test_network.py
Fixes [Bug 1647633](https://bugzilla.mozilla.org/show_bug.cgi?id=1647633)
=> Bug 1647633 - Add rate limiting functionality to stand alone creation on upload manager

.circleci/config.yml, glean-core/src/lib.rs
(Creating this as a draft because this forcibly dumps core right now -- will take that out before merging, after testing that the artifact saving works...)
=> Bug 1641619: Fix saving of coredump artifacts for Python

docs/dev/docs.md, docs/user/adding-glean-to-your-project.md, docs/user/adding-new-metrics.md, docs/user/experiments-api.md, docs/user/general-api.md, docs/user/metrics/boolean.md, docs/user/metrics/counter.md, docs/user/metrics/datetime.md, docs/user/metrics/event.md, docs/user/metrics/labeled_booleans.md, docs/user/metrics/labeled_counters.md, docs/user/metrics/labeled_strings.md, docs/user/metrics/memory_distribution.md, docs/user/metrics/string.md, docs/user/metrics/string_list.md, docs/user/metrics/timespan.md, docs/user/metrics/timing_distribution.md, docs/user/metrics/uuid.md, docs/user/pings/custom.md, docs/user/pings/testing-custom-pings.md, docs/user/testing-metrics.md
All the referenced bugs were filed today.
=> Create skeleton documentation for the C# language bindings [doc only

glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/debug/GleanDebugActivityTest.kt, glean-core/ios/Glean/Glean.swift, glean-core/ios/GleanTests/GleanTests.swift
Fixes [Bug 1648009](https://bugzilla.mozilla.org/show_bug.cgi?id=1648009)
=> Bug  1648009 - Let debug view tag be set before init on Android and iOS

taskcluster/scripts/cross-compile-setup.sh
=> TC: Ensure we're compiling dependencies in non-debug mode. [ci full]

glean-core/csharp/Glean/Dispatchers.cs, glean-core/csharp/Glean/Net/HttpClientUploader.cs, glean-core/csharp/GleanTests/DispatchersTests.cs
See the individual commit messages for a detailed explanation.
=> Bug 1650012 - Always wrap `Action` in try/catch when dispatching in C#

glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt, glean-core/ios/GleanTests/GleanTests.swift, glean-core/ios/GleanTests/TestUtils.swift
BONUS: Also change android tests to make sure we don't
get the same failures on them in the future.
=> Bug 1649751 - Fix swift CI failure on baseline tests

docs/user/adding-glean-to-your-project.md
Thanks @psymoon for reporting.
[doc only]
=> Fix the name used in the example

glean-core/src/lib.rs
=> Bug 1653383 - Remove stray comment referring to removed argument

.circleci/config.yml, docs/book.toml
This gives us:
* ability to define the branch for the open-on link
* fixed rendering of mermaid when it contains HTML-like characters
[doc only]
=> Bug 1653471 - Upgrade mdbook-dtmo

bin/prepare-release.sh
=> Bug 1653205 - Use bsd-sed compatible commands when replacing versions

.dictionary, CHANGELOG.md, docs/SUMMARY.md, docs/dev/core/internal/payload.md, docs/user/metrics/index.md, docs/user/metrics/jwe.md
* Also add entry about JWE related changes to CHANGELOG.md
=> Bug 1650787 - Add docs about JWE metric type

docs/user/general-api.md
Should land after #1046 to be accurate.
=> Bug 1650753 - Document behavior of `setUploadEnabled` if Glean is not initialized

.buildconfig.yml, CHANGELOG.md, Cargo.lock, DEPENDENCIES.md, glean-core/Cargo.toml, glean-core/ffi/Cargo.toml, glean-core/preview/Cargo.toml, gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy
=> Bumped version to 31.6.0

docs/appendix/glossary.md
=> Bug 1653194 - Add the definition for 'measurement window' to glossary

docs/appendix/twig.md
=> Add @hackebrot's TWiG post about burnham 👩‍🚀

bin/update-glean-parser-version.sh, docs/SUMMARY.md, docs/dev/upgrading-glean-parser.md, glean-core/python/glean/__init__.py
Also, check the glean_parser version at runtime from the Python bindings.
=> Bug 1655481, Bug 1655760: Add glean_parser version update script

.dictionary, docs/SUMMARY.md, docs/dev/ci.md, docs/dev/cut-a-new-release.md, docs/dev/docs.md, docs/dev/testing.md
After the trouble Mike had yesterday I thought it would be fair to properly document it now.
---
I also slightly re-ordered some chapters. I _think_ that way it fits better, but I'd be okay to take that out.
While I was at it I also fixed the link-checker docs.
=> Document the CI setup and expectations

.circleci/config.yml, taskcluster/scripts/rustup-setup.sh
=> CI: Enable RUST_LOG for all Rust task

.buildconfig.yml, CHANGELOG.md, Cargo.lock, DEPENDENCIES.md, glean-core/Cargo.toml, glean-core/csharp/Glean/Glean.csproj, glean-core/ffi/Cargo.toml, glean-core/preview/Cargo.toml, gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy
in progress: https://github.com/mozilla/glean/releases/tag/v32.2.0
=> Merge back release v32.2.0

.github/dependabot.yml
=> Bug 1597249 - Configure dependabot to check Rust and Python dependencies daily

glean-core/python/glean/_loader.py, glean-core/python/requirements_dev.txt, glean-core/python/tests/test_dispatcher.py, glean-core/python/tests/test_glean.py, glean-core/python/tests/test_network.py
flake8-bugbear is a stricter code smell checker for Python.
It did find one bona fide potential problem, so I think it's useful to integrate
it into CI for now.
=> Python: Use flake8-bugbear

.circleci/config.yml, CHANGELOG.md, bin/bootstrap.sh, bin/build-carthage.sh, samples/ios/app/Cartfile, samples/ios/app/bootstrap.sh, samples/ios/app/glean-sample-app.xcodeproj/project.pbxproj
Replaces #1167
---
My Xcode beta download finished so I tried it quickly.
Pushing here to test on CI.
=> Update to Xcode 12

.buildconfig.yml, CHANGELOG.md, Cargo.lock, DEPENDENCIES.md, glean-core/Cargo.toml, glean-core/csharp/Glean/Glean.csproj, glean-core/ffi/Cargo.toml, glean-core/preview/Cargo.toml, gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy
In progress: https://github.com/mozilla/glean/releases/tag/v32.3.0
=> Merge back 32.3.0 release

docs/appendix/twig.md
=> Add missing Twigs

.dictionary, docs/dev/core/dependency-management.md
=> Document dependency updates for Rust deps

glean-core/src/lib.rs, glean-core/src/lib_unit_tests.rs, glean-core/src/storage/mod.rs, glean-core/src/upload/mod.rs, glean-core/src/upload/policy.rs
BONUS: Make uploader tests sync by default
=> Bug 1661276 - Make upload policies easily configurable for tests

CHANGELOG.md
[doc only]
---
In progress: https://app.circleci.com/pipelines/github/mozilla/glean/5866/workflows/1f9ed3a5-2df1-42f4-85d9-a896a5359b8d
=> Add back release notes for 32.3.1

CHANGELOG.md, build.gradle, glean-core/android/src/test/java/mozilla/telemetry/glean/private/EventMetricTypeTest.kt
Nothing surprising, but see the individual commits for more info.
=> Use Kotlin 1.4.10

docs/dev/ci.md
=> Document the special ci-full behavior

samples/ios/app/Cartfile
This now includes the required upstream fixes in a proper release.
=> Use swifter release

.dictionary, CHANGELOG.md, Makefile, glean-core/Cargo.toml, glean-core/csharp/Glean/GleanParser.cs, glean-core/ios/sdk_generator.sh, glean-core/python/glean/__init__.py, glean-core/python/setup.py, glean-core/src/upload/mod.rs, gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy
This cherry-picks 2 commits from the `main` branch onto the support branch in preparation of a release of v32.4.1
=> [hotfix patches] glean_parser upgrade & ping dir size transformation

docs/SUMMARY.md, docs/dev/core/internal/directory-structure.md
=> Bug 1667881 - Document the pending ping file format

Makefile, bin/check-artifact.sh, gradle-plugin/build.gradle, publish.gradle, taskcluster/ci/module-build/kind.yml
=> [ci full] Bug 1667410 - Check the contents of produced Maven artifacts

.dictionary, docs/user/pings/custom.md, glean-core/android/src/test/java/mozilla/telemetry/glean/pings/CustomPingTest.kt
This also specifically points out in the docs that pings need to be
registered before initialization for this to work.
=> Bug 1657379 - Test that events in custom pings are flushed at startup.

docs/user/adding-new-metrics.md
This also changes some of the headings which were at the
wrong level (not really visible unless you have a toc).
=> Add a table of contents to the "adding new metrics" page

glean-core/rlb/src/dispatcher/global.rs
Unfortunately this test can't run by default because it influences the
global dispatcher. We can fix that by resetting the dispatcher.
The test can be manually run with:
cargo test -p glean -- --ignored global_nested_calls
=> Test that nested dispatcher calls work as expected

Cargo.lock, glean-core/Cargo.toml
~~**NOTE**: hold off on merging while I do another test please.~~
=> Do not require default-features on rkv and downgrade bincode

glean-core/src/lib.rs
=> Fix comment on about upload manger's rate limiter

glean-core/rlb/src/private/ping.rs, glean-core/src/traits/ping.rs
This also adds a notice to the RLB type to mention to keep the trait updated.
=> Change the `Ping` trait to match the RLB API

glean-core/rlb/src/lib.rs, glean-core/rlb/src/net/mod.rs
=> Move the UPLOAD_MANAGER to the RustBindingState struct

glean-core/src/database/mod.rs
See upstream fix: https://github.com/mozilla/rkv/pull/211
=> rkv: Handle all corrupted cases in the migration

docs/dev/core/logging-levels.md, glean-core/ffi/src/handlemap_ext.rs, glean-core/ffi/src/lib.rs, glean-core/src/database/mod.rs, glean-core/src/debug.rs, glean-core/src/event_database/mod.rs, glean-core/src/lib.rs, glean-core/src/storage/mod.rs, glean-core/src/upload/directory.rs, glean-core/src/upload/mod.rs, glean-core/src/upload/request.rs
Creating this as a draft initially, for now I have only added the docs with the logging level guidelines I propose we adopt for glean-core. Wanted to discuss this prior to actually going ahead and making the changes to all our logs ;)
=> Bug 1673392 - Audit log levels of log messages in glean-core

glean-core/src/traits/event.rs
=> Fix documentation of event recording

glean-core/rlb/src/private/boolean.rs, glean-core/rlb/src/private/counter.rs, glean-core/rlb/src/private/labeled.rs, glean-core/rlb/src/private/ping.rs, glean-core/rlb/src/private/quantity.rs, glean-core/rlb/src/private/string.rs, glean-core/rlb/src/private/timespan.rs, glean-core/rlb/src/private/uuid.rs
=> Bug 1681570: Remove docs on implementations of traits in the RLB

glean-core/android/src/main/java/mozilla/telemetry/glean/net/Upload.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/scheduler/PingUploadWorker.kt, glean-core/ffi/glean.h, glean-core/ffi/src/upload.rs, glean-core/ios/Glean/GleanFfi.h, glean-core/ios/Glean/Net/HttpPingUploader.swift, glean-core/ios/Glean/Net/Upload.swift, glean-core/python/glean/glean.py, glean-core/python/glean/net/ping_upload_worker.py, glean-core/rlb/src/net/mod.rs, glean-core/src/upload/mod.rs
I did not include these changes in C#, as I was not sure it is necessary. 
Please let me know if I should :)
=> Bug 1680224 - Return a specific wait interval value with PingUploadTask::Wait

docs/appendix/twig.md
=> Add end-of-year TWiG

glean-core/rlb/examples/prototype.rs, glean-core/rlb/src/test.rs, glean-core/rlb/tests/schema.rs
Fixes to some various clippy checks that appeared over the break.
=> Clippy fixes

glean-core/ios/GleanTests/GleanTests.swift
=> Fix the Swift tests to accomodate for the new metric

Cargo.lock
Updated:
* uuid
* tempfile
* ctor
* log
* serde
Closes #1424
Closes #1425
Closes #1426
Closes #1427
=> Update subset of dependencies

docs/dev/core/internal/implementations.md
=> Update documentation about the different implementations

glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt
=> Bug 1685273 - Disable frequent-intermittently failing test for now

.circleci/config.yml, glean-core/android/src/main/java/mozilla/telemetry/glean/net/Upload.kt, glean-core/ffi/examples/glean_app.c, glean-core/ffi/glean.h, glean-core/ios/Glean/GleanFfi.h, glean-core/ios/Glean/Net/Upload.swift, glean-core/python/glean/net/ping_upload_worker.py
Based on #1442 which needs to land first.
I set that other branch as the base. Let's see if that then auto-updates when the other PR lands.
=> Update cbindgen in use on CI

docs/dev/android/locally-published-components-in-fenix.md
=> Update docs on which places in Fenix to modify for a local build

docs/appendix/twig.md
=> Add Jan 15 TWIG

.swiftformat
=> Remove long-unused swiftformat config file

.buildconfig.yml, CHANGELOG.md, Cargo.lock, DEPENDENCIES.md, glean-core/Cargo.toml, glean-core/csharp/Glean/Glean.csproj, glean-core/ffi/Cargo.toml, glean-core/python/setup.py, glean-core/rlb/Cargo.toml, gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy
https://github.com/mozilla/glean/releases/tag/v34.0.0
=> Merge back release v34.0.0

docs/user/metric-parameters.md
Noticed this when working on mozilla/glean-dictionary#357. I'm not sure if my additions are actually correct, but that's part of the point of this PR. 😄
=> Go into more detail on metric expiry

CHANGELOG.md, docs/user/pings/baseline.md, glean-core/python/glean/glean.py, glean-core/python/glean/metrics/event.py, glean-core/python/tests/test_glean.py
**NOTE**:
This pull request will **merge automatically** when CI passes and it gets one accepting review!
This tests out [GitHub's new feature](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/automatically-merging-a-pull-request)
=> Bug 1688842 - Python: Expose the client activity API

glean-core/android/src/main/java/mozilla/telemetry/glean/private/TimingDistributionMetricType.kt, glean-core/ios/Glean/Metrics/TimingDistributionMetric.swift, glean-core/python/glean/metrics/timing_distribution.py, glean-core/src/metrics/timing_distribution.rs, glean-core/src/traits/timing_distribution.rs
=> Bug 1691469 - Remove incorrect documentation about error reporting on timing distributions

docs/user/README.md
=> Fix link to the dev book

docs/user/appendix/twig.md
=> New TWiG: Boring Monitoring

docs/dev/core/internal/payload.md, docs/dev/core/new-metric-type.md
Also update the payload docs' links to not be broken.
=> bug 1694999 - Update payload doc to include "rate" metric

.circleci/config.yml, Makefile, docs/dev/README.md, docs/dev/android/setup-android-build-environment.md, docs/dev/contributing.md, docs/dev/core/internal/debug-pings.md, docs/dev/core/new-metric-type.md, docs/dev/cut-a-new-release.md, docs/dev/python/setting-up-python-build-environment.md
Based on #1521 to avoid duplicating work, can be rebased  when that lands.
=> Link-check both books

.circleci/config.yml, CHANGELOG.md, Makefile
This PR solves [bug 1648118](https://bugzilla.mozilla.org/show_bug.cgi?id=1648118).
Any suggestion is appreciated!
=> Bug 1648118: Change the `fmt-` and `lint-` make commands for consistency

.dictionary, docs/dev/SUMMARY.md, docs/dev/core/new-metric-type/platform.md
So, I'm still not 100% sure on *where* this belongs, but I thought in the meantime we could review the content itself.
=> [doc only] [Bug 1696188] Document adding new metric type to data platform

README.md
Gah -- #1536 wasn't quite right either. We have two books and we should link to both!
=> [no bug] [doc only] Add links to both doc books

glean-core/src/metrics/labeled.rs
I wish I found about this earlier :\
=> Fix the misleading comment about label validation

docs/user/user/metrics/timespan.md, docs/user/user/metrics/timing_distribution.md
=> Bug 1699653 - Document the convenience function `measure`

docs/user/appendix/twig.md
Forgot to add my TWiG to the index....
=> Add missing TWiG

docs/shared/blockquote-info.html, docs/shared/blockquote-stop.html, docs/shared/blockquote-warning.html, docs/shared/glean.css, docs/shared/tabs.js, docs/user/SUMMARY.md, docs/user/appendix/contribution-guidelines.md
This is mostly copy pasta from the re-structuring proposal + the playground code :) With some neat little additions such as the "STOP" custom blockquote. 
I foresee it being used for example on [Bug 1706549](https://bugzilla.mozilla.org/show_bug.cgi?id=1706549).
[Rendered](https://innate-earth.surge.sh/appendix/contribution-guidelines.html)
=> Bug 1708435 - Add a contributions guideline page to Appendix

docs/user/README.md
Forgot to include this change in [the other PR](https://github.com/mozilla/glean/pull/1605).
=> Bug 1708435 - Mention contribution guidelines section on book README.md

docs/user/reference/yaml/index.md
=> Bug 1708361 - Add note on how to disable yamllint if necessary

docs/user/reference/metrics/counter.md, docs/user/reference/metrics/labeled_counters.md
=> Bug 1708661 - Counter: Explicitly mention that `0` is not reported

.dictionary, docs/user/SUMMARY.md, docs/user/language-bindings/index.md
[doc only]
---
It fits in there right well, but that means I'm not sure if I should also mention Glean.js or the FOG integration there?
=> Bug 1708429 - Document the available language bindings

docs/user/reference/general/index.md, docs/user/user/adding-glean-to-your-project.md
... is fundamental and prevents anomalous behaviors.
=> Bug 1706549 - Document that calling Glean.initialize with real values... [doc only]

glean-core/src/scheduler.rs
Not sure how that didn't trigger in #1629 before
=> Fix latest clippy suggestion

glean-core/tests/labeled.rs
Nit I stumbled upon while implementing error recording for Glean.js.
=> No bug - Remove unnecessary call to strip_label

docs/user/reference/metrics/quantity.md
[doc only]
...And add Glean.js information to this page.
=> Bug 1698800 - Conform quantity metric reference page to new format

.dictionary, docs/dev/ios/setup-ios-build-environment.md
=> Document how to set up the dev env on M1 macbooks

.buildconfig.yml, CHANGELOG.md, Cargo.lock, DEPENDENCIES.md, glean-core/Cargo.toml, glean-core/android/dependency-licenses.xml, glean-core/csharp/Glean/Glean.csproj, glean-core/ffi/Cargo.toml, glean-core/python/setup.py, glean-core/rlb/Cargo.toml, gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy
=> Merge back release of v39.0.0

docs/user/appendix/twig.md
=> Add latest twig

.circleci/config.yml, bin/build-xcframework.sh, bin/publish-glean-swift.sh
Preparing for the xcframework build, first test run!
=> Bug 1711447 - Build for all iOS targets and bundle an xcframework

.circleci/config.yml
I manually fixed up the v39.0.1 release.
The steps I took went into this patch now.
Yes, it was that easy.
=> Fix remaining issues for release

bin/build-xcframework.sh
[doc only] // not really, but release only
=> iOS: Fix all occurences of `Glean.` in a line

docs/user/SUMMARY.md, docs/user/user/adding-glean-to-your-project/javascript.md, docs/user/user/adding-glean-to-your-project/qt.md
Still need to add QML documentation to other pages, but those will come in a future PR.
=> Bug 1714361 - Document adding Glean.js to Qt/QML project

docs/user/user/adding-glean-to-your-project/kotlin.md
=> Bug 1714932 - Document how to add Glean test dependencies to Android projects

docs/user/reference/general/initializing.md, docs/user/reference/general/register-custom-pings.md, docs/user/reference/pings/index.md, glean-core/rlb/examples/prototype.rs
=> Bug 1714942 - Document initialization for Rust and Desktop

docs/user/reference/metrics/custom_distribution.md
=> Update Custom Distribution documentation

docs/user/reference/metrics/string_list.md
=> Bug 1712073 - Update structure of string list reference page

docs/user/reference/metrics/rate.md
=> Bug 1712071 - Update structure of Rate metric reference page 

docs/user/language-bindings/javascript/plugins/encryption.md
=> Fix wording

.circleci/config.yml
=> Update to latest mdbook-dtmo

docs/user/reference/metrics/event.md
=> Bug 1715052 - Document the ping lifetime requirement for events

glean-core/python/requirements_dev.txt
Replaces dependabot's #1681 PR.
=> Upgrade mypy, and add new types info package

.dictionary, docs/user/user/adding-glean-to-your-project/javascript.md
=> Mention using webextension-polyfill outside of Firefox for Glean.js

.dictionary, docs/user/appendix/twig.md
=> Add funday twig

.circleci/config.yml
=> Use mdbook-dtmo 0.9.0 when generating the Glean book

docs/dev/SUMMARY.md, docs/dev/core/internal/database.md, docs/dev/core/internal/index.md
=> Bug 1718040 - Document database format internals

.taskcluster.yml, taskcluster/glean_taskgraph/__init__.py, taskcluster/glean_taskgraph/build_config.py, taskcluster/glean_taskgraph/job.py, taskcluster/glean_taskgraph/loader/__init__.py, taskcluster/glean_taskgraph/loader/build_config.py, taskcluster/glean_taskgraph/loader/multi_dep.py, taskcluster/glean_taskgraph/target_tasks.py, taskcluster/glean_taskgraph/transforms/__init__.py, taskcluster/glean_taskgraph/transforms/beetmover.py, taskcluster/glean_taskgraph/transforms/module_build.py, taskcluster/glean_taskgraph/transforms/multi_dep.py, taskcluster/glean_taskgraph/transforms/signing.py, taskcluster/glean_taskgraph/worker_types.py
Fixes issue #1717, see also RELENG-617
=> Run taskgraph generation with Python 3

CHANGELOG.md
=> Merge back changelog for v39.0.4

.buildconfig.yml, CHANGELOG.md, Cargo.lock, DEPENDENCIES.md, glean-core/Cargo.toml, glean-core/android/dependency-licenses.xml, glean-core/csharp/Glean/Glean.csproj, glean-core/ffi/Cargo.toml, glean-core/python/setup.py, glean-core/rlb/Cargo.toml, gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy
THE GECKOVIEW VERSION (hopefully)
=> Merge back v40.0.0

.taskcluster.yml
The change in #1734 wasn't quite right. I'm fixing based on the
[fenix .taskcluster.yml](https://github.com/mozilla-mobile/fenix/blob/main/.taskcluster.yml#L250-L288)
@MihaiTabara
=> fix the decision task

docs/user/reference/general/shutdown.md, glean-core/rlb/examples/prototype.rs
=> Bug 1721388 - Document shutdown API (or why it doesn't exist)

.github/auto_assign.yml
[Alessio's back alright](https://www.youtube.com/watch?v=6M6samPEMpM).
=> Add Alessio back to the reviewer list

docs/user/SUMMARY.md, docs/user/reference/metrics/index.md, docs/user/reference/metrics/quantity.md, docs/user/reference/metrics/text.md
=> Bug 1727299 - Document new text metric

docs/user/reference/metrics/timing_distribution.md
=> C++ timing_distribution needs std::move [doc only]

glean-core/ios/Glean.xcodeproj/project.pbxproj, glean-core/ios/Glean/Metrics/QuantityMetric.swift, glean-core/ios/GleanTests/Metrics/QuantityMetricTypeTest.swift
The file wasn't added for some reason and so it wasn't being built and linked into the resulting Glean framework.
=> This adds the QuantityMetricType to the Xcode project file

bin/publish-glean-swift.sh
[doc only] // not really but we don't need CI on this
=> Show all executed commands

docs/user/appendix/twig.md
=> Add the missing TWiG posts

glean-core/rlb/src/lib.rs, glean-core/rlb/tests/persist_ping_lifetime.rs
We'll need a minor (new API) release after.
=> Bug1729723 expose persist ping lifetime

CHANGELOG.md
=> Add changelog entry for URL metric type on iOS

docs/user/appendix/twig.md
=> Add today's TWiG

.dictionary, docs/user/user/adding-glean-to-your-project/qt.md
=> Bug 1727352 - Document how to use unminified Glean.js in Qt

.circleci/config.yml, CHANGELOG.md
CircleCI announcement: https://discuss.circleci.com/t/xcode-13-rc-released/41256
Full software list: https://circle-macos-docs.s3.amazonaws.com/image-manifest/v6052/index.html
---
Let's see how that goes.
=> Bug 1731979 - Upgrade to Xcode 13.0.0

docs/user/SUMMARY.md, docs/user/reference/yaml/metrics.md, docs/user/reference/yaml/pings.md, docs/user/reference/yaml/tags.md, docs/user/user/metrics/adding-new-metrics.md, docs/user/user/pings/custom.md
See: https://github.com/mozilla/glean_parser/pull/406
=> Add documentation for tags

.circleci/config.yml
=> Don't run the android setup if tests will be skipped anyway

docs/dev/cut-a-new-release.md
=> Properly document current release packages

docs/user/reference/yaml/metrics.md
=> No bug - Remove weird written comment about changing metric types after release

docs/user/reference/general/experiments-api.md
=> No bug - Add bug number to JS tabs in experiements API docs

docs/user/user/pings/index.md
=> Bug 1742371 - Update rate limit documentatio with new JS limits

docs/user/user/pings/custom.md
=> Fix timestamp calculation error in glean.restarted docs

docs/user/reference/yaml/metrics.md, docs/user/reference/yaml/pings.md
=> Bug 1743488 - Document the default value for send_in_pings

docs/user/reference/general/toggling-upload-status.md
[doc only]
I tried to add some more interesting examples, but the only one I am confident in is the JS one. The Swift and Kotlin ones I copied and edited from our sample apps and the other ones I just didn't. Let me know if the ones I put there are not too confusing.
=> Bug 1741813 - Make setUploadEnabled documentation more robust

glean-core/android/src/main/java/mozilla/telemetry/glean/private/TimespanMetricType.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/private/TimespanMetricTypeTest.kt, glean-core/src/glean.udl, glean-core/src/lib.rs, glean-core/src/lib_unit_tests.rs, glean-core/src/metrics/timespan.rs, glean-core/tests/timespan.rs
=> Migrate timespan metric implementation

glean-core/android/src/main/java/mozilla/telemetry/glean/private/BooleanMetricType.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/debug/GleanDebugActivityTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/private/BooleanMetricTypeTest.kt, glean-core/src/core/mod.rs, glean-core/src/glean.udl, glean-core/src/lib.rs, glean-core/src/metrics/boolean.rs, glean-core/tests/boolean.rs, glean-core/tests/labeled.rs, glean-core/tests/ping_maker.rs
=> Migrate boolean metric implementation

docs/user/reference/metrics/event.md
=> Update events documentation with InvalidValue error info

docs/user/user/pings/index.md
https://bugzilla.mozilla.org/show_bug.cgi?id=1746884 Bug filed to update the note.
=> Bug 1742613 - Add deprecation note to legacy headers [doc only]

docs/user/reference/yaml/index.md, docs/user/user/adding-glean-to-your-project/swift.md, glean-core/ios/sdk_generator.sh
Turns out everything is in place to support tags already.
=> Bug 1738879 - Document tags.yaml support for an Xcode project

.buildconfig.yml, CHANGELOG.md, Cargo.lock, DEPENDENCIES.md, glean-core/Cargo.toml, glean-core/ffi/Cargo.toml, glean-core/python/setup.py, glean-core/rlb/Cargo.toml, gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy
A proper release now, hopefully.
=> Merge back v43.0.2

docs/dev/README.md
=> Bug 1696400 - Update SDK team list in dev book

glean-core/android/src/main/java/mozilla/telemetry/glean/private/CounterMetricType.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/private/CounterMetricTypeTest.kt, glean-core/src/glean.udl, glean-core/src/metrics/counter.rs, samples/android/app/src/androidTest/java/org/mozilla/samples/gleancore/MainActivityTest.kt
=> [UniFFI] Fix up for counter metric

docs/user/user/integrating-glean-for-product-managers.md
The PR related to the glam [issue](https://github.com/mozilla/glam/issues/1550)
Added notes detailing next steps required to onboard Glean apps to GLAM
=> added glam related notes to integrating-glean-for-product-managers.md

taskcluster/scripts/cross-compile-setup.sh
The old ones are probably expired.
=> Use updated cctools & clang [ci full]

docs/user/reference/metrics/rate.md
=> Bug 1745750 - Document Rate metric APIs on JavaScript

glean-core/ios/Glean/Glean.swift, glean-core/ios/GleanTests/Scheduler/MetricsPingSchedulerTests.swift, glean-core/ios/GleanTests/TestUtils.swift, glean-core/src/metrics/event.rs, samples/ios/app/glean-sample-app/ViewController.swift, samples/ios/app/glean-sample-appUITests/EventPingTest.swift, samples/ios/app/metrics.yaml
=> [Swift] Get sample app running with UniFFI-powered Glean

.circleci/config.yml
See https://discuss.circleci.com/t/legacy-convenience-image-deprecation for details
=> CI: Migrate away from CircleCI legacy convenience images

docs/user/reference/metrics/url.md
Note that we should probably wait for the other changeset in bug 1766980 to land before merging this, but I don't think it would be a huge problem in any case. We know we need the APIs, we know we need to update the docs :)
=> Bug 1766980 - Update the URL docs to mention the FF APIs [docs only]

docs/dev/core/internal/implementations.md
[doc only]
---
I considered re-doing that page, but opted for doing the minimal thing now to at least be more accurate.
The nicer UTF-8 characters were also used a while back on https://mozilla.github.io/glean/book/user/pings/sent-by-glean.html
=> Update the features matrix to reflect current state

docs/user/SUMMARY.md, docs/user/user/metrics/validation-checklist.md
I tried to keep this as general as possible, but there might be other advices we could give folks that want to perform initial validation of their data.
=> Bug 1768142 - Create a checklist for helping with data validation.

glean-core/ios/Glean/Scheduler/MetricsPingScheduler.swift, glean-core/ios/GleanTests/GleanTests.swift, glean-core/src/glean.udl, glean-core/src/lib.rs, glean-core/src/metrics/boolean.rs, glean-core/src/metrics/datetime.rs, glean-core/src/traits/boolean.rs
Tackling on some cleanups & fixes
=> Small cleanups & fixes for uniffi

.buildconfig.yml, CHANGELOG.md, Cargo.lock, DEPENDENCIES.md, glean-core/Cargo.toml, glean-core/android/dependency-licenses.xml, glean-core/ffi/Cargo.toml, glean-core/python/setup.py, glean-core/rlb/Cargo.toml, gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy
Starting the release now.
44.1.2 went awry and wasn't released.
As per the changelog we added new functionality (new public functions) and so we go for a bumped minor version
=> Merge back release v44.2.0

.dictionary, docs/user/README.md
This got lost somewhen and people were left wondering :-)
=> Document where to submit requests/bugs [doc only]

CHANGELOG.md, Makefile, glean-core/Cargo.toml, glean-core/ios/sdk_generator.sh, glean-core/python/glean/__init__.py, glean-core/python/setup.py, gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy
This relaxed a version requirement, making it compatible with m-c again
=> Upgrade to glean_parser v6.0.1

.dictionary, docs/user/reference/metrics/boolean.md, docs/user/reference/metrics/counter.md, docs/user/reference/metrics/custom_distribution.md, docs/user/reference/metrics/datetime.md, docs/user/reference/metrics/event.md, docs/user/reference/metrics/labeled_booleans.md, docs/user/reference/metrics/labeled_counters.md, docs/user/reference/metrics/labeled_strings.md, docs/user/reference/metrics/memory_distribution.md, docs/user/reference/metrics/quantity.md, docs/user/reference/metrics/rate.md, docs/user/reference/metrics/string.md, docs/user/reference/metrics/string_list.md, docs/user/reference/metrics/text.md, docs/user/reference/metrics/timespan.md, docs/user/reference/metrics/timing_distribution.md, docs/user/reference/metrics/url.md, docs/user/reference/metrics/uuid.md, docs/user/reference/pings/index.md
=> Bug 1770149 - UniFFI: Adjust docs for all metric types

.gitignore, glean-core/rlb/README.md
=> Small cleanup fixes

Cargo.lock, DEPENDENCIES.md, bin/dependency-summary.sh, glean-core/Cargo.toml, glean-core/android-native/dependency-licenses.xml, glean-core/android/dependency-licenses.xml, glean-core/src/error.rs
Everything is handled by UniFFI now
=> Remove ffi-support crate

.buildconfig.yml, CHANGELOG.md, Cargo.lock, DEPENDENCIES.md, glean-core/Cargo.toml, glean-core/android-native/dependency-licenses.xml, glean-core/android/dependency-licenses.xml, glean-core/python/setup.py, glean-core/rlb/Cargo.toml, gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy
Incrementing to 51.0.0
[Full changelog](https://github.com/mozilla/glean/compare/v50.1.2...v51.0.0)
* General
* Remove `testHasValue` from all implementations.
`testGetValue` always returns a null value
(`null`, `nil`, `None` depending on the language) and does not throw an exception ([#2087](https://github.com/mozilla/glean/pull/2087)).
* BREAKING CHANGE: Dropped `ping_name` argument from all `test_get_num_recorded_errors` methods ([#2088](https://github.com/mozilla/glean/pull/2088))  
Errors default to the `metrics` ping, so that's what is queried internally.
* BREAKING: Disable `safe-mode` everywhere. This causes all clients to migrate from LMDB to safe-mode storage ([#2123](https://github.com/mozilla/glean/pull/2123))
* Kotlin
* Fix the Glean Gradle Plugin to work with Android Gradle …
=> Bumped version to 51.0.0

docs/dev/android/development-with-android-components.md, docs/dev/android/locally-published-components-in-fenix.md
=> Bug 1779268 -  Document how to swap out the whole Glean Gradle Plugin in A-C 

docs/user/reference/general/initializing.md
Was trying something out and found this 👀
=> Update Rust glean::initialize documentation

glean-core/python/setup.py
=> Python: Remove unused function `find_packages` from setup.py

build.gradle, gradle/wrapper/gradle-wrapper.properties
These are in alignment with m-c.
=> Update kotlin and gradle to newer versions.

glean-core/src/database/mod.rs, glean-core/src/upload/directory.rs, glean-core/tests/storage.rs, taskcluster/scripts/cross-compile-setup.sh
=> Apply beta clippy suggestions [ci full]

Makefile, README.md, docs/dev/core/internal/upload.md, glean-core/src/upload/mod.rs
=> Remove references to glean-ffi

.circleci/config.yml, .circleci/jazzy.yml, CHANGELOG.md, bin/run-ios-build.sh, bin/run-ios-sample-app-build.sh, bin/run-ios-sample-app-test.sh, bin/run-ios-tests.sh, glean-core/ios/Glean.xcodeproj/project.pbxproj, glean-core/ios/Glean.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
CircleCI announcement: https://discuss.circleci.com/t/xcode-14-rc-released/45334
Full software list: https://circle-macos-docs.s3.amazonaws.com/image-manifest/v8770/index.html
---
We should hold off on this until we're sure that our consumers can use it.
firefox-ios: https://github.com/mozilla-mobile/firefox-ios/issues/11610
focus already enabled xcode 14: https://github.com/mozilla-mobile/focus-ios/issues/3308
=> Upgrade to Xcode 14.0.0

build.gradle
AC and A-S have already picked up this change, let's keep Glean in sync as well.
=> Bump jna to 5.12.1

docs/user/_includes/lifetimes-parameters.md, docs/user/reference/yaml/metrics.md
=> Bug 1795925 - Document version expiry in the yaml reference

glean-core/ios/GleanTests/Metrics/LabeledMetricTests.swift, glean-core/rlb/src/lib.rs, glean-core/src/error.rs, glean-core/src/glean.udl, glean-core/src/lib.rs, glean-core/src/metrics/ping.rs
I'm not 100% happy with just logging this. Maybe we should record an error? hmmm.
=> Bug 1797262 - Handle upload trigger/cancel failure by logging, but not panicking

docs/dev/android/development-with-android-components.md, docs/dev/cut-a-new-release.md, docs/user/language-bindings/android/instrument-android-crashes-example.md, docs/user/language-bindings/index.md, docs/user/user/adding-glean-to-your-project/kotlin.md
=> Use moved repository location of android-components

docs/shared/label-check.js, docs/user/book.toml, docs/user/reference/metrics/index.md
=> Docs: Add a label checker to the label format docs

Cargo.lock, glean-core/Cargo.toml
Note: This keeps LMDB enabled.
=> Bug 1780370 - Upgrade to rkv 0.18

glean.1.schema.json
Not sure if this needs to be updated manually, but those changes are the same as done in https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/750
=> [Bug 1799509] Add count to timing_distribution

docs/user/reference/general/initializing.md
=> Bug 1800457 - Document `test_reset_glean` in the RLB

CHANGELOG.md, Makefile, glean-core/Cargo.toml, glean-core/build/Cargo.toml, glean-core/build/src/lib.rs, glean-core/ios/sdk_generator.sh, glean-core/python/glean/__init__.py, glean-core/python/setup.py, gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy
=> Update to glean-parser v6.4.0

glean-core/android/src/test/java/mozilla/telemetry/glean/private/CounterMetricTypeTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/private/TimespanMetricTypeTest.kt, glean-core/rlb/src/test.rs, glean-core/src/dispatcher/mod.rs, glean-core/src/lib.rs, glean-core/src/lib_unit_tests.rs
Can be reviewed commit-by-commit to make it easier.
=> Cleaning up some old todos and ignored tests.

.dictionary, Makefile, docs/dev/SUMMARY.md, docs/dev/ios/debug-glean-on-ios.md
=> Bug 1753016 - Document how to use local Glean build in other applications

.circleci/config.yml
I'm manually doing this for v52.0.1
=> CI: Change directory before upload

tools/embedded-uniffi-bindgen/src/main.rs
=> Rust: Mention the correct option in the context

Cargo.lock, glean-core/Cargo.toml, glean-core/rlb/Cargo.toml, samples/rust/Cargo.toml
m-c wants to update for sure: https://bugzilla.mozilla.org/show_bug.cgi?id=1813411
=> Rust: Update env_logger dependency

glean-core/ios/GleanTests/Metrics/LabeledMetricTests.swift
And you can't build iOS except on Mac hw.
=> Missed a comma

CHANGELOG.md, glean-core/metrics.yaml, glean-core/rlb/tests/upload_timing.rs, glean-core/src/internal_metrics.rs, glean-core/src/lib.rs, glean-core/src/metrics/timing_distribution.rs, glean-core/src/upload/mod.rs
=> Bug 1814592 - Instrument the time needed for a successful/failure upload of a ping

CHANGELOG.md
=> Changelog for the iOS `baseline.duration` bugfix

build.gradle, glean-core/android/build.gradle, samples/android/app/build.gradle
Also remove some unnecessary kotlin-stdlib usage as it's already implicit.
=> Update Kotlin to version 1.8.10

Cargo.lock, glean-core/python/glean/__init__.py, glean-core/python/glean/_subprocess/_process_dispatcher_helper.py, glean-core/python/requirements_dev.txt
Using the excellent [paul-mclendahand](https://github.com/willkg/paul-mclendahand)
=> Rollup some dependabot PRs

build.gradle
Changelog:
https://github.com/java-native-access/jna/blob/master/CHANGES.md#release-5130
=> Update jna to version 5.13.0

build.gradle
Updated in AC via https://github.com/mozilla-mobile/firefox-android/pull/1770
=> Update Kotlin to version 1.8.20

settings.gradle
Changelog (it's been awhile): https://bitbucket.org/snakeyaml/snakeyaml/wiki/Changes
=> Update snakeyaml to version 2.0

.dictionary, docs/user/reference/metrics/url.md, docs/user/reference/yaml/metrics.md
[doc only]
---
related to https://github.com/mozilla/glean_parser/pull/589
=> Bug 1834596 - docs: Update data sensitivity categories

build.gradle
Bumped upstream in https://bugzilla.mozilla.org/show_bug.cgi?id=1826590
=> Update Kotlin Coroutines to version 1.7.1

CHANGELOG.md
=> Update CHANGELOG.md for #2498

.circleci/config.yml
I manually did this for 54.0.0
=> CI: Fix Python release process

docs/user/user/debugging/javascript.md
=> Bug 1855793 - window.Glean doc updates

docs/user/language-bindings/javascript/cli.md
Docs only PR companion for https://github.com/mozilla/glean.js/pull/1768
=> Bug 1852217 - Glean.js python env var docs

CHANGELOG.md
=> Experimentation ID was actually released in v55

build.gradle
Changelog: https://github.com/robolectric/robolectric/releases/tag/robolectric-4.11
=> Update robolectric to version 4.11

docs/user/reference/general/initializing.md
=> Bug 1862618 - Fix link to Glean.js API docs

.circleci/config.yml, CHANGELOG.md, Cargo.lock, bin/run-ios-build.sh, bin/run-ios-sample-app-build.sh, bin/run-ios-sample-app-test.sh, bin/run-ios-tests.sh, build-scripts/xc-universal-binary.sh, docs/dev/ios/setup-ios-build-environment.md, samples/ios/app/README.md, supply-chain/audits.toml
This is missing the cargo-vet, I'll add that once I know CI works.
=> Update to Xcode 15

CHANGELOG.md, glean-core/metrics.yaml, glean-core/src/core/mod.rs, glean-core/src/database/mod.rs, glean-core/src/internal_metrics.rs, glean-core/src/lib_unit_tests.rs
WIP for instrumenting which RKV failure caused a new rkv to be created
=> Bug 1815253 - Record what caused an RKV db load failure

build.gradle
Changelogs:
* https://developer.android.com/jetpack/androidx/releases/annotation#1.7.1
* https://developer.android.com/jetpack/androidx/releases/browser#1.7.0
* https://github.com/detekt/detekt/releases/
* https://github.com/mockito/mockito/releases
* https://github.com/JetBrains/kotlin/releases/tag/v1.8.22
* https://github.com/robolectric/robolectric/releases/tag/robolectric-4.11.1
* https://github.com/java-native-access/jna/blob/master/CHANGES.md#release-5140
=> Update Gradle dependencies to latest versions

CHANGELOG.md, gradle/wrapper/gradle-wrapper.properties, gradlew.bat
Release notes: https://docs.gradle.org/8.6/release-notes.html
=> Update Gradle to version 8.6

docs/user/reference/metrics/timing_distribution.md
=> Bug 1877828 - Docs: Add the missing closing footer for `accumulateSamples` doc

glean-core/python/glean/net/http_client.py, glean-core/python/glean/net/ping_uploader.py, glean-core/python/requirements_dev.txt
Rollup of #2724,  #2725, #2732, #2733
=> Rollup of dependabot PRs

.dictionary, docs/user/user/adding-glean-to-your-project/kotlin.md
=> Bug 1879830 - Docs: Remove note about earlier versions of Gradle plugin

docs/user/reference/yaml/metrics.md
=> Bug 1880116 - Docs: Type changes are allowed, but discouraged

glean-core/src/metrics/boolean.rs, glean-core/src/metrics/counter.rs, glean-core/src/metrics/custom_distribution.rs, glean-core/src/metrics/datetime.rs, glean-core/src/metrics/denominator.rs, glean-core/src/metrics/event.rs, glean-core/src/metrics/experiment.rs, glean-core/src/metrics/labeled.rs, glean-core/src/metrics/memory_distribution.rs, glean-core/src/metrics/numerator.rs, glean-core/src/metrics/quantity.rs, glean-core/src/metrics/rate.rs, glean-core/src/metrics/string.rs, glean-core/src/metrics/string_list.rs, glean-core/src/metrics/text.rs, glean-core/src/metrics/timespan.rs, glean-core/src/metrics/timing_distribution.rs, glean-core/src/metrics/url.rs, glean-core/src/metrics/uuid.rs
[doc only]
---
Staring at this while doing the object metric ... so I just had to fix it across the board.
=> Rust: Fix docs for all core metric implementations

gradle/libs.versions.toml
=> Update some AndroidX dependencies to the latest versions

bin/dependency-summary.sh
=> Bug 1882799 - Add check for minimal cargo-about version available

Makefile, glean-core/python/glean/_builtins.py, glean-core/python/glean/_loader.py, glean-core/python/glean/_process_dispatcher.py, glean-core/python/glean/metrics/datetime.py, glean-core/python/glean/metrics/event.py, glean-core/python/glean/metrics/timing_distribution.py, glean-core/python/glean/net/ping_upload_worker.py, glean-core/python/tests/conftest.py, glean-core/python/tests/metrics/test_counter.py, glean-core/python/tests/metrics/test_event.py, glean-core/python/tests/metrics/test_labeled.py, glean-core/python/tests/metrics/test_quantity.py, glean-core/python/tests/metrics/test_string.py, glean-core/python/tests/metrics/test_timespan.py, glean-core/python/tests/metrics/test_timing_distribution.py, glean-core/python/tests/metrics/test_url.py, glean-core/python/tests/metrics/test_uuid.py, glean-core/python/tests/test_glean.py, glean-core/python/tests/test_loader.py, glean-core/python/tests/test_network.py, glean-core/python/tests/test_subprocess.py
We didn't actually check and ran the formatting, so this contains a bunch of changes in the second commit.
But now it's clean.
=> Python: Check format as part of linting

Makefile
=> Use correct task names in Makefile

bin/build-win.sh
Needs fixes from #2801 to actually work, but can land independently
=> Fix the windows helper script to actually work with current maturin build

gradle/libs.versions.toml
Changelogs:
* https://github.com/mockito/mockito/releases/tag/v5.11.0
* https://github.com/robolectric/robolectric/releases/tag/robolectric-4.12
* https://github.com/robolectric/robolectric/releases/tag/robolectric-4.12.1
=> Update some Android test dependencies to the latest versions

docs/dev/core/internal/payload.md, docs/user/reference/metrics/object.md
=> Object metric: Better spell out what the structure allows

docs/user/reference/metrics/index.md
=> Bug 1895607 - Docs: Add link to the object metric in reference docs

CHANGELOG.md, glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/config/Configuration.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/scheduler/MetricsPingSchedulerTest.kt, glean-core/rlb/src/lib.rs, glean-core/src/database/mod.rs, glean-core/src/glean.udl, glean-core/src/lib.rs, samples/android/app/src/main/java/org/mozilla/samples/gleancore/GleanApplication.kt
Backports https://github.com/mozilla/glean/pull/2851 to v60.1
=> [backport v60.1] Kotlin: Allow configuring delayPingLifetimeIo in Kotlin

.buildconfig.yml, .dictionary, CHANGELOG.md, Cargo.lock, DEPENDENCIES.md, glean-core/Cargo.toml, glean-core/rlb/Cargo.toml, gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy, pyproject.toml
Let's get this out too, so we're in a consistent state.
=> Merge back release v60.3.0

glean-core/src/debug.rs, glean-core/src/lib.rs
=> Escape html-like text in docs

CHANGELOG.md
=> Backport v60.0.1 release notes

glean-core/android/src/main/java/mozilla/telemetry/glean/config/Configuration.kt, glean-core/ios/Glean/Config/Configuration.swift, glean-core/python/glean/config.py, glean-core/rlb/src/configuration.rs, glean-core/src/lib.rs
=> Remove experimental notation on `enableEventTimestamps`

gradle/libs.versions.toml
Changelogs: https://developer.android.com/jetpack/androidx/releases/test
=> Update AndroidX Test to the latest releases

CHANGELOG.md, gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy
Turns out using that was actually not working due to differing types.
I also added a changelog entry now.
=> Gradle plugin: Convert env dir to File

docs/user/language-bindings/android/android-build-configuration-options.md
=> Use correct parameter name in example

gradle/libs.versions.toml
Changelogs:
* https://developer.android.com/jetpack/androidx/releases/annotation#1.8.1
* https://developer.android.com/jetpack/androidx/releases/lifecycle#2.8.4
* https://github.com/robolectric/robolectric/releases/tag/robolectric-4.13
* https://www.jacoco.org/jacoco/trunk/doc/changes.html
=> Update some Gradle dependencies to the latest releases

samples/android/app/metrics.yaml, samples/android/app/src/main/java/org/mozilla/samples/gleancore/MainActivity.kt, samples/ios/app/glean-sample-app/ViewController.swift, samples/ios/app/glean-sample-appUITests/ViewControllerTest.swift, samples/ios/app/metrics.yaml
This tests the generation of nested arrays.
This currently lacks a test that it correctly serializes.
---
This needs https://github.com/mozilla/glean_parser/pull/729
and I would like to add a proper test of the serialization.
=> Bug 1908157 - Android sample: Extra nested array

Cargo.lock, glean-core/Cargo.toml, glean-core/build/Cargo.toml, glean-core/build/src/lib.rs, glean-core/python/glean/__init__.py, glean-core/rlb/src/private/object.rs, glean-core/src/traits/mod.rs, samples/rust/Cargo.toml, samples/rust/metrics.yaml, samples/rust/src/main.rs
Needs https://github.com/mozilla/glean_parser/pull/742
=> Bug 1910809 - Rust: Test an object metric with null values

CHANGELOG.md
=> Add link to glean_parser update PR

glean-core/rlb/Cargo.toml
It's been picked up automatically
[doc only]
=> Remove explicit example from Cargo manifest

glean-core/rlb/src/lib.rs
=> Wrap one more paragraph

CHANGELOG.md, Cargo.lock, Makefile, glean-core/Cargo.toml, glean-core/build/Cargo.toml, glean-core/build/src/lib.rs, glean-core/ios/sdk_generator.sh, glean-core/python/glean/__init__.py, glean-core/src/lib.rs, glean-core/src/metrics/labeled.rs, glean-core/src/metrics/mod.rs, glean-core/src/metrics/quantity.rs, glean-core/tests/labeled.rs, gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy, pyproject.toml, samples/rust/metrics.yaml
It'll require mozilla/glean_parser#763 to be merged, released, and then the new version required here.
=> bug 1925346 - Implement new metric type labeled_quantity

.dictionary, docs/user/user/howto/investigating-data-issues/investigating-data-issues.md
Some small nits that occurred to me while reading this excellent guide.
=> Clarify OS and Device info suitability in Data Investigation Guide

samples/rust/src/main.rs
This makes local debugging easier by:
1. Keeping the files in the order as they arrive
2. Putting the ping name into the file, making it easy to pick out the right file to look at.
=> sample MovingUploader: count and type in filename

docs/dev/cut-a-new-release.md
=> Bug 1879869 - Document how to manually publish Rust crates in the release docs

CHANGELOG.md
=> Update changelog for everything since the last release

docs/dev/core/internal/upload.md
=> Bug 1951667 - Describe ping request, including uploader capabilities, in more detail

Cargo.lock, deny.toml, glean-core/Cargo.toml, glean-core/src/glean.udl, glean-core/src/lib.rs, supply-chain/audits.toml, supply-chain/config.toml, supply-chain/imports.lock, tools/embedded-uniffi-bindgen/Cargo.toml
Minimal code changes on our side.
Not yet ready, will need some vetting.
=> Upgrading to uniffi 0.29

.dictionary, .gitignore, docs/user/SUMMARY.md, docs/user/language-bindings/android/gecko-content-processes-and-glean.md, docs/user/reference/general/initializing.md
Adding some better docs and links to the Firefox source docs for FOG IPC
=> Bug 1950869 - Document how GeckoView content processes record data in Glean on Android

docs/dev/testing.md
=> Document usage of cargo nextest

.circleci/config.yml, CHANGELOG.md, README.md, glean-core/Cargo.toml, glean-core/build/Cargo.toml, glean-core/rlb/Cargo.toml, glean-core/rlb/examples/crashing-threads.rs
With the latest uniffi we generate code that requires at least that.
=> Update to MSRV 1.82

CHANGELOG.md
=> Fix up changelog entry

glean-core/android/src/main/java/mozilla/telemetry/glean/debug/GleanDebugActivity.kt
This reverts commit 24165f9fe177ccd1c0b43cbb2db1434fe9da0d00.
---
It seems this is currently causing issues in the raptor/browsertime tests. Or so I think. But the only way to find out is to release and get that into m-c for a try run
=> Revert "Bug 1946133 - GleanDebugActivity fixes for StrictMode violation in Fenix

docs/dev/cut-a-new-release.md
=> New release step: pick a song

docs/user/language-bindings/android/instrument-android-crashes-example.md
Small PR - Commit 4f8c7124bee5bc61ac7c6c028486de7aa77a3f70 moved `GleanApplication.kt`. This PR adjusts sources to changes. Relevant page: https://mozilla.github.io/glean/book/language-bindings/android/instrument-android-crashes-example.html
=> Update `GleanApplication.kt` example

CHANGELOG.md, docs/user/reference/metrics/labeled_quantity.md, glean-core/android/src/main/java/mozilla/telemetry/glean/private/LabeledMetricType.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/private/LabeledMetricTypeTest.kt, glean-core/ios/Glean/Metrics/LabeledMetric.swift, glean-core/ios/GleanTests/Metrics/LabeledMetricTests.swift, glean-core/python/glean/metrics/__init__.py, glean-core/python/glean/metrics/labeled.py, glean-core/python/tests/metrics/test_labeled.py, glean-core/src/glean.udl
=> Bug 1926646 - Implement LabeledQuantity for Kotlin/Swift/Python

CHANGELOG.md
=> docs: Fix up changelog, link goes above notes

docs/user/reference/metrics/event.md
=> docs: Remove wrong blockquote include

CHANGELOG.md
=> docs: Properly indent lists in the changelog

glean-core/ios/sdk_generator.sh
This reverts commit b6ae9c79213c6fa1d1c59ae469b62e9982da6cd1.
---
Oops, I broke CI.
=> Revert "Quote shell variables to please shellcheck"

.buildconfig.yml, Cargo.lock, DEPENDENCIES.md, glean-core/Cargo.toml, glean-core/rlb/Cargo.toml, gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy, pyproject.toml
In #3204 I backported the changelog, but not the version bumps. Doing that now.
=> Backport missing version bumps

docs/dev/android/development-with-mozilla-central.md
Currently the substitution approach doesn't reliably work.
[doc only]
=> docs: Document how to use mavenLocal or a dev version on try

CHANGELOG.md
=> Backport 64.5.5 changelog

.circleci/config.yml, CHANGELOG.md, bin/update-xcode-version.sh, docs/dev/ios/setup-ios-build-environment.md, samples/ios/app/README.md
I should have gone straigt for that version...
=> Swift: Build on Xcode 16.4

glean-core/android/src/main/java/mozilla/telemetry/glean/private/ObjectMetricType.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/private/ObjectMetricTypeTest.kt, glean-core/ios/Glean/Metrics/ObjectMetric.swift, glean-core/ios/GleanTests/Metrics/ObjectMetricTests.swift
Needs https://github.com/mozilla/glean_parser/pull/808 to go along with it.
=> Bug 1983858 - Implement ObjectSerialize recursively
