mozilla/glean

glean-core/src/database/mod.rs, glean-core/src/inner.rs, glean-core/src/lib.rs
This PR moves the rkv implementation details, including Lifetime.Application handling, to
the newly introduced Database module.
=> Move the storage details to a separate module

glean-core/android/build.gradle, glean-core/android/sdk_generator.gradle, samples/android/app/build.gradle
This moves the `sdk_generator.gradle` file back to something that could be more easily shared between legacy glean and glean.rs by adding config variables for the things that need to be different.
Also, this will no longer download glean_parser on every build.
=> Be more dynamic in use of glean_parser

build.gradle, glean-core/android/build.gradle
This applies the changes from [c40e2cc in mozilla/application-services](https://github.com/mozilla/application-services/tree/c40e2ccb422cf4af9ffdf095149cec34de1d4bef) to our repo, with minimal tweaks due to the different directory layout and the glean parsers integration.
**Note** - klint and detekt are currently not invoked on CI, even though they can run manually, because we have dozens of errors :)
=> Backport updates from application-services gradle files

build.gradle
`./gradlew detekt` didn't run for me without that file locally.
Here's application-services file: https://github.com/mozilla/application-services/blob/377c1580deb21b9e17f8ba6d36e2565bab0891a5/.detekt.yml
It's 500 lines long. I don't like that and I don't understand roughly 499 of those lines, so I opted for having the most minimal working config instead.
Edit: after more testing and chatting I removed the config file from the build.gradle. We can add it back when we _do_ need to change the config.
=> Add (empty) detekt config to make detekt happy

.circleci/config.yml
The Android 27 SDK ends up getting downloaded by the build script.  Using the Docker image with that version already baked should save on CI runtime, theoretically, though we should confirm that before merging.
=> Use Android 27 docker image

.circleci/config.yml, build.gradle, glean-core/android/build.gradle, glean-core/android/src/main/AndroidManifest.xml, glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/config/Configuration.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/net/HttpPingUploader.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/net/PingUploader.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/scheduler/PingUploadWorker.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/TestUtil.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/net/HttpPingUploaderTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/scheduler/PingUploadWorkerTest.kt, samples/android/app/build.gradle, samples/android/app/src/main/java/org/mozilla/samples/glean/MainActivity.kt, samples/android/app/src/main/res/layout/activity_main.xml
We have upload \o/  (Well, mostly thanks to copying a bunch of already working code over from glean-ac -- thanks to @travis79 and @Dexterp37).
The first commit just copies the files from glean-ac over.  The second commit includes the changes to make them work in the new context.  So it might be easier to review by only looking at the second commit in order to ignore things that were already reviewed on the glean-ac side.
There are a few TODOs here, with bugs already created and noted.
=> 1551153: Enable the ping uploader in glean-core

glean-core/android/src/main/java/mozilla/telemetry/glean/private/CounterMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/rust/LibGleanFFI.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/private/CounterMetricTypeTest.kt, glean-core/ffi/src/lib.rs, glean-core/src/metrics/counter.rs, glean-core/src/metrics/mod.rs
We actually should use u32 internally, but:
because Kotlin doesn't (yet) have unsigned integers, it's always going to pass us signed values.
We also do all the error checking on the Rust side, so we need to receive the signed value to check for negativity and bail out.
We still don't do overflow checks though.
[Bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1552131)
=> Use i32 everywhere for counters

Cargo.lock, glean-core/android/src/main/java/mozilla/telemetry/glean/private/BooleanMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/CounterMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/StringMetricType.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/TestUtil.kt, glean-core/ffi/Cargo.toml, glean-core/ffi/src/lib.rs
This enables a logger implementation on platforms that are not Android: we couldn't see any log beyond FFI for this reason, since tests are x86/x64.
This additionally redirects Kotlin logcat to stdout in tests.
=> Redirect logging to stdout in tests

glean-core/android/pings.yaml, glean-core/android/sdk_generator.gradle
This just copies over the updated `pings.yaml` from glean-ac and updates the glean_parser to a version that supports the new metadata.
=> 1547967: Include pings metadata

.buildconfig.yml, glean-core/android/build.gradle, publish.gradle, settings.gradle
This enables back artifact publishing by integrating back the changes to the gradle scripts up until
changeset mozilla/application-services@5d8dd7b .
This allows to publish glean-core to a local Maven repo with the following command:
`./gradlew publishToMavenLocal`
Once published, the package can be consumed by other applications built locally. Instructions on how to do that will come as part of [bug 1551156](https://bugzilla.mozilla.org/show_bug.cgi?id=1551156).
=> Merge the latest changes from a-s gradle scripts

docs/dev/core/new-metric-type.md, glean-core/android/src/main/java/mozilla/telemetry/glean/private/BooleanMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/CounterMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/StringMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/rust/LibGleanFFI.kt, glean-core/ffi/examples/glean.h, glean-core/ffi/src/lib.rs, glean-core/src/common_metric_data.rs, glean-core/src/metrics/boolean.rs, glean-core/src/metrics/counter.rs, glean-core/src/metrics/string.rs
Posting this because the code part was easy, but I have some hesitations:
* The `should_record` check _also_ happens on the Rust side
* We do avoid putting any work in the Dispatcher queue with this.
* The (Rust-side) check is on the metric and requires access to the glean object, therefore we need to re-implement it for every type
* There might be a way of using traits here to implement it just once (we will need to "re-implement" exposing the common metric data though)
* I opted for not doing that now (it's a refactoring, not blocking anything and the code duplication so far is simple)
*  We also need to duplicate code on the Kotlin side, because we need a `*_should_record` function per type. Unfortunately I don't see a way to avoid this (again, duplication here contains no complex …
=> Bug 1552850 - Implement shouldRecord on the Kotlin side

docs/dev/core/new-metric-type.md, glean-core/src/metrics/boolean.rs, glean-core/src/metrics/counter.rs, glean-core/src/metrics/mod.rs, glean-core/src/metrics/string.rs
Bikeshed:
Should we call the trait `MetricType` or something else?
right now it only exposes the `meta()` method and the `should_record` method, but maybe we have more in the future?
=> Refactored should record

Makefile
This allows to only run clippy, which is much faster than its Kotlin
counterpart.
=> Split linting into multiple tasks

glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/net/PingUploader.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt, glean-core/src/database/mod.rs
Import the tests over from [this version GleanTest.kt](https://raw.githubusercontent.com/mozilla-mobile/android-components/8ef0d4b3247255ca6c456e9b5ab61338bc109209/components/service/glean/src/test/java/mozilla/components/service/glean/GleanTest.kt) from glean-ac.
**Note**: the first commit simply overwrites the current test file we own.
=> Import GleanTest.kt from glean-ac

glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/rust/LibGleanFFI.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt, glean-core/examples/sample.rs, glean-core/ffi/examples/glean.h, glean-core/ffi/examples/glean_app.c, glean-core/ffi/src/lib.rs, glean-core/src/lib.rs, glean-core/tests/boolean.rs, glean-core/tests/common/mod.rs, glean-core/tests/counter.rs, glean-core/tests/string.rs
Follow up to #90 in which we now keep track of the flag before we initialize.
We can eventually deprecate the "call before init" way and move the flag into the initializer.
For now this is the easy way out of crashing.
=> Bug 1553424 - Setting uploadEnabled before initialization should not crash

glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/PingType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/rust/LibGleanFFI.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/private/PingTypeTest.kt, glean-core/examples/sample.rs, glean-core/ffi/examples/glean.h, glean-core/ffi/src/lib.rs, glean-core/src/lib.rs, glean-core/src/metrics/mod.rs, glean-core/src/metrics/ping.rs, glean-core/src/ping/mod.rs, glean-core/tests/ping.rs
I'm just posting this here for discussion -- either here or in our next meeting if that's more efficient.  FFI and Kotlin side not implemented yet.
I first considered putting the ping registry on the Glean object, since it sort of logically makes sense there.  However, libraries need to register pings at any time during startup, including before `Glean::initialize` is called.  Since we've tied `new` and `initialize` together, we couldn't add pings to the ping registry before the Glean singleton is initialized, since before that there is no Rust-side Glean object.  An alternative to make that work would be to split `new` and `initialize` apart again, which isn't great.
So I came up with this solution which uses an actual global object and state on the Rust side.  It's not bad, but it does …
=> Move PingType metadata to the Rust side

build.gradle, glean-core/android/build.gradle
With this `./gradlew docs` will generate HTML documentation in build/javadoc/glean.rs/
=> Bug 1555031 - Generate kotlin docs

.circleci/config.yml, glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/rust/LibGleanFFI.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/TestUtil.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/private/LabeledMetricTypeTest.kt, glean-core/ffi/examples/Makefile, glean-core/ffi/examples/glean.h, glean-core/ffi/examples/glean_app.c, glean-core/ffi/src/lib.rs
This brings back in some testing content from glean-ac in LabeledMetricTypeTests.kt.
Mainly, this checks pings against the schema, since getting that right for labeled metrics is a bit fiddly.
In order to do this, it makes `collectAndCheckPingSchema` from glean-ac work and updates the API to use `PingType` rather than ping names.
This had knockon effects in the FFI, and then the C FFI example, so that's been updated to run on Linux and also run in CI.  **I plan to go back and make that work on Mac as well again, once I've verified CI is working on that.**
=> Reinstate deep JSON inspection of labeled metric tests

.circleci/config.yml, docs/SUMMARY.md, docs/api/index.md, glean-core/android/build.gradle
This is an experimental follow-on to link to the Kotlin docs from the mdbook content and then run on CI and deploy all together.
=> Add Kotlin docs to CI

.circleci/config.yml, docs/SUMMARY.md, docs/api/index.md, glean-core/android/build.gradle
Persisting the docs in two different tasks and then merging for deployment didn't work as I had hoped, so I'm trying something different.
=> Fix Kotlin doc deployment

glean-core/android/build.gradle
This fixes a crash occurring in glean when the connectivity is disabled and then enabled. See
https://github.com/mozilla-mobile/android-components/issues/3110 for context.
=> Upgrade the WorkManager dependency to 2.0.1

docs/dev/core/new-metric-type.md, glean-core/ffi/src/labeled.rs, glean-core/src/metrics/boolean.rs, glean-core/src/metrics/counter.rs, glean-core/src/metrics/labeled.rs, glean-core/src/metrics/mod.rs, glean-core/src/metrics/ping.rs, glean-core/src/metrics/string.rs, glean-core/src/metrics/string_list.rs, glean-core/src/metrics/uuid.rs, glean-core/tests/labeled.rs
This has the overhead of storing a metric instance per labeled metric.
However, these should be rather small.
And on the upside this allows us to store metric-type-specific data
(e.g. the time unit for DateTime) for that metric only instead of inside
the common metric data.
=> Store an instance of the underlying metric and clone it on request

glean-core/src/metrics/string.rs, glean-core/tests/string.rs
This is about to land in glean-ac too. Let's not merge it until mozilla-mobile/android-components#3236 is merged.
=> Bump the string length limit to 100 characters to match glean-ac

glean-core/src/error_recording.rs, glean-core/src/lib.rs, glean-core/src/metrics/counter.rs, glean-core/src/metrics/datetime.rs, glean-core/src/metrics/labeled.rs, glean-core/src/metrics/string.rs, glean-core/src/metrics/string_list.rs, glean-core/tests/counter.rs, glean-core/tests/labeled.rs, glean-core/tests/string.rs
Based on #95, needs a rebase when that lands.
The last 3 commits are relevant. We now have all things in place for error reporting using labeled metrics.
Even though the error reporting itself doesn't use the labeled metrics, we simply depend on the same "encoding" of labels into the key.
=> Add error reporting for labeled metrics (and counters)

glean-core/android/build.gradle
This does (more-or-less) what android-components does to get logging messages out from running the Android tests.  This will make it easier to diagnose what's going on when tests fail in CI.
=> 1556486: Output logging from Android tests

glean-core/src/metrics/mod.rs
Suggesting a small change that I missed in review.
The variable name `tz` feels very much like "timezone" to me, particularly given the context here of date times.  It actually confused me when I was trying to document this for 1552774, so thought maybe I'd just change it...?
=> Rename tz -> time_unit to avoid confusion with timezone

docs/dev/core/internal.md, glean-core/examples/sample.rs, glean-core/ffi/src/lib.rs, glean-core/src/lib.rs, glean-core/src/ping/mod.rs, glean-core/tests/ping_maker.rs
Sequence numbers are stored as a counter under a name that includes the storage name:
<storage name>#sequence
Everything is stored in the special `glean.internal` storage.
This is not used for anything else.
=> Implement sequence numbers as a counter

glean-core/src/lib.rs, glean-core/src/metrics/datetime.rs, glean-core/src/ping/mod.rs, glean-core/src/util.rs
Implement start and end times for pings
The start time can be stored and persisted as a datetime metric.
The end time is only ever needed in-memory for the moment the ping is
assembled and stored.
We also store the object creation time in the Glean object itself (which
is used as the first start time), because:
* that was the easy way
* glean-ac does something similar (storing it in the PingMaker object)
* we don't have global metrics in the core library itself on which we
could just set the date
=> Implement start_time/end_time for pings

glean-core/src/internal_metrics.rs, glean-core/src/lib.rs, glean-core/src/metrics/datetime.rs, glean-core/src/ping/mod.rs, glean-core/tests/datetime.rs
=> Correctly set first_run_date as a datetime metric

glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/TestUtil.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/private/PingTypeTest.kt
Since updating to WorkManager dependency 2.0.1, we are now able to properly run WorkManager in tests using TestDriver.
=> Update TestUtil.triggerWorkManager to remove workaround

docs/user/adding-glean-to-your-project.md
These are the correct and current dependency instructions for glean-ac, which are likely to remain the same even when glean-ac becomes a wrapper around glean-core.  So I'm just uncommenting this back in preparation for removing most of the docs in glean-ac and linking to the docs here.
=> 1557734: Reinstate dependency instructions

README.md, docs/README.md
I called the Glean library out more clearly as the *"Glean SDK"*, to make clear that this is the client-side of the end-to-end *"Glean project"*.
I also linked back to the overview article on fx-data-docs.
=> Name the Glean SDK more clearly vs. the Glean project

docs/user/debugging.md, docs/user/metrics/datetime.md, docs/user/metrics/event.md, docs/user/metrics/timespan.md, docs/user/metrics/timing_distribution.md, docs/user/metrics/uuid.md, docs/user/pings/events.md, docs/user/pings/index.md, docs/user/pings/metrics.md
The current docs show *"status: not implemented"* for a few features (metrics, pings, debug activity).
However, we now point from android-components to these docs as the main docs, so this is misleading.
We should prioritize providing correct and helpful docs for the a-c glean sdk, as this is actively getting used.
=> Fix showing "not implemented" status in docs

glean-core/android/src/main/java/mozilla/telemetry/glean/config/Configuration.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/net/HttpPingUploader.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/TestUtil.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/debug/GleanDebugActivityTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/net/HttpPingUploaderTest.kt
This removes the GCP ping redirection, in parallel with the glean-ac change [here](https://github.com/mozilla-mobile/android-components/pull/3343)
=> Remove GCP ping redirection

README.md, docs/README.md, docs/contributing.md, docs/dev/android/setup-android-build-environment.md, docs/dev/testing.md, docs/user/debugging.md
This should make the docs make sense whether the reader is coming for glean-ac or glean-core.
=> 1559133: Make landing page less confusing

.circleci/config.yml
According to online resources using the gradle daemon means we might run into memory issues already.
Not using it is a first step.
Next one would be to tell the JVM to start with less heap to begin with.
https://support.circleci.com/hc/en-us/articles/115014359648-Exit-code-137-Out-of-memory
https://stackoverflow.com/questions/38967991/why-are-my-gradle-builds-dying-with-exit-code-137
=> Don't use the gradle daemon in CI

glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/PingType.kt
When we switched to either a string name or a ping type object we
introduced a generic function, but didn't adjust the log message.
This results in the object's string representation to be used (which is
most likely just `PingType0x12345` or something along those lines).
The non-generic wrapper functions do know how to get to the name, so we
can use that knowledge and pass it in.
=> Use a closure to get the ping's name

glean-core/src/error.rs, glean-core/src/ping/mod.rs
glean AC uses `context.cacheDir`, but I didn't want to pass that through the FFI, so now we build our own temp directory to which we can write files.
=> Use created temporary directory

docs/user/pings/baseline.md
Thanks for @tdsmith for noticing.
=> Put baseline.duration into the right category

.circleci/config.yml
=> Make Gradle adhere to a strict 2GB heap limit

docs/user/pings/metrics.md
As discovered by @chutten...
This is a port of just the documentation part of
https://github.com/mozilla-mobile/android-components/pull/3204
This keeps the docs in line with the current behavior of glean-ac.
The code parts of that PR are not relevant since we don't yet have a metrics ping scheduler in glean-core.
=> Update docs for the metrics ping.

docs/user/adding-glean-to-your-project.md, glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt
This additionally clarifies the documentation about the lack of support for multiple application processes and what happens in case an initialization is attempted on non-main processes.
=> Restrict Glean to only init on the main process.

glean-core/ffi/src/boolean.rs, glean-core/ffi/src/counter.rs, glean-core/ffi/src/datetime.rs, glean-core/ffi/src/lib.rs, glean-core/ffi/src/macros.rs, glean-core/ffi/src/string.rs, glean-core/ffi/src/string_list.rs, glean-core/ffi/src/timespan.rs, glean-core/ffi/src/uuid.rs
This should be considered a discussion ground.
Notable things:
* It doesn't handle the `test_(get|has)_value` functions yet
* In part because some of those are a bit more complex
* It can't wrap all actual record functions
* It can do some, see e.g. the counter
* It might be possible to include some more
* The chosen syntax in the macro is arbitrary and can be changed
=> Use a macro to reduce boilerplate in FFI layer

glean-core/ffi/src/macros.rs
This allows skipping the automatic implementation of the constructor
function.
It then has to be implemented manually (which might be required if the
type has some extra work to do during construction).
cc @mdboom 	this might solve your issues in #161 
=> Make constructor function optional in macro.

glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt
=> Re-enable test

glean-core/android/src/main/java/mozilla/telemetry/glean/private/TimespanMetricType.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/private/TimespanMetricTypeTest.kt, glean-core/ffi/src/timespan.rs, glean-core/src/metrics/timespan.rs, glean-core/tests/timespan.rs
This adds tests to verify the behavior [we discussed in bug 1562859](https://bugzilla.mozilla.org/show_bug.cgi?id=1562859).
=> Don't overwrite existing value/running timer with raw API

.circleci/config.yml, docs/dev/testing.md
Here's an idea to reduce CI time for doc-only changes:
For doc-only changes we might not require the full CI run.
The Android tests are what's taking the longest, so let's make this
easily skippable.
Just add `[skip android]` somewhere in the commit message.
* Should we do this?
* If so, where to document?
* If so, skipping only Android or also rust tests? What about lints?
* Everything else is reasonably fast, which is why I didn't add a way to skip it yet
* Naming: `skip android`, `doc only`, ...
* not possible: `ci skip` - circleci uses that to skip the full build (but we require the build to deploy docs)
**Update**
* Docs added.
* Marker changed to `[doc only]`
=> Skip Android tests if commit contains marker

docs/SUMMARY.md, docs/dev/core/internal/clearing.md, docs/dev/core/internal/index.md, docs/dev/core/internal/payload.md, docs/dev/core/internal/reserved-ping-names.md, docs/user/metrics/event.md
This also sets up a space for more documentation about metrics in the ping payload.  We should fill this out, but I've created a [separate bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1566854) to do that as follow-on work.
=> 1557046: Document more about event payload

glean-core/src/metrics/event.rs, glean-core/src/metrics/experiment.rs, glean-core/src/metrics/string.rs, glean-core/src/metrics/string_list.rs, glean-core/src/util.rs
This works by starting one character beyond the truncation point and moves back until it finds a character boundary.  The string is then truncated to the byte immediately preceding that boundary.
An alternative would have been to iterate over characters from the beginning, but that would be O(n), whereas this is O(1) (since barring corrupted string data, it should only have to look at at most 3 bytes).
=> 1567914: String truncation shouldn't truncate in the middle of a codepoint

glean-core/android/src/main/java/mozilla/telemetry/glean/private/HistogramBase.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/TimingDistributionMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/rust/LibGleanFFI.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/private/TimingDistributionMetricTypeTest.kt, glean-core/ffi/src/lib.rs, glean-core/ffi/src/timing_distribution.rs, glean-core/src/error_recording.rs, glean-core/src/metrics/counter.rs, glean-core/src/metrics/datetime.rs, glean-core/src/metrics/event.rs, glean-core/src/metrics/labeled.rs, glean-core/src/metrics/string_list.rs, glean-core/src/metrics/timespan.rs, glean-core/src/metrics/timing_distribution.rs, glean-core/src/util.rs, glean-core/tests/timing_distribution.rs
This is porting over the changes from mozilla-mobile/android-components#3829 to glean-core.
=> Add a common histogram base class to `TimingDistributionMetricType`

docs/user/metric-parameters.md
This is the only bit Glean-general docs in glean_parser that hasn't already been copied over here.  (Everything else in the glean_parser docs is API docs that are specific to glean_parser).
=> [doc only] 1562681: Add missing "type" parameter to docs

glean-core/src/metrics/timing_distribution.rs, glean-core/tests/timing_distribution.rs
This additionally adds a test that reports no error and one
that attempts to accumulate negative samples and, as such,
triggers error reporting.
=> Don't report errors, when no errors occurred, in timing_distribution

glean-core/android/src/main/java/mozilla/telemetry/glean/Dispatchers.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/BooleanMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/CounterMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/DatetimeMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/EventMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/LabeledMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/StringListMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/StringMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/TimespanMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/TimingDistributionMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/UuidMetricType.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/DispatchersTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt
Keeping things in sync with glean-ac.  This was a little more problematic on the implementation side of things than glean-ac, mostly due to needing the Rust side of Glean initialized to be able to determine if upload is enabled and if a metric is disabled (in the `shouldRecord` methods).  I ended up just keeping parallel variables on the Kotlin side to eliminate/reduce the need to query across the FFI boundary.
=> 1568034 - Update Dispatchers to queue tasks before Glean is initialized

glean-core/src/database/mod.rs, glean-core/src/event_database/mod.rs, glean-core/src/lib.rs, glean-core/src/ping/mod.rs
This also tries to unify the wording of log messages where appropriate.
This is all I found right now.
I'm a bit torn about 2 occasions where I do `let Err(e) = ...` just to log and rethrow the error (at which point the actual error will still bubble up and get logged at the FFI boundary I think).
=> Log the same actions as glean AC

.gitignore, glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/config/Configuration.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/rust/LibGleanFFI.kt, glean-core/examples/sample.rs, glean-core/ffi/examples/glean.h, glean-core/ffi/examples/glean_app.c, glean-core/ffi/src/lib.rs, glean-core/src/error_recording.rs, glean-core/src/lib.rs, glean-core/src/ping/mod.rs, glean-core/src/storage/mod.rs, glean-core/tests/boolean.rs, glean-core/tests/common/mod.rs, glean-core/tests/counter.rs, glean-core/tests/datetime.rs, glean-core/tests/event.rs, glean-core/tests/labeled.rs, glean-core/tests/ping_maker.rs, glean-core/tests/string.rs, glean-core/tests/string_list.rs, glean-core/tests/timespan.rs, glean-core/tests/timing_distribution.rs, glean-core/tests/uuid.rs
This is a first draft/PoC of using a structure passed over FFI.
Notable:
* We need to ensure Kotlin and Rust use the same (C-compatible) structure
* Kotlin/JNA does the conversions, I'm not sure how heavy that is, then again we convert the configuration once.
* Passing null over is a bit tricky, but JNA has helpers (LongByReference)
* We still need to convert from the C-compatible types (`FfiStr`, ~~`*const i64`~~) to usable Rust types
* This currently does not use the defaults. The Glean constructor should take `Options` where it can provide a default (or we write the builder pattern, though that's a bit more code for a single use)
=> Use a config structure to pass data to Rust

docs/dev/core/new-metric-type.md, glean-core/android/src/main/java/mozilla/telemetry/glean/rust/LibGleanFFI.kt, glean-core/ffi/examples/glean.h, glean-core/ffi/src/boolean.rs, glean-core/ffi/src/counter.rs, glean-core/ffi/src/datetime.rs, glean-core/ffi/src/event.rs, glean-core/ffi/src/macros.rs, glean-core/ffi/src/string.rs, glean-core/ffi/src/string_list.rs, glean-core/ffi/src/timespan.rs, glean-core/ffi/src/timing_distribution.rs, glean-core/ffi/src/uuid.rs
This removes the `should_record` functions from the FFI since they are no longer used.
=> 1569603 - Remove `glean_*_should_record` functions from FFI

glean-core/android/src/main/java/mozilla/telemetry/glean/private/TimespanMetricType.kt, glean-core/src/metrics/timespan.rs, glean-core/tests/timespan.rs
This is related to mozilla-mobile/android-components#3970
=>  Report an error if Timespans are used twice before are cleared

docs/user/adding-glean-to-your-project.md
Based on feedback from support provided by @travis79.
This updates the "integrating in your project" docs to be accurate for `glean-ac`.  It also clarifies how you would find version numbers for `glean-ac`.  
We don't really have supported releases for `glean-core` yet, so it's probably only confusing to document things about that now and it's all pretty TBD how that all will work, so best to keep this only documenting the things that are working and available now.
=> Update integration docs to be more appropriate for glean-ac

glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/rust/LibGleanFFI.kt, glean-core/ffi/examples/glean.h, glean-core/ffi/src/lib.rs, glean-core/src/lib.rs
So for this I actually have 2 different variants: this in here or [introducing a new FFI function](https://github.com/mozilla/glean/compare/clear-stores-2).
I considered this because I felt introducing all that FFI shenangigans for it wasn't worth it and it's _just_ a test API.
I await your judgement on either solution.
=> Clear stores in tests by toggling upload

glean-core/android/src/main/java/mozilla/telemetry/glean/scheduler/PingUploadWorker.kt
Fixes an issue that could cause the `PingUploadWorker` to loop forever if one were enqueued when upload was disabled.
=>  Bug 1572509 -  Fix PingUploadWorker loop if upload disabled

glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/rust/LibGleanFFI.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/private/PingTypeTest.kt, glean-core/ffi/examples/glean.h, glean-core/ffi/src/lib.rs, glean-core/src/lib.rs
This should enable storing pings concurrently eventually.
This is in part to address [bug 1553813](https://bugzilla.mozilla.org/show_bug.cgi?id=1553813), though it does nothing in parallel yet.
We don't know if that's an actuall bottleneck and right now I think we would just run into lock contention on the database anyway (plus right now we send _at most_ 2 pings at once)
=> Move collecting and storing multiple pings at once into Rust core

glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/scheduler/MetricsPingScheduler.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/scheduler/PingUploadWorker.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/scheduler/MetricsPingSchedulerTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/scheduler/PingUploadWorkerTest.kt
This cancels any pending `PingUploadWorkers` or `MetricsPingWorkers` when upload is disabled.
=>  Bug 1548535 - Cancel any pending workers when ping upload disabled

docs/dev/core/internal/payload.md, docs/user/metrics/timing_distribution.md
This updates the docs to be in line with https://github.com/mozilla-mobile/android-components/pull/4028
(It does mean that it's out-of-line with what's currently in glean-core, but those changes should be forthcoming soon...)
=> [doc only] 1564989: Document functional timing distributions

docs/user/metrics/string_list.md, glean-core/src/metrics/string_list.rs, glean-core/tests/string_list.rs
This prevents `StringListMetricType` from accepting empty lists to the `set()` method.
=>  Bug 1556995 - Fix Glean storing/sending of empty StringListMetricType

.circleci/config.yml
The Debian container in use is shipping libtinfo.so.6, but the Clang deployed in the NDK requires v5.
We hack around that by symlinking the new to the old version, they seem to be mostly compatible.
=> HACK: Fix up missing libtinfo.so.5

.circleci/config.yml
They are currently mostly failing due to out of memory issues.
Disabling to not waste resources.
We will re-enable them once we figure out what's going on.
=> Disable beta builds

docs/user/experiments-api.md, glean-core/src/lib.rs, glean-core/src/metrics/experiment.rs
Adds limits to the `extras` HashMap in experiments.rs
=>  Bug 1566001 - Add limits for the experiment's extra HashMap

docs/user/experiments-api.md, glean-core/src/lib.rs, glean-core/src/metrics/experiment.rs, glean-core/src/storage/mod.rs
This adds error reporting to the string truncation and extra truncation when it occurs in the experiments API.
=>  Bug 1574468 - Add experiments limits violations error reporting

glean-core/android/build.gradle, glean-core/android/src/main/java/mozilla/telemetry/glean/Dispatchers.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/debug/GleanDebugActivity.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/scheduler/MetricsPingScheduler.kt, glean-core/android/src/test/java/android/util/Log.java
This required switching all of our logging over to use Android.util.Log and also required a little hack to get mocked objects that used the Log to work.
=> Bug 1576857 - Remove dependency on android-components support-base

glean-core/android/build.gradle, glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/DistributionData.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/StringListMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/utils/JsonUtils.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/utils/JsonUtilsTest.kt
Inlining wasn't ideal in every case, so I went ahead and copied over the extension files for the JSON stuff from android-components to the /utils directory and added the extension for `Context` that detects the main process to the `Glean.kt` file.
=> Bug 1576774 - Removed android-components support-ktx dependency

.circleci/config.yml
codecov upload occasionally fails due to network issues.
Most of the time this is solved by rerunning the task again.
Instead of that, let's just try 3 times total.
=> Retry codecov upload 2 times in case of failures

glean-core/ffi/src/lib.rs
On debug builds enable debug logging.
On release builds enable info logging.
=> On iOS enable logging with a level filter.

glean-core/android/sdk_generator.gradle, glean-core/android/src/main/java/mozilla/telemetry/glean/private/LabeledMetricType.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/private/LabeledMetricTypeTest.kt
This is needed in order to accumulate to `labeled_counter`(s) when required by Gecko categorical histograms.
I went for the easiest solution here: we pay the cost of storing the list of strings on the Kotlin side instead of having a new FFI function for that. Would that be ok, as a short term solution for feature parity? I'm happy to file a bug and take on this after.
This is a port of mozilla-mobile/android-components#4439
=> Enable looking up labels by their index in LabeledMetricType

glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/config/Configuration.kt
This is the glean-core companion to mozilla-mobile/android-components#4454 . In addition to
what's done in the other PR, this allows to change the HTTP endpoint in the constructor. That change was not backported to glean-core.
=> Make the Glean SDK general API to be callable from Java

glean-core/android/src/main/java/mozilla/telemetry/glean/scheduler/PingUploadWorker.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt, glean-core/ios/Glean/Net/HttpPingUploader.swift, glean-core/src/ping/mod.rs, glean-core/tests/common/mod.rs, glean-core/tests/ping.rs
This changes the location glean-core stores pending pings to. It's changing from `pings` to `pending_pings`, which is the same location being used by [glean-ac](https://github.com/mozilla-mobile/android-components/blob/914091cebc92046dbc71742ddc8aefa7d7880371/components/service/glean/src/main/java/mozilla/components/service/glean/storages/PingStorageEngine.kt#L50).
=> Allow easy migration of pending pings from glean-ac

glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/acmigration/GleanACDataMigrator.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/rust/LibGleanFFI.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/acmigration/GleanACDataMigratorTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/acmigration/GleanDataMigrationTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/debug/GleanDebugActivityTest.kt, glean-core/ffi/cbindgen.toml, glean-core/ffi/src/from_raw.rs, glean-core/ffi/src/lib.rs, glean-core/src/ac_migration/mod.rs, glean-core/src/database/mod.rs, glean-core/src/lib.rs, glean-core/src/lib_unit_tests.rs, glean-core/src/ping/mod.rs
This PR enables the cross-platform Glean SDK to migrate sequence numbers from glean-ac.
This additionally adds initial test coverage for the migration process.
=> Migrate sequence numbers

docs/user/adding-glean-to-your-project.md, glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/scheduler/MetricsPingScheduler.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/utils/ThreadUtils.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt
This is a port of https://github.com/mozilla-mobile/android-components/pull/4477
=> 1581556: Register lifecycle observers on the main thread

glean-core/android/src/main/java/mozilla/telemetry/glean/acmigration/GleanACDataMigrator.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/acmigration/engines/BooleansStorageEngine.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/BooleanMetricType.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/acmigration/GleanDataMigrationTest.kt
This adds the BooleansStorageEngine to the migration engines for the AC -> Glean-core migration.
=> 1585333 - Add BooleansStorageEngine to AC data migration

glean-core/android/src/test/java/mozilla/telemetry/glean/acmigration/GleanDataMigrationTest.kt
This merely adds test coverage for the migration code implemented by @travis79 that also magically migrates labeled things.
This works, under the hood, because we store things the same way across glean-ac and glean-core and use the same wrapping mechanism for labeled types.
=> Migrate labeled stuff

glean-core/android/src/main/java/mozilla/telemetry/glean/Dispatchers.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/private/EventMetricTypeTest.kt
This is basically a port of https://github.com/mozilla-mobile/android-components/pull/4595 to glean-core.
glean-core didn't actually have the same underlying bug, however, it was loading queued pings from disk on the main thread.  (Oh noes, I/O on the main thread!!!)  That has been fixed so it does this on an "early" (non-queued) task just as on glean-ac.
The other changes to glean-ac were not required, since everything is already internally synchronous on the Rust side when `sendPings` is called.
=> 1585021: Fix ordering of events at startup to prevent negative timestamps

glean-core/android/src/test/java/mozilla/telemetry/glean/acmigration/GleanDataMigrationTest.kt
This changes the migration test to ignore non 'baseline' pings before starting to validate the data.
=> Properly wait for the 'baseline' ping

.gitignore, glean-core/ios/Glean/Glean.swift, glean-core/ios/Glean/Net/HttpPingUploader.swift, glean-core/ios/Glean/Scheduler/PingUploadOperation.swift
This fixes the delayed uploading of pings.  Due to a combination of factors, including using the wrong URLSessionTask and not using the extended background operation properly, the pings would sometimes not be sent when going to background.
=> 1582447 - Fix delayed ping uploading

build.gradle, glean-core/android/build.gradle, glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/scheduler/MetricsPingScheduler.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/scheduler/PingUploadWorker.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/TestUtil.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/acmigration/GleanDataMigrationTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/debug/GleanDebugActivityTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/private/EventMetricTypeTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/private/PingTypeTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/scheduler/MetricsPingSchedulerTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/scheduler/PingUploadWorkerTest.kt
This was a bit less trivial than expected: the new version required a version upgrade of some other dependencies as well, so I ended up upgrading them all. We are now matching the [same version that Android Components is using](https://github.com/mozilla-mobile/android-components/blob/master/buildSrc/src/main/java/Dependencies.kt).
This allowed to simplify the code in a few places: see the 'BONUS' commits.
=> Upgrade `WorkManager` to version 2.2.0

.circleci/config.yml
If that unbreaks CI, it needs to land before the other failing PRs.
=> Use fixed version of grcov (and fix arguments)

.circleci/config.yml, publish.gradle
This will only include a Linux-compatible build for now.
Windows (the easier part) and macOS (the harder part) will follow eventually.
=> Include a `forUnitTests` package in the release

glean-core/android/src/main/java/mozilla/telemetry/glean/testing/GleanTestRule.kt
This change was applied to Glean AC a while ago[1], but we forgot to
port it over.
[1]: https://github.com/mozilla-mobile/android-components/commit/5ec752f2587432e369b905f6de68cebabfd63ada
=> Allow configuration of Glean through the GleanTestRule

.buildconfig.yml
This release includes #357 and it's needed to provide a green build at mozilla-mobile/android-components#4620
=> Release a new testing version (TESTING3)

glean-core/android/src/main/java/mozilla/telemetry/glean/private/DatetimeMetricType.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/private/DatetimeMetricTypeTest.kt
ZONE_OFFSET only provides the default offset from UTC without DST considerations.
DST_OFFSET needs to be added to get the full offset for the calendar instance.
There's a _very small_ hint in the deprecated `Date` class that one
needs to do this[1].
Neither the docs for ZONE_OFFSET[2] nor the ones for DST_OFFSET[3]
mention this explicitly.
I guess the existence of both fields is the only indicator there.
[1]: https://docs.oracle.com/javase/7/docs/api/java/util/Date.html#getTimezoneOffset()
[2]: https://docs.oracle.com/javase/7/docs/api/java/util/Calendar.html#ZONE_OFFSET
[3]: https://docs.oracle.com/javase/7/docs/api/java/util/Calendar.html#DST_OFFSET
=> Take DST into account when converting a calendar into its items

.circleci/config.yml
This ... is a bit hacky in that it needs to stop cargo/rust from
invoking the linker on Linux, which will fail. But if the "linker" just
doesn't do anything, the old file will remain and it will happily use it
in the packaging step.
There's a test release in my separate repository: https://github.com/badboy/glean-test-tc/releases/tag/v0.0.1-TESTING3
Here's a file listing of what's now in that `forUnitTest` jar:
<details>
```
.
├── META-INF
│   └── MANIFEST.MF
├── com
│   └── sun
│       └── jna
│           ├── aix-ppc
│           │   └── libjnidispatch.a
│           ├── aix-ppc64
│           │   └── libjnidispatch.a
│           ├── darwin
│           │   └── libjnidispatch.jnilib
│           ├── freebsd-x86
│           │   └── libjnidispatch.so
│           ├── freebsd-x86-64
│   …
```
=> Build macOS library on macOS, then copy it over for packaging

build.gradle, docs/dev/android/setup-android-build-environment.md, glean-core/android/build.gradle
Now there's no need to generate Android toolchains anymore.
=> Upgrade to Android NDK r20

samples/ios/app/glean-sample-app.xcodeproj/project.pbxproj
On a fresh clone, the glean-sample-app would not build until the `carthage bootstrap` command was run.  This adds the command to the build phases in order to simplify building from a fresh clone.
=> Add `carthage bootstrap` command to iOS glean-sample-app

glean-core/android/build.gradle, glean-core/android/proguard-rules-consumer.pro
@badboy found that our QA build of Fenix was crashing due to Glean classes being optimized (= removed) by ProGuard.
**How did I test this?**
For some reason, I can't produce working builds of Fenix (locally!) due to GeckoView. In order to test that this was working, I did the following:
- Published glean from this branch to local Maven.
- Imported the local glean in Android Components and published a new build of A-C to the local Maven.
- Imported the local A-C build in Fenix. I added the `-printusage pro-guard-fenix-usage.txt` in `app/proguard-rules.pro` for Fenix. This generated a `pro-guard-fenix-usage.txt` file with a list of "optimized" stuff. Without this rule, the file contains `mozilla.telemetry.*` classes. With this rule, they are missing.
=> Make sure ProGuard doesn't remove Glean classes from the app

glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt
We need to keep track of pings, so they get re-registered after a reset.
This state is kept across Glean resets, which should only ever happen in test mode.
Or by the instrumentation tests (`connectedAndroidTest`), which relaunches the application activity,
but not the whole process, meaning globals, such as the ping types, still exist from the old run.
I'm not super happy with keeping this state around, but given that the
queue is actually a set and it's unlikely to have hundreds and hundreds
of custom pings it should not have much of an impact.
=> Keep track of pings in all modes

publish.gradle
This adds the JNA dependencies to the `forUnitTest` variant.
Here's the generated `pom` file, which I had to rename for uploading needs :)
[glean-forUnitTests-0.0.1-TESTING7.txt](https://github.com/mozilla/glean/files/3734993/glean-forUnitTests-0.0.1-TESTING7.txt)
=> Add 'jnaTest' dependencies to the 'forUnitTest' JAR

glean-core/android/build.gradle
I noticed that we were using a quite old version in our tests. I updated the version to the latest release.
=> Update the Glean ping schema revision to a recent version

Makefile
Stumbled upon this last night: https://jakemccrary.com/blog/2018/12/27/a-more-helpful-makefile/
Went ahead and implemented it. This will list all documented make commands like this:
```
$ make
android-emulator               Start the Android emulator with a predefined image
build-apk                      Build an apk of the Glean sample app
build-kotlin                   Build all Kotlin code
build-rust                     Build all Rust code
build-swift                    Build all Swift code
cbindgen                       Regenerate the FFI header file
clippy                         Run cargo-clippy to lint Rust code
docs                           Build the Rust and Kotlin API documentation
kotlin-docs                    Build the Kotlin documentation
ktlint                         Run …
```
=> By default make `make` print helpful output

docs/user/debugging.md
Probably shouldn't land before we land glean-core in a-c.
BREAKING CHANGE:
When used through Android Components,
previously users had to use the `mozilla.components.service.glean.debug.GleanDebugActivity` name.
It's now required to use `mozilla.telemetry.glean.debug.GleanDebugActivity``
=> Use glean-core specific full path for debug activity in the docs

glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/testing/GleanTestLocalServer.kt
This is importing just the rule from mozilla-mobile/android-components#4786
=> Add the GleanTestLocalServer to glean-core

build.gradle, samples/android/app/README.md, samples/android/app/build.gradle, samples/android/app/metrics.yaml, samples/android/app/pings.yaml, samples/android/app/src/androidTest/java/org/mozilla/samples/gleancore/GleanTestRunner.kt, samples/android/app/src/androidTest/java/org/mozilla/samples/gleancore/MainActivityTest.kt, samples/android/app/src/androidTest/java/org/mozilla/samples/gleancore/pings/BaselinePingTest.kt, samples/android/app/src/main/java/org/mozilla/samples/glean/GleanApplication.kt, samples/android/app/src/main/java/org/mozilla/samples/glean/MainActivity.kt
Related to [Bug 1570252](https://bugzilla.mozilla.org/show_bug.cgi?id=1570252)
I basically just copy pasted the tests from the sample app in android components, so they should do the same thing.
Unfortunately (or fortunately depending on how you look at it) this tests are failing, because while adding them to the project we found two bugs in the actual glean app.
@badboy reported one of them ([Bug 1588717](https://bugzilla.mozilla.org/show_bug.cgi?id=1588717)) and is still loking into the other one.
The one bug that is already reported is also happening for the instrumented tests in android-components. Which means that they are not probably run on CI there, as well.
=> Add instrumented tests to sample app

.circleci/config.yml
This adds this nice thing to our CircleCI:
(and it also moves the html report to less subfolders, so getting to them is less clicking)
=> Store Gradle test results in CI

CHANGELOG.md, docs/user/metrics/timing_distribution.md, glean-core/android/src/main/java/mozilla/telemetry/glean/private/TimingDistributionMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/rust/LibGleanFFI.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/private/TimingDistributionMetricTypeTest.kt, glean-core/ffi/glean.h, glean-core/ffi/src/timing_distribution.rs, glean-core/ios/Glean/GleanFfi.h, glean-core/ios/Glean/Metrics/TimingDistributionMetric.swift, glean-core/src/metrics/timing_distribution.rs, glean-core/tests/timing_distribution.rs
`TimingDistributionMetricType.start()` doesn't really need a Glean object, since it doesn't matter whether upload is enabled or not to start the timer.  It only matters later when we stop and record the sample, so we can just to that there only.
=> 1588452: Don't crash TimingDistribution.start() prior to Glean.init

.buildconfig.yml, Cargo.lock, docs/dev/cut-a-new-release.md, glean-core/Cargo.toml, glean-core/ffi/Cargo.toml
For local development and easy testing in a-c and Fenix we should have a version number bigger than the released one.
The gradle/maven way is to `major+1` + `-SNAPSHOT`.
The Rust/semver way is to `major+1` + `-alpha.0` (less relevant, as we don't push to crates.io just yet).
I would totally expect that we go `19.1.0` next first, but that's for the release to decide.
=> Prepare for next release cycle

CHANGELOG.md, glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/rust/LibGleanFFI.kt, glean-core/ffi/glean.h, glean-core/ffi/src/lib.rs, glean-core/ios/Glean/Glean.swift, glean-core/ios/Glean/GleanFfi.h, glean-core/src/event_database/mod.rs, glean-core/src/lib.rs, glean-core/src/metrics/ping.rs, glean-core/tests/ping.rs, glean-core/tests/ping_maker.rs
This now matches the behavior of glean-ac (logging from the uploader)
=> 1589743: Don't log pings twice

glean-core/android/src/test/java/mozilla/telemetry/glean/private/AccumulationsBeforeGleanInitTest.kt
I missed this as part of #400.  It is now fully covered by the tests added
there.
Also \o/ last `@Ignore`d test!
=> CLEANUP: Remove test for preinit timing distribution recording

.circleci/config.yml
Release announcement from CircleCI: https://discuss.circleci.com/t/xcode-11-1-image-released/32668
It also looks like we might not need to install carthage manually.
This might fix problems with an expired certificate that is used to sign
the SDK package.
=> (CI) Upgrade Xcode image used.

.circleci/config.yml
This hopefully reduces memory usage and thus makes the build pass again.
This is fine without looking further into whether lld is a good fit for
us, because it's only used for the coverage step.
=> Use lld for linking

.circleci/config.yml, Makefile
I'm not 100% sure why but:
* with LLD the coverage breaks
* ~~it now works again with the default linker~~ it doesn't, using a bigger instance now
I also updated the make command and upgraded to the latest version of grcov.
This is still flaky and at least I don't spend time looking at code coverage, so if this keeps braking I propose to remove it for now.
=> Revert #418 - Use lld for linking

CHANGELOG.md, docs/SUMMARY.md, docs/user/focused-use-cases.md, docs/user/instrument-android-crashes-example.md
This adds a new example application to the samples directory, and a walkthrough readme to a new section titled "Focused Use Cases" in the docs
=> 1582479 - Document Glean crash capabilities as a use-case focus

glean-core/android/src/test/java/mozilla/telemetry/glean/GleanFromJavaTest.java
This adds the same test that we have in A-C (mozilla-mobile/android-components#4892).
=> Add test coverage for calling the Glean APIs from Java

glean-core/android/build.gradle, gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy, samples/android/app/build.gradle, settings.gradle
This works for me.
I can:
1) Sync the IDE to get autocompletion and the "build" button working
2) Build from the commandline
3) Publish to local maven, and the plugin is there
4) This plugin can be used to build Fenix
=> Fix Gradle plugin usage with AndroidStudio

glean-core/Cargo.toml, glean-core/LICENSE, glean-core/README.md, glean-core/ffi/Cargo.toml, glean-core/ffi/LICENSE, glean-core/ffi/README.md, glean-core/src/lib.rs
This adds a bit of metadata, makes the list of files to package explicit
and includes READMEs and license files per crate (because `cargo`
refuses to just pick the top-level README).
After merging what I need to do:
* Fetch master
* Reset the version numbers to 19.1.0
* Publish both crates
Later I'm also gonna provide configurations to use `cargo-release` and document that in the overall release process.
=> Prepare for crates.io releases

glean-core/ffi/Cargo.toml
The way it's currently build depends on being run from the workspace
anyway, so bundling it in the crate doesn't make sense.
Plus, if build, it might contain files we don't want to include (such as
the final binary)
=> Don't bundle FFI example in crate

glean-core/ios/Glean/Config/Configuration.swift, glean-core/ios/Glean/Scheduler/GleanLifecycleObserver.swift
Due to the way the sample app works with Carthage, I need to land this on master first:
* Allow defining the endpoint at initialization time
* fixing the baseline duration, which is not started when the app is opened the first time as it doesn't get a foreground notification.
=> Preparation for UI/Integration tests

.flake8
As discussed in #telemetry-client, 88 is not a great number.
=> Update flake8 maximum line length

glean-core/ffi/glean.h, glean-core/ffi/src/lib.rs, glean-core/ios/Glean/GleanFfi.h, glean-core/src/metrics/mod.rs
This fixes the formatting that is breaking the tree.
=> Fixup cargo fmt on the latest version of Rust

docs/dev/cut-a-new-release.md, gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy
This is required to make https://github.com/mozilla-mobile/fenix/pull/6476 work.
I tried using both of the following plugins to include the version in the build programatically:
https://plugins.gradle.org/plugin/com.github.gmazzo.buildconfig
https://github.com/mfuerstenau/gradle-buildconfig-plugin
(There is also a buildConfig feature as part of the Android gradle plugin, which doesn't work here because this is a Gradle plugin we are building, not an Android application).
Unfortunately, this doesn't work because the plugin needs to be used one way to build the plugin that we ship for third parties, and used as a script for use internally in this repo.  In the latter form, there is no chance for the buildConfig script to run, and worse, no way to import the configuration class that it …
=> Include version in Glean plugin

docs/user/metrics/boolean.md, docs/user/metrics/counter.md, docs/user/metrics/datetime.md, docs/user/metrics/string.md, docs/user/metrics/timespan.md, docs/user/metrics/timing_distribution.md, docs/user/metrics/uuid.md
This doesn't include metrics that are GV-only (since it's unlikely they'll
be needed from Java), and doesn't include event or string_list where the
conversion to Java is more complex and I'd need to fire up the compiler to
check my work.
=> 1588062: Add metrics usage documentation for Java.

bin/build-rust-docs.sh, docs/user/pings/custom.md
When `mdbook` reports errors, it doesn't actually return a UNIX error code.  So there were `include` directives inserted into the docs that were "broken" but still passed CI.
I filed this issue with mdbook: https://github.com/rust-lang/mdBook/issues/1094
In the meantime, we can use grep to detect errors and return an error code from CI.
=> Fix and disallow mdbook errors

glean-core/android/src/main/AndroidManifest.xml
This makes the `GleanDebugActivity` launch as a [`singleInstance` Activity](https://developer.android.com/guide/topics/manifest/activity-element.html#lmode).  This causes the `GleanDebugActivity` to correctly handle additional `Intents` if the application was launched with a `GleanDebugActivity` `Intent` using the `adb` command.
=> Bug 1595211 - Makes GleanDebugActivity launch as a `singleInstance` Activity.

.circleci/config.yml
Due to how we use the glean-gradle-plugin both as an external Maven package and internally as a script, it ends up getting published once in the correct way (with a version number) and again with an unspecified version (since it doesn't use the publishing metadata we've set up).  This results in two copies of the plugin being published to releases, for example [see the 20.2.0 release](https://github.com/mozilla/glean/releases/tag/v20.2.0).
This filters the unnecessary ones out when making a release.
=> Don't release glean-gradle-plugin with unspecified version

glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/ios/Glean/Glean.swift
As @hawkinsw pointed out, this is no longer true and potentially confusing...
=> Update docs about calling Glean.initialize first

CHANGELOG.md, glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/TimingDistributionMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/rust/LibGleanFFI.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/GleanFromJavaTest.java, glean-core/android/src/test/java/mozilla/telemetry/glean/private/TimingDistributionMetricTypeTest.kt
This also has the nice side effect of adding type safety to the `GleanTimerId` for Kotlin calls, making
it an opaque type for end users.
=> Allow to use the `GleanTimerId` from Java

samples/android/app/build.gradle
Our sample app is using the wrong field as the target version.
=> Fix the `targetSdkVersion` of the glean sample app

Cargo.lock, glean-core/Cargo.toml, glean-core/ffi/Cargo.toml
This will allow us to match the version of the dependencies vendored in mozilla-central.
=> Bump `once_cell` and `lazy_static` to newer versions

.circleci/config.yml
The integration tests take much longer, so run them separate in parallel
to the others.
=> Split iOS build into normal test and integration test

.buildconfig.yml, CHANGELOG.md, Cargo.lock, glean-core/Cargo.toml, glean-core/ffi/Cargo.toml, gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy
We need this so we can properly deploy the glean-gradle-plugin see [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1597239)
=> Make v21.0.0 release

glean-core/ios/Glean.xcodeproj/project.pbxproj, glean-core/ios/base.xcconfig
Turns out I didn't get this quite right the first time.  Having `Glean.h` set as the Objective-C bridging header was preventing it from being exported publicly.  It also turns out that we didn't need to mark that as the bridging header, so removing it allowed me to properly export the public header.  
This ultimately fixes a warning seen in the lockwise-iOS integration about implicitly importing "Glean.h" through module "Glean".
=> Bug 1596762 - Fix for public header export

glean-core/src/metrics/timespan.rs
This ensures that no error is recorded if a product disables upload and 'baseline.duration' is attempted
to be recorded when going to background. Without this change, it would record an error if upload was disabled at startup, when coming to foreground.
This check was present in [glean-ac](https://github.com/mozilla-mobile/android-components/blob/594be62732d9f4cacca3b2841cca299064709822/components/service/glean/src/main/java/mozilla/components/service/glean/private/TimespanMetricType.kt#L67-L69).
Is this a bug or did we remove it for some reason?
**Note**: we do have the same problem in the `TimingDistirbutionMetricType`, where we don't check if we're allowed to record at startup
=> Check if Timespans are allowed to record at stop

glean-core/python/glean/config.py, glean-core/python/glean/metrics/experiment.py
This just fixes the docstring formatting on dataclasses so they show up correctly in the generated docs.  (No content changes, just moving things around...)
=> Fix Python docstrings

glean-core/android/build.gradle, glean-core/android/src/main/java/mozilla/telemetry/glean/scheduler/GleanLifecycleObserver.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/scheduler/MetricsPingScheduler.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/scheduler/MetricsPingSchedulerTest.kt
The official docs say that using the `androidx.lifecycle` API [requires adding](https://developer.android.com/jetpack/androidx/releases/lifecycle#declaring_dependencies) an `annotationProcessor` (Java) or `kapt` processor (Kotlin) in order to correctly handle the `@OnLifecycleEvent` annotation.
Some random components in a-c that use lifecycles do this, fwiw, but glean, both here and in a-c, does not.
It's not clear from the docs what happens if you don't do that, however [this StackOverflow question](https://stackoverflow.com/questions/49602410/when-should-we-use-android-arch-lifecyclecompiler-or-android-arch-lifecycleco) in the last, non-upvoted answer (I know how that must sound) says:
```
Lifecycle runtime will do one of 2 things:
- Use reflection to look up the annotated methods,
- or …
```
=> WIP: Use DefaultLifecycleObserver interface, rather than lifecycle annotations

CHANGELOG.md, glean-core/android/build.gradle, glean-core/android/src/main/java/mozilla/telemetry/glean/scheduler/GleanLifecycleObserver.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/scheduler/MetricsPingScheduler.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/scheduler/MetricsPingSchedulerTest.kt
This doesn't require annotations or any Java8 magic, so hopefully will work.
=> Use the LifecycleEventObserver API

docs/dev/core/internal/directory-structure.md, docs/dev/python/setting-up-python-build-environment.md, docs/user/adding-glean-to-your-project.md, docs/user/adding-new-metrics.md, docs/user/debugging.md, docs/user/experiments-api.md, docs/user/metrics/labeled_counters.md, docs/user/metrics/string.md, docs/user/metrics/string_list.md, docs/user/pings/baseline.md, docs/user/pings/custom.md, docs/user/pings/events.md, docs/user/pings/metrics.md, docs/user/pings/testing-custom-pings.md, docs/user/testing-metrics.md
@hackebrot: Everything documented here should be working (including the PyPI package).  I'd appreciate your feedback on this PR as a user especially.
=> Document all the Python things

.gitignore, Makefile, docs/code_coverage.md
This just adds instructions for generating it.
Adding to CI will be a follow-on task.
=> Add support for Python code coverage

glean-core/python/requirements_dev.txt
m2r is a markdown-to-restructred text converter.
I copied this from glean_parser, which uses it for its doc generation, but it's
not needed here.
=> Python: Remove unnecessary m2r dependency.

CHANGELOG.md, glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt, glean-core/python/glean/glean.py, glean-core/python/tests/test_glean.py
This guarantees that call to the API that happen before the Glean SDK is initialized don't get lost
and are played back once the Glean SDK is finally initialized.
=> Dispatch experiments asynchronously

CHANGELOG.md
This was mistakenly added to the wrong category by github merging.
=> Move experiments changelog entry to unreleased

.circleci/config.yml
Looks like this might speed it up from previously 12 minutes total time to now 8 minutes.
=> Build dependencies in Debug mode for test

CHANGELOG.md, glean-core/src/metrics/string_list.rs, glean-core/tests/string_list.rs
Oops.  ¯\_(ツ)_/¯
This will affect analysis against previously collected data, since the old values will be truncated, but new values will not.  Thoughts about that?
=> 1595548: Fix truncation of string list items

.circleci/config.yml, bin/build-carthage.sh
Step 1 of getting full binary releases.
See "Carthage binary snapshot URL" in https://circleci.com/gh/mozilla/glean/24984
```
Add the following line to your Cartfile:
binary "https://circleci.com/api/v1.1/project/github/mozilla/glean/24984/artifacts/0/dist/mozilla.glean.json" ~> 0.0.1-snapshot # mozilla/glean@036dd574ff6bb25126f0c9220740afa75898d447
```
I can do the "do that at release time and add it to the GitHub release" in a followup
=> Build carthage binary snapshots for each build

.circleci/config.yml
This replaces the upstream git repository and branch of Glean as used in the
sample app by the commit it's currently testing on.
That way integration tests actually run against the code that is changed
without awkward hacks or landing these things separately.
=> Use local checkout through Carthage

glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/config/Configuration.kt, glean-core/examples/sample.rs, glean-core/ffi/glean.h, glean-core/ffi/src/lib.rs, glean-core/ios/Glean/GleanFfi.h, glean-core/ios/Glean/Utils/Utils.swift, glean-core/python/glean/_ffi.py, glean-core/src/database/mod.rs, glean-core/src/lib.rs, glean-core/src/lib_unit_tests.rs, glean-core/tests/boolean.rs, glean-core/tests/common/mod.rs, glean-core/tests/counter.rs, glean-core/tests/custom_distribution.rs, glean-core/tests/datetime.rs, glean-core/tests/labeled.rs, glean-core/tests/memory_distribution.rs, glean-core/tests/ping_maker.rs, glean-core/tests/quantity.rs, glean-core/tests/string.rs, glean-core/tests/string_list.rs, glean-core/tests/timespan.rs, glean-core/tests/timing_distribution.rs, glean-core/tests/uuid.rs
Fixes [Bug 1596440](https://bugzilla.mozilla.org/show_bug.cgi?id=1596440)
Opening this as WIP so I can get validation that I am on the right way and also to discuss the name of the `defer_collection` configuration option -- keeping in mind that we might change this config option to a interval right after this gets PR accepted (see [comment #9](https://bugzilla.mozilla.org/show_bug.cgi?id=1596440#c9) and [comment #10](https://bugzilla.mozilla.org/show_bug.cgi?id=1596440#c10)).
I think the biggest part of this is done, that was adding the option and changing the way metrics are stored when the config option is set. I thought I had to change a little bit the `PingMaker`, but after looking at the code seems like my changes to `Database` were all that was necessary.
In my test I wasn't sure …
=> Add option to defer ping lifetime metric persistence

glean-core/android/src/main/java/mozilla/telemetry/glean/Dispatchers.kt, glean-core/ios/Glean/Dispatchers.swift
Fixes [Bug 1600005](https://bugzilla.mozilla.org/show_bug.cgi?id=1600005)
Messages to assert if Glean is in testing mode for both Kotlin
and Swift were referencing the old enableTestingMode API which
is deprecated. Both have been updated to mirror the new API.
=> Update message on "test mode" assertions

glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/ios/Glean/Glean.swift
I put this explicitely in two commits.
I'm not sure if there was a reason we went for the "call getUploadEnabled() again". IMO that seems unnecessary.
=> Toggle only

.circleci/config.yml, Cargo.lock, Cargo.toml, Makefile, glean-core/ffi/src/lib.rs, glean-core/ffi/src/ping_type.rs, glean-core/preview/Cargo.toml, glean-core/preview/examples/prototype.rs, glean-core/preview/src/lib.rs, glean-core/preview/src/metrics/mod.rs, glean-core/preview/src/metrics/ping.rs
For now this only supports a minimal interface on top of Glean
```rust
let cfg = Configuration {
data_path,
application_id: "org.mozilla.glean_core.example".into(),
upload_enabled: true,
max_events: None,
};
glean::initialize(cfg)?;
glean::register_ping_type(&PrototypePing);
if glean::send_ping_by_name("prototype") {
log::info!("Successfully collected a prototype ping");
} else {
log::info!("Prototype ping failed");
}
```
=> Add a crate for the nice control API

glean-core/android/src/main/java/mozilla/telemetry/glean/scheduler/DeletionPingUploadWorker.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/scheduler/PingUploadWorker.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/scheduler/PingUploadWorkerTest.kt, samples/android/app/src/androidTest/java/org/mozilla/samples/gleancore/pings/DeletionRequestPingTest.kt
I moved shared functionality into free-standing functions
We could keep it in the companion object, but it felt a bit weird to re-use functions in another class across its companion object.
Also the one in the derived class just shadows the one from the superclass, so we need to use explicit calls.
=> Refactor Android uploaders to share more code

.buildconfig.yml, CHANGELOG.md, Cargo.lock, glean-core/Cargo.toml, glean-core/ffi/Cargo.toml, glean-core/preview/Cargo.toml, gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy
In order for me to publish the API preview crate, I actually need minimal changes on the FFI layer.
Which means I need to release that.
Which means we need to do a full release.
(And this is where I think having all with the same version number falls down a bit, maybe we need to revisit that in the new year)
=> Release version 22.0.0

samples/ios/app/glean-sample-appUITests/ViewControllerTest.swift
For some reason we see frequent timeout errors in these tests when run
on CI.
It's unclear if that is due to a too-short timeout or actual issues.
Let's increase it for now and see if it is still hit.
=> Extend timeout in UI tests

.gitignore, docs/user/debugging.md, glean-core/ios/Glean.xcodeproj/project.pbxproj, glean-core/ios/Glean/Config/Configuration.swift, glean-core/ios/Glean/Debug/GleanDebugTools.swift, glean-core/ios/Glean/Glean.swift, glean-core/ios/GleanTests/Debug/GleanDebugUtilityTests.swift, glean-core/ios/GleanTests/GleanTests.swift, samples/ios/app/glean-sample-app/AppDelegate.swift, samples/ios/app/glean-sample-app/Info.plist
This adds CLI handling for the `sendPing`, `tagPings`, and `logPings` commands by using the UserDefaults API to receive and parse launch arguments.
=> 1586736 - Add Glean-iOS debug functionality

CHANGELOG.md, gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy
This ensures that, whenever a change is made to a registry file, docs and specific metrics APIs are regenerated accordingly.
This was tested by adding metrics to both the sample app and glean-core's registry files, then just building using the "Android Studio" hammer button. Doc changes were picked up and the APIs were correctly regenerated.
Without this change, sometimes, the code wouldn't be regenerated.
=> Add glean registry files as `inputs` to the generation tasks

glean-core/tests/boolean.rs, glean-core/tests/common/mod.rs, glean-core/tests/counter.rs, glean-core/tests/custom_distribution.rs, glean-core/tests/datetime.rs, glean-core/tests/event.rs, glean-core/tests/labeled.rs, glean-core/tests/memory_distribution.rs, glean-core/tests/metrics.rs, glean-core/tests/ping.rs, glean-core/tests/ping_maker.rs, glean-core/tests/quantity.rs, glean-core/tests/storage.rs, glean-core/tests/string.rs, glean-core/tests/string_list.rs, glean-core/tests/timespan.rs, glean-core/tests/timing_distribution.rs, glean-core/tests/uuid.rs
Fixes [Bug 1601209](https://bugzilla.mozilla.org/show_bug.cgi?id=1601209)
Turns out there already was a function to "share configuration in glean-core tests" (the `tests::common::new_glean`). It just didn't work for cases when we needed to create multiple instances of glean in the same test with the same data directory.
That was fixed by adding the option to pass the tempdir as an argument to the function, which makes it possible to call it multiple times with the same data directory.
=> Enhance `new_glean` test function to attend to all test cases

glean-core/tests/ping_maker.rs
This test was added after the new_glean function landed, but that change
was not included in the branch, so it only broke once merged into
master.
=> Pass missing None argument in test function

glean-core/android/src/main/java/mozilla/telemetry/glean/config/Configuration.kt, glean-core/python/glean/_ffi.py, glean-core/src/database/mod.rs, glean-core/src/lib.rs
Fixes [Bug 1596442](https://bugzilla.mozilla.org/show_bug.cgi?id=1596442)
Continuation of #530 
I wasn't sure if I should add a method for this directly on the Glean object.
=> Add method to persist ping lifetime data on demand

docs/user/collected-metrics/metrics.md, docs/user/error-reporting.md, docs/user/metrics/timing_distribution.md, glean-core/android/src/main/java/mozilla/telemetry/glean/testing/ErrorType.kt, glean-core/ios/Glean/Testing/ErrorType.swift, glean-core/metrics.yaml, glean-core/python/glean/testing/error_type.py, glean-core/src/error_recording.rs, glean-core/src/metrics/timing_distribution.rs, glean-core/tests/timing_distribution.rs
This is used by the timing distribution metric type whenever a passed sample is bigger than 10 minutes.
I wonder if this could be used in other metrics as well. I can't seem to find an immediate use for this outside of timing distributions.
=> Introduce the `InvalidOverflow` error

.circleci/config.yml
Turns out it takes the destination as a file path, not a directory path,
if the source is just a file
=> Specify the exact file name for storing the log artifact

glean-core/src/database/mod.rs, glean-core/src/lib_unit_tests.rs, glean-core/tests/event.rs, glean-core/tests/memory_distribution.rs, glean-core/tests/storage.rs, glean-core/tests/timing_distribution.rs
With the release of Rust 1.40.0 a few new clippy lints were introduced.
For us they only apply to test code.
The following code automatically applied all of then:
cargo +nightly fix -Z unstable-options --clippy
(This autofix feature requires Rust nightly, which is 2 versions ahead
of stable as always, but the code is still valid for our minimum supported Rust version)
=> Let clippy fix our code

glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/scheduler/MetricsPingScheduler.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/scheduler/MetricsPingSchedulerTest.kt
This attempts to fix the problem of components/products recording metrics while or before Glean is still initializing and then flowing into overdue startup `metrics` pings that get generated.
Note that the current behaviour, without this fix, is flaky:
- We're always collecting & sending a `metrics` ping at startup if *any* component or product records a metric and a ping is overdue (not already sent on the current calendar day and we're after 4AM);
- Metrics collected during early startup will get into the generated overdue `metrics` ping, violating the principle of "measurement windows", letting data from a future measurement window fall into the ping related to a previous measurement window.
=> Metrics recorded during init must not get into overdue `metrics` pings

glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/rust/LibGleanFFI.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/scheduler/MetricsPingSchedulerTest.kt, glean-core/ffi/glean.h, glean-core/ffi/src/lib.rs, glean-core/ios/Glean/GleanFfi.h, glean-core/src/database/mod.rs, glean-core/src/lib.rs, glean-core/src/lib_unit_tests.rs
This PR changes the behaviour of `lifetime: application` metrics ([docs](https://mozilla.github.io/glean/book/user/metric-parameters.html#optional-metric-parameters)).
*Current behaviour*
The `lifetime: application` are only stored in volatile memory so, when a product using Glean is closed, they are lost. Product should regenerate them at startup. If glean generates any startup ping, they will be missing from the generated pings.
*New behaviour*
The `lifetime: application` are stored in the metrics database and _not_ cleared on shutdown. They are instead cleared at startup, after all the Glean SDK-owned pings are generated. Any previously stored `lifetime: application` metric will make it into these pings.
Any product-set startup metric will be recorded _after_ Glean inits, so no data is …
=> Change the behaviour of `lifetime: application`

docs/user/general-api.md
The [General API docs][docs] contain a table with a broken Markdown link to Custom pings. 📝 
[docs]: https://mozilla.github.io/glean/book/user/general-api.html
=> Fix broken link in General API docs

.buildconfig.yml, CHANGELOG.md, Cargo.lock, bin/prepare-release.sh, glean-core/Cargo.toml, glean-core/ffi/Cargo.toml, glean-core/metrics.yaml, glean-core/preview/Cargo.toml, gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy
A couple of complications beyond the usual here:
I merged the `v22.1.0` tag into master -- I don't think this was done earlier, and it fixes the changelog which previously didn't have an entry for that version.
Updated the `prepare_release.sh` script to update the version in `glean-preview`.
=> Release 23.0.0

CHANGELOG.md, glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/scheduler/MetricsPingScheduler.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/scheduler/MetricsPingSchedulerTest.kt
This uses a simple `Timer`, rather than the WorkManager for the MetricsPingScheduler.
As planned, we can also move the actual scheduling algorithm to Rust, but that is saved for future work.  This is just the simplest change possible to get us off of the WorkManager here.
=> 1602024: Improve the metrics ping scheduler

CHANGELOG.md, gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy
This is a bugfix for 5ca9f66908449f374866d70ac4384b70c3ed1514 so that the plugin won't break if either the metrics.yaml or pings.yaml file is missing when adding it as a task dependency.  This was discovered in https://github.com/mozilla-mobile/android-components/pull/5490 when trying to integrate the Gradle plugin into a-c.
=> Fix Gradle plugin to handle missing metadata files

glean-core/android/build.gradle, glean-core/android/src/test/java/mozilla/telemetry/glean/private/PingTypeTest.kt
This PR updates to pipeline schema that the unit tests run against to the latest master.
It adds a test for `snake_case` and `kebab-case` ping names (both of which must work indefinitely), and we can see the `kebab-case` one failing because of https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/470 not being merged.
=> Update payload schema tested against

.circleci/config.yml, CHANGELOG.md, glean-core/python/setup.py
This needs to support all platforms that Firefox can be built *on* (not necessarily built *for*).
From the [Firefox macOS build prerequisites](https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Build_Instructions/Mac_OS_X_Prerequisites), that appears to be MacOSX 10.9 or later.
From the [Rust documentation](https://forge.rust-lang.org/release/platform-support.html), it appears that the rustc `x86_64-apple-darwin` target produces code that is compatible on 10.7 or later, so I think it has us covered.
This the produces a wheel that runs on macOS 10.7 or later, with Python 3.5 or later, for x86_64.
It's not clear whether we need `x86` wheels, but that can be a follow-on PR if necessary.  That would require adding another Rust target and build etc...
=> Build macOS wheels for Python bindings

.circleci/config.yml, Makefile, glean-core/preview/src/lib.rs, glean-core/preview/src/test.rs
We clear all metrics when upload is disabled (glean-core takes care of that),
so we need to reset the initial values only known to the platform when
re-enabling upload.
Now the client info and the channel are passed into the initialize
function of glean_preview.
Before this commit we didn't keep that data around, which means we also
couldn't restore it.
By introducing a small wrapper around the Glean instance we are able to
carry around that data and reuse it when necessary.
This now also adds tests for glean-preview with one big caveat:
Because glean_preview is a global-singleton, we need to run the tests
single-threaded to avoid different tests stomping over each other.
There's no explicit check in the tests, developers will notice problems
by tests just hard crashing on them.
Pass …
=> 1605411 - Reset core client metrics when re-enabling upload

.circleci/config.yml, glean-core/ios/Glean/Glean.swift, samples/ios/app/glean-sample-appUITests/BaselinePingTest.swift
It's basically: Queue ping submission behind other metric operations.
I _think_ this might actually be the cause for both problems (the "crash" and the timeout).
Please see individual commit messages for detailed explanations.
=> 1607730 - Try fixing iOS integration test interkittens

Cargo.lock, glean-core/Cargo.toml, glean-core/src/error.rs
We can just implement the error trait ourselves and add some quick
Display formatting. It's not that much more code for us either.
=> Remove failure as a direct dependency

.circleci/config.yml
This reorganizes the circleci config so that it's hopefully a little easier to manage.
Everything is organized into the following sections: Project, Rust, Android, iOS, Python, Docs
A few things have been refactored into commands that are reused.
Other than that, though, this is just a reorg/refactor and shouldn't change the behavior of the tasks in any way.
=> Reorganize and refactor the CircleCI config

docs/user/metric-parameters.md
In our docs we say that linking to the "data review" is ok, but
we usually encourage to link to the data review response.
Clarifying the messaging a bit to make it explicit.
=> Mention linking to the 'data review response'

docs/user/metrics/string.md
We currently report 50, but the real limit is [100](https://github.com/mozilla/glean/blob/4a64270ba246b8eb88f0b8382d0cd2423443fa1c/glean-core/src/metrics/string.rs#L12).
=> Report the correct limit for String metric types [doc only]

bin/spellcheck.sh
Not everyone's* bash has the globstar feature included, making it throw
an error.
`find` on the other hand is nearly ubiquitous.
* Mac's bash.
=> Replace newer bash-feature globstar with a simple find

.github/CODEOWNERS, .github/auto_assign.yml
Everyone from the current Glean team will now be added as an reviewer
automatically, but only one per PR.
People can still re-assign of course.
Using https://github.com/kentaro-m/auto-assign/
=> Switch to an auto-assign bot

.circleci/config.yml
We already publish them to PyPI.  This just adds them to GitHub so GitHub releases can be a canonical source for all build artifacts.
=> Publish Python wheels to GitHub

CHANGELOG.md, glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/scheduler/DeletionPingUploadWorker.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/scheduler/PingUploadWorker.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/testing/GleanTestLocalServer.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/utils/WorkManagerUtils.kt, samples/android/app/src/androidTest/java/org/mozilla/samples/gleancore/pings/BaselinePingTest.kt, samples/android/app/src/androidTest/java/org/mozilla/samples/gleancore/pings/DeletionRequestPingTest.kt, samples/android/app/src/androidTest/java/org/mozilla/samples/gleancore/pings/SharedTestUtils.kt
This PR changes the upload work units so that, when the `GleanTestLocalServer` rule is used in integration tests, no need for external hacks is required to force the `WorkManager` to run the jobs.
The underlying problem is that, when running in test mode, the `WorkManager` does not automatically run its jobs and there's no way to tell "just behave as in production". Moreover, we're forced to set the `WorkManager` in test mode, otherwise tests crash at startup.
**How to test**
The related PR in Android Components (mozilla-mobile/android-components#5549) was used to test this, by performing a [local substitution](https://mozilla.github.io/glean/book/dev/howtos/development-with-android-components.html) of the Glean SDK with this changes in A-C.
=> Automatically flush upload WorkManager jobs when using the `GleanTestLocalServer` rule

.circleci/config.yml
This will re-use the binary build of Glean in the integration tests.
Old timing:
* build+test: 9min
* integraion test: 10min
New timing:
* build+test: unchanged
* integration test: 4-5min
Caution: This does not necessarily reduce the _total_ runtime of CI, as previously build+test and integration tests could run in parallel.
They now need to run sequentially.
https://bugzilla.mozilla.org/show_bug.cgi?id=1594334
=> Re-use already-built Glean in integration tests

.circleci/config.yml
Should fix these failures when deploying a release:
https://circleci.com/gh/mozilla/glean/38685
```
#!/bin/bash -eo pipefail
./ghr -replace ${CIRCLE_TAG} dist
Failed to find assets from dist: failed to get file stat: stat /home/circleci/project/dist: no such file or directory
Exited with code exit status 11
```
https://circleci.com/gh/mozilla/glean/38683
```
#!/bin/bash -eo pipefail
GHR=ghr_v0.13.0_linux_amd64
GHR_SHA256=c428627270ae26e206cb526cb8c7bdfba475dd278f6691ddaf863355adadfa13
curl -sfSL --retry 5 --retry-delay 10 -O "https://github.com/tcnksm/ghr/releases/download/v0.13.0/${GHR}.tar.gz"
echo "${GHR_SHA256} *${GHR}.tar.gz" | shasum -a 256 -c -
tar -xf "${GHR}.tar.gz"
cp ./${GHR}/ghr ghr
/bin/bash: line 3: shasum: command not found
```
=> Fix Python publishing to github

glean-core/android/src/main/java/mozilla/telemetry/glean/Dispatchers.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/DispatchersTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/private/AccumulationsBeforeGleanInitTest.kt
This does not block the main thread when flushing enqueued tasks at initialization. This works and retains the current implemented behaviour, at least in Kotlin, since [this](https://github.com/mozilla/glean/blob/fa6aaac11d8d8eb1b883a085fdcc508dba275a6a/glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt#L257) already dispatches `setUploadEnabled` in the APIs threadpool.
=> Don't block on dispatching tasks enqueued before init

CHANGELOG.md, docs/user/pings/index.md, glean-core/android/build.gradle, glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/ios/Glean/Glean.swift, glean-core/metrics.yaml, glean-core/python/glean/glean.py, glean-core/python/tests/conftest.py, glean-core/python/tests/metrics/test_labeled.py, glean-core/python/tests/test_glean.py
Fixes [Bug 1601489](https://bugzilla.mozilla.org/show_bug.cgi?id=1601489)
This is how this will look in the metrics ping: 
```json
{
"client_info": {
"android_sdk_version": "28",
"app_build": "0",
"app_display_version": "glean.version.name",
"architecture": "armeabi-v7a",
"client_id": "41dabd38-1b93-473b-8bc1-0e4284a65c53",
"device_manufacturer": "unknown",
"device_model": "robolectric",
"first_run_date": "2020-01-09+01:00",
"os": "Android",
"os_version": "9",
"telemetry_sdk_build": "23.0.1"
},
"metrics": {
"string": {
"glean.baseline.locale": "en-US"
}
},
"ping_info": {
"end_time": "2020-01-09T17:24+01:00",
"ping_type": "metrics",
"seq": 0,
"start_time": "2020-01-09T17:24+01:00"
}
}
```
=> Add locale metric to metrics ping

CHANGELOG.md, docs/user/metrics/timing_distribution.md, glean-core/android/src/test/java/mozilla/telemetry/glean/private/TimingDistributionMetricTypeTest.kt, glean-core/ios/GleanTests/Metrics/TimingDistributionMetricTests.swift, glean-core/src/metrics/timing_distribution.rs, glean-core/tests/timing_distribution.rs
This will be reported when stop_and_accumulate() is called without a prior call to start()
=> Report `invalid_state` when stopping non started TimingDistribution

.circleci/config.yml, build-scripts/xc-universal-binary.sh, glean-core/ios/Glean.xcodeproj/project.pbxproj
Turns out: most of the time during the iOS builds is spent on building Glean twice (for 2 iOS targets). It accounted for about 80% of the runtime for the build.
We can cache that. It improves subsequent builds on a fresh cache significantly.
The downside: the cache is big (300-400mb) which takes time to restore (about a minute on CircleCI).
Still, in total we save a bit.
This also means it is slower on dependency changes (or version updates of Glean itself), because the cache is invalidated.
Additionally for some reason our Xcode project was set to choose "Use Release for command-line builds". I changed that to "Debug", but haven't really seen it make a difference. I might be misunderstanding that setting or we already do force Debug whenever we don't force Release, I don't know. That …
=> Cache cargo builds on CI for iOS

glean-core/ios/Glean.xcodeproj/project.pbxproj, glean-core/ios/Glean/Glean.swift, glean-core/ios/Glean/Scheduler/MetricsPingScheduler.swift, glean-core/ios/Glean/Utils/Utils.swift, glean-core/ios/GleanTests/Scheduler/MetricsPingSchedulerTests.swift
This adds the MetricsPingScheduler to the iOS bindings.
=> Bug 1586738 - Add Glean-iOS MetricsPingScheduler

glean-core/src/util.rs
For reasons chrono's API can be more cumbersome than I would like, but
converting between the system's local time and the same
system-independent fixed offset is doable in fewer lines.
Solution from
https://github.com/chronotope/chrono/issues/104#issuecomment-255655945
=> Use simpler conversion between local and fixed offset

Cargo.lock, Cargo.toml, Makefile, glean-core/benchmark/Cargo.toml, glean-core/benchmark/LICENSE, glean-core/benchmark/README.md, glean-core/benchmark/benches/bench_basic.rs, glean-core/benchmark/src/lib.rs, glean-core/src/database/mod.rs
A "store" is a handle to the database.
Glean has 3 different ones and can keep them open throughout its lifetime.
Not frequently re-opening database handles also might be a performance
improvement.
Extracted from #664 because it's unrelated. Not directly related to a filed bug.
=> Keep the stores open all the time

glean-core/android/src/test/java/mozilla/telemetry/glean/shadows/ShadowLog.java, glean-core/android/src/test/resources/robolectric.properties
This filters CursorWindowStats, SQLiteCursor and SQLiteConnectionPool to only print errors.
Note: prior art is F-Droid merit, see [this commit](https://gitlab.com/fdroid/fdroidclient/commit/acbf5637)
=> Provide a Robolectric ShadowLog for filtering stray log lines

CHANGELOG.md, glean-core/src/metrics/experiment.rs, glean-core/src/metrics/mod.rs, glean-core/src/storage/mod.rs
I couldn't find a magic serde incantation to have a different behavior on JSON vs. bincode, so I came up with this.  But maybe there's something I missed...
=> 1612940: Don't include null extras in experiments

.circleci/config.yml, docs/book.toml, docs/glean.css, docs/tabs.css
After a comment from @mdboom I opted for quickly writing a plugin to add a "open on github" link to each page.
It looks like this (see the bottom):
=> Add "open on github" link to docs

.circleci/config.yml, Makefile, glean-core/preview/src/test.rs
Because glean_preview is a global-singleton, we need to run the tests one-by-one to avoid different tests stomping over each other.
This is only an issue because we're resetting Glean, this cannot happen in normal use of glean-preview.
We use a global lock to force synchronization of all tests, even if run multi-threaded.
This allows us to run without `--test-threads 1`.
---
Other options I tried:
* `#[ignore]` -- we use that else where and we still need to pass `--test-threads 1` to make it work reliably
* Gating on a cargo feature -- we still need to pass `--test-threads 1` to make it work reliably
=> Synchronize glean-preview tests on a global lock

.circleci/config.yml, docs/code_coverage.md
Coverage reports by now are merely a noise, take extra CI time and we
ran into some problems before generating them.
This also allows us to drop the one usage of a "xlarge" instance on CircleCI.
=> Drop automated code coverage reports

glean-core/android/src/test/java/mozilla/telemetry/glean/DispatchersTest.kt
Across multiple async tasks it's better to use an atomic integer.
We also need to wait for all of them to complete.
=> Avoid race-condition and thus tackle intermittent

.circleci/config.yml, Makefile
The default test target runs both testDebugUnitTest and testReleaseUnitTest, effectively running everything twice.
This seems like a waste of resources (and time) and just running it once seems fine.
Now we could decide to run testReleaseUnitTest on CI, but testDebugUnitTest for developer machines.
=> Run Kotlin tests only once in debug configuration

.circleci/config.yml, Makefile
Require manual approval for iOS CI jobs on PRs
This changes CI in the following ways:
* iOS jobs (build, test and integration test) become manual-approval-required on PRs
* That means the expensive job is not even run unless someone does so
manually
* iOS jobs are still run by default on master merges
Due to how CircleCI works the iOS tests become their own workflow on PRs,
but must be in the ci workflow on master merges (so that the doc deploy can depend on it).
=> Require manual approval for iOS jobs

glean-core/src/lib_unit_tests.rs, glean-core/src/ping/mod.rs, glean-core/src/upload/mod.rs, glean-core/src/upload/request.rs, glean-core/src/upload/util.rs
Part of the resolution for [Bug 1605077](https://bugzilla.mozilla.org/show_bug.cgi?id=1605077)
What the changes here try to accomplish:
- Setup initial structure for the upload module.
- Create one of the main functions this module will have. Specifically the one that returns a new `Request` for one of the pending pings.
I thought best to send this incomplete and have different PRs for:
- The function to process a ping upload response.
- Adding interface for the new functionality to the Glean object.
I will also create a different bug for adding logic to deal with the deletion request ping. I am aware this code doesn't handle that at all.
For more details on what this new module will try to accomplish, please refer to:
- [Implementation proposal for moving the ping uploading logic to …
=> Create upload module with "get ping request" functionality

glean-core/android/src/test/java/mozilla/telemetry/glean/TestUtil.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/scheduler/MetricsPingSchedulerTest.kt
also fixes that the MPS tests hang when run in isolation.
=> 1609442 - Test that a startup ping contains the old version after an upgrade 

CHANGELOG.md, docs/user/pings/baseline.md, glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/rust/LibGleanFFI.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/scheduler/GleanLifecycleObserver.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt, glean-core/ffi/glean.h, glean-core/ffi/src/lib.rs, glean-core/ios/Glean/GleanFfi.h, glean-core/pings.yaml, glean-core/src/lib.rs, glean-core/src/lib_unit_tests.rs, glean-core/src/metrics/experiment.rs, glean-core/src/ping/mod.rs
This attempts to address the problem of 'force-close' interfering with the `baseline` ping. It implements the following logic:
**In addition to the current behaviour:**
- when the Glean SDK is initialized, it checks for a dirty flag:
- if the flag is set, it generates a baseline ping with reason `dirty_startup` (a new standard field being added to all pings, see #649 );
- if the flag is not set, then set it to true;
- when going to background, clear the dirty flag after computing the foreground duration and submitting the baseline ping.
This will guarantee that whenever the product using the Glean SDK is force-closed or crashes before it has the chance to send a baseline ping with a specific reason, signaling that there was a dirty flag set.
_Important_: there will be no foreground …
=> Send a `baseline` at startup if the previous session ended abruptly

CHANGELOG.md, docs/user/pings/baseline.md, docs/user/pings/deletion_request.md, docs/user/pings/events.md, glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/scheduler/MetricsPingSchedulerTest.kt, glean-core/ios/GleanTests/Debug/GleanDebugUtilityTests.swift, glean-core/ios/GleanTests/Metrics/PingTests.swift, glean-core/ios/GleanTests/Net/DeletionRequestPingTests.swift, glean-core/src/ping/mod.rs, glean-core/src/upload/util.rs, glean-core/tests/ping_maker.rs, samples/android/app/src/androidTest/java/org/mozilla/samples/gleancore/pings/BaselinePingTest.kt, samples/android/app/src/androidTest/java/org/mozilla/samples/gleancore/pings/DeletionRequestPingTest.kt, samples/ios/app/glean-sample-appUITests/BaselinePingTest.swift, samples/ios/app/glean-sample-appUITests/DeletionRequestPingTest.swift, samples/ios/app/glean-sample-appUITests/ViewControllerTest.swift
Needs https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/485 to land first.
=> 1609149 - Remove `ping_type` from pings.

docs/user/metrics/index.md
This is the final PR that adds documentation to the Glean Book for requesting new metric types.
=> Document the process for requesting new metric types [doc only]

CHANGELOG.md, glean-core/ios/Glean/Glean.swift
This is the iOS equivalent to [Bug 1604862](https://bugzilla.mozilla.org/show_bug.cgi?id=1604862)
=> Bug 1614785 - Add clearing of app lifetime metrics after sending metrics ping

.circleci/config.yml
The Docker image used for Linux wheels has an ancient version of Perl that ships `sha256sum` but not the generic `shasum`.
=> 1609169: Fix deploying Python wheels to Github

docs/user/pings/index.md, glean-core/metrics.yaml
"Device model" can mean different things on Android; clarify that this is `Build.MODEL` and not e.g. `Build.DEVICE`.
=> Disambiguate device model

CHANGELOG.md, glean-core/android/src/main/java/mozilla/telemetry/glean/Dispatchers.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/utils/WorkManagerUtils.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/DispatchersTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/GleanFromJavaTest.java, glean-core/android/src/test/java/mozilla/telemetry/glean/TestUtil.kt
I tested this both using Fenix and the Glean SDK sample app: this seem to work as expected. Accumulated data is correctly accounted for and any pre-init dispatched piece of information is sent.
This PR additionally fixes some weird bugs we had in our testing code that made our tests hang forever under certain circumstances. Se the indivudual commit messages.
**TODO**
=> Make Glean init in Kotlin fully async

glean-core/src/upload/mod.rs, glean-core/src/upload/request.rs
Resolves [Bug 1614281](https://bugzilla.mozilla.org/show_bug.cgi?id=1614281)
While trying to use `get_next_ping` from the upload module, the requester will now receive three possible return values:
* `Processing` - which means the pings directory is currently being processed and the requester should come back later;
* `Empty` - which means the pings queue is empty and requester can stop asking for more pings;
* `Next(PingRequest)` - if no processing is going on and there are pings in the queue, requester will get the oldest ping in it.
This also includes minor fixes to tests in the upload module.
=> Have `get_next_ping` signal when ping directory is being processed

CHANGELOG.md, glean-core/python/glean/_dispatcher.py, glean-core/python/tests/test_glean.py
This is a Python port of https://github.com/mozilla/glean/pull/657
=> 1609735: Python: Add instrumentation when overflowing preinit queue

glean-core/android/src/main/java/mozilla/telemetry/glean/Dispatchers.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/DispatchersTest.kt
I had a weird feeling while dealing with the intermittent from #672 . And I was (sadly) right: whenever something throws an exception in our dispatcher queue, everything goes kaput.
Luckily, our APIs are not really expected to throw exceptions ([except at startup](https://github.com/mozilla/glean/blob/f9d320db8763524fbdd5c03d2ec3be61667e5d68/glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt#L464) and in the test APIs).
Still, this is something we need to do a bit better. I'll work on our resiliency as part of this.
=> Test that exceptions in dispatched actions are correctly handled

.circleci/config.yml
The image doesn't have `sudo` and thus this fails.
We already switched away from shasum in #704
=> Don't try to install perl on the PyPi image anymore

docs/user/general-api.md
There is a paragraph here referring to "the following steps" that no longer is right before those steps it's referring to.  Just moving it down the page so it makes more sense.
=> [doc only] Move 'following steps' right before steps

glean-core/src/lib.rs, glean-core/src/ping/mod.rs, glean-core/src/upload/directory.rs, glean-core/src/upload/mod.rs
Resolves [Bug 1614280](https://bugzilla.mozilla.org/show_bug.cgi?id=1614280)
After a good discussion in the bug I decided to take a rather simplistic approach to implementing this.
This is my understanding:
1. I don't need to worry about stale ping files when a user has disabled upload, that is taken care of elsewhere (https://github.com/mozilla/glean/blob/master/glean-core/src/lib.rs#L332).
2. Even if a client has upload enabled, if there is a deletion-request ping file we should send that.
My solution was to have the DirectoryManager always check the deletion_request directory, regardless of upload enabled or not.
=> Support deletion request pings in upload module

.dictionary, bin/spellcheck.sh, samples/ios/app/README.md, tools/analysis/ping-patterns/README.md
This expands the spellchecker to run on all of the markdown files checked into git (except DEPENDENCIES.md).
This fixes a minor bug with the spellcheck script so it will always spellcheck the CHANGELOG.
The issue is that when the docs are built, `./CHANGELOG.md` is copied to `docs/appendix/changelog.md`.  The spellcheck script only looked at `.md` in the `docs` directory, so the changelog would be spellchecked only if the developer had previously built the docs.  Notably, it meant the `CHANGELOG.md` was not spellchecked on CI.  This should at least keep things consistent, and not force users to spellcheck things in the CHANGELOG that were previously missed by CI.
=> Spellcheck all the things

docs/SUMMARY.md, docs/user/debugging/index.md, docs/user/debugging/python.md, glean-core/python/glean/config.py, glean-core/python/glean/glean.py, glean-core/python/glean/util.py, glean-core/python/tests/test_glean.py
The debugging features in Python are a lot "simpler" than the other platforms because we're just providing a programmatic API at this point.  But things like sending to the Glean Debug View do work, so we should document that.
=> Python: Make public, document and test the debugging features

glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/TestUtil.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/scheduler/DeletionPingUploadWorkerTest.kt, glean-core/src/lib.rs, glean-core/tests/ping.rs
The old code already did what we wanted, because when `upload_enabled` is false the ping submission will exit early.
This just makes it more explicit, easier to read and understand without that context and we avoid a useless log line.
=> Ensure we only generate a deletion-request ping when toggling from on to off

glean-core/src/lib.rs, glean-core/src/upload/directory.rs, glean-core/src/upload/mod.rs, glean-core/src/upload/request.rs
Resolves [Bug 1614284](https://bugzilla.mozilla.org/show_bug.cgi?id=1614284).
I figured glean-ffi already does the job of locking the Glean object until completion of most functions, because it usually uses [`with_glean`](https://github.com/mozilla/glean/blob/master/glean-core/ffi/src/lib.rs#L45-L57) and [`with_glean_mut`](https://github.com/mozilla/glean/blob/master/glean-core/ffi/src/lib.rs#L66-L78), which locks Glean.
Nonetheless, I decided to lock the queue until done clearing all the stores, because what if we are not interfacing with glean through the FFI?
@badboy Is there a good way to still keep this behind a feature flag?
=> Add interface for the upload module to Glean object

.circleci/config.yml, glean-core/Cargo.toml, glean-core/src/lib.rs
After talking to @badboy we decided that the best solution to keep the upload changes off master, now that we are going to add them to the ffi and bindings, was to make a separate branch instead of feature flagging.
This PR removes the feature flags, but it also doesn't point to master but to the new branch m16/ping-uploading. I will keep that up to date with master as much as possible and all my upcoming PRs will point to it, until we are confident enough to merge to master without the feature flag.
What do you think, @Dexterp37 ?
=> Remove upload feature flag

.circleci/config.yml, Cargo.lock, README.md, glean-core/preview/Cargo.toml, glean-core/preview/tests/glean.1.schema.json, glean-core/preview/tests/schema.rs
Ping schema is taken from https://raw.githubusercontent.com/mozilla-services/mozilla-pipeline-schemas/f2a7ce4/schemas/glean/glean/glean.1.schema.json
and vendored.
It was changed to include an "$originUrl" as a way to track which one we imported.
---
Through #717 we noticed we only validate pings against the schema in Kotlin and Python test suites.
This is for several reasons:
* Validation is done by `glean_parser`, a Python project. A Python environment is only around for Kotlin and Python test suites
* Pings generated by _only_ `glean_core` are not trivially valid, due to `client_info` data misssing. We can set it, but it's not done by default.
But we only require _jsonschema validation_, and that's independent of other work from `glean_parser`, so one thing we can do is use a Rust …
=> Validate a simple generated custom ping against the ping schema

.circleci/config.yml, bin/update-schema.sh, glean-core/android/build.gradle, glean-core/preview/tests/glean.1.schema.json, glean-core/python/tests/conftest.py
Previously we ran schema checks in Python (`test_glean.py`) and Kotlin (several).
These relied on fetching the schema from the mozilla-pipeline-schemas repository.
For reproducability it uses a fixed git hash across both tests.
Now we also bundle a schema into the repository and run a single test
against it from glean-preview.
This is a small imrprovement, but it still means we can miss updating it
(or miss updating all places in the repository to the same version).
The previous commit already introduced a script to automate that.
This CI task now runs an explicit check, failing if the upstream version
changed.
This does mean that unrelated PRs can now fail due to schema changes,
that may not affect them.
In a future world we could have a nightly task that runs this check and
opens a PR …
=> Add script to update schema and run checks on CI

.circleci/config.yml, Cargo.lock, DEPENDENCIES.md, about.toml, deny.toml, glean-core/Cargo.toml, glean-core/android/dependency-licenses.xml
An accumulation of multiple changes, none of which are super critical.
I marked them all as `[doc only]` because either they are or it's Rust tests only and I ran those locally (the dep upgrade)
=> Updated dependency summary and reducing dep tree

docs/user/debugging/python.md
My application used `logging.basicConfig(level=logging.INFO)` to configure logging and I realized that pings weren't logged even though I set the according configuration option `log_pings` to `True` (see [documentation](https://mozilla.github.io/glean/book/user/debugging/python.html#logging-pings)). 📝  
This PR updates the Python SDK documentation to point out that the `glean` logger uses level `DEBUG` and consumers need to configure logging accordingly, if they want pings to be logged.
=> Update Python SDK documentation for logging pings 

.dictionary, CHANGELOG.md, gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy
Fixes https://github.com/mozilla-mobile/fenix/issues/8039
=> 1615256: Don't clean the miniconda installation on `gradlew clean`

Cargo.lock, DEPENDENCIES.md, glean-core/Cargo.toml, glean-core/android/dependency-licenses.xml
Nothing but running `cargo update` (and `bin/dependency-summary.sh`).
We rely on Cargo.lock for reproducible builds as we ship precompiled
libaries for Android and iOS.
We should still be compatible with the versions specified in the
respective Cargo.toml files, which is important for integration into
m-c, where we don't necessarily want to upgrade all transitive
dependencies all the time.
=> Update locked dependencies

glean-core/android/build.gradle
This was broken by #747. This PR properly scapes the paths on Windows.
=> Properly escape Glean schema path on Windows

.dictionary, docs/SUMMARY.md, docs/dev/core/internal/implementations.md
As discused in the [Naming proposal](https://docs.google.com/document/d/1M8xc_LmOxqnalyM6FJyIYtp1KnumSsQe99-XcWYYSJw/edit#) I'm bringing the table over into our offical SDK docs..
I also call them "implementations" side-stepping all the platform/architecture/project discussion (aaaand that's a new bikeshedding...)
Rendered:
(I'm considering making our main content _slightly _wider to better accomodate tables.)
=> Add a table of all different implementations and projects of the Glean SDK

docs/user/metric-lifetime-timeline.svg
@chutten pointed out a small bug in this diagram after it was merged.
In the second example, the metric wasn't being cleared at the end of Ping 1.
Before:
After:
=> Fix metric lifetime timeline diagram

docs/user/metrics/labeled_booleans.md, docs/user/metrics/labeled_counters.md, docs/user/metrics/labeled_strings.md, glean-core/ios/Glean/Metrics/LabeledMetric.swift, glean-core/ios/GleanTests/Metrics/LabeledMetricTests.swift
Bug 1621698
I ran all these locally and they were green:
* `make swiftlint`
* `make swiftfmt`
* `make test-swift`
Guess we can skip the iOS tests here before merge.
=> iOS: Add missing `testGetNumRecordedErrors` methods for labeled metrics

.circleci/config.yml, .dictionary, Cargo.lock, docs/user/collected-metrics/metrics.md, glean-core/Cargo.toml, glean-core/metrics.yaml, glean-core/python/glean/_util.py, glean-core/python/glean/net/ping_upload_worker.py, glean-core/python/setup.py, glean-core/python/tests/test_glean.py, glean-core/src/histogram/exponential.rs, glean-core/src/histogram/functional.rs, glean-core/src/util.rs
This addresses the following bugs to make 32-bit Windows builds pass the
unit tests.
1622909: Release 32-bit wheels for Windows
1623335: Functional bucketing fixes
1623587: Unable to detect locale on Windows
Also relevant (but a follow-on) is:
1623307: Add Windows tests to CI
=> Python: Windows x86 support

glean-core/android/src/main/java/mozilla/telemetry/glean/private/TimespanMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/TimingDistributionMetricType.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/private/TimespanMetricTypeTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/private/TimingDistributionMetricTypeTest.kt, glean-core/ios/Glean/Metrics/TimespanMetric.swift, glean-core/ios/Glean/Metrics/TimingDistributionMetric.swift, glean-core/ios/GleanTests/Metrics/TimespanMetricTests.swift, glean-core/ios/GleanTests/Metrics/TimingDistributionMetricTests.swift
This adds convenience methods to simplify measuring a function or block of code to both Android and iOS.
=> Bug 1598993 - Add convenience `measure` methods to TimingDistribution and Timespan metrics

docs/appendix/twig.md
This adds Anthony's TWiG post and my TWiG post.  The post will be published today on the Moz data blog, so let's wait until then to merge, just to verify it lands before the docs are updated by this PR.
=> [doc only] Update TWiG posts

docs/user/metric-parameters.md, glean-core/src/lib_unit_tests.rs
This additionally adds test coverage as requested by @badboy
=> Document potential data loss when changing metric types

docs/dev/core/new-metric-type/kotlin.md, glean-core/android/src/main/java/mozilla/telemetry/glean/private/BooleanMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/CounterMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/CustomDistributionMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/DatetimeMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/MemoryDistributionMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/PingType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/QuantityMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/StringListMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/StringMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/TimespanMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/TimingDistributionMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/UuidMetricType.kt
They cause us more trouble than they are worth.
This is safe.
The only thing we did do in finalizers is cleaning up the allocated
object on the native Rust side.
Without these we now potentially leak memory.
_But_ metric types were already only used for metrics, and those are
statics, so they live for the entire application runtime.
Once the application is done and exits the Glean library will also be
unloaded and thus all its data be deallocated.
The only place where we create metrics at runtime is in tests.
So we're now leaking those in tests, but that should be fine.
As a side note: Java 9 deprecates finalizers in the language, Android
itself doesn't support Java 9 (yet) and has its own implementation of it
anyway, but that's nonetheless a good hint that finalizers might not be
the …
=> Remove all finalizers from metric type implementations in Kotlin

CHANGELOG.md, docs/user/adding-glean-to-your-project.md, glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt, glean-core/python/glean/_dispatcher.py, glean-core/python/glean/testing/__init__.py, glean-core/python/tests/test_dispatcher.py, glean-core/python/tests/test_glean.py
This runs most of Glean's work (and its blocking I/O) on a separate worker thread.
This removes the need for users to do this themselves for performance reasons.  It doesn't really address @wlach's issue of wanting to fire off pings completely independently as a library, which still requires more discussion (see https://bugzilla.mozilla.org/show_bug.cgi?id=1625166).
=> 1604191: Python: run Glean work on a worker thread

Cargo.lock, glean-core/Cargo.toml, glean-core/src/util.rs
Otherwise this will fail with a error on MSVC:
fatal error LNK1181: cannot open input file 'm.lib'
We also don't need libc. `size_t` is properly defined, so we can
replicate that.
Additionally, applying the `controlfp` changes on MSVC seem to break the
tests anyway.
=> Only link against libm for the Windows GNU target

docs/user/debugging/android.md, docs/user/debugging/ios.md
This clarifies the documentation around logging pings with the Glean debug utilities by stating that pings will not be logged until submitted, along with giving information on how to trigger ping submission on normal ping schedules.
=> [doc only] Bug 1623506 - Clarify documentation that pings will not be logged until submitted

docs/user/pings/index.md, glean-core/metrics.yaml, glean.1.schema.json
Needs upstream schema to be deployed.
I also intend to update the schema in this repository once that is done.
=> Bug 1625207 - device manufacturer & model are now optional

glean-core/ffi/src/lib.rs, glean-core/preview/src/lib.rs, glean-core/src/error.rs, glean-core/src/lib.rs
This has two things:
* Getting the global object now gives an option and thus the FFI layer can return an error instead of panicking.
* Better docs on why the other code is ok, with the addition of logging an error instead of panicking.
Again: it is unlikely to ever hit any of these cases for our current wrappers, as they only initialize once.
=> Bug 1626258 - Better handling of global object in a threadsafe manner.

.dictionary, CHANGELOG.md, glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/TestUtil.kt, glean-core/ios/Glean/Glean.swift, glean-core/ios/Glean/Scheduler/MetricsPingScheduler.swift, glean-core/ios/GleanTests/GleanTests.swift, glean-core/ios/GleanTests/Scheduler/MetricsPingSchedulerTests.swift, glean-core/python/tests/test_glean.py, glean-core/src/lib.rs
I found a much simpler way forward here that really only adds some slightly different logic in `Glean::new` and a bit of a refactor.  I'm much happier with this than the earlier two approaches.
TODO:
=> 1624695: Act on changes in upload enable state outside of application

docs/user/collected-metrics/metrics.md, glean-core/android/src/main/java/mozilla/telemetry/glean/utils/LocaleUtils.kt, glean-core/ios/Glean/Utils/Utils.swift, glean-core/metrics.yaml
this also updates the metrics.yaml in one place, as right now we're still sending that metric.
I looked at the Kotlin code and it seems it "can, but never should be" an empty string, instead of our now "und" string.
Want me to also catch that?
See https://github.com/mozilla/glean/blob/undefined-locale-swift/glean-core/android/src/main/java/mozilla/telemetry/glean/utils/LocaleUtils.kt#L39
=> Return the undefined locale for Swift if it can't be otherwise determined

glean-core/android/src/main/java/mozilla/telemetry/glean/private/TimespanMetricType.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/private/TimingDistributionMetricType.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/private/TimespanMetricTypeTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/private/TimingDistributionMetricTypeTest.kt, glean-core/ios/Glean/Metrics/TimespanMetric.swift, glean-core/ios/Glean/Metrics/TimingDistributionMetric.swift, glean-core/ios/GleanTests/Metrics/TimespanMetricTests.swift, glean-core/ios/GleanTests/Metrics/TimingDistributionMetricTests.swift
=> Bug 1627841 - Cancel on exceptions in wrapped measurement function

.buildconfig.yml, .dictionary, CHANGELOG.md, Cargo.lock, glean-core/Cargo.toml, glean-core/ffi/Cargo.toml, glean-core/preview/Cargo.toml, gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy
=> Release v27.0.0

CHANGELOG.md, glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt, glean-core/ios/Glean/Glean.swift, glean-core/ios/GleanTests/GleanTests.swift
=> Bug 1628057: Include app lifetime metrics in dirty_startup baseline pings

glean-core/ios/Glean/Glean.swift, glean-core/ios/Glean/Net/HttpPingUploader.swift, glean-core/ios/Glean/Utils/Utils.swift, glean-core/ios/GleanTests/Net/DeletionRequestPingTests.swift
This updates the Glean-iOS bindings to use the Application Support directory rather than the Documents directory.  It also renames the `getDocumentsDirectory` utility function to be more appropriately named.
=> Bug 1628323 - Change Glean iOS to use Application Support directory

CHANGELOG.md, glean-core/python/glean/_process_dispatcher.py, glean-core/python/glean/glean.py, glean-core/python/glean/net/ping_upload_worker.py, glean-core/python/glean/testing/__init__.py, glean-core/python/tests/metrics/test_labeled.py, glean-core/python/tests/test_glean.py, glean-core/python/tests/test_network.py
`Glean._reset` is called:
1) as part of resetting every unit test, both within Glean and for our users
writing Glean-aware unit tests,
2) atexit
Glean._reset deletes the Glean data directory if it's a temporary directory
(but not under normal circumstances where a permanent location is used).
There is a race condition between the ping uploader and Glean._reset if
the data directory is deleted while pings are still being uploaded. This
solves that by always firing off a single ping uploader process at a time,
and running both ping uploaders and the temporary directory deletion on that
same one-at-a-time process.
It does not use a Process pool to keep a single process around, because
that would add a lot of complexity to handle a daemon process, vs. this
"fire and forget" process.
This also …
=> Bug 1628301, Bug 1628297: Fix race condition deleting tempdir

.dictionary, CHANGELOG.md, glean-core/python/glean/net/http_client.py, glean-core/python/tests/test_network.py
These exceptions occur when the network is down, the URL doesn't resolve,
and a bunch of other things. If any of these fail, we should just log and return
False so the ping uploader can move on to other pings or try again next time.
This is preferable to displaying a long (but ultimately harmless) traceback.
=> Bug 1628310: Don't raise HTTPException or socket.gaierror

docs/dev/python/setting-up-python-build-environment.md
The bug proposes integrating the logging level control between Python and Rust,
but I think this has minimal benefit for the amount of complexity.
This just documents that there are two sources of log messages, how to control
them and where to get more info if you need to do something more sophisticated.
=> [doc only] Bug 1600946: Document how to control logging

glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/TestUtil.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/pings/DeletionPingTest.kt, glean-core/src/upload/mod.rs
As it turns out removing those tests indeed made us _miss_ some of the details of the deletion-request ping, but not for long.
I brought back the tests, rewrote them to work against the new mechanism and extended them slightly, just for good measure.
I also added some additional trace logging. It's only visible if `RUST_LOG=trace` is set, plus some cleanup.
=> Bug 1628747 - Bring back deletion request pings

CHANGELOG.md, glean-core/python/glean/_ffi.py, glean-core/python/glean/_process_dispatcher.py, glean-core/python/glean/config.py, glean-core/python/glean/glean.py, glean-core/python/glean/net/ping_upload_worker.py, glean-core/python/glean/subprocess/__init__.py, glean-core/python/glean/subprocess/_process_dispatcher_helper.py, glean-core/python/glean/testing/__init__.py, glean-core/python/tests/test_glean.py, glean-core/python/tests/test_network.py
This avoids a number of features that are tricky on Windows, especially on MSYS, such as
duplicating file handles to a spawned subprocess.
=> Bug 1628885: Use subprocess rather than multiprocessing for ping uploading

glean-core/src/database/mod.rs, glean-core/src/error_recording.rs, glean-core/src/storage/mod.rs
This renames usage of `metric_name` to `metric_id` to be more clear about what is being used.
=> Bug 1626542 - Rename `metric_name` to `metric_id` for clarification

docs/user/pings/deletion_request.md
Augments the deletion request ping documentation to indicate how to send secondary ids in the deletion request ping.
=> [doc only] Bug 1632237 - Document how to send secondary ids in deletion request pings

glean-core/src/event_database/mod.rs, glean-core/src/upload/directory.rs, glean-core/src/upload/mod.rs, glean-core/tests/common/mod.rs, glean-core/tests/ping_maker.rs, taskcluster/ci/rust/kind.yml, taskcluster/glean_taskgraph/transforms/__init__.py, taskcluster/glean_taskgraph/transforms/script_to_run_task.py, taskcluster/scripts/rust/rustup-setup.sh
cc @MihaiTabara 
Just extending TaskCluster by 2 tasks:
* Rust tests
* Rust clippy (linting)
(meanwhile also fixes some clippy warnings)
Did this to play around with TaskCluster a bit more and understand how transforms work and how new tasks are added.
Contains `[ci skip]`, so CircleCI tasks won't run.
=> Add a new task to run Rust tests

CHANGELOG.md, glean-core/python/glean/_dispatcher.py, glean-core/python/glean/_process_dispatcher.py, glean-core/python/glean/glean.py, glean-core/python/glean/net/http_client.py, glean-core/python/glean/testing/__init__.py, glean-core/python/tests/test_dispatcher.py
Fixes a race condition in the `atexit` handlers.
Glean currently has two atexit handlers: (a) to make sure the thread worked completes all of its tasks, and (b) that (among other things) deletes the data directory if it's a tmpdir. atexit handlers are run sequentially on the main thread, but the ordering is based on the order in which they are registered, which is somewhat non-deterministic in Glean.
If (b) runs before (a), the data directory is deleted, and then any operations that might be waiting the thread queue will fail with "Database not found".
The fix is to combine the atexit handlers into one, and join on the thread queue before deleting the tempdir.
This raised another issue in my mind that using a tempdir by default is probably not a good choice, and we are seeing this bug in …
=> Bug 1634310: Python: Fix race condition in atexit

.dictionary, CHANGELOG.md, Makefile, glean-core/python/ffi_build.py, glean-core/python/glean/_ffi.py, glean-core/python/requirements_dev.txt, glean-core/python/setup.py
This uses the instructions in the [CFFI docs](https://cffi.readthedocs.io/en/latest/cdef.html) to parse the glean.h header at build time, rather than run time.
This improves the time of `import glean` from 301ms to 0.3ms.  Seems like a big win, particularly for commandline apps that may run multiple times as part of a build, etc.
=> Python: Parse glean.h header at build time

.circleci/config.yml, .dictionary, CHANGELOG.md
the spellcheck task broke on master, so I figured it'd be easier to fix that first before cutting a release.
Let's run it and see what happens.
=> Changelog updates

docs/user/adding-glean-to-your-project.md
My preference would be to simply do this as part of the template, but that does not seem to be
possible (bug flags seem not to be remembered as part of the bookmarkable template)
/cc @mreid-moz
=> Suggest needinfo'ing mreid when filing the bug to add a project to the pipeline

Makefile, glean-core/python/glean/_process_dispatcher.py, glean-core/python/glean/_subprocess/_process_dispatcher_helper.py
When ping uploading was moved to a separate process, that meant we
weren't collecting coverage from anything happening in the subprocess.
This fixes that by telling the subprocess when coverage is being run (using
an environment variable), enabling it in the subprocess, and then combining
the results before generating the HTML.
=> MAINT: Python collect coverage across processes

glean-core/android/src/test/java/mozilla/telemetry/glean/pings/CustomPingTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/pings/DeletionPingTest.kt, glean-core/src/upload/mod.rs
Unfortunately we can't really test concurrent submissions, because that's essentially a race condition afterall:
1. If ping is submitted while old worker is not finished yet it will pick it up. The Rust test shows that. The upload mechanism keeps an in-memory list during runtime.
2. If ping is submitted and the old worker is already finished, the new worker will start.
3. If ping is submitted and the old worker is about to end, but the new worker still sees it, the ping won't get uploaded and the new worker will not do any work.
At worst we're acting slightly better than the old mechanism.
Case 3 is for such a small window, it's not worth tackling (and again: no data is loss, latest at the next submission or startup the pending ping gets submitted).
=> Bug 1634353 - Test upload behavior for pings in quick succession 

.circleci/config.yml
This caused an error on the release task, which is probably a bug in the
curl version in use.
But we don't actually need it.
From curl's manpage:
> When curl is about to retry a transfer, it will first wait one second
> and then for all forthcoming retries it will double the waiting time until it reaches 10 minutes
> which then will be the delay between the rest of the retries.
> By using --retry-delay you disable this exponential backoff algorithm.
=> Don't overwrite retry delay

.circleci/config.yml, bin/update-schema.sh
As discovered in #877.
We can avoid using the API and thus running into rate limits by just always fetching from the main branch
=> Always fetch the "latest" schema from the master branch

glean-core/python/setup.py
Currently, Glean fails to install on Windows, outside of MinGW. This enables that support again.
=> Enable Glean Python support outside of MinGW

glean-core/src/error.rs
=> Remove the double spacing in the Utf8Error message

docs/dev/core/internal/upload.md, glean-core/android/src/main/java/mozilla/telemetry/glean/net/Upload.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/rust/LibGleanFFI.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/scheduler/PingUploadWorker.kt, glean-core/ffi/examples/glean_app.c, glean-core/ffi/glean.h, glean-core/ffi/src/lib.rs, glean-core/ios/Glean/GleanFfi.h, glean-core/ios/Glean/Net/HttpPingUploader.swift
Due to the way we use CFFI in Python, we cannot use a `union` type as a return value. On the other
hand, this works fine with output parameters. This commit changes the API to use output parameters
to accommodate all the supported language bindings.
=> Get upload tasks using an output parameter 

.coveragerc, Makefile, glean-core/python/glean/_subprocess/_process_dispatcher_helper.py
This adds an extra environment variable set only when running the Glean coverage tests, so the multiprocess coverage feature doesn't kick in when Glean-using libraries are running *their* coverage tests.
=> Bug 1639158: Fix Python coverage testing

docs/user/pings/index.md
=> Remove `ping_type` from `ping_info` docs

docs/user/metrics/event.md
=> Document the max number of keys for `extra_keys`

glean-core/ios/GleanTests/GleanTests.swift
This adds a line to reset the cache variable tracking running in other processes so that it doesn't interfere with other tests ran after this test.
=> Fix iOS tests

CHANGELOG.md, glean-core/python/glean/glean.py, glean-core/python/tests/test_glean.py
This makes the Python bindings have the same semantics of the other bindings, i.e. application lifetime metrics are cleared on the next startup after the Glean-owned pings are generated.
=> Clear `lifetime: application` metrics in the Python bindings

CHANGELOG.md, glean-core/ios/sdk_generator.sh, glean-core/python/setup.py, glean-core/python/tests/test_glean.py, gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy
This PR makes sure such metrics don't get recorded as `lifetime: user`.
=> Fix `lifetime: application` metrics in Python

CHANGELOG.md, glean-core/ffi/src/uuid.rs, glean-core/python/tests/metrics/test_uuid.py
This adds a log error when invalid UUIDs are passed to UUID metric types instead of attempting to unwrap, which would panic on invalid UUIDs.
=> Don't crash on invalid UUIDs in Python

docs/dev/python/setting-up-python-build-environment.md
The documented value doesn't work for me, locally. This works and matches what we advertise for the android bindings.
=> Fix the docs for `RUST_LOG` verbose logging [doc only]

glean-core/ios/GleanTests/Debug/GleanDebugUtilityTests.swift, glean-core/ios/GleanTests/GleanTests.swift, glean-core/ios/GleanTests/Metrics/EventMetricTests.swift, glean-core/ios/GleanTests/Metrics/PingTests.swift, glean-core/ios/GleanTests/Net/DeletionRequestPingTests.swift, glean-core/ios/GleanTests/Net/HttpPingUploaderTests.swift, glean-core/ios/GleanTests/Scheduler/MetricsPingSchedulerTests.swift
This is recommended to ensure they don't linger around across tests:
https://github.com/AliSoftware/OHHTTPStubs#using-ohhttpstubs-in-your-unit-tests
We didn't have issues with this yet, but ... I let you decide if we pull this in :P
=> iOS: Remove all stubs on teardown of tests

glean-core/python/glean/glean.py
Since Glean.initialize is called multiple times during the running of
the test suite, it actually registers the atexit handler multiple times,
which results in it running multiple times at exit.
This behavior is undocumented in the atexit documentation, but a short test
script shows that multiply-registered functions are called multiple times at
exit.
As far as I can tell, this is only an issue during testing, not in normal
app usage where Glean.initialize is a no-op after the first time it is called.
However, this saves a bit of time at completion for our own test suite and
probably also for users' test suites that use the `testing.reset_glean` helper.
=> Unregister the atexit handler in Glean._reset

glean-core/ffi/src/lib.rs, glean-core/src/lib.rs, glean-core/src/upload/mod.rs
By doing this we don't erroneously wait at least 1 second, at startup, in the Python language bindings.
=> Synchronously scan for pings in stand alone upload processes

.circleci/config.yml
This might allow us to look into crashes we see on CI, a la:
SIGSEGV (0xb) at pc=0x00007fd4a72c4181, pid=3244, tid=0x00007fd459891700
JRE version: OpenJDK Runtime Environment (8.0_252-b09) (build 1.8.0_252-b09)
Java VM: OpenJDK 64-Bit Server VM (25.252-b09 mixed mode linux-amd64 compressed oops)
Problematic frame:
C  [libc.so.6+0x15c181]
Core dump written. Default location: /home/circleci/project/glean-core/android/core or core.3244
---
I've seen this now far too many times on CI. I'm getting worried, let's figure this out.
=> Capture a potential core dump as a build artifact

about.toml
This is required for flate2/adler. Without this, cargo about will fail.
=> Add the missing 'Zlib' license to about.toml

DEPENDENCIES.md, glean-core/Cargo.toml, glean-core/android/dependency-licenses.xml
"miniz_oxide" is the default for flate2, but if Glean is a dependency of
a bigger project that transitively also uses flate2 somewhere else, the
backend in use might change.
We don't really care about the backened in use.
This is fixing an issue when integrating back into mozilla-central,
where flate2 is already in tree and transitively used _somehwere_ with
different features.
--- 
not sure how far along the release is, the dependency summary changes might be in that already, I can drop them from here (and at the latest they would get in with the next version bump)
=> Bug 1640927 - Flate2 is default oxidized

Cargo.lock, glean-core/Cargo.toml
No major things went into flate2 since then, except they upped the
version requirement of libc in 1.0.13[1].
This leads to problems when integrating back into mozilla-central, where
the version requirements on libc are a bit more strict.
To avoid issues we can relax what we depend on and allow older version
of flate2, and thus older versions of libc.
For our own builds targetting e.g. Android or iOS we will actually use
the latest flate2 and libc release.
[1]: https://github.com/alexcrichton/flate2-rs/commit/c9b256a624d04353bc6928dacf9d0c99aa61c261
=> Relax version requirement for flate2 for compatibility reasons

glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/rust/LibGleanFFI.kt
Oh boy, this was driving me ... into the dark corners of debugging today.
We saw SEGFAULTS on CI happening more and more frequently recently. I
was able to reproduce it in 1 out of 5 runs inside the Docker container
also used for TaskCluster now.
The error we were seeing was attributed to libc as follows:
C  [libc.so.6+0x18e5a1]
After some wrestling with the environmnet, installing gdb, enabling coredumps (`ulimit -c unlimited`),
adding debug info back to the build and reading 40-item long stacktrace,
that spans the JVM, C, our FFI part, our Rust implementation and the Rust standard library there, I found the culprit:
We don't pass it the data!
And because this is an optimized build and things get shuffled around it
might or might not be pointing to valid memory or be a null pointer.
But …
=> Pass a reason when collecting pings for tests or a null pointer.

.circleci/config.yml
Instead of a fixed path let's just search for it.
=> CI: Find, gather and upload core files and logs if possible

taskcluster/ci/android-build/kind.yml, taskcluster/glean_taskgraph/job.py, taskcluster/scripts/rust/rustup-setup.sh
This is the next step in our taskcluster support: building & running the Kotlin code & tests on CI.
cc @MihaiTabara
=> Bug 1639183 - Android builds on TaskCluster

glean-core/android/build.gradle
[doc only]
---
don't need a full CI run on the PR here.
=> Bug 1641793- Android: Export proguard rules in debug, as a consumer might still enable proguard/r8

glean-core/Cargo.toml, glean-core/ffi/Cargo.toml, glean-core/preview/Cargo.toml
The list contains "globs", meaning it previously looked for `README.md`
or `LICENSE` in all subfolders, leading to the inclusion of far too
many files, e.g. from a virtualenv.
=> Use absolute paths in `include` list for packaging

glean-core/ffi/cbindgen.toml, glean-core/ffi/glean.h, glean-core/ffi/src/boolean.rs, glean-core/ffi/src/counter.rs, glean-core/ffi/src/custom_distribution.rs, glean-core/ffi/src/datetime.rs, glean-core/ffi/src/lib.rs, glean-core/ffi/src/macros.rs, glean-core/ffi/src/memory_distribution.rs, glean-core/ffi/src/quantity.rs, glean-core/ffi/src/string.rs, glean-core/ffi/src/string_list.rs, glean-core/ffi/src/timespan.rs, glean-core/ffi/src/timing_distribution.rs, glean-core/ffi/src/uuid.rs, glean-core/ios/Glean/GleanFfi.h, glean-core/python/glean/metrics/lifetime.py, glean-core/python/glean/metrics/memoryunit.py, glean-core/python/glean/metrics/timeunit.py, glean-core/python/glean/net/upload_task_tag.py, glean-core/python/tests/test_glean.py, glean-core/src/common_metric_data.rs, glean-core/src/metrics/memory_unit.rs, glean-core/src/metrics/time_unit.rs
This was prompted by the recent bug in the Python bindings that the `Lifetime` enum in glean_parser and glean-core didn't match.  I think that rather than treating glean_parser as the canonical source of values, we should treat the Rust glean-core as the canonical source of values and get them from there where possible.
This exposes the C-like enums (Rust empty enums) through cbindgen so we can use them directly from Python and not have to make sure that the values are in sync.
Then to make sure glean_parser is correct (since glean_parser doesn't / can't have a dependency on glean-core), this just adds a test to make sure its enums are in sync with glean-core's.  It does mean we won't catch those issues until upgrading the version of glean_parser in glean, but that should be more than …
=> Bug 1640692: Python: Use Rust as canonical source for enum values

docs/SUMMARY.md, docs/user/debugging/android.md, docs/user/debugging/debug-ping-view.md, docs/user/debugging/python.md
At the same time, remove some notes which were redundant
with what was already present in the Glean documentation.
Original document: https://docs.telemetry.mozilla.org/concepts/glean/debug_ping_view.html
=> Bug 1640660 - Move Glean debug ping viewer documentation from dtmo

glean-core/csharp/.gitignore, glean-core/csharp/csharp.sln, glean-core/csharp/csharp/Configuration/Configuration.cs, glean-core/csharp/csharp/Dispatchers.cs, glean-core/csharp/csharp/Glean.cs, glean-core/csharp/csharp/Glean.csproj, glean-core/csharp/csharp/LibGleanFFI.cs, samples/csharp/csharp.sln, samples/csharp/csharp/Program.cs, samples/csharp/csharp/csharp.csproj
This PR sets up the language binding structure and provides a minimal API surface to use them.
It additionally commits a sample application to test the bindings.
The plan:
- attempt to merge this PR, keeping followin PRs small and focused;
- mockup most of the system;
- scale up with other devs after the first metric type is merged.
Things it does:
- Picks the `glean_ffi.dll` and allows to call glean-core functions;
- Defines the project structure;
- Initializes Glean and wires up Rust logging.
- Adds a sample c# application that uses nuGet to consume the library.
This PR will **NOT** cover:
- adding a proper logging system;
- adding a new metric type;
- initialize core metrics;
- properly initialize Glean;
- add test coverage for the basic functionalities;
- make sure it picks the right …
=> Add minimal language bindings for C#

samples/android/app/src/androidTest/java/org/mozilla/samples/gleancore/pings/BaselinePingTest.kt, samples/android/app/src/androidTest/java/org/mozilla/samples/gleancore/pings/DeletionRequestPingTest.kt, samples/android/app/src/androidTest/java/org/mozilla/samples/gleancore/pings/SharedTestUtils.kt
Fixes [Bug 1620673](https://bugzilla.mozilla.org/show_bug.cgi?id=1620673)
As an extra, I noticed the `validateBaselinePing` integration test was also failing and fixed it. It was a known issue of getting the `foreground` ping instead of the `background` one, which doesn't have a `duration` field and fails the test. This has been fixed in a-c and fenix already.
=> Verify if *only* deletion request was sent on android sample app tests

.circleci/config.yml
Something in 1.44.0 (released 2020-06-04) broke the Windows build,
resulting in an error like:
undefined reference to `_Unwind_Resume'
We already build with `panic=abort`.
For now this will reenable working builds until we figure out what's
broken.
=> CI: Pin Rust to 1.43.0 for Python builds

glean-core/csharp/Glean.csproj, glean-core/csharp/LibGleanFFI.cs
This only allows local developer builds outside of Windows. More project file tweaks will come next week to package a single nuGet file with all the dependencies.
=> Enable cross-platform c# local developer builds

.circleci/config.yml
This is an attempt to investigate the intermittent Python test segfaults by saving the coredump files.
=> Bug 1641619: Save coredumps from Python tests

.gitignore, glean-core/csharp/.gitignore, glean-core/csharp/Glean.csproj, samples/csharp/csharp.csproj
This additionally updates the sample application to use that package.
The nuGet package can be built with this command:
`dotnet pack glean-core/csharp/csharp.sln -c Release -p:IsPublicPackage=true`
Updating the package can be done from the nuGet website or using the `dotnet publish` command.
=> Enable the creation of a multi-platform nuGet package for c#

glean-core/csharp/Glean/Glean.cs, glean-core/csharp/Glean/LibGleanFFI.cs
STR:
```
GleanInstance.Initialize("fxrpc",  "0.1.1",  true, 
new Configuration(Configuration.DefaultTelemetryEndpoint, null, null), "data");
```
It will have InvalidOperationException at https://github.com/mozilla/glean/blob/b949d4927a1e86b4ba469653cc62fc52eecf6add/glean-core/csharp/Glean/Glean.cs#L93
=> Solving InvalidOperationException when assigning a null max_events in C# config

glean-core/android/src/main/java/mozilla/telemetry/glean/scheduler/PingUploadWorker.kt
Fixes [Bug 1644290](https://bugzilla.mozilla.org/show_bug.cgi?id=1644290)
This is a temporary fix so we can stop [this issue](https://github.com/mozilla-mobile/fenix/issues/11335). 
I opened a bug to move this retrying logic to the Rust side: https://bugzilla.mozilla.org/show_bug.cgi?id=1644364
=> Add maximum number of retries to PingUploadWorker

glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt, glean-core/csharp/Glean/Glean.cs, glean-core/csharp/Glean/LibGleanFFI.cs, glean-core/csharp/GleanTests/GleanTests.cs
This adds the two APIs to control upload enabled.
We have no uploader yet, so I had to leave a bunch of TODOs. That's fine, since this already unblock a clean initial integration with our consumers.
=> Add "SetUploadEnabled"

.circleci/config.yml, CHANGELOG.md, README.md, bin/prepare-release.sh, bin/spellcheck.sh, docs/contributing.md, docs/dev/android/development-with-android-components.md, docs/dev/android/locally-published-components-in-fenix.md, docs/dev/core/internal/payload.md, docs/dev/cut-a-new-release.md, docs/dev/ios/debug-glean-on-ios.md, docs/dev/testing.md, docs/user/adding-glean-to-your-project.md, docs/user/instrument-android-crashes-example.md, glean-core/Cargo.toml, glean-core/ffi/Cargo.toml, glean-core/preview/Cargo.toml, samples/ios/app/Cartfile
This switches all docs and config over to the default branch named "main".
When this lands we need to change the default branch on GitHub to "main": https://github.com/mozilla/glean/settings/branches
For your local checkout the following commands will allow you to fetch the new default branch and delete the old one:
```
git fetch upstream
git checkout main
git branch --delete master
```
=> Rename default branch

glean-core/ios/Glean/Net/HttpPingUploader.swift, glean-core/python/glean/net/ping_upload_worker.py
Reopening https://github.com/mozilla/glean/pull/957
=>  Limit the number of upload retries in Python and iOS

glean-core/csharp/Glean/LibGleanFFI.cs, glean-core/csharp/Glean/Metrics/BooleanMetricType.cs, glean-core/csharp/GleanTests/Metrics/BooleanMetricTypeTest.cs
---
Re-open of #959 -- that was closed by accident. Original by @daoshengmu. The old PR already had a r+ review, with minimal nits and comments.
=> Support BooleanMetricType in C# binding.

build.gradle
Partial revert of ce019d2ba11307c7e82af446f7101d3db8ed823d
=> Drop the version requirement for lifecycle extensions down again

docs/README.md, docs/appendix/twig.md
I remember we talked about this briefly, don't remember if we filed a bug.
But I wanted to get _something_ done today.
I felt that there's only 3 big chapters worth listing, but then also mentioning the TWiG felt like the right thing to do.
=> Add brief overview section on book's main page

glean-core/csharp/Glean/Configuration/Configuration.cs, glean-core/csharp/Glean/Net/HttpClientUploader.cs, glean-core/csharp/Glean/Net/PingUploader.cs, glean-core/csharp/GleanTests/Net/HttpClientUploaderTest.cs
This adds an HTTP stack to enable ping sending. This is modelled after the Kotlin implementation.
=> Add a default ping uploader in C#

CHANGELOG.md, glean-core/src/upload/request.rs
Drop the sub-second precision and report GMT
as timezone identifier, as required by https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Date
=> Fix the `Date` header generated by glean-core

.dictionary, docs/appendix/glossary.md, docs/user/debugging/android.md, glean-core/android/src/main/java/mozilla/telemetry/glean/debug/GleanDebugActivity.kt
Related to [Bug 1646002](https://bugzilla.mozilla.org/show_bug.cgi?id=1646002)
[doc only]
=> Make android debug activity usage documentation clearer

.dictionary, CHANGELOG.md, docs/user/adding-glean-to-your-project.md, glean-core/python/glean/_dispatcher.py, glean-core/python/tests/test_dispatcher.py
Cc: @wlach -- I'd appreciate your review as well, even though permissions don't seem to let me request it...
=> Bug 1646402: Python: Don't use threading in multiprocessing subprocesses

CHANGELOG.md, docs/dev/core/internal/upload.md, docs/user/pings/index.md, glean-core/src/lib.rs, glean-core/src/upload/mod.rs
Related to [Bug 1543612](https://bugzilla.mozilla.org/show_bug.cgi?id=1543612)
I wanted to get some feedback on my approach to this problem before I continued. My goal here was to try and replicate [what Firefox does to rate limit ping uploads](https://searchfox.org/mozilla-central/rev/4bb2401ecbfce89af06fb2b4d0ea3557682bd8ff/toolkit/components/telemetry/app/TelemetrySend.jsm#84), specifically:
> Only allow up to 10 ping uploads per minute.
This turned out to be tricky. The challenges on the current implementation and how I decided to solve them are:
- It doesn't really know exactly when the ping is uploaded.
- My solution here was to ignore this fact and just try to limit the number of times `get_upload_task` can be called per minute.
- It sends pings to upload one at a time, not in …
=> Limit the number of ping upload requests per minute

.circleci/config.yml, CHANGELOG.md, Makefile, glean-core/python/setup.py
As a first step to reduce the size of the library we ship this switches the Python build to contain the release builds.
I _think_ this works. Controlling it through an environment variable used by the Makefile seemed easy enough, additionally the Python setup script can read the same one.
For the Windows builds we're calling cargo directly, so we just pass `--release` directly.
We might lose some more readable stacktraces in case of bugs (but I guess so far we haven't received any of those anyway?)
=> Bug 1597714 - Build for release when assembling Python release

glean-core/csharp/Glean/Glean.csproj
This makes the build system fail if any glean-core FFI library file is not available when creating the nuGet package. It additionally makes sure that, when packaging the final library, the right group of libraries is picked.
Note: this additionally bumps the version to another fake one, since this is still unofficial/unlisted.
=> Fix the C# build to create proper public nuGet packages

CHANGELOG.md, glean-core/python/glean/_util.py
This is needed for Python 3.8 on Windows support
=> Python: Fix how locales are looked up

glean-core/python/setup.py
This fixes things so the wheel pattern matcher will refuse to install Glean on
Python 3.5
This should have been included in #987, but I just noticed it now.
=> Python: Don't allow wheels to install on Python 3.5

.circleci/config.yml
They take a total of about 20 Minutes on CI.
We don't need the artifacts.
We got TaskCluster now to generate the artifacts AND publish straight to Maven.
=> CI: Remove Android build tasks from CircleCI

glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/config/Configuration.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/debug/GleanDebugActivity.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/net/Upload.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/rust/LibGleanFFI.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt, glean-core/ffi/glean.h, glean-core/ffi/src/lib.rs, glean-core/ios/Glean/Config/Configuration.swift, glean-core/ios/Glean/Debug/GleanDebugTools.swift, glean-core/ios/Glean/Glean.swift, glean-core/ios/Glean/GleanFfi.h, glean-core/ios/Glean/Net/HttpPingUploader.swift, glean-core/ios/Glean/Net/Upload.swift, glean-core/ios/GleanTests/Config/ConfigurationTests.swift, glean-core/ios/GleanTests/Debug/GleanDebugUtilityTests.swift, glean-core/ios/GleanTests/Net/HttpPingUploaderTests.swift, glean-core/src/lib.rs, glean-core/src/lib_unit_tests.rs, glean-core/src/upload/directory.rs, glean-core/src/upload/mod.rs, glean-core/src/upload/request.rs, glean-core/src/util.rs, glean-core/tests/memory_distribution.rs, glean-core/tests/ping_maker.rs, glean-core/tests/timing_distribution.rs
Fixes [Bug 1640575](https://bugzilla.mozilla.org/show_bug.cgi?id=1640575).
~As a bonus also fixes (or at least partially fixes) [Bug 1605097](https://bugzilla.mozilla.org/show_bug.cgi?id=1605097), because persisting the tag was the best way I found to move it to Rust.~ Not anymore, this was defered to a later PR. Because the tag was not being persisted any longer, I had to drop the commit where I removed the debug view tag management from python in favour of the rust implementation. Since python instantiates a standalone upload manager to do the upload, without persisting the tag we don't pck up on it during upload. When I work on the PR to persist the headers I can bring the python commit back.
I realized after the fact that this could be broken down into smaller PRs, which can stil be …
=> Bug 1640575 - Move "debug view tagging" to Rust

CHANGELOG.md, glean-core/ffi/src/lib.rs, glean-core/src/lib.rs, glean-core/src/upload/directory.rs, glean-core/src/upload/mod.rs
The tests on the upload module either used a standalone upload manager or the upload manager that is created when you create a new Glean instance. When creating a standalone one, the tests "wait" for upload manager to be done scanning the pending pings directory. When using the one inside Glean the don't.
This is most probably not causing the CI failures, if it is that would mean I understand those failures even less than I thought. Still, it is a good thing to add to the tests.
Also, opening this PR will allow me to send new commits to test fixes to the CI problem.
=> Bug 1648695 - Fix failing rust upload tests on CI

gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy
The errors from glean_parser during an Android application/library build were a bit hidden by noise that's probably only meaningful to Glean internal developers but not our users.
1) It would show the entire commandline used to call Python, which included a longish trampoline script.
2) It would show a traceback in the trampoline script which isn't really relevant to the failure in glean_parser itself.
This is should make it easier to spot glinter information or syntax errors in metrics.yaml files.
=> Bug 1647736: Make glean_parser glinter and error output more obvious

taskcluster/glean_taskgraph/__init__.py
Backporting https://github.com/mozilla-mobile/android-components/pull/7555 from AC to ensure we have a safety check to fail early in case versions mismatch.
CC: @badboy
=> Bug 1643378 - add consistency check for Github release version.

glean-core/ios/Glean/Metrics/LabeledMetric.swift
This makes the subscript access to the LabeledMetrics public, otherwise, consuming applications don't have access to record to the LabeledMetrics because the subscript defaults to internal access.
=> Bug 1649286 - Make Glean-iOS LabeledMetric subscript public

glean-core/csharp/Glean/Glean.cs, glean-core/csharp/Glean/LibGleanFFI.cs, glean-core/csharp/GleanTests/GleanTests.cs
See the individual commit messages for the explanation.  This was tested locally with [this repo](https://github.com/daoshengmu/GleanUnity/tree/master/GleanUnity)
=> Bug 1648784: fix an initialization crash when Glean is used in Unity

CHANGELOG.md, docs/user/collected-metrics/metrics.md, docs/user/pings/baseline.md, glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt, glean-core/ios/Glean/Glean.swift, glean-core/ios/GleanTests/GleanTests.swift, glean-core/metrics.yaml, glean-core/pings.yaml, glean-core/python/glean/glean.py
Fixes [Bug 1609968](https://bugzilla.mozilla.org/show_bug.cgi?id=1609968)
Opening this as a draft because I believe the `send_if_empty` addition to the baseline ping should be discussed. 
Removing the locale means that when `foreground` or `dirty_startup` the baseline ping will have no metrics, so I believe adding this flag makes sense. If everyone agrees on that, still this would need to wait for a fix in the glean_parser, because the `send_if_empty` breaks the baseline ping documentation.
=> Bug 1609968 - Remove locale from baseline ping

glean-core/csharp/Glean/Glean.cs
`applicationVersion` is not optional when calling `GleanInstance.Initialize` in C#, and Python binding is also doing this way.
Besides, using Reflection approach sounds like not a good idea, some applications are made by Unity ` callling System.Reflection.Assembly.GetEntryAssembly()` will return null.
=> Using application version as display id instead of using reflection.

.circleci/config.yml
The container used to build Python packages for Linux doesn't have ssh and git preinstalled, so CircleCI spends 2m40 installing them (for some unknown reason).  Installing the RPM packages for them only takes 10s, so this saves us non-trivial amounts of time on release.
=> Bug 1648094: Install ssh and git on Python Linux container

samples/csharp/Program.cs
Windows uses a backward slash (`\`),
*nix uses a forward slash (`/`).
Let's use a function to do the right thing here.
=> Use Path.* methods for path handling

CHANGELOG.md, glean-core/ffi/src/lib.rs, glean-core/src/lib.rs, glean-core/src/ping/mod.rs, glean-core/src/upload/directory.rs, glean-core/src/upload/mod.rs, glean-core/src/upload/request.rs, glean-core/src/util.rs, glean-core/tests/common/mod.rs, glean-core/tests/event.rs, glean-core/tests/ping_maker.rs
I tried to make this so that it is easy to persist more headers or even other types of metadata in the future.
=> Bug 1605097 - Persist X-Debug-ID header and use persisted on creation of requests

glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/csharp/Glean/Glean.cs, glean-core/ios/Glean/Glean.swift, glean-core/ios/GleanTests/TestUtils.swift, glean-core/python/glean/glean.py
From the commit message:
The task running the intialization runs asynchronously.
It therefore can happen that we externally modify the uploadEnabled
flag.
Up to now we forgot to recheck it.
By doing this as the last thing before flushing the queue of tasks it
should be in the expected order for users:
1. First Glean fully initializes, with the uploadEnabled flag as set in
the `initialize` call.
2. Potentially queued up tasks (such as metric recordings) are replayed
3. Finally toggling the flag is respected.
---
This fixes the one encountered issue where changes to the flag are simply not reflected at all.
=> Bug 1650752 - Reapply async upload toggle after initialize

CHANGELOG.md, glean-core/src/error.rs, glean-core/src/lib.rs, glean-core/src/lib_unit_tests.rs
Using an empty application id makes it impossible to upload pings to ingestion, since the application id is used to build the submission path. This makes sure the error is caught instead of just silently failing to upload pings.
=> Bug 1649925 - Ensure Glean does not initialize with an empty application id

CHANGELOG.md, glean-core/ffi/glean.h, glean-core/ffi/src/lib.rs, glean-core/ios/Glean/GleanFfi.h, glean-core/python/glean/net/ping_upload_worker.py, glean-core/python/tests/conftest.py, glean-core/python/tests/test_network.py, glean-core/src/lib.rs, glean-core/src/upload/mod.rs
This works by initializing a full Glean in the subprocess that
*doesn't* do any startup work such as setting metrics or submitting
pings. This makes it safe to initialize Glean in the subprocess,
and thus errors can be reported there.
=> Bug 1644359: Support error reporting in Python bindings

.circleci/config.yml
A full Python build needs to run in order for a Python documentation build to work.
As of #995, the Python 3.8 test job needs to run even for doc-only builds,
rather than the Python 3.7 test job.
=> Fix doc-only builds

glean-core/csharp/Glean/Glean.csproj, glean-core/csharp/Glean/LibGleanFFI.cs, glean-core/csharp/Glean/Metrics/BooleanMetricType.cs, glean-core/csharp/Glean/Metrics/DatetimeMetricType.cs, glean-core/csharp/Glean/Metrics/PingType.cs, glean-core/csharp/Glean/Metrics/StringMetricType.cs, glean-core/csharp/Glean/Metrics/UuidMetricType.cs, glean-core/csharp/GleanTests/GleanTests.csproj, glean-core/csharp/csharp.sln, samples/csharp/Sample.csproj
This replaces the use of `SafeHandle`-derived classes when passing Glean handles back and forth from the FFI layer. It was crashing on x86 because, while Glean correctly uses uint64 as handles, `SafeHandle` was using `IntPtr` under the hood, which is 4 bytes on 32 bit architectures.
This made glean-core panic because it was seeing an unknown handle when it was passed back from C# to glean-core over the FFI.
All in all, we don't really need `SafeHandle`(s) for everything: we just need it for Win32 handles or pointers coming from the FFI. Moreover, we don't really care yet about cleaning up, so no need to get desperate about re-implementing `SafeHandle`-like mechanism for uint64: that would also be complicated, because the .NET marshaler knows about `SafeHandle` and behaves in a special way …
=> Bug 1649925 - Make sure Glean C# doesn't crash on x86

.circleci/config.yml
Reverts mozilla/glean#1038
This fixes bug 1652137.  It's easiest just to revert this commit -- it worked fine before only slowly.  Finding the correct way to install ssh that has the correct algorithms installed to communicate with Github's much newer ssh server may take some time (and IMHO isn't a high priority).
=> Revert "Bug 1648094: Install ssh and git on Python Linux container"

.circleci/config.yml
The Mac container doesn't have Python 3.8, it has 3.7.  This wasn't
caught in #995 because the release jobs weren't tested.
=> Bug 1652139: Fix Python macos releases

glean-core/src/debug.rs, glean-core/src/lib.rs, glean-core/src/util.rs
This is still a work in progress. I wanted to get some feedback on my approcah before moving forward.
For now I only have the logic abstracting away the debug options into their own struct and getting the values from the env. I still need to deal with: better testing coverage, move log_pings management to the core, updating documentation.
I tried to make the logic a bit generic in case we add more debugging options in the future, which I know we will: https://bugzilla.mozilla.org/show_bug.cgi?id=1634064
Now, still it might be a little overkill, so please let me know your thoughts. 
**NOTE** Thanks to @badboy I was able to make this code look a little nicer, sorry for nerdsniping you, hehe.
[UPDATE]
This is now ready for review. I will make this part 1 of 2.
This introduces the …
=> Bug 1646706 - Manage debug options in the core and get them from the environment

docs/dev/core/internal/upload.md, docs/dev/docs.md
This is a braindump of the desired architecture for the upload modules implemented in the language bindings, that directly interact with the lower level upload module in glean-core.
A preview of the mermaid plot:
=> Bug 1640201 - Add the high level design docs for the upload module [doc only]

glean-core/src/error.rs, glean-core/src/histogram/functional.rs, glean-core/src/metrics/experiment.rs
* Lint error related to usage of __NonExhaustive pattern explicitly;
* Lint error related to usage of `and_then` instead of `map`;
* Overflow error on add, fixed by using `saturating_add` explicitly.
=> Fix errors surfaced by new rust stable version 1.45.0

.circleci/config.yml
Python 3.8 dropped the "m" ABI flag (which indicates the use of pymalloc vs.
system malloc) since both modes of building are now ABI compatible.
=> Fix PyPI Linux releases

CHANGELOG.md, docs/user/debugging/android.md, glean-core/android/src/main/java/mozilla/telemetry/glean/debug/GleanDebugActivity.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/debug/GleanDebugActivityTest.kt
Products might want to debug a product and launch it using different options. Without this change, such options are discarded by Glean.
**How to test this**
1. `adb shell am set-debug-app -w org.mozilla.samples.gleancore`
2. adb shell am start -d "https://www.example.com" -n org.mozilla.samples.gleancore/mozilla.telemetry.glean.debug.GleanDebugActivity --es tagPings mytest --es otherOption other-value
3. Place a breakpoint [in the MainActivity](https://searchfox.org/glean/rev/7ad095554c6baa2b92f9ab005a1dcaf157e61723/samples/android/app/src/main/java/org/mozilla/samples/glean/MainActivity.kt#19) and inspect `intent.data` (should be `"https://www.example.com"`) and `intent.getStringExtra(otherOption)` (should be `other-value`)
More context on why this is needed can be [read on the …
=> Bug 1634064 - Propagate `GleanDebugActivity` intent options to the main intent

.dictionary, CHANGELOG.md, glean-core/ffi/glean.h, glean-core/ffi/src/jwe.rs, glean-core/ffi/src/lib.rs, glean-core/ios/Glean/GleanFfi.h, glean-core/src/lib_unit_tests.rs, glean-core/src/metrics/jwe.rs, glean-core/src/metrics/mod.rs, glean-core/tests/jwe.rs
I decided to separate this into two parts, this one just with the core and ffi changes, the next with the addition of this metric type to the bindings.
I found a bug on https://github.com/mozilla/glean/blob/main/glean-core/src/error_recording.rs#L61, which the bindings PR will depend on too. If you notice, we jump on the count from 2 directly to 4. I'll send a separate PR to fix that.
This implementation was based on [this document](https://docs.google.com/document/d/1nntNIiE6braTGzoKf-lx21OVDd8ssyeIeJu3jnQQfEE/edit?usp=sharing).
=> Bug 1650787 - Implement the JWE metric type on the core and FFI

CHANGELOG.md, glean-core/android/src/main/java/mozilla/telemetry/glean/scheduler/MetricsPingScheduler.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/scheduler/MetricsPingSchedulerTest.kt
This is the fix for the Android/Kotlin bindings and a modified test to cover the case.
=> Bug 1653244 - Fix experiment info getting cleared before getting into metrics ping

docs/user/debugging/android.md, docs/user/debugging/index.md, docs/user/debugging/ios.md, docs/user/pings/index.md, glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/debug/GleanDebugActivity.kt, glean-core/android/src/main/java/mozilla/telemetry/glean/rust/LibGleanFFI.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/debug/GleanDebugActivityTest.kt, glean-core/ffi/glean.h, glean-core/ffi/src/lib.rs, glean-core/ios/Glean/Debug/GleanDebugTools.swift, glean-core/ios/Glean/Glean.swift, glean-core/ios/Glean/GleanFfi.h, glean-core/src/debug.rs, glean-core/src/lib.rs, glean-core/src/ping/mod.rs
This implements the new ping tagging system in the Glean SDK. It adds a CLI option for `adb`, all the glean-core implementation and environment variable support.
Please note that I had to refactor the debug options module a bit in order to allow using non-`String` option types.
=> Bug 1634064 - Implement the 'X-Source-Tags' header

glean-core/python/glean/_ffi.py, glean-core/python/glean/glean.py, glean-core/python/tests/metrics/test_string.py
This is just resolving a part of 1653046 and making the FFI calls type safe.
Full-on type safety in Python is a much broader problem that affects many
call sites so deferring for now.
=> Bug 1653046: Don't send NULLs over FFI where not expected

samples/csharp/Sample.csproj, samples/csharp/app.manifest
Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1653897
The `Environment.OSVersion` object we use in `Glean.cs` will return a version that represents an approximate version of the OS. But, it is not reliable, we still need to add this manifest in a project.
=> Bug 1653897 - Fix the C# sample app to report the correct version on Windows 10

glean-core/python/tests/test_glean.py
This just adds code to print out the URL read from the file so we can hopefully better diagnose the error.  This only adds a print to a test, and even that will only be shown if the test fails, so low risk to just include this.
=> Bug 1653995: Provide more info to diagnose intermittent

CHANGELOG.md, docs/user/general-api.md, glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/TestUtil.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/private/EventMetricTypeTest.kt, glean-core/csharp/Glean/Glean.cs, glean-core/csharp/GleanTests/GleanTests.cs, glean-core/ios/Glean/Glean.swift, glean-core/ios/GleanTests/GleanTests.swift, glean-core/ios/GleanTests/Metrics/EventMetricTests.swift, glean-core/python/glean/glean.py, glean-core/python/tests/metrics/test_event.py, glean-core/python/tests/test_glean.py, samples/android/app/src/main/java/org/mozilla/samples/glean/MainActivity.kt
Replicating the commit messages for information:
Always enqueue an async task to change upload
That way it follows what a user expect when calling it in between other calls:
It executes in the right order.
Because the dispatch queue is halted until Glean is fully initialized
we can safely enqueue here and it will execute after initialization.
and
Deprecate `getUploadEnabled()` across all implementations
Due to Glean's asynchronous initialization the return value can be incorrect.
Applications should not rely on Glean's internal state.
Upload enabled status should be tracked by the application and communicated to Glean if it changes.
Note: The method was removed from the C# implementation.
--- 
This probably deserves some extra eyes on it. Putting you 3 on it, but maybe one or 2 should be …
=> Bug 1649926 - Always enqueue an async task to change upload and deprecate `getUploadEnabled`

glean-core/ios/Glean/Dispatchers.swift, glean-core/ios/Glean/Glean.swift, glean-core/ios/GleanTests/DispatchersTest.swift, glean-core/ios/GleanTests/GleanTests.swift, glean-core/ios/GleanTests/Metrics/EventMetricTests.swift, glean-core/ios/GleanTests/Scheduler/MetricsPingSchedulerTests.swift
This unifies the naming across Kotlin and Swift.
I picked `queueing` because there were more occurences already.
=> Use one more e in "queueing" to make it consistent with Kotlin

docs/user/collected-metrics/metrics.md, glean-core/metrics.yaml, glean-core/pings.yaml
This fixes the YAML formatting so it uses the `|` rather than `>` mode for multi-line strings. These preserve the newlines as-is, rather than converting all newlines to spaces, which is compatible with markdown paragraph formatting etc. (not that we have any right now.
Also changed `overflew` (which is admittedly cool) to `overflowed`.
=> Fix YAML formatting

docs/user/debugging/ios.md, glean-core/ios/Glean/Debug/GleanDebugTools.swift, glean-core/ios/Glean/Glean.swift, glean-core/ios/GleanTests/GleanTests.swift
Tested locally and it works.
Not sure if I should have added tests anywhere for this changes. I followed the `debugViewTag` implementation which also doesn't have explicit tests.
=> Implement ping tagging for iOS

.dictionary, docs/README.md, docs/SUMMARY.md, docs/user/adding-glean-to-your-project.md, docs/user/adding-new-metrics.md, docs/user/android-build-configuration-options.md, docs/user/debugging/android.md, docs/user/debugging/index.md, docs/user/debugging/ios.md, docs/user/experiments-api.md, docs/user/general-api.md, docs/user/instrument-android-crashes-example.md, docs/user/metric-parameters.md, docs/user/pings/baseline.md, docs/user/pings/custom.md, docs/user/pings/index.md, docs/user/pings/testing-custom-pings.md, docs/user/testing-metrics.md
This is just a basic cleanup of things I found reading through the user
documentation, mainly of the form:
- Correcting the uses of "Glean" vs. "Glean SDK"
- Updating a few facts that became out of date
- Removing a little Python -> C# copy-pasta
- Adding the missing new metric parameter `data_sensitivity`
- Not linking out to glean_parser for the metric parameter docs (which have been
duplicated in the Glean Book for some time).
=> [doc only] Documentation cleanup

README.md, docs/README.md
This sets the correct product & components and adds the whiteboard tag
to place it in our triage list.
[doc only]
=> Use a shorter bugzilla link everywhere

docs/user/debugging/index.md
[doc only]
BONUS: standardize language used throughout debug doc
=> Bug 1648110 - Make debug docs more detailed

CHANGELOG.md, docs/user/collected-metrics/metrics.md, docs/user/pings/index.md, glean-core/metrics.yaml, glean-core/src/error.rs, glean-core/src/internal_metrics.rs, glean-core/src/lib.rs, glean-core/src/upload/directory.rs, glean-core/src/upload/mod.rs, glean-core/src/upload/request.rs
This required a bit more changes than I expected because of the need to record metrics.
Data review for the metrics recorded here is still ongoing.
=> Bug 1597761 - Don't create PingRequest if body exceeds 1MB

CHANGELOG.md, Cargo.lock, docs/dev/python/setting-up-python-build-environment.md, glean-core/ffi/Cargo.toml, glean-core/ffi/glean.h, glean-core/ffi/src/fd_logger.rs, glean-core/ffi/src/lib.rs, glean-core/ios/Glean/GleanFfi.h, glean-core/python/glean/_ffi.py
This works by setting up a named pipe between Python and Rust logging.
This requires adding another thread to the Python side to read from the log.
The overhead of that *could* be problematic.
I have no idea if this approach will work on Windows.
This at least *does* work -- any callback-based approach has been ruled
out due to limitations of CFFI or the need to go to a compiling-against-
a-specific-version-of-Python approach (see details in bug).
=> 1641148: Integrate Python and Rust logging

glean-core/ios/Glean/Scheduler/PingUploadOperation.swift, samples/android/app/metrics.yaml, samples/android/app/src/androidTest/java/org/mozilla/samples/gleancore/pings/DeletionRequestPingTest.kt, samples/android/app/src/main/java/org/mozilla/samples/glean/GleanApplication.kt, samples/ios/app/glean-sample-app/AppDelegate.swift, samples/ios/app/glean-sample-appUITests/DeletionRequestPingTest.swift, samples/ios/app/metrics.yaml
This adds a fake legacy telemetry id to test out the payload of the deletion-request ping to ensure that we can indeed send other ids in it.
=> Bug 1654811 - Add "fake" legacy telemetry ID to deletion-request integration tests

docs/user/debugging/android.md
This has existed at the new name for 6 months, so fine to remove it now
=> [doc only] Bug 1589116: Remove old debug activity classpath

CHANGELOG.md, glean-core/android/src/main/java/mozilla/telemetry/glean/scheduler/MetricsPingScheduler.kt
This works around a bug in the Java compiler on some Android 8/8.1 devices (SDK=25). See [here](https://issuetracker.google.com/issues/110848122#comment17) for more details. On buggy devices, an `AssertionError` is raised because the timezone name `enum` switch is compiled into racy code. Since we only use the timezone name in our logs, we can safely swap that out.
We don't need this defensive programming in `DateUtis.kt` as we're not using timezone names there.
=> Bug 1655613 - Work around a crash on Android 8 buggy devices

glean-core/android/proguard-rules-consumer.pro
The Glean SDK ships with classes used for tests as well. They are disabled and not directly usable in production code: they throw if used there. They can be used in tests just fine but, outside of tests, the test dependency they use won't be there, hence the warning. It's safe to suppress these.
See the [proguard docs](https://www.guardsquare.com/en/products/proguard/manual/usage) and [where was this discovered](https://github.com/mozilla-mobile/firefox-echo-show/pull/333).
=> Bug 1655116 - Suppress proguard warnings for `mozilla.telemetry.glean.testing.**`

CHANGELOG.md, docs/user/experiments-api.md, glean-core/csharp/Glean/Glean.cs, glean-core/csharp/Glean/LibGleanFFI.cs, glean-core/csharp/Glean/Metrics/EventMetricType.cs, glean-core/csharp/Glean/Metrics/RecordedExperimentData.cs, glean-core/csharp/GleanTests/GleanTests.cs
This follows the Kotlin implementation.
=> Bug 1648412 - Implement the experiments API in C#

.circleci/config.yml, Makefile, docs/dev/core/internal/payload.md, docs/dev/core/internal/upload.md, docs/user/adding-glean-to-your-project.md, docs/user/adding-new-metrics.md, docs/user/metrics/index.md, docs/user/pings/baseline.md, docs/user/pings/custom.md, docs/user/pings/events.md, docs/user/pings/index.md
The Python-based linkchecker had buggy checking of anchors within pages,
which has caused a number of our internal doc links to break.
This replaces it with a different link checking tool, and then corrects
all of the errors it found.
=> Bug 1657908: Use a better link checker in CI and fix links

samples/ios/app/glean-sample-app/ViewController.swift
- This fixes the deprecation warning in the iOS sample app by removing the use of `getUploadEnabled` in favor of persisting the state of the upload enabled preference in `UserDefaults`.
- Also includes a minor refactor of the handler for the toggle to simplify it.
=> Bug 1657441 - Fix deprecation warning in iOS sample app.

.circleci/config.yml, CHANGELOG.md, glean-core/ios/Glean/Utils/Logger.swift
This adds a 100ms delay after launching the app to the `testDeletionRequestPing` test in order to prevent a race condition that is happening when the test is triggering `setUploadEnabled(false)` very quickly after app launch, which is intermittently causing the deletion-request ping to not be sent.
=> Bug 1655100 - Capture device logs to diagnose intermittent iOS integration test failure

CHANGELOG.md, docs/dev/core/internal/upload.md, glean-core/src/lib.rs
This will be introduced as an experiment in a patch release and shipped to Fenix quickly to see if this is the issue with not getting all migration pings.
(A successful migration sends 11 pings, so stopping with 10 does seem to point at the rate limiter, but this experiment will help us confirm.)
=> Increase rate limiter to 15 pings per minute.

.circleci/config.yml
CircleCI recently upgraded that image from OpenJDK 8 to OpenJDK 11.
We pin to the old version for now.
---
Followup filed: https://bugzilla.mozilla.org/show_bug.cgi?id=1659706
=> Bug 1659548 - CI: Downgrade Android image to use

glean-core/android/src/test/java/mozilla/telemetry/glean/pings/DeletionPingTest.kt, glean-core/src/upload/directory.rs
There's a rare case where this races against a parallel deletion of all pending ping files.
This could therefore fail, in which case we don't care about the result and can ignore the ping, it's already been deleted.
=> Bug 1656934 - Upload manager: ignore files if metadata can't be read

Makefile, docs/contributing.md
This was previously already removed from CI,
but we missed to remove the make task and documentation.
[doc only]
=> Don't require swiftformat to run anymore

CHANGELOG.md, glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/GleanTest.kt, glean-core/android/src/test/java/mozilla/telemetry/glean/private/EventMetricTypeTest.kt, glean-core/ios/Glean/Glean.swift
~~I don't like the second commit that disables the metrics ping by setting the last sent date, awkardly.
Not sure why that is necessary, at a minimum we should have a nicer way to deal with it.~~
Otherwise this seems to work in our tests.
We would need to take this to a test drive in Fenix to figure out if that fixes the startup delay for them.
=> Bug 1657292 - Ping registration off main thread

glean-core/csharp/Glean/Net/BaseUploader.cs, glean-core/python/glean/net/ping_upload_worker.py, glean-core/src/upload/directory.rs, glean-core/src/upload/mod.rs
While working on this I realized that Python and C# don't have the exponential backoff like Android does.
Not necessary at the moment obviously, but I guess it's time to at least file a bug about adding a duration to the `PingUploadTask::Wait`, so that we can implement the exponential backoff on the Rust side. That way this behaviour can be consistent across all bindings.
=> Bug 1656879 - Move MAX_WAIT_ATTEMPTS logic to the core

glean-core/src/upload/mod.rs
This is just a quick fix so that intermittents stop for today.
A more sustainable approach for this would be having a way to turn limits off for tests. I am almost at EOD for today so, quick fix it is for now and tomorrow I work on the more involved fix.
=> Bug 1661276 - Raise limit for max wait attempts

glean-core/python/requirements_dev.txt
dependabot put us in an unsupported state: auditwheel 3.2.0 requires exactly wheel 0.34.2
=> Python: Fix wheel dependency so it matches auditwheel

Makefile
The new pip resolver (which should soon be the default) is stricter about global consistency of versions.
This should error out of there is an inconsistency between versions of
libraries, and avoid dependabot creating errors that lead to the fix in #1184
For context: "The new dependency resolver is significantly stricter and more consistent when it receives incompatible instructions, and reduces support for certain kinds of constraints files, so some workarounds and workflows may break." [ref](https://discuss.python.org/t/announcement-pip-20-2-release/4863)
=> Python: Use new pip-resolver

CHANGELOG.md, glean-core/ios/Glean.xcodeproj/project.pbxproj
This avoids linker errors due to missing errors such as as "___llvm_profile_runtime".
We only use code coverage in development for our manual checks, but we
should not put that in released binary frameworks.
=> iOS: Disable code coverage 

glean-core/src/database/mod.rs, glean-core/src/event_database/mod.rs, glean-core/src/metrics/custom_distribution.rs, glean-core/src/metrics/datetime.rs, glean-core/src/metrics/memory_distribution.rs, glean-core/src/metrics/timing_distribution.rs
I added this check to the metrics code that wasn't checking, to avoid running unnecessary code when the metric won't be recorded after all.
I also added checks to the `record_*` functions on the databases, just to be sure we are not recording when we don't want to. Note that I only check if upload is disabled on the databases.
=> Bug 1661036 - Check if upload is enabled before recording a metric

glean-core/android/src/main/java/mozilla/telemetry/glean/Glean.kt, glean-core/csharp/Glean/Glean.cs, glean-core/ios/Glean/Glean.swift, glean-core/python/glean/glean.py, glean-core/src/lib.rs
The error message is now just an info message, so that it doesn't clutter users logs.
=> Bug 1662584 - Submitting a ping with upload disabled no longer errors

.dictionary, docs/user/adding-glean-to-your-project.md
This makes the "enable app id" requirement more visible and adds mention of the ABI split/size concern for android projects.
=> Bug 1655749 - Mention ABI split [doc only]

.circleci/config.yml, .gitignore, CHANGELOG.md, Makefile, bin/prepare-release.sh, docs/dev/python/setting-up-python-build-environment.md, docs/user/adding-glean-to-your-project.md, glean-core/python/ffi_build.py, glean-core/python/requirements_dev.txt, glean-core/python/setup.py, setup.py
This will ship a Python source package that should be installable on platforms that we don't provide wheels for (if the destination has `cargo` on the path).  Of particular note to support Apple Silicon and more niche OSes like *BSD.
=> 1660120: Make Python bindings installable from source

CHANGELOG.md, glean-core/ffi/src/lib.rs, glean-core/src/lib.rs, glean-core/src/upload/mod.rs
The bug that was causing that intermittent, was due to scanning the pings directories **before** running the `on_upload_disabled` function that deleted non-deletion request pings.
I fix that in this PR by moving the scanning to **after** function the `on_upload_disabled` function. 
As I mentioned in the bug, I was able to reproduce the intermittent reliably in a specific branch of mine, with the fix I don't get the errors anymore on that branch either.
=> Bug 1656934 - Scan pending pings directories after dealing with upload status

Makefile, bin/update-glean-parser-version.sh
Previously it used whatever was the latest version.
This could lead to CI failures when we update glean_parser but don't
update inside this repository.
[doc only]
---
This either needs to land before #1213 and then that one gets an update, or land after and we rebase this one.
=> Use the same glean_parser version as used across the repository

bin/spellcheck.sh
The spellchecking CI *does* highlight the misspelled word using colorizing when
run locally, but this is somehow broken when displayed in the CircleCI log
viewer online.
There doesn't appear to be a way to put custom delimiters around the misspelled
word, but it is possible to *only* display the misspelled word without the
context from the rest of the line.  This is probably more helpful to understand
which words the spellchecker doesn't like.
Running the spellchecker locally through `make spellcheck` doesn't change --
that will still use the interactive version of aspell.
=> Improve spellchecker output in CI

.circleci/config.yml
For the source release, we need to run the `setup.py` script from the top-level directory (but the venv is still under `glean-core/python`).  I think this is the correct solution in place of #1209.
=> Fix pypi-source-release job

glean-core/python/requirements_dev.txt
The setuptools-git package is needed to include all files checked into git,
rather than the default Python heuristic that just (mainly) includes .py files.
This is why the released Python source package was only ~5kb rather than 1.5MB.
=> Bug 1660210: Fix Python source package release

glean-core/src/lib.rs
This is not really an error and due to re-sets of the Glean object
during tests leads to some noise in the log.
It will still be visible in our CI (because that runs at log level debug),
but reduces noise in consumer's tests.
=> Drop `duplicate ping` log message to `debug` level

glean-core/android/build.gradle
I discovered this by comparing the output of a working `publishToMavenLocal` build against a broken one.  The differences were minor, but in the broken one the `mergeReleaseJniLibFolders` task was running *before* the Rust binaries were built with cargo, but *after* in the working build.
Adding this dependency seems to re-order things correctly (perhaps at the loss of a little parallelism).
=> [ci full] Bug 1666859: Fix missing Rust binaries from package

CHANGELOG.md, glean-core/src/upload/mod.rs
Found this bug during vlidation of these metrics. 
See: https://sql.telemetry.mozilla.org/queries/75022/source?p_date=2020-09-16--2020-09-28#187737
=> Bug 1657852 - Transform ping dir size to kB before accumulating

Cargo.lock
v0.4.3 was yanked, let's upgrade what we link into Glean.
=> Upgrade crossbeam-channel to non yanked version

glean-core/ios/Glean/Glean.swift, glean-core/ios/Glean/Net/HttpPingUploader.swift
The uploader is always started after pings are already submitted (and assembled).
The ping uploader can potentially block as it uploads several pings and
even goes to sleep if told to wait (soon).
By putting it on a background thread we ensure this doesn't stop any
other work.
This was already manually done in one place, but not in the others.
This should be equivalent to Android's way of pushing this work to a
workmanager job.
Unfortunately this is near impossible to add a test for, as we would somehow need to instruct the uploader to block so that we can encounter the problems. Which we can't.
So we have to live with the existing tests (they pass) & integration tests (on CI).
---
This should unblock #1240
=> Bug 1668820 - Always launch the ping uploader on a background thread

docs/user/pings/index.md
Also reorganizes document to describe experiments as a subsection of ping_info
=> [doc only] Bug 1635377: Document metrics and events sections

.circleci/config.yml
It is super slow and at the moment causes quite some failures due to
timeouts or other network problems.
The image should get us a suitable version of swiftlint already without
requiring an update.
[doc only]
=> Don't update homebrew to install swiftlint

.circleci/config.yml, Cargo.lock, glean-core/Cargo.toml, glean-core/ffi/glean.h, glean-core/ios/Glean/GleanFfi.h, glean-core/src/database/mod.rs, glean-core/src/error.rs
The default is still Rkv's LMDB storage backend and we don't have any
intention to change that at the moment.
=> Bug 1670184 - Upgrade to rkv 0.15.0 and make the backend selectable

.github/dependabot.yml, Cargo.lock
Dependabot should be able to handle the cargo workspace as one thing.
Otherwise I just ran `cargo update` to upgrade dependencies with minor/patch version releases.
=> Dependabot updates

glean-core/metrics.yaml
All of these "metrics" land in the `ping_info` section.
Internally this is considered the `glean_internal_info` ping.
One note: `experiments` is actually a key-value dictionary.
This does not exist as a metric type, we therefore label it a `string`.
The pipeline won't like this when it generates a schema purely based on
what's annoated in metrics.yaml
@fbertsch Will this cause trouble for the schema generator?
=> Bug 1671192 - Document ping info in metrics yaml
